export const businessFr: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // Entrepreneur Mind
  'What defines an entrepreneur?': { prompt: "Qu'est-ce qui définit un entrepreneur?", options: ["Quelqu'un avec un emploi", "Quelqu'un qui crée et dirige une entreprise", "Un manager dans une corporation", "Un freelance uniquement"], correctAnswer: "Quelqu'un qui crée et dirige une entreprise" },
  'Failure is a normal part of entrepreneurship.': { prompt: "L'échec est une partie normale de l'entrepreneuriat.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A growth ___ means believing abilities can be developed over time.': { prompt: "Un ___ de croissance signifie croire que les compétences peuvent être développées avec le temps.", options: ["État d'esprit", "Plan", "Taux", "Graphique"], correctAnswer: "État d'esprit" },
  'Waiting for the "perfect" idea before starting anything.': { prompt: "Attendre l'idée \"parfaite\" avant de commencer quoi que ce soit.", options: ["Bonne pratique", "Mauvaise pratique"], correctAnswer: "Mauvaise pratique" },
  'What is "bootstrapping"?': { prompt: 'Qu\'est-ce que le "bootstrapping"?', options: ["Porter des bottes au travail", "Autofinancer son entreprise sans investisseurs", "Obtenir un prêt bancaire", "Embaucher une grande équipe d'abord"], correctAnswer: "Autofinancer son entreprise sans investisseurs" },
  'Entrepreneurs must do everything alone to succeed.': { prompt: "Les entrepreneurs doivent tout faire seuls pour réussir.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Which entrepreneurial mindset is better?': { prompt: "Quel état d'esprit entrepreneurial est meilleur?", options: ["J'ai échoué une fois, donc je ne suis pas fait pour ça.", "J'ai échoué une fois — maintenant je sais ce qui ne marche pas."], correctAnswer: "J'ai échoué une fois — maintenant je sais ce qui ne marche pas." },

  // Finding Ideas
  'Where do the best business ideas come from?': { prompt: "D'où viennent les meilleures idées d'entreprise?", options: ["Copier exactement les concurrents", "Résoudre de vrais problèmes que les gens ont", "Le brainstorming aléatoire uniquement", "Acheter des idées en ligne"], correctAnswer: "Résoudre de vrais problèmes que les gens ont" },
  'A good business idea must be completely original.': { prompt: "Une bonne idée d'entreprise doit être complètement originale.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A pain ___ is a specific problem your customers experience.': { prompt: "Un ___ de douleur est un problème spécifique que vos clients rencontrent.", options: ["Point", "Niveau", "Score", "Zone"], correctAnswer: "Point" },
  'Asking potential customers about their problems before building.': { prompt: "Demander aux clients potentiels leurs problèmes avant de construire.", options: ["Bonne pratique", "Mauvaise pratique"], correctAnswer: "Bonne pratique" },
  'What is a "niche" market?': { prompt: 'Qu\'est-ce qu\'un marché "niche"?', options: ["Le plus grand marché possible", "Un segment petit et spécialisé du marché", "Un marché qui n'existe pas", "N'importe quel marché en ligne"], correctAnswer: "Un segment petit et spécialisé du marché" },
  'Your own frustrations can be a source of business ideas.': { prompt: "Vos propres frustrations peuvent être une source d'idées d'entreprise.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Validation
  // Note: detailed 'What is idea validation?' entry is below in the expanded section
  'You should build the full product before validating the idea.': { prompt: "Vous devriez construire le produit complet avant de valider l'idée.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A landing page can help ___ interest before building a product.': { prompt: "Une page d'atterrissage peut aider à ___ l'intérêt avant de construire un produit.", options: ["Tester", "Cacher", "Réduire", "Bloquer"], correctAnswer: "Tester" },
  'Spending 6 months building without talking to customers.': { prompt: "Passer 6 mois à construire sans parler aux clients.", options: ["Bonne pratique", "Mauvaise pratique"], correctAnswer: "Mauvaise pratique" },
  'What is the cheapest way to validate a business idea?': { prompt: "Quelle est la façon la moins chère de valider une idée d'entreprise?", options: ["Construire le produit complet", "Parler aux clients potentiels", "Engager un consultant", "Faire des publicités TV"], correctAnswer: "Parler aux clients potentiels" },
  'Pre-orders are a strong form of validation.': { prompt: "Les précommandes sont une forme solide de validation.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Which validation approach is better?': { prompt: "Quelle approche de validation est meilleure?", options: ["Je pense que c'est une super idée, construisons-la!", "Parlons d'abord à 20 clients potentiels."], correctAnswer: "Parlons d'abord à 20 clients potentiels." },

  // Business Model
  'What is a business model?': { prompt: "Qu'est-ce qu'un modèle d'affaires?", options: ["Un mannequin de mode pour les affaires", "Comment une entreprise crée et capture de la valeur", "Un design de carte de visite", "Le logo de l'entreprise"], correctAnswer: "Comment une entreprise crée et capture de la valeur" },
  'Subscription is a type of business model.': { prompt: "L'abonnement est un type de modèle d'affaires.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A ___ model charges users a recurring fee for access.': { prompt: "Un modèle d'___ facture aux utilisateurs des frais récurrents pour l'accès.", options: ["Abonnement", "Grossiste", "Enchères", "Troc"], correctAnswer: "Abonnement" },
  'What is a "freemium" model?': { prompt: 'Qu\'est-ce qu\'un modèle "freemium"?', options: ["Tout est gratuit", "Fonctionnalités de base gratuites, fonctionnalités premium payantes", "Seulement des options payantes", "Un essai gratuit uniquement"], correctAnswer: "Fonctionnalités de base gratuites, fonctionnalités premium payantes" },
  'Having multiple revenue streams in your business.': { prompt: "Avoir plusieurs sources de revenus dans votre entreprise.", options: ["Bonne pratique", "Mauvaise pratique"], correctAnswer: "Bonne pratique" },
  'Every business must use the same business model.': { prompt: "Chaque entreprise doit utiliser le même modèle d'affaires.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What does B2B mean?': { prompt: "Que signifie B2B?", options: ["Back to Basics", "Business to Business", "Buy to Build", "Brand to Brand"], correctAnswer: "Business to Business" },

  // Target Market
  'What is a target market?': { prompt: "Qu'est-ce qu'un marché cible?", options: ["Tout le monde dans le monde", "Le groupe spécifique le plus susceptible d'acheter votre produit", "Vos concurrents", "Les gens qui n'aiment pas votre produit"], correctAnswer: "Le groupe spécifique le plus susceptible d'acheter votre produit" },
  'Trying to sell to "everyone" is a good strategy.': { prompt: 'Essayer de vendre à "tout le monde" est une bonne stratégie.', options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A buyer ___ is a fictional representation of your ideal customer.': { prompt: "Un ___ d'acheteur est une représentation fictive de votre client idéal.", options: ["Persona", "Profil", "Image", "Plan"], correctAnswer: "Persona" },
  'Defining your customer by age, interests, and problems.': { prompt: "Définir votre client par âge, intérêts et problèmes.", options: ["Bonne pratique", "Mauvaise pratique"], correctAnswer: "Bonne pratique" },
  'What is market segmentation?': { prompt: "Qu'est-ce que la segmentation de marché?", options: ["Ignorer le marché", "Diviser le marché en groupes distincts", "Fusionner tous les clients ensemble", "Copier le marché d'un concurrent"], correctAnswer: "Diviser le marché en groupes distincts" },
  'Demographics include age, gender, and income level.': { prompt: "Les données démographiques incluent l'âge, le sexe et le niveau de revenu.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // MVP Building
  'What does MVP stand for?': { prompt: "Que signifie MVP?", options: ["Most Valuable Player", "Minimum Viable Product", "Maximum Value Proposition", "Market Value Price"], correctAnswer: "Minimum Viable Product" },
  'An MVP should have every possible feature.': { prompt: "Un MVP devrait avoir toutes les fonctionnalités possibles.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'An MVP includes only the ___ features needed to test your idea.': { prompt: "Un MVP inclut uniquement les fonctionnalités ___ nécessaires pour tester votre idée.", options: ["Essentielles", "Toutes les", "Meilleures", "Supplémentaires"], correctAnswer: "Essentielles" },
  'Launching a simple version to get feedback quickly.': { prompt: "Lancer une version simple pour obtenir des retours rapidement.", options: ["Bonne pratique", "Mauvaise pratique"], correctAnswer: "Bonne pratique" },
  'Who popularized the concept of MVP?': { prompt: "Qui a popularisé le concept de MVP?", options: ["Steve Jobs", "Eric Ries", "Elon Musk", "Mark Zuckerberg"], correctAnswer: "Eric Ries" },
  'Which MVP approach is better?': { prompt: "Quelle approche MVP est meilleure?", options: ["Passons un an à le perfectionner avant que quiconque ne le voie.", "Lançons une version basique ce mois-ci et apprenons des utilisateurs."], correctAnswer: "Lançons une version basique ce mois-ci et apprenons des utilisateurs." },
  'The goal of an MVP is to learn, not to impress.': { prompt: "L'objectif d'un MVP est d'apprendre, pas d'impressionner.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Sales 101
  'What is the first step in selling?': { prompt: "Quelle est la première étape de la vente?", options: ["Conclure l'affaire", "Comprendre les besoins du client", "Donner un prix", "Envoyer une facture"], correctAnswer: "Comprendre les besoins du client" },
  'Good salespeople talk more than they listen.': { prompt: "Les bons vendeurs parlent plus qu'ils n'écoutent.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A sales ___ is the series of steps from first contact to purchase.': { prompt: "Un ___ de vente est la série d'étapes du premier contact à l'achat.", options: ["Entonnoir", "Échelle", "Roue", "Chaîne"], correctAnswer: "Entonnoir" },
  'Pressuring someone to buy immediately.': { prompt: "Presser quelqu'un d'acheter immédiatement.", options: ["Bonne pratique", "Mauvaise pratique"], correctAnswer: "Mauvaise pratique" },
  'What is a "cold call"?': { prompt: 'Qu\'est-ce qu\'un "appel à froid"?', options: ["Appeler en hiver", "Contacter quelqu'un qui ne s'attend pas à votre appel", "Un appel de suivi", "Appeler votre meilleur client"], correctAnswer: "Contacter quelqu'un qui ne s'attend pas à votre appel" },
  'Follow-up is one of the most important parts of sales.': { prompt: "Le suivi est l'une des parties les plus importantes de la vente.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Which sales approach is better?': { prompt: "Quelle approche de vente est meilleure?", options: ["Achetez ça maintenant, c'est le meilleur produit!", "Quel problème essayez-vous de résoudre? Voyons si nous pouvons aider."], correctAnswer: "Quel problème essayez-vous de résoudre? Voyons si nous pouvons aider." },

  // Pitching
  'What is an elevator pitch?': { prompt: "Qu'est-ce qu'un elevator pitch?", options: ["Vendre des ascenseurs", "Un résumé d'entreprise de 30-60 secondes", "Une longue présentation", "Une proposition écrite"], correctAnswer: "Un résumé d'entreprise de 30-60 secondes" },
  'A pitch deck should typically have 10-15 slides.': { prompt: "Un pitch deck devrait généralement avoir 10-15 diapositives.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Investors want to know your problem, solution, and ___ model.': { prompt: "Les investisseurs veulent connaître votre problème, solution et modèle d'___.", options: ["Affaires", "Mode", "Couleur", "Construction"], correctAnswer: "Affaires" },
  'Reading directly from your slides during a pitch.': { prompt: "Lire directement vos diapositives pendant un pitch.", options: ["Bonne pratique", "Mauvaise pratique"], correctAnswer: "Mauvaise pratique" },
  "What should a pitch start with?": { prompt: "Par quoi un pitch devrait-il commencer?", options: ["Vos chiffres de revenus", "Le problème que vous résolvez", "Les biographies de votre équipe", "Une blague"], correctAnswer: "Le problème que vous résolvez" },
  'Showing traction (users, revenue) strengthens a pitch.': { prompt: "Montrer de la traction (utilisateurs, revenus) renforce un pitch.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Which pitch opening is better?': { prompt: "Quelle ouverture de pitch est meilleure?", options: ["Notre entreprise a été fondée en 2024 et nous avons 3 employés...", "40% des petites entreprises échouent parce qu'elles ne gèrent pas leur trésorerie. Nous résolvons ça."], correctAnswer: "40% des petites entreprises échouent parce qu'elles ne gèrent pas leur trésorerie. Nous résolvons ça." },

  // ── NEW: Detailed Business questions (24 modules × 8 questions) ──

  // Entrepreneur Mind (detailed)
  'What is the most important trait of a successful entrepreneur?': { prompt: "Quel est le trait le plus important d'un entrepreneur à succès?", options: ["Avoir beaucoup d'argent pour démarrer", "La résilience — la capacité de persister à travers les échecs et revers tout en apprenant et s'adaptant", "Un business plan parfait", "Un diplôme MBA"], correctAnswer: "La résilience — la capacité de persister à travers les échecs et revers tout en apprenant et s'adaptant" },
  'Having a growth mindset — believing skills and intelligence can be developed — is crucial for entrepreneurial success.': { prompt: "Avoir un état d'esprit de croissance — croire que les compétences et l'intelligence peuvent être développées — est crucial pour le succès entrepreneurial.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What does "bias toward action" mean for entrepreneurs?': { prompt: 'Que signifie "biais vers l\'action" pour les entrepreneurs?', options: ["Être impulsif sans réfléchir", "Préférer agir et tester les idées rapidement plutôt que de sur-planifier et attendre des conditions parfaites", "N'agir que quand tout est certain", "Ignorer tous les conseils"], correctAnswer: "Préférer agir et tester les idées rapidement plutôt que de sur-planifier et attendre des conditions parfaites" },
  'Successful entrepreneurs view failure not as an endpoint but as ___ that provides valuable information.': { prompt: "Les entrepreneurs à succès voient l'échec non comme une fin mais comme un ___ qui fournit des informations précieuses.", options: ["punition", "feedback", "chance", "coïncidence"], correctAnswer: "feedback" },
  'Entrepreneurs should avoid all risk to protect their business.': { prompt: "Les entrepreneurs devraient éviter tout risque pour protéger leur entreprise.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Why is self-discipline more important than motivation for entrepreneurs?': { prompt: "Pourquoi l'autodiscipline est-elle plus importante que la motivation pour les entrepreneurs?", options: ["Ce n'est pas le cas — la motivation est tout ce dont vous avez besoin", "La motivation va et vient, mais la discipline assure que vous travaillez de manière cohérente même quand vous n'en avez pas envie", "La discipline est seulement pour les employés", "C'est la même chose"], correctAnswer: "La motivation va et vient, mais la discipline assure que vous travaillez de manière cohérente même quand vous n'en avez pas envie" },
  'What is the "opportunity cost" mindset that entrepreneurs need?': { prompt: "Quel est l'état d'esprit du \"coût d'opportunité\" dont les entrepreneurs ont besoin?", options: ["Tout est gratuit", "Comprendre que chaque choix signifie renoncer à des alternatives — le temps passé sur une chose ne peut pas être passé sur une autre", "Ne penser qu'à l'argent", "Ignorer les options et s'en tenir à un seul plan pour toujours"], correctAnswer: "Comprendre que chaque choix signifie renoncer à des alternatives — le temps passé sur une chose ne peut pas être passé sur une autre" },
  'Surrounding yourself with other ambitious and supportive people significantly impacts your entrepreneurial success.': { prompt: "S'entourer d'autres personnes ambitieuses et bienveillantes impacte significativement votre succès entrepreneurial.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Finding Ideas (detailed)
  'What is the best source of business ideas?': { prompt: "Quelle est la meilleure source d'idées d'entreprise?", options: ["Copier exactement ce que font les concurrents", "Identifier de vrais problèmes que les gens vivent et sont prêts à payer pour résoudre", "Brainstorming aléatoire sans connaissance du marché", "Attendre que l'inspiration frappe"], correctAnswer: "Identifier de vrais problèmes que les gens vivent et sont prêts à payer pour résoudre" },
  'A good business idea must be completely original and never done before.': { prompt: "Une bonne idée d'entreprise doit être complètement originale et jamais faite auparavant.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What does "scratch your own itch" mean in finding business ideas?': { prompt: 'Que signifie "gratter sa propre démangeaison" pour trouver des idées d\'entreprise?', options: ["Une condition médicale", "Construire un produit ou service qui résout un problème que vous vivez personnellement", "Copier l'idée de quelqu'un d'autre", "Construire uniquement pour le plaisir"], correctAnswer: "Construire un produit ou service qui résout un problème que vous vivez personnellement" },
  'Which approach is best for generating viable business ideas?': { prompt: "Quelle approche est la meilleure pour générer des idées d'entreprise viables?", options: ["Rester dans sa chambre à réfléchir seul", "Parler aux clients potentiels, observer les marchés, noter les plaintes et identifier les écarts entre ce qui existe et ce que les gens veulent", "Ne lire que des livres d'affaires", "Demander à ChatGPT des idées aléatoires"], correctAnswer: "Parler aux clients potentiels, observer les marchés, noter les plaintes et identifier les écarts entre ce qui existe et ce que les gens veulent" },
  'The intersection of what you are skilled at, what you enjoy, and what people will ___ for is the sweet spot for business ideas.': { prompt: "L'intersection de ce dans quoi vous êtes doué, ce que vous aimez, et ce pour quoi les gens vont ___ est le point idéal pour les idées d'entreprise.", options: ["applaudir", "payer", "attendre", "espérer"], correctAnswer: "payer" },
  'You should spend months perfecting your idea before talking to any potential customers.': { prompt: "Vous devriez passer des mois à perfectionner votre idée avant de parler à des clients potentiels.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is a "trend-based" approach to finding business ideas?': { prompt: "Qu'est-ce qu'une approche \"basée sur les tendances\" pour trouver des idées d'entreprise?", options: ["Suivre uniquement les tendances de la mode", "Identifier les technologies émergentes, changements culturels ou réglementaires qui créent de nouveaux besoins ou rendent de nouvelles solutions possibles", "Ne regarder que les données passées", "Ignorer les changements du marché"], correctAnswer: "Identifier les technologies émergentes, changements culturels ou réglementaires qui créent de nouveaux besoins ou rendent de nouvelles solutions possibles" },
  'Solving a problem for a small, specific group of people is often better than trying to serve everyone.': { prompt: "Résoudre un problème pour un petit groupe spécifique de personnes est souvent mieux qu'essayer de servir tout le monde.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Validation (detailed)
  'What is idea validation?': { prompt: "Qu'est-ce que la validation d'idée?", options: ["Demander à vos amis s'ils aiment votre idée", "Tester si de vrais clients potentiels vont réellement payer pour votre produit ou service avant de construire la version complète", "Déposer un brevet", "Écrire un business plan de 50 pages"], correctAnswer: "Tester si de vrais clients potentiels vont réellement payer pour votre produit ou service avant de construire la version complète" },
  'A landing page with an email sign-up form is a valid way to test interest in a product before building it.': { prompt: "Une page d'atterrissage avec un formulaire d'inscription par email est un moyen valide de tester l'intérêt pour un produit avant de le construire.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Why is validation important before building a full product?': { prompt: "Pourquoi la validation est-elle importante avant de construire un produit complet?", options: ["Ce n'est pas important — construisez et ils viendront", "Elle vous empêche de perdre des mois ou des années à construire quelque chose que personne ne veut, économisant temps, argent et énergie émotionnelle", "Seuls les investisseurs se soucient de la validation", "Elle garantit le succès"], correctAnswer: "Elle vous empêche de perdre des mois ou des années à construire quelque chose que personne ne veut, économisant temps, argent et énergie émotionnelle" },
  'Which is the strongest form of validation?': { prompt: "Quelle est la forme de validation la plus forte?", options: ["Des gens disant \"j'achèterais ça\"", "Des gens payant réellement — précommandes, acomptes ou achat d'une version minimale viable", "Des likes sur les réseaux sociaux", "Une réponse positive de la famille"], correctAnswer: "Des gens payant réellement — précommandes, acomptes ou achat d'une version minimale viable" },
  'The "Mom Test" is a framework that helps you ask better customer interview questions by focusing on their ___ behavior rather than hypothetical opinions.': { prompt: "Le \"Mom Test\" est un cadre qui vous aide à poser de meilleures questions en entretien client en vous concentrant sur leur comportement ___ plutôt que sur des opinions hypothétiques.", options: ["passé", "futur", "en ligne", "aléatoire"], correctAnswer: "passé" },
  'Validation is a one-time event — once validated, you never need to test assumptions again.': { prompt: "La validation est un événement unique — une fois validé, vous n'avez plus jamais besoin de tester vos hypothèses.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is a "smoke test" in business validation?': { prompt: "Qu'est-ce qu'un \"smoke test\" en validation d'entreprise?", options: ["Tester les alarmes incendie", "Présenter un produit comme s'il existait (via une page d'atterrissage ou une pub) pour évaluer la demande réelle avant de le construire", "Brûler votre business plan", "Un test de capacité pulmonaire"], correctAnswer: "Présenter un produit comme s'il existait (via une page d'atterrissage ou une pub) pour évaluer la demande réelle avant de le construire" },
  'If you survey 100 people and 90 say they love your idea, that alone is sufficient validation to invest heavily.': { prompt: "Si vous sondez 100 personnes et que 90 disent qu'elles adorent votre idée, cela seul est une validation suffisante pour investir massivement.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },

  // Pricing Strategy
  'What is value-based pricing?': { prompt: "Qu'est-ce que la tarification basée sur la valeur?", options: ["Fixer les prix en fonction de vos coûts plus une marge", "Fixer les prix en fonction de la valeur perçue par le client, pas de ce que ça vous coûte", "S'aligner sur les prix des concurrents", "Toujours être le moins cher"], correctAnswer: "Fixer les prix en fonction de la valeur perçue par le client, pas de ce que ça vous coûte" },
  'Underpricing your product can actually hurt sales because customers may perceive it as low quality.': { prompt: "Sous-évaluer votre produit peut en fait nuire aux ventes car les clients peuvent le percevoir comme de basse qualité.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is a pricing tier strategy?': { prompt: "Qu'est-ce qu'une stratégie de paliers de prix?", options: ["Offrir un seul prix", "Offrir plusieurs niveaux de prix (comme Basique, Pro, Entreprise) pour capter différents segments de clients prêts à payer différents montants", "Une remise pour les clients fidèles", "Fixer les prix selon l'heure de la journée"], correctAnswer: "Offrir plusieurs niveaux de prix (comme Basique, Pro, Entreprise) pour capter différents segments de clients prêts à payer différents montants" },
  'What is the "anchoring" effect in pricing?': { prompt: "Qu'est-ce que l'effet d'\"ancrage\" en tarification?", options: ["Lier votre prix à une ancre de bateau", "Montrer un prix de référence plus élevé d'abord fait paraître un prix plus bas comme une meilleure affaire — le premier chiffre ancre la perception", "Garder les prix fixes pour toujours", "Ne vendre qu'aux enchères"], correctAnswer: "Montrer un prix de référence plus élevé d'abord fait paraître un prix plus bas comme une meilleure affaire — le premier chiffre ancre la perception" },
  'Pricing at $9.99 instead of $10.00 uses ___ pricing, which takes advantage of how our brains process numbers.': { prompt: "Fixer le prix à 9,99$ au lieu de 10,00$ utilise la tarification ___, qui exploite la façon dont notre cerveau traite les nombres.", options: ["premium", "psychologique", "de gros", "dynamique"], correctAnswer: "psychologique" },
  'You should never raise your prices once customers are used to the current price.': { prompt: "Vous ne devriez jamais augmenter vos prix une fois que les clients sont habitués au prix actuel.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is "price elasticity" and why does it matter?': { prompt: "Qu'est-ce que l'\"élasticité des prix\" et pourquoi est-ce important?", options: ["L'élasticité de votre produit", "La sensibilité de la demande client aux changements de prix — les produits inélastiques supportent les hausses de prix sans perdre beaucoup de clients", "Un type de remise", "La vitesse de changement des prix"], correctAnswer: "La sensibilité de la demande client aux changements de prix — les produits inélastiques supportent les hausses de prix sans perdre beaucoup de clients" },
  'Offering a free trial can be an effective pricing strategy because it reduces the perceived risk for new customers.': { prompt: "Offrir un essai gratuit peut être une stratégie de prix efficace car elle réduit le risque perçu pour les nouveaux clients.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Branding
  'What is a brand?': { prompt: "Qu'est-ce qu'une marque?", options: ["Juste un logo et des couleurs", "La perception globale, le sentiment et la réputation que les gens associent à votre entreprise", "Seulement le nom de votre entreprise", "Une campagne marketing"], correctAnswer: "La perception globale, le sentiment et la réputation que les gens associent à votre entreprise" },
  'Consistent branding across all channels increases customer trust and recognition.': { prompt: "Un branding cohérent sur tous les canaux augmente la confiance et la reconnaissance des clients.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is a brand "positioning statement"?': { prompt: "Qu'est-ce qu'une \"déclaration de positionnement\" de marque?", options: ["Une déclaration sur l'emplacement de votre bureau", "Une déclaration claire de qui vous servez, ce que vous offrez, comment vous êtes différent et pourquoi les clients devraient vous choisir", "Un avertissement légal", "L'adresse de votre entreprise"], correctAnswer: "Une déclaration claire de qui vous servez, ce que vous offrez, comment vous êtes différent et pourquoi les clients devraient vous choisir" },
  'Your brand ___ is the personality and emotion you convey through your words, whether formal, friendly, playful, or authoritative.': { prompt: "La ___ de votre marque est la personnalité et l'émotion que vous transmettez à travers vos mots, qu'elle soit formelle, amicale, ludique ou autoritaire.", options: ["logo", "voix", "couleur", "prix"], correctAnswer: "voix" },
  'Why is storytelling important for branding?': { prompt: "Pourquoi le storytelling est-il important pour le branding?", options: ["Ce n'est pas important", "Les histoires créent des connexions émotionnelles, rendent votre marque mémorable et aident les clients à se voir dans votre récit", "Seuls les livres ont besoin d'histoires", "C'est uniquement pour les réseaux sociaux"], correctAnswer: "Les histoires créent des connexions émotionnelles, rendent votre marque mémorable et aident les clients à se voir dans votre récit" },
  'A small business cannot build a strong brand without a large marketing budget.': { prompt: "Une petite entreprise ne peut pas construire une marque forte sans un gros budget marketing.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is brand differentiation?': { prompt: "Qu'est-ce que la différenciation de marque?", options: ["Copier ce que font les concurrents", "Communiquer clairement ce qui rend votre entreprise unique et pourquoi les clients devraient vous choisir plutôt que les alternatives", "Avoir un plus grand bureau", "Dépenser plus en publicité"], correctAnswer: "Communiquer clairement ce qui rend votre entreprise unique et pourquoi les clients devraient vous choisir plutôt que les alternatives" },
  'Rebranding should be considered when your brand no longer reflects your current business, audience, or values.': { prompt: "Le rebranding devrait être envisagé quand votre marque ne reflète plus votre entreprise, audience ou valeurs actuelles.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Social Media (Business)
  'What is the most important principle of social media marketing for businesses?': { prompt: "Quel est le principe le plus important du marketing sur les réseaux sociaux pour les entreprises?", options: ["Publier le plus possible", "Fournir une vraie valeur à votre audience — éduquer, divertir ou inspirer — plutôt que de seulement promouvoir vos produits", "Ne publier que des publicités", "Copier les publications des concurrents"], correctAnswer: "Fournir une vraie valeur à votre audience — éduquer, divertir ou inspirer — plutôt que de seulement promouvoir vos produits" },
  'It is better to be excellent on two or three social media platforms than mediocre on all of them.': { prompt: "Il vaut mieux être excellent sur deux ou trois plateformes de réseaux sociaux que médiocre sur toutes.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is "engagement rate" and why does it matter?': { prompt: "Qu'est-ce que le \"taux d'engagement\" et pourquoi est-ce important?", options: ["Le nombre d'abonnés", "Le pourcentage de votre audience qui interagit avec votre contenu — il mesure à quel point votre contenu résonne", "Le nombre de publications", "Votre budget publicitaire"], correctAnswer: "Le pourcentage de votre audience qui interagit avec votre contenu — il mesure à quel point votre contenu résonne" },
  'What type of content typically performs best on social media?': { prompt: "Quel type de contenu performe généralement le mieux sur les réseaux sociaux?", options: ["De longs communiqués de presse", "Les vidéos courtes, histoires relatables, conseils éducatifs et contenu qui déclenche des émotions ou fournit une valeur immédiate", "Uniquement des publications texte sans images", "Des commentaires automatisés par des bots"], correctAnswer: "Les vidéos courtes, histoires relatables, conseils éducatifs et contenu qui déclenche des émotions ou fournit une valeur immédiate" },
  'A content ___ helps you plan, organize, and schedule your social media posts in advance for consistent publishing.': { prompt: "Un ___ de contenu vous aide à planifier, organiser et programmer vos publications sur les réseaux sociaux à l'avance pour une publication cohérente.", options: ["calendrier", "fortune", "cloud", "dossier"], correctAnswer: "calendrier" },
  'Responding to comments and messages quickly is crucial for building a loyal social media community.': { prompt: "Répondre rapidement aux commentaires et messages est crucial pour construire une communauté fidèle sur les réseaux sociaux.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is "organic reach" vs "paid reach" on social media?': { prompt: "Qu'est-ce que la \"portée organique\" vs la \"portée payante\" sur les réseaux sociaux?", options: ["C'est la même chose", "La portée organique est le nombre de personnes qui voient votre contenu sans payer, tandis que la portée payante est l'audience gagnée par la publicité", "Organique signifie utiliser des légumes dans votre contenu", "La portée payante est toujours meilleure"], correctAnswer: "La portée organique est le nombre de personnes qui voient votre contenu sans payer, tandis que la portée payante est l'audience gagnée par la publicité" },
  'Tracking analytics (impressions, reach, engagement, clicks, conversions) is essential for improving your social media strategy over time.': { prompt: "Suivre les analyses (impressions, portée, engagement, clics, conversions) est essentiel pour améliorer votre stratégie de réseaux sociaux au fil du temps.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Customer Service
  'Why is customer service important for business growth?': { prompt: "Pourquoi le service client est-il important pour la croissance de l'entreprise?", options: ["Ce n'est pas important", "Un excellent service client génère des achats répétés, des recommandations bouche-à-oreille et une valeur vie plus élevée", "Seules les grandes entreprises en ont besoin", "C'est seulement important pour le commerce de détail"], correctAnswer: "Un excellent service client génère des achats répétés, des recommandations bouche-à-oreille et une valeur vie plus élevée" },
  'A customer complaint is an opportunity to build loyalty if handled well.': { prompt: "Une plainte client est une opportunité de construire la fidélité si elle est bien gérée.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is the best first step when handling an upset customer?': { prompt: "Quelle est la meilleure première étape pour gérer un client mécontent?", options: ["Argumenter avec lui", "Écouter activement et reconnaître sa frustration avant d'essayer de résoudre le problème", "Offrir immédiatement un remboursement sans comprendre le problème", "Le transférer à quelqu'un d'autre"], correctAnswer: "Écouter activement et reconnaître sa frustration avant d'essayer de résoudre le problème" },
  'The Net Promoter Score (NPS) measures customer loyalty by asking how likely customers are to ___ your business to others.': { prompt: "Le Net Promoter Score (NPS) mesure la fidélité client en demandant à quel point les clients sont susceptibles de ___ votre entreprise aux autres.", options: ["se plaindre de", "recommander", "investir dans", "concurrencer"], correctAnswer: "recommander" },
  'What is "proactive" customer service?': { prompt: "Qu'est-ce que le service client \"proactif\"?", options: ["Attendre que les clients vous contactent avec des problèmes", "Contacter les clients avant que les problèmes ne surviennent — envoyer des mises à jour, prendre des nouvelles et anticiper les besoins avant qu'ils ne deviennent des plaintes", "Ignorer les besoins des clients", "Ne répondre que sur les réseaux sociaux"], correctAnswer: "Contacter les clients avant que les problèmes ne surviennent — envoyer des mises à jour, prendre des nouvelles et anticiper les besoins avant qu'ils ne deviennent des plaintes" },
  'Responding to negative online reviews publicly and professionally can turn a bad situation into a positive brand impression.': { prompt: "Répondre publiquement et professionnellement aux avis négatifs en ligne peut transformer une mauvaise situation en impression de marque positive.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'SITUATION: A customer demands a full refund for a product they used for 3 months. Your policy is 30-day refunds. What should you do?': { prompt: "SITUATION : Un client exige un remboursement complet pour un produit utilisé pendant 3 mois. Votre politique est de 30 jours. Que devriez-vous faire?", options: ["Refuser immédiatement en citant la politique", "Écouter sa préoccupation, comprendre pourquoi il est mécontent, offrir des alternatives comme un remboursement partiel, un crédit ou un échange, et le faire se sentir valorisé", "Donner un remboursement complet pour éviter le conflit", "Ignorer la demande"], correctAnswer: "Écouter sa préoccupation, comprendre pourquoi il est mécontent, offrir des alternatives comme un remboursement partiel, un crédit ou un échange, et le faire se sentir valorisé" },
  'Empowering frontline employees to make decisions and solve customer problems without management approval leads to faster and better customer service.': { prompt: "Donner aux employés de première ligne le pouvoir de prendre des décisions et résoudre les problèmes clients sans l'approbation de la direction mène à un service client plus rapide et meilleur.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Financial Basics
  'What are the three main financial statements every business owner should understand?': { prompt: "Quels sont les trois principaux états financiers que tout propriétaire d'entreprise devrait comprendre?", options: ["Déclaration fiscale, relevé bancaire, rapport de crédit", "Compte de résultat, bilan et tableau des flux de trésorerie", "Facture, reçu et bon de commande", "Budget, prévision et estimation"], correctAnswer: "Compte de résultat, bilan et tableau des flux de trésorerie" },
  'Revenue and profit are the same thing.': { prompt: "Le chiffre d'affaires et le profit sont la même chose.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is "gross margin"?': { prompt: "Qu'est-ce que la \"marge brute\"?", options: ["Le chiffre d'affaires total de l'entreprise", "Le pourcentage du chiffre d'affaires restant après soustraction du coût direct des marchandises vendues", "Le nombre total de clients", "Votre budget marketing"], correctAnswer: "Le pourcentage du chiffre d'affaires restant après soustraction du coût direct des marchandises vendues" },
  'What is the difference between fixed costs and variable costs?': { prompt: "Quelle est la différence entre coûts fixes et coûts variables?", options: ["Il n'y a pas de différence", "Les coûts fixes restent les mêmes quel que soit le volume de ventes (loyer, salaires) tandis que les coûts variables changent avec le volume de production (matériaux, expédition)", "Les coûts fixes sont toujours plus élevés", "Les coûts variables sont toujours plus bas"], correctAnswer: "Les coûts fixes restent les mêmes quel que soit le volume de ventes (loyer, salaires) tandis que les coûts variables changent avec le volume de production (matériaux, expédition)" },
  'The ___ point is the level of sales at which total revenue equals total costs, meaning the business is neither making nor losing money.': { prompt: "Le seuil de ___ est le niveau de ventes auquel le chiffre d'affaires total égale les coûts totaux, ce qui signifie que l'entreprise ne gagne ni ne perd d'argent.", options: ["rentabilité", "départ", "fin", "maximum"], correctAnswer: "rentabilité" },
  'A profitable business can still fail if it runs out of cash.': { prompt: "Une entreprise rentable peut quand même échouer si elle manque de trésorerie.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is accounts receivable?': { prompt: "Qu'est-ce que les comptes clients (créances)?", options: ["L'argent que vous devez aux fournisseurs", "L'argent que les clients vous doivent pour des produits ou services déjà livrés", "Le solde de votre compte bancaire", "Votre facture fiscale"], correctAnswer: "L'argent que les clients vous doivent pour des produits ou services déjà livrés" },
  'Separating personal and business finances from day one is essential for legal protection and accurate financial tracking.': { prompt: "Séparer les finances personnelles et professionnelles dès le premier jour est essentiel pour la protection juridique et un suivi financier précis.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Cash Flow
  'What is cash flow?': { prompt: "Qu'est-ce que le flux de trésorerie?", options: ["La même chose que le profit", "Le mouvement d'argent entrant et sortant de votre entreprise sur une période donnée", "Votre chiffre d'affaires total", "L'argent de votre compte épargne"], correctAnswer: "Le mouvement d'argent entrant et sortant de votre entreprise sur une période donnée" },
  'Cash flow management is the number one reason small businesses fail.': { prompt: "La gestion de trésorerie est la raison numéro un de l'échec des petites entreprises.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is "positive cash flow"?': { prompt: "Qu'est-ce qu'un \"flux de trésorerie positif\"?", options: ["Avoir de l'argent à la banque", "Quand l'argent entrant dépasse l'argent sortant pendant une période donnée", "Quand vous faites une vente", "Quand vous obtenez un prêt"], correctAnswer: "Quand l'argent entrant dépasse l'argent sortant pendant une période donnée" },
  'How can a business improve its cash flow?': { prompt: "Comment une entreprise peut-elle améliorer son flux de trésorerie?", options: ["Dépenser plus pour les bureaux", "Facturer plus vite, offrir des remises de paiement anticipé, négocier des délais plus longs avec les fournisseurs et réduire les dépenses inutiles", "Ignorer les factures impayées", "Embaucher plus de monde immédiatement"], correctAnswer: "Facturer plus vite, offrir des remises de paiement anticipé, négocier des délais plus longs avec les fournisseurs et réduire les dépenses inutiles" },
  'A cash flow ___ projects future cash inflows and outflows to help you anticipate and prepare for periods of tight cash.': { prompt: "Une ___ de trésorerie projette les entrées et sorties de cash futures pour vous aider à anticiper et préparer les périodes de trésorerie serrée.", options: ["prévision", "quittance", "facture", "dépôt"], correctAnswer: "prévision" },
  'Offering payment plans to customers can improve cash flow by making it easier for them to buy while providing you with regular income.': { prompt: "Offrir des plans de paiement aux clients peut améliorer le flux de trésorerie en leur facilitant l'achat tout en vous fournissant un revenu régulier.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is a "cash reserve" and why is it important?': { prompt: "Qu'est-ce qu'une \"réserve de trésorerie\" et pourquoi est-elle importante?", options: ["De l'argent pour acheter des articles de luxe", "Des économies mises de côté pour couvrir 3-6 mois de dépenses de fonctionnement en cas d'urgence ou de périodes creuses", "De l'argent pour investir en bourse", "Le solde minimum requis par votre banque"], correctAnswer: "Des économies mises de côté pour couvrir 3-6 mois de dépenses de fonctionnement en cas d'urgence ou de périodes creuses" },
  'Recurring revenue models (subscriptions, retainers) provide more predictable cash flow than one-time sales.': { prompt: "Les modèles de revenus récurrents (abonnements, honoraires) fournissent un flux de trésorerie plus prévisible que les ventes ponctuelles.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Hiring
  'When should a small business owner make their first hire?': { prompt: "Quand un propriétaire de petite entreprise devrait-il faire sa première embauche?", options: ["Jamais — tout faire soi-même pour toujours", "Quand vous refusez régulièrement du travail ou ne pouvez pas livrer de la qualité à cause de la charge de travail, et que les revenus le supportent", "Immédiatement au démarrage", "Seulement quand vous avez 100 clients"], correctAnswer: "Quand vous refusez régulièrement du travail ou ne pouvez pas livrer de la qualité à cause de la charge de travail, et que les revenus le supportent" },
  'Hiring for attitude and cultural fit is often more important than hiring purely for technical skills.': { prompt: "Embaucher pour l'attitude et l'adéquation culturelle est souvent plus important qu'embaucher uniquement pour les compétences techniques.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is the biggest cost of a bad hire?': { prompt: "Quel est le plus gros coût d'une mauvaise embauche?", options: ["Juste leur salaire", "Productivité perdue, moral d'équipe endommagé, temps de formation gaspillé, problèmes clients potentiels et coût de remplacement — souvent 2-3x le salaire du poste", "Rien si vous les licenciez rapidement", "Seulement les frais de recrutement"], correctAnswer: "Productivité perdue, moral d'équipe endommagé, temps de formation gaspillé, problèmes clients potentiels et coût de remplacement — souvent 2-3x le salaire du poste" },
  'What should you do before hiring a full-time employee?': { prompt: "Que devriez-vous faire avant d'embaucher un employé à temps plein?", options: ["Rien — publiez une offre d'emploi", "Envisager de commencer avec un contractuel ou freelance pour tester la relation de travail et valider le besoin", "Embaucher la première personne qui postule", "N'embaucher que des amis et de la famille"], correctAnswer: "Envisager de commencer avec un contractuel ou freelance pour tester la relation de travail et valider le besoin" },
  'A clear job ___ that defines responsibilities, expectations, and success metrics is essential for attracting the right candidates and setting them up for success.': { prompt: "Une ___ de poste claire qui définit les responsabilités, attentes et métriques de succès est essentielle pour attirer les bons candidats et les préparer au succès.", options: ["titre", "description", "entretien", "offre"], correctAnswer: "description" },
  'You should hire someone just like yourself to ensure alignment.': { prompt: "Vous devriez embaucher quelqu'un exactement comme vous pour assurer l'alignement.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is an effective interview technique for evaluating candidates?': { prompt: "Quelle est une technique d'entretien efficace pour évaluer les candidats?", options: ["Ne poser que des questions sur leurs loisirs", "Poser des questions comportementales sur des expériences passées et donner des tâches pratiques liées au travail réel", "Ne poser que des questions théoriques", "Les laisser parler sans structure"], correctAnswer: "Poser des questions comportementales sur des expériences passées et donner des tâches pratiques liées au travail réel" },
  'A structured onboarding process significantly increases new hire retention and time-to-productivity.': { prompt: "Un processus d'intégration structuré augmente significativement la rétention des nouvelles recrues et le temps de productivité.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Leadership
  'What is the primary role of a leader in a business?': { prompt: "Quel est le rôle principal d'un leader dans une entreprise?", options: ["Faire tout le travail soi-même", "Définir la vision, responsabiliser l'équipe, supprimer les obstacles et créer un environnement où les gens font leur meilleur travail", "Micro-gérer chaque tâche", "Avoir le plus grand bureau"], correctAnswer: "Définir la vision, responsabiliser l'équipe, supprimer les obstacles et créer un environnement où les gens font leur meilleur travail" },
  'Effective leaders admit their mistakes and take responsibility rather than blaming their team.': { prompt: "Les leaders efficaces admettent leurs erreurs et prennent la responsabilité plutôt que de blâmer leur équipe.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is the difference between management and leadership?': { prompt: "Quelle est la différence entre management et leadership?", options: ["C'est la même chose", "Le management se concentre sur les processus et l'efficacité, tandis que le leadership se concentre sur la vision, l'inspiration et le développement des personnes", "Le management est toujours meilleur", "Le leadership est seulement pour les PDG"], correctAnswer: "Le management se concentre sur les processus et l'efficacité, tandis que le leadership se concentre sur la vision, l'inspiration et le développement des personnes" },
  'Giving regular, specific, and constructive ___ is one of the most important leadership skills for developing your team.': { prompt: "Donner un ___ régulier, spécifique et constructif est l'une des compétences de leadership les plus importantes pour développer votre équipe.", options: ["ordres", "feedback", "bonus", "cours"], correctAnswer: "feedback" },
  'Delegating tasks means you are being lazy as a leader.': { prompt: "Déléguer des tâches signifie que vous êtes paresseux en tant que leader.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'How should a leader handle conflict within their team?': { prompt: "Comment un leader devrait-il gérer les conflits au sein de son équipe?", options: ["L'ignorer et espérer que ça passe", "L'aborder directement et rapidement, écouter toutes les parties, se concentrer sur le problème plutôt que les personnalités, et faciliter une résolution", "Prendre un camp immédiatement", "Licencier les deux personnes impliquées"], correctAnswer: "L'aborder directement et rapidement, écouter toutes les parties, se concentrer sur le problème plutôt que les personnalités, et faciliter une résolution" },
  'What is "servant leadership"?': { prompt: "Qu'est-ce que le \"leadership serviteur\"?", options: ["Être un serviteur de vos employés", "Une philosophie de leadership où l'objectif principal du leader est de servir son équipe — supprimer les obstacles, fournir des ressources et prioriser la croissance de l'équipe", "Un style de leadership faible", "Le leadership par la peur"], correctAnswer: "Une philosophie de leadership où l'objectif principal du leader est de servir son équipe — supprimer les obstacles, fournir des ressources et prioriser la croissance de l'équipe" },
  'The best leaders create more leaders, not just followers.': { prompt: "Les meilleurs leaders créent plus de leaders, pas juste des suiveurs.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Operations
  'What are business operations?': { prompt: "Que sont les opérations d'entreprise?", options: ["Seulement les processus de fabrication", "Les activités, systèmes et processus quotidiens nécessaires pour faire fonctionner votre entreprise et livrer votre produit de manière cohérente", "Juste l'embauche et le licenciement", "Seulement la comptabilité"], correctAnswer: "Les activités, systèmes et processus quotidiens nécessaires pour faire fonctionner votre entreprise et livrer votre produit de manière cohérente" },
  'Documenting your business processes in Standard Operating Procedures (SOPs) makes your business more scalable and less dependent on any single person.': { prompt: "Documenter vos processus dans des Procédures Opérationnelles Standard (SOP) rend votre entreprise plus évolutive et moins dépendante d'une seule personne.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is a "bottleneck" in business operations?': { prompt: "Qu'est-ce qu'un \"goulot d'étranglement\" dans les opérations d'entreprise?", options: ["Un goulot de bouteille étroit", "Un point dans votre processus où le travail s'accumule parce que cette étape ne peut pas gérer le volume, ralentissant tout en aval", "Une stratégie marketing", "Un type de produit"], correctAnswer: "Un point dans votre processus où le travail s'accumule parce que cette étape ne peut pas gérer le volume, ralentissant tout en aval" },
  'What is the purpose of Key Performance Indicators (KPIs)?': { prompt: "Quel est le but des Indicateurs Clés de Performance (KPI)?", options: ["Avoir l'air impressionnant dans les rapports", "Mesurer des métriques spécifiques et quantifiables qui montrent si votre entreprise est sur la bonne voie pour atteindre ses objectifs", "Créer plus de paperasse", "Les KPI sont seulement pour les grandes entreprises"], correctAnswer: "Mesurer des métriques spécifiques et quantifiables qui montrent si votre entreprise est sur la bonne voie pour atteindre ses objectifs" },
  'The ___ methodology focuses on eliminating waste and maximizing value in business processes.': { prompt: "La méthodologie ___ se concentre sur l'élimination du gaspillage et la maximisation de la valeur dans les processus d'entreprise.", options: ["Lean", "Lourde", "Rapide", "Grande"], correctAnswer: "Lean" },
  'Automating repetitive tasks saves time and reduces human error in operations.': { prompt: "Automatiser les tâches répétitives économise du temps et réduit les erreurs humaines dans les opérations.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is "quality control" in operations?': { prompt: "Qu'est-ce que le \"contrôle qualité\" dans les opérations?", options: ["Contrôler vos employés", "Des systèmes et processus pour assurer que votre produit ou service répond de manière cohérente aux normes définies avant d'atteindre le client", "Une réglementation gouvernementale uniquement", "Vérifier la qualité une fois par an"], correctAnswer: "Des systèmes et processus pour assurer que votre produit ou service répond de manière cohérente aux normes définies avant d'atteindre le client" },
  'Small businesses do not need formal operations processes — they can figure things out as they go.': { prompt: "Les petites entreprises n'ont pas besoin de processus opérationnels formels — elles peuvent se débrouiller au fur et à mesure.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },

  // Partnerships, Funding, Legal, Scaling, Automation, Exit Strategy, Master CEO
  // (Abbreviated entries for remaining modules - key prompts from gameQuestions.ts)

  'What is a strategic business partnership?': { prompt: "Qu'est-ce qu'un partenariat stratégique d'entreprise?", options: ["Seulement une fusion légale", "Une relation mutuellement bénéfique entre deux entreprises où les deux parties accèdent à de nouveaux clients, ressources ou capacités", "Embaucher un consultant", "Toute amitié professionnelle"], correctAnswer: "Une relation mutuellement bénéfique entre deux entreprises où les deux parties accèdent à de nouveaux clients, ressources ou capacités" },
  'A written partnership agreement is essential even when partnering with friends or family.': { prompt: "Un accord de partenariat écrit est essentiel même en s'associant avec des amis ou de la famille.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What should you evaluate before entering a business partnership?': { prompt: "Que devriez-vous évaluer avant d'entrer dans un partenariat d'entreprise?", options: ["Seulement si vous aimez la personne", "Valeurs et objectifs alignés, compétences complémentaires, définition claire des rôles, attentes financières et comment vous gérerez les désaccords", "Seulement le chiffre d'affaires de l'autre", "Rien — les partenariats marchent toujours"], correctAnswer: "Valeurs et objectifs alignés, compétences complémentaires, définition claire des rôles, attentes financières et comment vous gérerez les désaccords" },
  'A ___ venture is a partnership where two or more businesses create a new entity together to pursue a specific opportunity.': { prompt: "Une ___ venture est un partenariat où deux ou plusieurs entreprises créent une nouvelle entité ensemble pour poursuivre une opportunité spécifique.", options: ["joint", "solo", "side", "main"], correctAnswer: "joint" },
  'What is a referral partnership?': { prompt: "Qu'est-ce qu'un partenariat de recommandation?", options: ["Un partenariat où vous payez des frais de recommandation à des inconnus", "Un accord où des entreprises complémentaires s'envoient des prospects qualifiés en échange d'une commission ou de recommandations réciproques", "Une collaboration sur les réseaux sociaux", "Un programme gouvernemental"], correctAnswer: "Un accord où des entreprises complémentaires s'envoient des prospects qualifiés en échange d'une commission ou de recommandations réciproques" },
  'Having an exit strategy in a partnership agreement from the beginning is unnecessary because good partnerships last forever.': { prompt: "Avoir une stratégie de sortie dans un accord de partenariat dès le début est inutile car les bons partenariats durent toujours.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is the biggest risk in a 50/50 business partnership?': { prompt: "Quel est le plus grand risque dans un partenariat 50/50?", options: ["Effort égal", "Impasse sur les décisions — quand les partenaires sont en désaccord et qu'aucun n'a la majorité pour trancher, l'entreprise peut être paralysée", "Profits égaux", "Responsabilité égale"], correctAnswer: "Impasse sur les décisions — quand les partenaires sont en désaccord et qu'aucun n'a la majorité pour trancher, l'entreprise peut être paralysée" },
  'The best partnerships are built on complementary strengths where each partner brings different but valuable skills and resources.': { prompt: "Les meilleurs partenariats sont construits sur des forces complémentaires où chaque partenaire apporte des compétences et ressources différentes mais précieuses.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Funding
  'What is "bootstrapping" a business?': { prompt: "Qu'est-ce que le \"bootstrapping\" d'une entreprise?", options: ["Utiliser un framework CSS Bootstrap", "Financer son entreprise avec ses économies personnelles et ses revenus plutôt qu'avec des investissements extérieurs, en gardant la pleine propriété", "Obtenir des subventions gouvernementales", "N'emprunter qu'aux banques"], correctAnswer: "Financer son entreprise avec ses économies personnelles et ses revenus plutôt qu'avec des investissements extérieurs, en gardant la pleine propriété" },
  'Venture capital is the best funding option for every type of business.': { prompt: "Le capital-risque est la meilleure option de financement pour tout type d'entreprise.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is an "angel investor"?': { prompt: "Qu'est-ce qu'un \"investisseur providentiel\" (angel investor)?", options: ["Un être divin qui aide les entreprises", "Un individu fortuné qui investit son propre argent dans des startups en démarrage en échange de parts, offrant souvent aussi du mentorat", "Une banque qui donne des prêts", "Un type de société de capital-risque"], correctAnswer: "Un individu fortuné qui investit son propre argent dans des startups en démarrage en échange de parts, offrant souvent aussi du mentorat" },
  'What does "equity dilution" mean when raising funds?': { prompt: "Que signifie la \"dilution des parts\" lors de la levée de fonds?", options: ["La qualité de votre produit diminue", "Votre pourcentage de propriété diminue chaque fois que vous donnez des parts à des investisseurs en échange de financement", "Votre équipe rétrécit", "Votre chiffre d'affaires baisse"], correctAnswer: "Votre pourcentage de propriété diminue chaque fois que vous donnez des parts à des investisseurs en échange de financement" },
  'Crowdfunding platforms like Kickstarter let entrepreneurs raise money from the ___ in exchange for early access, rewards, or equity.': { prompt: "Les plateformes de financement participatif comme Kickstarter permettent aux entrepreneurs de lever de l'argent auprès du ___ en échange d'un accès anticipé, de récompenses ou de parts.", options: ["gouvernement", "public", "banques", "concurrents"], correctAnswer: "public" },
  'Taking on debt (a business loan) means giving up ownership of your company.': { prompt: "Contracter une dette (un prêt commercial) signifie renoncer à la propriété de votre entreprise.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What should you have ready before approaching investors?': { prompt: "Que devriez-vous avoir prêt avant d'approcher des investisseurs?", options: ["Juste une bonne idée", "Un pitch deck convaincant, des projections financières, une compréhension claire de votre marché, une preuve de traction et une demande spécifique avec une utilisation définie des fonds", "Seulement votre CV", "Un produit fini sans croissance restante"], correctAnswer: "Un pitch deck convaincant, des projections financières, une compréhension claire de votre marché, une preuve de traction et une demande spécifique avec une utilisation définie des fonds" },
  'Revenue-based financing, where you repay a percentage of monthly revenue, is an alternative to traditional loans or equity that aligns repayment with your cash flow.': { prompt: "Le financement basé sur les revenus, où vous remboursez un pourcentage du chiffre d'affaires mensuel, est une alternative aux prêts traditionnels ou aux parts qui aligne le remboursement sur votre flux de trésorerie.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Legal Basics
  'Why should you form a legal business entity (like an LLC) rather than operate as a sole proprietor?': { prompt: "Pourquoi devriez-vous créer une entité juridique (comme une SARL) plutôt que d'opérer en tant qu'entreprise individuelle?", options: ["Ça sonne plus professionnel", "Une SARL crée une séparation juridique entre vos actifs personnels et les responsabilités de l'entreprise, vous protégeant si l'entreprise est poursuivie", "Il n'y a aucun avantage", "Seules les grandes entreprises ont besoin d'entités juridiques"], correctAnswer: "Une SARL crée une séparation juridique entre vos actifs personnels et les responsabilités de l'entreprise, vous protégeant si l'entreprise est poursuivie" },
  'A contract is only legally valid if it is written by a lawyer.': { prompt: "Un contrat n'est juridiquement valide que s'il est rédigé par un avocat.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is intellectual property (IP)?': { prompt: "Qu'est-ce que la propriété intellectuelle (PI)?", options: ["Seulement les brevets", "Les créations de l'esprit — inventions, designs, noms de marque, contenu écrit et code logiciel — qui peuvent être légalement protégées", "La propriété physique uniquement", "Un type d'immobilier"], correctAnswer: "Les créations de l'esprit — inventions, designs, noms de marque, contenu écrit et code logiciel — qui peuvent être légalement protégées" },
  'What is a "terms of service" agreement?': { prompt: "Qu'est-ce qu'un accord de \"conditions d'utilisation\"?", options: ["Un contrat de travail", "Un document juridique qui définit les règles, droits et responsabilités des utilisateurs de votre produit ou service", "Un document marketing", "Un accord d'investisseur"], correctAnswer: "Un document juridique qui définit les règles, droits et responsabilités des utilisateurs de votre produit ou service" },
  'A Non-Disclosure ___ (NDA) is a legal contract that prevents someone from sharing your confidential business information.': { prompt: "Un accord de non-___ (NDA) est un contrat légal qui empêche quelqu'un de partager vos informations commerciales confidentielles.", options: ["divulgation", "document", "demande", "évaluation"], correctAnswer: "divulgation" },
  'You do not need to collect sales tax if you are a small online business.': { prompt: "Vous n'avez pas besoin de collecter la taxe de vente si vous êtes une petite entreprise en ligne.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is the purpose of a privacy policy for a business with a website or app?': { prompt: "Quel est le but d'une politique de confidentialité pour une entreprise avec un site web ou une application?", options: ["C'est une décoration optionnelle", "Elle divulgue légalement comment vous collectez, utilisez, stockez et protégez les données des utilisateurs — et c'est requis par la loi dans la plupart des juridictions", "Elle ne s'applique qu'aux entreprises de réseaux sociaux", "C'est la même chose que les conditions d'utilisation"], correctAnswer: "Elle divulgue légalement comment vous collectez, utilisez, stockez et protégez les données des utilisateurs — et c'est requis par la loi dans la plupart des juridictions" },
  'Consulting a lawyer before signing major contracts, leases, or partnership agreements is a worthwhile investment.': { prompt: "Consulter un avocat avant de signer des contrats majeurs, baux ou accords de partenariat est un investissement qui en vaut la peine.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Scaling Up
  'What does "scaling" a business mean?': { prompt: "Que signifie \"scaler\" une entreprise?", options: ["Agrandir votre bureau", "Augmenter significativement le chiffre d'affaires sans augmentation proportionnelle des coûts ou ressources", "Embaucher plus de personnes linéairement avec la croissance", "Déménager dans un autre pays"], correctAnswer: "Augmenter significativement le chiffre d'affaires sans augmentation proportionnelle des coûts ou ressources" },
  'A business should focus on scaling before it has achieved product-market fit and a repeatable sales process.': { prompt: "Une entreprise devrait se concentrer sur le scaling avant d'avoir atteint l'adéquation produit-marché et un processus de vente reproductible.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Which is the biggest challenge when scaling a business?': { prompt: "Quel est le plus grand défi lors du scaling d'une entreprise?", options: ["Avoir plus d'espace de bureau", "Maintenir la qualité, la culture et l'expérience client tout en croissant rapidement", "Changer le nom de l'entreprise", "Licencier tous les employés d'origine"], correctAnswer: "Maintenir la qualité, la culture et l'expérience client tout en croissant rapidement" },
  'What is a "scalable" business model?': { prompt: "Qu'est-ce qu'un modèle d'affaires \"scalable\"?", options: ["Toute entreprise qui existe", "Un modèle où vous pouvez servir significativement plus de clients sans augmenter proportionnellement les coûts — comme les logiciels, produits numériques ou services productisés", "Seulement les entreprises tech", "Une entreprise qui ne change jamais"], correctAnswer: "Un modèle où vous pouvez servir significativement plus de clients sans augmenter proportionnellement les coûts — comme les logiciels, produits numériques ou services productisés" },
  'The "___" framework by Verne Harnish identifies four key areas for scaling: People, Strategy, Execution, and Cash.': { prompt: "Le cadre \"___\" de Verne Harnish identifie quatre domaines clés pour le scaling : Personnes, Stratégie, Exécution et Trésorerie.", options: ["Lean", "Scaling Up", "Startup", "Growth"], correctAnswer: "Scaling Up" },
  'Automating and systematizing your core processes is essential before you can scale effectively.': { prompt: "Automatiser et systématiser vos processus de base est essentiel avant de pouvoir scaler efficacement.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'SITUATION: Your business is growing 50% year-over-year but your team is burned out and quality is slipping. What should you do?': { prompt: "SITUATION : Votre entreprise croît de 50% par an mais votre équipe est épuisée et la qualité diminue. Que devriez-vous faire?", options: ["Continuer à pousser la croissance", "Pauser la croissance agressive, corriger les systèmes internes, embaucher et former pour gérer le volume actuel, puis reprendre le scaling sur une base plus solide", "Vendre l'entreprise immédiatement", "Ignorer les problèmes de qualité"], correctAnswer: "Pauser la croissance agressive, corriger les systèmes internes, embaucher et former pour gérer le volume actuel, puis reprendre le scaling sur une base plus solide" },
  'Key hires in leadership and management positions become increasingly important as you scale, since the founder cannot manage everything directly.': { prompt: "Les embauches clés aux postes de leadership et de management deviennent de plus en plus importantes à mesure que vous scalez, car le fondateur ne peut pas tout gérer directement.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Automation (Business)
  'What is business automation?': { prompt: "Qu'est-ce que l'automatisation d'entreprise?", options: ["Remplacer tous les employés par des robots", "Utiliser la technologie et des outils pour effectuer automatiquement des tâches répétitives, libérant du temps humain pour le travail créatif et stratégique", "Seulement pour les entreprises manufacturières", "Rendre votre site web plus rapide"], correctAnswer: "Utiliser la technologie et des outils pour effectuer automatiquement des tâches répétitives, libérant du temps humain pour le travail créatif et stratégique" },
  'Small businesses can benefit from automation just as much as large corporations.': { prompt: "Les petites entreprises peuvent bénéficier de l'automatisation autant que les grandes entreprises.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Which business process is the best candidate for automation?': { prompt: "Quel processus d'entreprise est le meilleur candidat pour l'automatisation?", options: ["Les décisions de stratégie créative", "Les tâches répétitives basées sur des règles qui se produisent fréquemment et suivent un schéma cohérent — comme envoyer des emails de bienvenue ou mettre à jour des tableurs", "Les projets uniques ponctuels", "Les conversations émotionnelles avec les clients"], correctAnswer: "Les tâches répétitives basées sur des règles qui se produisent fréquemment et suivent un schéma cohérent — comme envoyer des emails de bienvenue ou mettre à jour des tableurs" },
  'What is a "workflow automation" tool?': { prompt: "Qu'est-ce qu'un outil d'\"automatisation de workflow\"?", options: ["Une application de liste de tâches", "Un logiciel qui connecte différentes applications et déclenche des actions automatiques entre elles", "Un outil de gestion de projet uniquement", "Un langage de programmation"], correctAnswer: "Un logiciel qui connecte différentes applications et déclenche des actions automatiques entre elles" },
  'An email ___ sequence automatically sends a series of pre-written emails to new subscribers or customers over a set period.': { prompt: "Une séquence email de ___ envoie automatiquement une série d'emails pré-écrits aux nouveaux abonnés ou clients sur une période définie.", options: ["blast", "goutte-à-goutte", "spam", "masse"], correctAnswer: "goutte-à-goutte" },
  'You should automate everything in your business, including personalized client relationships.': { prompt: "Vous devriez tout automatiser dans votre entreprise, y compris les relations personnalisées avec les clients.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is the first step to automating your business processes?': { prompt: "Quelle est la première étape pour automatiser vos processus d'entreprise?", options: ["Acheter le logiciel le plus cher", "Cartographier vos processus actuels, identifier les tâches répétitives les plus chronophages et prioriser l'automatisation de celles avec le plus grand impact", "Tout automatiser d'un coup", "Embaucher un consultant en automatisation immédiatement"], correctAnswer: "Cartographier vos processus actuels, identifier les tâches répétitives les plus chronophages et prioriser l'automatisation de celles avec le plus grand impact" },
  'Chatbots and AI can handle common customer questions automatically, reducing response times and freeing up your team for complex issues.': { prompt: "Les chatbots et l'IA peuvent gérer automatiquement les questions courantes des clients, réduisant les temps de réponse et libérant votre équipe pour les problèmes complexes.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Exit Strategy
  'What is an exit strategy?': { prompt: "Qu'est-ce qu'une stratégie de sortie?", options: ["Savoir où sont les sorties de secours dans votre bureau", "Une approche planifiée pour comment vous quitterez éventuellement votre entreprise — par vente, fusion, introduction en bourse ou succession — idéalement en maximisant la valeur", "Abandonner quand ça devient difficile", "Un plan pour votre dernier jour de travail"], correctAnswer: "Une approche planifiée pour comment vous quitterez éventuellement votre entreprise — par vente, fusion, introduction en bourse ou succession — idéalement en maximisant la valeur" },
  'You should think about your exit strategy from the very beginning, not just when you are ready to sell.': { prompt: "Vous devriez penser à votre stratégie de sortie dès le début, pas seulement quand vous êtes prêt à vendre.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What makes a business attractive to potential buyers?': { prompt: "Qu'est-ce qui rend une entreprise attractive pour les acheteurs potentiels?", options: ["L'implication personnelle du propriétaire dans tout", "Des revenus récurrents, des processus documentés, une équipe solide, une base de clients diversifiée et une croissance constante sans que le propriétaire soit nécessaire au quotidien", "De grands bureaux", "Le plus d'abonnés sur les réseaux sociaux"], correctAnswer: "Des revenus récurrents, des processus documentés, une équipe solide, une base de clients diversifiée et une croissance constante sans que le propriétaire soit nécessaire au quotidien" },
  'What is the difference between an asset sale and a stock sale?': { prompt: "Quelle est la différence entre une vente d'actifs et une vente d'actions?", options: ["Il n'y a pas de différence", "Dans une vente d'actifs, l'acheteur achète des actifs spécifiques ; dans une vente d'actions, l'acheteur achète les parts de propriété de l'ensemble de l'entreprise incluant tous les actifs et passifs", "Les ventes d'actifs sont toujours meilleures", "Les ventes d'actions sont seulement pour les entreprises publiques"], correctAnswer: "Dans une vente d'actifs, l'acheteur achète des actifs spécifiques ; dans une vente d'actions, l'acheteur achète les parts de propriété de l'ensemble de l'entreprise incluant tous les actifs et passifs" },
  'Business valuation often uses a multiple of ___, which represents the true profitability of the business after adjusting for owner expenses.': { prompt: "L'évaluation d'entreprise utilise souvent un multiple de ___, qui représente la vraie rentabilité de l'entreprise après ajustement des dépenses du propriétaire.", options: ["chiffre d'affaires", "bénéfices", "abonnés", "employés"], correctAnswer: "bénéfices" },
  'If your business depends entirely on you personally for client relationships and service delivery, it will be very difficult to sell.': { prompt: "Si votre entreprise dépend entièrement de vous personnellement pour les relations clients et la livraison de services, il sera très difficile de la vendre.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is an "earn-out" in a business sale?': { prompt: "Qu'est-ce qu'un \"earn-out\" dans une vente d'entreprise?", options: ["Gagner de l'argent avant la vente", "Une structure de deal où une partie du prix d'achat est payée dans le temps en fonction de l'atteinte de certains objectifs de performance après la vente", "Un type de prêt", "Gagner la confiance de vos employés"], correctAnswer: "Une structure de deal où une partie du prix d'achat est payée dans le temps en fonction de l'atteinte de certains objectifs de performance après la vente" },
  'Planning your exit 3-5 years in advance allows you to maximize the sale price by optimizing the business for what buyers value most.': { prompt: "Planifier votre sortie 3-5 ans à l'avance vous permet de maximiser le prix de vente en optimisant l'entreprise pour ce que les acheteurs valorisent le plus.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },

  // Master CEO
  'What is the primary focus of a CEO versus a manager?': { prompt: "Quel est le focus principal d'un PDG par rapport à un manager?", options: ["Les PDG et les managers font la même chose", "Un PDG se concentre sur la vision, la stratégie, la culture et les relations externes, tandis qu'un manager se concentre sur l'exécution, les processus et la performance de l'équipe", "Les PDG font tout le travail eux-mêmes", "Les managers prennent des décisions plus importantes"], correctAnswer: "Un PDG se concentre sur la vision, la stratégie, la culture et les relations externes, tandis qu'un manager se concentre sur l'exécution, les processus et la performance de l'équipe" },
  'A Master CEO spends most of their time working IN the business on daily tasks rather than ON the business on strategy and growth.': { prompt: "Un PDG maître passe la plupart de son temps à travailler DANS l'entreprise sur les tâches quotidiennes plutôt que SUR l'entreprise sur la stratégie et la croissance.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'What is "strategic thinking" and why is it essential for a CEO?': { prompt: "Qu'est-ce que la \"pensée stratégique\" et pourquoi est-elle essentielle pour un PDG?", options: ["Penser à des stratégies de jeux vidéo", "La capacité d'analyser le paysage concurrentiel, anticiper les tendances futures et prendre des décisions qui positionnent l'entreprise pour le succès à long terme", "Penser à quoi faire aujourd'hui", "Seulement pertinent lors des réunions de planification"], correctAnswer: "La capacité d'analyser le paysage concurrentiel, anticiper les tendances futures et prendre des décisions qui positionnent l'entreprise pour le succès à long terme" },
  'A CEO quarterly ___ session with the leadership team reviews progress, adjusts strategy, and sets priorities for the next 90 days.': { prompt: "Une session de ___ trimestrielle du PDG avec l'équipe de direction examine les progrès, ajuste la stratégie et définit les priorités pour les 90 prochains jours.", options: ["vacances", "planification", "fête", "embauche"], correctAnswer: "planification" },
  'How should a CEO prioritize their time?': { prompt: "Comment un PDG devrait-il prioriser son temps?", options: ["Répondre à chaque email immédiatement", "Se concentrer sur les quelques activités à fort impact que seul lui peut faire — stratégie, relations clés, culture et décisions qui font avancer significativement l'entreprise", "Assister à chaque réunion", "Faire ce qui semble urgent"], correctAnswer: "Se concentrer sur les quelques activités à fort impact que seul lui peut faire — stratégie, relations clés, culture et décisions qui font avancer significativement l'entreprise" },
  'Building a strong company culture is one of the CEO most important responsibilities because it shapes how every employee makes decisions.': { prompt: "Construire une culture d'entreprise forte est l'une des responsabilités les plus importantes du PDG car elle façonne la façon dont chaque employé prend des décisions.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'What is the role of a CEO in building the senior leadership team?': { prompt: "Quel est le rôle d'un PDG dans la construction de l'équipe de direction?", options: ["Tout faire soi-même", "Recruter, développer et retenir des leaders exceptionnels qui peuvent prendre en charge les grandes fonctions de l'entreprise", "N'embaucher que des travailleurs bon marché", "Éviter d'avoir quelqu'un de trop talentueux qui pourrait menacer votre position"], correctAnswer: "Recruter, développer et retenir des leaders exceptionnels qui peuvent prendre en charge les grandes fonctions de l'entreprise" },
  'A Master CEO continuously invests in their own learning and personal development because the business can only grow as far as the leader grows.': { prompt: "Un PDG maître investit continuellement dans son propre apprentissage et développement personnel car l'entreprise ne peut croître que dans la mesure où le leader croît.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
};

export default businessFr;
