export const codingFr: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // What is Code?
  'What is the primary purpose of code?': { prompt: "Quel est le but principal du code?", options: ["Rendre les ordinateurs jolis", "Donner des instructions à un ordinateur", "Remplacer le matériel", "Se connecter à internet"], correctAnswer: "Donner des instructions à un ordinateur" },
  'Which of the following is a programming language?': { prompt: "Lequel des suivants est un langage de programmation?", options: ["HTML", "JavaScript", "Photoshop", "Windows"], correctAnswer: "JavaScript" },
  'What does a compiler do?': { prompt: "Que fait un compilateur?", options: ["Exécute le code ligne par ligne", "Traduit le code en langage machine avant l'exécution", "Conçoit des interfaces utilisateur", "Se connecte aux bases de données"], correctAnswer: "Traduit le code en langage machine avant l'exécution" },
  'What is the output of a "Hello World" program?': { prompt: 'Quel est le résultat d\'un programme "Hello World"?', options: ["Il crée un site web", 'Il affiche le texte "Hello World"', "Il installe un logiciel", "Il ouvre un navigateur"], correctAnswer: 'Il affiche le texte "Hello World"' },
  'Python and JavaScript are both programming languages.': { prompt: "Python et JavaScript sont tous deux des langages de programmation.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Computers can understand human language directly without code.': { prompt: "Les ordinateurs peuvent comprendre directement le langage humain sans code.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'An algorithm is a step-by-step set of instructions to solve a problem.': { prompt: "Un algorithme est un ensemble d'instructions étape par étape pour résoudre un problème.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A ___ is a software that translates code into machine-readable instructions line by line at runtime.': { prompt: "Un ___ est un logiciel qui traduit le code en instructions lisibles par la machine ligne par ligne à l'exécution.", options: ["Compilateur", "Interpréteur", "Débogueur", "Éditeur"], correctAnswer: "Interpréteur" },

  // Variables
  'Which keyword declares a variable that can be reassigned in JavaScript?': { prompt: "Quel mot-clé déclare une variable qui peut être réassignée en JavaScript?", options: ["const", "let", "final", "static"], correctAnswer: "let" },
  'What will `let x = 5; x = 10; console.log(x);` output?': { prompt: "Que va afficher `let x = 5; x = 10; console.log(x);`?", options: ["5", "10", "undefined", "Error"], correctAnswer: "10" },
  'Which keyword creates a variable that cannot be reassigned?': { prompt: "Quel mot-clé crée une variable qui ne peut pas être réassignée?", options: ["var", "let", "const", "mut"], correctAnswer: "const" },
  'What is the scope of a variable declared with "var" inside a function?': { prompt: 'Quelle est la portée d\'une variable déclarée avec "var" dans une fonction?', options: ["Portée de bloc", "Portée de fonction", "Portée globale", "Portée de module"], correctAnswer: "Portée de fonction" },
  'What happens if you use a variable before declaring it with "let"?': { prompt: 'Que se passe-t-il si vous utilisez une variable avant de la déclarer avec "let"?', options: ["Elle retourne undefined", "Elle lance une ReferenceError", "Elle retourne null", "Ça fonctionne normalement"], correctAnswer: "Elle lance une ReferenceError" },
  'In JavaScript, variable names can start with a number.': { prompt: "En JavaScript, les noms de variables peuvent commencer par un chiffre.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  '"let" and "const" are block-scoped in JavaScript.': { prompt: '"let" et "const" ont une portée de bloc en JavaScript.', options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The naming convention "myVariableName" is called ___.': { prompt: 'La convention de nommage "myVariableName" s\'appelle ___.', options: ["snake_case", "camelCase", "PascalCase", "kebab-case"], correctAnswer: "camelCase" },

  // Data Types
  'Which of these is NOT a primitive data type in JavaScript?': { prompt: "Lequel n'est PAS un type de données primitif en JavaScript?", options: ["string", "number", "boolean", "array"], correctAnswer: "array" },
  'What does typeof null return in JavaScript?': { prompt: "Que retourne typeof null en JavaScript?", options: ['"null"', '"undefined"', '"object"', '"boolean"'], correctAnswer: '"object"' },
  'What is the result of "5" + 3 in JavaScript?': { prompt: 'Quel est le résultat de "5" + 3 en JavaScript?', options: ["8", '"53"', "NaN", "Error"], correctAnswer: '"53"' },
  'Which data type represents true or false?': { prompt: "Quel type de données représente vrai ou faux?", options: ["string", "number", "boolean", "null"], correctAnswer: "boolean" },
  'NaN stands for "Not a Number" and its type is "number".': { prompt: 'NaN signifie "Not a Number" et son type est "number".', options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'undefined and null are the same thing in JavaScript.': { prompt: "undefined et null sont la même chose en JavaScript.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'JavaScript is a dynamically typed language.': { prompt: "JavaScript est un langage à typage dynamique.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The JavaScript operator ___ is used to check the data type of a variable.': { prompt: "L'opérateur JavaScript ___ est utilisé pour vérifier le type de données d'une variable.", options: ["instanceof", "typeof", "datatype", "checktype"], correctAnswer: "typeof" },

  // If/Else
  'What does the "else if" statement do?': { prompt: 'Que fait l\'instruction "else if"?', options: ["Termine le programme", "Vérifie une autre condition si la précédente était fausse", "Boucle le code", "Déclare une variable"], correctAnswer: "Vérifie une autre condition si la précédente était fausse" },
  'What is the result of: if (0) { "yes" } else { "no" }?': { prompt: 'Quel est le résultat de : if (0) { "yes" } else { "no" }?', options: ['"yes"', '"no"', "undefined", "Error"], correctAnswer: '"no"' },
  'Which operator checks equality WITHOUT type coercion?': { prompt: "Quel opérateur vérifie l'égalité SANS conversion de type?", options: ["==", "===", "!=", ">="], correctAnswer: "===" },
  'What is a ternary operator?': { prompt: "Qu'est-ce qu'un opérateur ternaire?", options: ["Une boucle qui s'exécute trois fois", "Un raccourci pour if/else : condition ? a : b", "Une fonction à trois paramètres", "Un opérateur qui compare trois valeurs"], correctAnswer: "Un raccourci pour if/else : condition ? a : b" },
  'Which value is NOT falsy in JavaScript?': { prompt: "Quelle valeur n'est PAS falsy en JavaScript?", options: ["0", '""', '"false"', "null"], correctAnswer: '"false"' },
  'In JavaScript, "else" can exist without a preceding "if".': { prompt: 'En JavaScript, "else" peut exister sans un "if" précédent.', options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'The condition (5 == "5") returns true in JavaScript.': { prompt: 'La condition (5 == "5") retourne true en JavaScript.', options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A ___ statement is used to select one of many code blocks to execute based on a value.': { prompt: "Une instruction ___ est utilisée pour sélectionner un bloc de code parmi plusieurs à exécuter selon une valeur.", options: ["if", "switch", "loop", "try"], correctAnswer: "switch" },

  // Loops
  'Which loop is best when you know the exact number of iterations?': { prompt: "Quelle boucle est la meilleure quand vous connaissez le nombre exact d'itérations?", options: ["while", "do...while", "for", "forEach"], correctAnswer: "for" },
  'What does the "break" statement do inside a loop?': { prompt: 'Que fait l\'instruction "break" dans une boucle?', options: ["Passe à l'itération suivante", "Quitte la boucle immédiatement", "Redémarre la boucle", "Met la boucle en pause"], correctAnswer: "Quitte la boucle immédiatement" },
  'How many times does this loop run? for(let i=0; i<3; i++)': { prompt: "Combien de fois cette boucle s'exécute-t-elle? for(let i=0; i<3; i++)", options: ["2", "3", "4", "Infini"], correctAnswer: "3" },
  'What is an infinite loop?': { prompt: "Qu'est-ce qu'une boucle infinie?", options: ["Une boucle qui s'exécute exactement 1000 fois", "Une boucle dont la condition ne devient jamais fausse", "Une boucle dans une autre boucle", "Une boucle qui s'exécute à l'envers"], correctAnswer: "Une boucle dont la condition ne devient jamais fausse" },
  'A "do...while" loop always executes its body at least once.': { prompt: 'Une boucle "do...while" exécute toujours son corps au moins une fois.', options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The "continue" statement exits the entire loop.': { prompt: 'L\'instruction "continue" quitte toute la boucle.', options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'You can nest loops inside other loops.': { prompt: "On peut imbriquer des boucles dans d'autres boucles.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The ___ loop in JavaScript iterates over the values of an iterable object like an array.': { prompt: "La boucle ___ en JavaScript itère sur les valeurs d'un objet itérable comme un tableau.", options: ["for...in", "for...of", "while", "forEach"], correctAnswer: "for...of" },

  // Functions
  'What is a function in programming?': { prompt: "Qu'est-ce qu'une fonction en programmation?", options: ["Un type de variable", "Un bloc de code réutilisable qui effectue une tâche", "Une propriété CSS", "Une requête de base de données"], correctAnswer: "Un bloc de code réutilisable qui effectue une tâche" },
  'What does the "return" keyword do?': { prompt: 'Que fait le mot-clé "return"?', options: ["Arrête tout le programme", "Renvoie une valeur de la fonction et la quitte", "Affiche une valeur dans la console", "Appelle une autre fonction"], correctAnswer: "Renvoie une valeur de la fonction et la quitte" },
  'What is an arrow function in JavaScript?': { prompt: "Qu'est-ce qu'une fonction fléchée en JavaScript?", options: ["Une fonction qui dessine des flèches", "Une syntaxe plus courte pour écrire des fonctions : () => {}", "Une fonction qui ne s'exécute qu'une fois", "Une fonction d'une bibliothèque"], correctAnswer: "Une syntaxe plus courte pour écrire des fonctions : () => {}" },
  'What is a callback function?': { prompt: "Qu'est-ce qu'une fonction de rappel (callback)?", options: ["Une fonction qui s'appelle elle-même", "Une fonction passée en argument à une autre fonction", "Une fonction qui ne retourne rien", "Une fonction qui s'exécute automatiquement"], correctAnswer: "Une fonction passée en argument à une autre fonction" },
  'What are default parameters?': { prompt: "Que sont les paramètres par défaut?", options: ["Des paramètres qui doivent toujours être fournis", "Des valeurs assignées aux paramètres si aucun argument n'est passé", "Des paramètres qui ne peuvent pas changer", "Le premier paramètre d'une fonction"], correctAnswer: "Des valeurs assignées aux paramètres si aucun argument n'est passé" },
  'A function without a return statement returns undefined.': { prompt: "Une fonction sans instruction return retourne undefined.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Arrow functions have their own "this" context.': { prompt: 'Les fonctions fléchées ont leur propre contexte "this".', options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A function that calls itself is known as a ___ function.': { prompt: "Une fonction qui s'appelle elle-même est connue comme une fonction ___.", options: ["callback", "récursive", "anonyme", "génératrice"], correctAnswer: "récursive" },

  // Arrays
  'How do you access the first element of an array called "arr"?': { prompt: 'Comment accéder au premier élément d\'un tableau appelé "arr"?', options: ["arr[1]", "arr[0]", "arr.first()", "arr.get(0)"], correctAnswer: "arr[0]" },
  'Which method adds an element to the END of an array?': { prompt: "Quelle méthode ajoute un élément à la FIN d'un tableau?", options: ["unshift()", "push()", "pop()", "shift()"], correctAnswer: "push()" },
  'What does the .map() method do?': { prompt: "Que fait la méthode .map()?", options: ["Filtre les éléments d'un tableau", "Crée un nouveau tableau en transformant chaque élément", "Trie le tableau", "Trouve un seul élément"], correctAnswer: "Crée un nouveau tableau en transformant chaque élément" },
  'What does .filter() return?': { prompt: "Que retourne .filter()?", options: ["Une seule valeur", "Un nouveau tableau avec les éléments qui passent un test", "Le tableau original modifié", "Un booléen"], correctAnswer: "Un nouveau tableau avec les éléments qui passent un test" },
  'What does [1,2,3].reduce((acc, val) => acc + val, 0) return?': { prompt: "Que retourne [1,2,3].reduce((acc, val) => acc + val, 0)?", options: ["[1,2,3]", "6", "0", "3"], correctAnswer: "6" },
  'The .splice() method modifies the original array.': { prompt: "La méthode .splice() modifie le tableau original.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Array.isArray([]) returns true.': { prompt: "Array.isArray([]) retourne true.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The ___ method removes the last element from an array and returns it.': { prompt: "La méthode ___ supprime le dernier élément d'un tableau et le retourne.", options: ["push()", "pop()", "shift()", "slice()"], correctAnswer: "pop()" },

  // Objects
  'How do you access the "name" property of an object called "user"?': { prompt: 'Comment accéder à la propriété "name" d\'un objet appelé "user"?', options: ["user[name]", "user.name", "user->name", "user::name"], correctAnswer: "user.name" },
  'What does Object.keys(obj) return?': { prompt: "Que retourne Object.keys(obj)?", options: ["Un tableau des valeurs de l'objet", "Un tableau des clés de l'objet", "Le nombre de clés", "Une copie de l'objet"], correctAnswer: "Un tableau des clés de l'objet" },
  'What is destructuring?': { prompt: "Qu'est-ce que la déstructuration?", options: ["Supprimer un objet", "Extraire des valeurs d'objets/tableaux dans des variables", "Fusionner deux objets", "Convertir un objet en chaîne"], correctAnswer: "Extraire des valeurs d'objets/tableaux dans des variables" },
  'What does the spread operator (...) do with objects?': { prompt: "Que fait l'opérateur spread (...) avec les objets?", options: ["Supprime toutes les propriétés", "Crée une copie superficielle ou fusionne des objets", "Convertit l'objet en tableau", "Gèle l'objet"], correctAnswer: "Crée une copie superficielle ou fusionne des objets" },
  'In JavaScript, arrays are a special type of object.': { prompt: "En JavaScript, les tableaux sont un type spécial d'objet.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Object.freeze() makes an object completely immutable at all levels.': { prompt: "Object.freeze() rend un objet complètement immuable à tous les niveaux.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'You can use bracket notation to access properties with spaces: obj["my prop"].': { prompt: 'On peut utiliser la notation crochets pour accéder aux propriétés avec des espaces : obj["my prop"].', options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A method is a ___ stored as an object property.': { prompt: "Une méthode est une ___ stockée comme propriété d'un objet.", options: ["chaîne", "nombre", "fonction", "booléen"], correctAnswer: "fonction" },

  // String Methods
  'What does "hello".toUpperCase() return?': { prompt: 'Que retourne "hello".toUpperCase()?', options: ['"Hello"', '"HELLO"', '"hello"', "Error"], correctAnswer: '"HELLO"' },
  'What does "hello world".split(" ") return?': { prompt: 'Que retourne "hello world".split(" ")?', options: ['"hello world"', '["hello", "world"]', '["hello world"]', '["h","e","l","l","o"," ","w","o","r","l","d"]'], correctAnswer: '["hello", "world"]' },
  'Which method checks if a string contains a substring?': { prompt: "Quelle méthode vérifie si une chaîne contient une sous-chaîne?", options: ["has()", "contains()", "includes()", "find()"], correctAnswer: "includes()" },
  'What does "  hello  ".trim() return?': { prompt: 'Que retourne "  hello  ".trim()?', options: ['"  hello  "', '"hello  "', '"  hello"', '"hello"'], correctAnswer: '"hello"' },
  'What are template literals in JavaScript?': { prompt: "Que sont les template literals en JavaScript?", options: ["Des chaînes avec des guillemets simples", "Des chaînes avec des backticks qui supportent les expressions : `${var}`", "Des chaînes qui ne peuvent pas changer", "Des chaînes stockées dans des templates"], correctAnswer: "Des chaînes avec des backticks qui supportent les expressions : `${var}`" },
  'Strings in JavaScript are immutable.': { prompt: "Les chaînes en JavaScript sont immuables.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  '"abc".indexOf("z") returns -1.': { prompt: '"abc".indexOf("z") retourne -1.', options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The ___ method extracts a section of a string and returns it as a new string.': { prompt: "La méthode ___ extrait une section d'une chaîne et la retourne comme nouvelle chaîne.", options: ["splice()", "slice()", "split()", "substr()"], correctAnswer: "slice()" },

  // Error Handling
  'Which block catches errors in JavaScript?': { prompt: "Quel bloc capture les erreurs en JavaScript?", options: ["if/else", "try/catch", "for/while", "switch/case"], correctAnswer: "try/catch" },
  'What does the "finally" block do?': { prompt: 'Que fait le bloc "finally"?', options: ["S'exécute seulement s'il y a une erreur", "S'exécute seulement s'il n'y a pas d'erreur", "S'exécute qu'il y ait ou non une erreur", "Empêche les erreurs de se produire"], correctAnswer: "S'exécute qu'il y ait ou non une erreur" },
  'How do you create a custom error in JavaScript?': { prompt: "Comment créer une erreur personnalisée en JavaScript?", options: ['error("message")', 'throw new Error("message")', 'new Exception("message")', 'raise("message")'], correctAnswer: 'throw new Error("message")' },
  'What type of error is accessing an undeclared variable?': { prompt: "Quel type d'erreur est l'accès à une variable non déclarée?", options: ["SyntaxError", "TypeError", "ReferenceError", "RangeError"], correctAnswer: "ReferenceError" },
  'A SyntaxError occurs when code violates the language grammar rules.': { prompt: "Une SyntaxError survient quand le code viole les règles de grammaire du langage.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'You can have a try block without a catch block if you include finally.': { prompt: "On peut avoir un bloc try sans bloc catch si on inclut finally.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'TypeError occurs when a value is not of the expected type.': { prompt: "TypeError survient quand une valeur n'est pas du type attendu.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The ___ keyword is used to manually trigger an error in JavaScript.': { prompt: "Le mot-clé ___ est utilisé pour déclencher manuellement une erreur en JavaScript.", options: ["catch", "error", "throw", "raise"], correctAnswer: "throw" },

  // DOM Basics
  'What does DOM stand for?': { prompt: "Que signifie DOM?", options: ["Data Object Model", "Document Object Model", "Digital Output Mechanism", "Document Oriented Mapping"], correctAnswer: "Document Object Model" },
  'Which method selects an element by its ID?': { prompt: "Quelle méthode sélectionne un élément par son ID?", options: ["querySelector()", "getElementById()", "getElementsByClass()", "findElement()"], correctAnswer: "getElementById()" },
  'What does document.querySelector(".box") select?': { prompt: 'Que sélectionne document.querySelector(".box")?', options: ['Tous les éléments avec la classe "box"', 'Le premier élément avec la classe "box"', 'L\'élément avec l\'ID "box"', "Rien"], correctAnswer: 'Le premier élément avec la classe "box"' },
  'How do you change the text inside an element?': { prompt: "Comment changer le texte à l'intérieur d'un élément?", options: ["element.value", "element.textContent", "element.text", "element.setText()"], correctAnswer: "element.textContent" },
  'innerHTML can be used to insert HTML tags into an element.': { prompt: "innerHTML peut être utilisé pour insérer des balises HTML dans un élément.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'querySelectorAll() returns a live HTMLCollection.': { prompt: "querySelectorAll() retourne une HTMLCollection dynamique.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'The DOM is created by the browser when it loads an HTML page.': { prompt: "Le DOM est créé par le navigateur quand il charge une page HTML.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The ___ property is used to change the CSS styles of a DOM element directly.': { prompt: "La propriété ___ est utilisée pour changer directement les styles CSS d'un élément DOM.", options: ["css", "style", "class", "design"], correctAnswer: "style" },

  // Events
  'Which method attaches an event handler to an element?': { prompt: "Quelle méthode attache un gestionnaire d'événements à un élément?", options: ["onClick()", "addEventListener()", "attachEvent()", "bindEvent()"], correctAnswer: "addEventListener()" },
  'What is event bubbling?': { prompt: "Qu'est-ce que le bouillonnement d'événements (event bubbling)?", options: ["Les événements vont du parent vers l'enfant", "Les événements vont de l'enfant vers le parent", "Les événements ne se déclenchent que sur la cible", "Les événements sont annulés automatiquement"], correctAnswer: "Les événements vont de l'enfant vers le parent" },
  'Which event fires when a user submits a form?': { prompt: "Quel événement se déclenche quand un utilisateur soumet un formulaire?", options: ["click", "submit", "change", "input"], correctAnswer: "submit" },
  'What does event.preventDefault() do?': { prompt: "Que fait event.preventDefault()?", options: ["Arrête le bouillonnement", "Empêche le comportement par défaut du navigateur", "Supprime le gestionnaire d'événements", "Déclenche l'événement à nouveau"], correctAnswer: "Empêche le comportement par défaut du navigateur" },
  'What does event.stopPropagation() do?': { prompt: "Que fait event.stopPropagation()?", options: ["Empêche le comportement par défaut", "Empêche l'événement de remonter aux éléments parents", "Supprime tous les gestionnaires d'événements", "Met l'événement en pause"], correctAnswer: "Empêche l'événement de remonter aux éléments parents" },
  'You can add multiple event listeners of the same type to one element.': { prompt: "On peut ajouter plusieurs gestionnaires d'événements du même type à un élément.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The "change" event fires on every keystroke in an input field.': { prompt: 'L\'événement "change" se déclenche à chaque frappe dans un champ de saisie.', options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Event ___ is the opposite of bubbling, where events flow from the root down to the target.': { prompt: "La ___ d'événement est l'opposé du bouillonnement, où les événements vont de la racine vers la cible.", options: ["délégation", "capture", "propagation", "liaison"], correctAnswer: "capture" },

  // APIs
  'What does API stand for?': { prompt: "Que signifie API?", options: ["Advanced Programming Interface", "Application Programming Interface", "Automated Process Integration", "Application Process Interaction"], correctAnswer: "Application Programming Interface" },
  'Which HTTP method is used to retrieve data?': { prompt: "Quelle méthode HTTP est utilisée pour récupérer des données?", options: ["POST", "PUT", "GET", "DELETE"], correctAnswer: "GET" },
  'What does a 404 status code mean?': { prompt: "Que signifie un code de statut 404?", options: ["Succès", "Erreur serveur", "Ressource non trouvée", "Non autorisé"], correctAnswer: "Ressource non trouvée" },
  'What format do most modern APIs return data in?': { prompt: "Dans quel format la plupart des API modernes retournent-elles les données?", options: ["XML", "JSON", "CSV", "HTML"], correctAnswer: "JSON" },
  'Which HTTP method is used to send new data to a server?': { prompt: "Quelle méthode HTTP est utilisée pour envoyer de nouvelles données à un serveur?", options: ["GET", "POST", "DELETE", "HEAD"], correctAnswer: "POST" },
  'A REST API uses standard HTTP methods like GET, POST, PUT, DELETE.': { prompt: "Une API REST utilise les méthodes HTTP standard comme GET, POST, PUT, DELETE.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'An API key is used to identify and authenticate the caller.': { prompt: "Une clé API est utilisée pour identifier et authentifier l'appelant.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A status code in the ___ range means the request was successful.': { prompt: "Un code de statut dans la plage ___ signifie que la requête a réussi.", options: ["100", "200", "300", "400"], correctAnswer: "200" },

  // Async/Await
  'What does the "async" keyword do before a function?': { prompt: 'Que fait le mot-clé "async" avant une fonction?', options: ["La rend plus rapide", "La fait retourner une Promise", "La rend synchrone", "Empêche les erreurs"], correctAnswer: "La fait retourner une Promise" },
  'What does "await" do?': { prompt: 'Que fait "await"?', options: ["Saute la ligne", "Met l'exécution en pause jusqu'à la résolution de la Promise", "Annule la Promise", "Crée un nouveau thread"], correctAnswer: "Met l'exécution en pause jusqu'à la résolution de la Promise" },
  'Which method of fetch() parses the response as JSON?': { prompt: "Quelle méthode de fetch() analyse la réponse en JSON?", options: [".json()", ".parse()", ".data()", ".toJSON()"], correctAnswer: ".json()" },
  'What is Promise.all() used for?': { prompt: "À quoi sert Promise.all()?", options: ["Exécuter les promesses l'une après l'autre", "Exécuter plusieurs promesses en parallèle et attendre toutes", "Annuler toutes les promesses", "Créer une seule promesse"], correctAnswer: "Exécuter plusieurs promesses en parallèle et attendre toutes" },
  '"await" can only be used inside an async function.': { prompt: '"await" ne peut être utilisé que dans une fonction async.', options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A Promise can be in one of three states: pending, fulfilled, or rejected.': { prompt: "Une Promise peut être dans l'un des trois états : pending, fulfilled ou rejected.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'fetch() throws an error for HTTP 404 responses.': { prompt: "fetch() lance une erreur pour les réponses HTTP 404.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'To handle errors with async/await, you wrap the code in a ___ block.': { prompt: "Pour gérer les erreurs avec async/await, on enveloppe le code dans un bloc ___.", options: ["if/else", "try/catch", "for/in", "switch/case"], correctAnswer: "try/catch" },

  // Git Basics
  'What is Git?': { prompt: "Qu'est-ce que Git?", options: ["Un langage de programmation", "Un système de contrôle de version distribué", "Un éditeur de texte", "Un framework web"], correctAnswer: "Un système de contrôle de version distribué" },
  'What does "git commit" do?': { prompt: 'Que fait "git commit"?', options: ["Téléverse le code sur GitHub", "Sauvegarde les changements stagés dans le dépôt local", "Télécharge le code d'un serveur", "Supprime les changements"], correctAnswer: "Sauvegarde les changements stagés dans le dépôt local" },
  'What does "git push" do?': { prompt: 'Que fait "git push"?', options: ["Télécharge les changements distants", "Téléverse les commits locaux vers le dépôt distant", "Crée une nouvelle branche", "Fusionne deux branches"], correctAnswer: "Téléverse les commits locaux vers le dépôt distant" },
  'What is a branch in Git?': { prompt: "Qu'est-ce qu'une branche dans Git?", options: ["Une copie de tout le projet", "Une ligne de développement indépendante", "Un fichier de sauvegarde", "Un type de commit"], correctAnswer: "Une ligne de développement indépendante" },
  'What does "git pull" do?': { prompt: 'Que fait "git pull"?', options: ["Pousse les changements locaux", "Récupère et fusionne les changements distants dans votre branche", "Supprime une branche", "Crée un nouveau dépôt"], correctAnswer: "Récupère et fusionne les changements distants dans votre branche" },
  'You must run "git add" before "git commit" to stage changes.': { prompt: 'Vous devez exécuter "git add" avant "git commit" pour stager les changements.', options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A merge conflict occurs when Git cannot automatically combine changes.': { prompt: "Un conflit de fusion survient quand Git ne peut pas combiner automatiquement les changements.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The command "git ___" creates a local copy of a remote repository.': { prompt: 'La commande "git ___" crée une copie locale d\'un dépôt distant.', options: ["fork", "clone", "copy", "download"], correctAnswer: "clone" },

  // CSS Layout
  'Which CSS property creates a flex container?': { prompt: "Quelle propriété CSS crée un conteneur flex?", options: ["display: block", "display: flex", "display: grid", "display: inline"], correctAnswer: "display: flex" },
  'What does "justify-content: center" do in flexbox?': { prompt: 'Que fait "justify-content: center" en flexbox?', options: ["Centre les éléments verticalement", "Centre les éléments sur l'axe principal", "Centre le texte", "Centre le conteneur sur la page"], correctAnswer: "Centre les éléments sur l'axe principal" },
  'Which property controls the direction of flex items?': { prompt: "Quelle propriété contrôle la direction des éléments flex?", options: ["flex-wrap", "flex-direction", "align-items", "justify-content"], correctAnswer: "flex-direction" },
  'What does "position: fixed" do?': { prompt: 'Que fait "position: fixed"?', options: ["Positionne par rapport au parent", "Positionne par rapport au viewport et reste fixe au défilement", "Retire du flux", "Centre l'élément"], correctAnswer: "Positionne par rapport au viewport et reste fixe au défilement" },
  'CSS Grid and Flexbox can be used together in the same layout.': { prompt: "CSS Grid et Flexbox peuvent être utilisés ensemble dans la même mise en page.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The "box-sizing: border-box" property makes padding and border included in the element width.': { prompt: 'La propriété "box-sizing: border-box" inclut le padding et la bordure dans la largeur de l\'élément.', options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Margin collapse happens with horizontal margins.': { prompt: "La fusion des marges se produit avec les marges horizontales.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'CSS ___ is a 2D layout system that uses rows and columns.': { prompt: "CSS ___ est un système de mise en page 2D qui utilise des lignes et des colonnes.", options: ["Flexbox", "Grid", "Float", "Table"], correctAnswer: "Grid" },

  // React Intro
  'What is React?': { prompt: "Qu'est-ce que React?", options: ["Un framework CSS", "Une bibliothèque JavaScript pour construire des interfaces utilisateur", "Un langage backend", "Un système de base de données"], correctAnswer: "Une bibliothèque JavaScript pour construire des interfaces utilisateur" },
  'What is JSX?': { prompt: "Qu'est-ce que JSX?", options: ["Un nouveau langage de programmation", "Une extension de syntaxe qui permet d'écrire du code semblable au HTML en JavaScript", "Un préprocesseur CSS", "Un framework de test"], correctAnswer: "Une extension de syntaxe qui permet d'écrire du code semblable au HTML en JavaScript" },
  'What does the Virtual DOM do?': { prompt: "Que fait le Virtual DOM?", options: ["Remplace entièrement le HTML", "Garde une copie légère du DOM pour minimiser les mises à jour du vrai DOM", "Stocke des données dans le navigateur", "Crée des animations"], correctAnswer: "Garde une copie légère du DOM pour minimiser les mises à jour du vrai DOM" },
  'What tool is commonly used to create a new React project?': { prompt: "Quel outil est couramment utilisé pour créer un nouveau projet React?", options: ["npm install react", "create-react-app ou Vite", "react init", "react new project"], correctAnswer: "create-react-app ou Vite" },
  'React components must always start with an uppercase letter.': { prompt: "Les composants React doivent toujours commencer par une lettre majuscule.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'React can only be used for web applications.': { prompt: "React ne peut être utilisé que pour des applications web.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'JSX expressions must be wrapped in a single parent element.': { prompt: "Les expressions JSX doivent être enveloppées dans un seul élément parent.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'In React, ___ are used to pass data from a parent component to a child component.': { prompt: "En React, les ___ sont utilisés pour passer des données d'un composant parent à un composant enfant.", options: ["states", "props", "hooks", "refs"], correctAnswer: "props" },

  // State
  'What hook is used to manage state in a functional React component?': { prompt: "Quel hook est utilisé pour gérer l'état dans un composant React fonctionnel?", options: ["useEffect", "useState", "useRef", "useContext"], correctAnswer: "useState" },
  'What happens when state is updated in React?': { prompt: "Que se passe-t-il quand l'état est mis à jour en React?", options: ["Rien", "Le composant se re-rend", "La page se recharge", "L'état est supprimé"], correctAnswer: "Le composant se re-rend" },
  'Why should you NOT mutate state directly (e.g., state.push(item))?': { prompt: "Pourquoi ne devez-vous PAS modifier l'état directement (ex: state.push(item))?", options: ["C'est plus lent", "React ne détectera pas le changement et ne re-rendra pas", "Ça cause une erreur de syntaxe", "Ça supprime l'état"], correctAnswer: "React ne détectera pas le changement et ne re-rendra pas" },
  'What does useEffect do?': { prompt: "Que fait useEffect?", options: ["Gère l'état", "Exécute des effets secondaires après le rendu", "Crée des composants", "Gère le routage"], correctAnswer: "Exécute des effets secondaires après le rendu" },
  'What is the dependency array in useEffect?': { prompt: "Qu'est-ce que le tableau de dépendances dans useEffect?", options: ["Une liste de packages requis", "Un tableau qui détermine quand l'effet se ré-exécute", "Une liste de composants", "Un gestionnaire d'erreurs"], correctAnswer: "Un tableau qui détermine quand l'effet se ré-exécute" },
  'State updates in React are batched and asynchronous.': { prompt: "Les mises à jour d'état en React sont groupées et asynchrones.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'useEffect with an empty dependency array [] runs only once after the first render.': { prompt: "useEffect avec un tableau de dépendances vide [] ne s'exécute qu'une fois après le premier rendu.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The ___ hook lets you access shared data without passing props through every level.': { prompt: "Le hook ___ vous permet d'accéder à des données partagées sans passer les props à chaque niveau.", options: ["useState", "useEffect", "useContext", "useReducer"], correctAnswer: "useContext" },

  // Components
  'What is a React component?': { prompt: "Qu'est-ce qu'un composant React?", options: ["Une classe CSS", "Un morceau d'interface réutilisable", "Une variable JavaScript", "Un fichier HTML"], correctAnswer: "Un morceau d'interface réutilisable" },
  'What is the difference between a functional and class component?': { prompt: "Quelle est la différence entre un composant fonctionnel et un composant de classe?", options: ["Aucune différence", "Le fonctionnel utilise des fonctions, le classe utilise des classes ES6", "Le classe est plus rapide", "Le fonctionnel ne peut pas avoir d'état"], correctAnswer: "Le fonctionnel utilise des fonctions, le classe utilise des classes ES6" },
  'What is the purpose of the "key" prop in lists?': { prompt: 'Quel est le but de la prop "key" dans les listes?', options: ["Style", "Aide React à identifier quels éléments ont changé", "Tri", "Filtrage"], correctAnswer: "Aide React à identifier quels éléments ont changé" },
  'What is prop drilling?': { prompt: "Qu'est-ce que le prop drilling?", options: ["Une optimisation de performance", "Passer des props à travers plusieurs niveaux de composants", "Percer dans le DOM", "Une technique de test"], correctAnswer: "Passer des props à travers plusieurs niveaux de composants" },
  'A component can return null to render nothing.': { prompt: "Un composant peut retourner null pour ne rien afficher.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Props are read-only and should not be modified by the child component.': { prompt: "Les props sont en lecture seule et ne doivent pas être modifiées par le composant enfant.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'React components can only return a single JSX element or fragment.': { prompt: "Les composants React ne peuvent retourner qu'un seul élément JSX ou fragment.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  '___ rendering in React means showing or hiding components based on conditions.': { prompt: "Le rendu ___ en React signifie afficher ou masquer des composants selon des conditions.", options: ["Dynamique", "Conditionnel", "Paresseux", "Serveur"], correctAnswer: "Conditionnel" },

  // Databases
  'What is a database?': { prompt: "Qu'est-ce qu'une base de données?", options: ["Un langage de programmation", "Une collection organisée de données structurées", "Un navigateur web", "Un framework CSS"], correctAnswer: "Une collection organisée de données structurées" },
  'What does SQL stand for?': { prompt: "Que signifie SQL?", options: ["Simple Query Language", "Structured Query Language", "Standard Question Logic", "Server Query Layer"], correctAnswer: "Structured Query Language" },
  'Which SQL command retrieves data from a table?': { prompt: "Quelle commande SQL récupère des données d'une table?", options: ["INSERT", "UPDATE", "SELECT", "DELETE"], correctAnswer: "SELECT" },
  'What is a NoSQL database?': { prompt: "Qu'est-ce qu'une base de données NoSQL?", options: ["Une base sans aucune requête", "Une base non relationnelle qui stocke les données dans des formats flexibles", "Une base SQL cassée", "Une base qui ne stocke que des nombres"], correctAnswer: "Une base non relationnelle qui stocke les données dans des formats flexibles" },
  'What is a primary key?': { prompt: "Qu'est-ce qu'une clé primaire?", options: ["La première colonne d'une table", "Un identifiant unique pour chaque enregistrement d'une table", "La donnée la plus importante", "Un mot de passe pour la base de données"], correctAnswer: "Un identifiant unique pour chaque enregistrement d'une table" },
  'PostgreSQL is a relational database management system.': { prompt: "PostgreSQL est un système de gestion de base de données relationnelle.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A foreign key links two tables together by referencing a primary key in another table.': { prompt: "Une clé étrangère lie deux tables ensemble en référençant une clé primaire dans une autre table.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The SQL ___ clause is used to filter records based on a condition.': { prompt: "La clause SQL ___ est utilisée pour filtrer les enregistrements selon une condition.", options: ["FROM", "WHERE", "ORDER BY", "GROUP BY"], correctAnswer: "WHERE" },

  // Auth
  'What is authentication?': { prompt: "Qu'est-ce que l'authentification?", options: ["Concevoir une interface", "Vérifier l'identité d'un utilisateur", "Chiffrer une base de données", "Déployer un site web"], correctAnswer: "Vérifier l'identité d'un utilisateur" },
  'What is the difference between authentication and authorization?': { prompt: "Quelle est la différence entre authentification et autorisation?", options: ["C'est la même chose", "L'authentification vérifie l'identité ; l'autorisation détermine les permissions", "L'autorisation vérifie l'identité ; l'authentification détermine les permissions", "Aucun rapport avec la sécurité"], correctAnswer: "L'authentification vérifie l'identité ; l'autorisation détermine les permissions" },
  'What is a JWT?': { prompt: "Qu'est-ce qu'un JWT?", options: ["Un framework JavaScript", "Un JSON Web Token utilisé pour la transmission sécurisée de données", "Un type de base de données", "Une propriété CSS"], correctAnswer: "Un JSON Web Token utilisé pour la transmission sécurisée de données" },
  'What is OAuth?': { prompt: "Qu'est-ce que OAuth?", options: ["Un langage de programmation", "Un protocole qui permet la connexion via des tiers (ex: Google, GitHub)", "Une requête de base de données", "Un framework CSS"], correctAnswer: "Un protocole qui permet la connexion via des tiers (ex: Google, GitHub)" },
  'Passwords should be stored as plain text in the database.': { prompt: "Les mots de passe doivent être stockés en texte brut dans la base de données.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A session token is typically stored in a cookie or local storage.': { prompt: "Un jeton de session est généralement stocké dans un cookie ou le stockage local.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Two-factor authentication adds an extra layer of security beyond a password.': { prompt: "L'authentification à deux facteurs ajoute une couche de sécurité supplémentaire au-delà du mot de passe.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  '___ is the process of converting a password into a fixed-length string that cannot be reversed.': { prompt: "Le ___ est le processus de conversion d'un mot de passe en une chaîne de longueur fixe qui ne peut pas être inversée.", options: ["Encodage", "Chiffrement", "Hachage", "Compression"], correctAnswer: "Hachage" },

  // Deployment
  'What does deployment mean in web development?': { prompt: "Que signifie le déploiement en développement web?", options: ["Écrire du code", "Rendre une application disponible aux utilisateurs sur internet", "Tester localement", "Concevoir un logo"], correctAnswer: "Rendre une application disponible aux utilisateurs sur internet" },
  'Which platform is commonly used for deploying frontend apps for free?': { prompt: "Quelle plateforme est couramment utilisée pour déployer gratuitement des applications frontend?", options: ["Microsoft Word", "Vercel", "Photoshop", "Excel"], correctAnswer: "Vercel" },
  'What is CI/CD?': { prompt: "Qu'est-ce que CI/CD?", options: ["Un framework CSS", "Intégration Continue / Déploiement Continu", "Inspection de Code / Design de Code", "Un système de base de données"], correctAnswer: "Intégration Continue / Déploiement Continu" },
  'What is an environment variable?': { prompt: "Qu'est-ce qu'une variable d'environnement?", options: ["Une variable JavaScript", "Une valeur de configuration stockée en dehors du code (ex: clés API)", "Une variable CSS", "Une colonne de base de données"], correctAnswer: "Une valeur de configuration stockée en dehors du code (ex: clés API)" },
  'A .env file should be committed to a public Git repository.': { prompt: "Un fichier .env devrait être commité dans un dépôt Git public.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'HTTPS encrypts data between the browser and server.': { prompt: "HTTPS chiffre les données entre le navigateur et le serveur.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Docker containers package an app with all its dependencies for consistent deployment.': { prompt: "Les conteneurs Docker empaquettent une application avec toutes ses dépendances pour un déploiement cohérent.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A ___ name (e.g., example.com) maps a human-readable address to a server IP address.': { prompt: "Un nom de ___ (ex: example.com) associe une adresse lisible par l'humain à une adresse IP de serveur.", options: ["hôte", "domaine", "serveur", "route"], correctAnswer: "domaine" },

  // Full Project
  'What is the typical first step in building a full-stack project?': { prompt: "Quelle est la première étape typique pour construire un projet full-stack?", options: ["Écrire du CSS", "Planifier les fonctionnalités et concevoir l'architecture", "Déployer en production", "Acheter un domaine"], correctAnswer: "Planifier les fonctionnalités et concevoir l'architecture" },
  'In the MVC pattern, what does "M" stand for?': { prompt: 'Dans le patron MVC, que signifie "M"?', options: ["Main", "Model", "Module", "Markup"], correctAnswer: "Model" },
  'What is a README file used for?': { prompt: "À quoi sert un fichier README?", options: ["Stocker des mots de passe", "Documenter ce que fait le projet et comment l'utiliser", "Exécuter l'application", "Styliser le projet"], correctAnswer: "Documenter ce que fait le projet et comment l'utiliser" },
  'What is the purpose of code review?': { prompt: "Quel est le but de la revue de code?", options: ["Rendre le code plus lent", "Détecter les bugs et améliorer la qualité du code par les retours des pairs", "Supprimer l'ancien code", "Déployer plus vite"], correctAnswer: "Détecter les bugs et améliorer la qualité du code par les retours des pairs" },
  'What does "refactoring" mean?': { prompt: 'Que signifie "refactoring"?', options: ["Ajouter de nouvelles fonctionnalités", "Restructurer le code existant sans changer son comportement", "Supprimer le projet", "Convertir dans un autre langage"], correctAnswer: "Restructurer le code existant sans changer son comportement" },
  'Version control is important even for solo projects.': { prompt: "Le contrôle de version est important même pour les projets solo.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Testing should only be done at the very end of a project.': { prompt: "Les tests ne devraient être faits qu'à la toute fin d'un projet.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'An ___ is a tool that manages project tasks, bugs, and features, such as Jira or Trello.': { prompt: "Un ___ est un outil qui gère les tâches, bugs et fonctionnalités du projet, comme Jira ou Trello.", options: ["IDE", "gestionnaire de tickets", "API", "ORM"], correctAnswer: "gestionnaire de tickets" },

  // Master Dev
  'What are design patterns?': { prompt: "Que sont les patrons de conception (design patterns)?", options: ["Des templates CSS de design", "Des solutions réutilisables à des problèmes logiciels courants", "Des schémas de base de données", "Des bibliothèques de composants UI"], correctAnswer: "Des solutions réutilisables à des problèmes logiciels courants" },
  'What is the SOLID principle about?': { prompt: "De quoi traite le principe SOLID?", options: ["Rendre le code plus rapide", "Cinq principes pour écrire du code POO maintenable", "La conception de base de données", "La sécurité réseau"], correctAnswer: "Cinq principes pour écrire du code POO maintenable" },
  'What is technical debt?': { prompt: "Qu'est-ce que la dette technique?", options: ["L'argent dû pour les serveurs", "Le coût des raccourcis dans le code qui doivent être corrigés plus tard", "Du CSS inutilisé", "Un internet lent"], correctAnswer: "Le coût des raccourcis dans le code qui doivent être corrigés plus tard" },
  'What is microservices architecture?': { prompt: "Qu'est-ce que l'architecture microservices?", options: ["Écrire du très petit code", "Construire une application comme une collection de petits services indépendants", "Un framework JavaScript", "Une méthodologie CSS"], correctAnswer: "Construire une application comme une collection de petits services indépendants" },
  'Clean code prioritizes readability over cleverness.': { prompt: "Le code propre privilégie la lisibilité plutôt que l'ingéniosité.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Premature optimization is generally considered bad practice.': { prompt: "L'optimisation prématurée est généralement considérée comme une mauvaise pratique.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A senior developer only writes code and does not mentor others.': { prompt: "Un développeur senior ne fait qu'écrire du code et ne mentore pas les autres.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'The ___ principle states that every module should have one reason to change.': { prompt: "Le principe de ___ stipule que chaque module ne devrait avoir qu'une seule raison de changer.", options: ["Ouvert/Fermé", "Responsabilité Unique", "Inversion de Dépendance", "Substitution de Liskov"], correctAnswer: "Responsabilité Unique" },
};

export default codingFr;
