export const guitarFr: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // Holding Guitar
  'How should you sit when holding a guitar?': { prompt: 'Comment devriez-vous vous asseoir en tenant une guitare?', options: ['Couché', 'Debout sur un pied', 'Droit avec la guitare sur votre jambe', 'Affalé en arrière'], correctAnswer: 'Droit avec la guitare sur votre jambe' },
  'The neck of the guitar should point downward.': { prompt: 'Le manche de la guitare devrait pointer vers le bas.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Your ___ hand strums while the other hand frets the notes.': { prompt: 'Votre main ___ gratte les cordes tandis que l\'autre main joue les notes sur les frettes.', options: ['Dominante', 'Gauche', 'Plus petite', 'Plus faible'], correctAnswer: 'Dominante' },
  'Gripping the guitar neck tightly with your whole palm.': { prompt: 'Serrer le manche de la guitare fermement avec toute la paume.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Where should your thumb be on the back of the neck?': { prompt: 'Où devrait se trouver votre pouce à l\'arrière du manche?', options: ['Par-dessus le haut', 'Sans toucher', 'Environ derrière le milieu du manche', 'Sur le côté'], correctAnswer: 'Environ derrière le milieu du manche' },
  'A guitar strap helps maintain proper posture while standing.': { prompt: 'Une sangle de guitare aide à maintenir une bonne posture debout.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Open Chords
  'What is an open chord?': { prompt: 'Qu\'est-ce qu\'un accord ouvert?', options: ['Un accord utilisant des cordes ouvertes (non frettées)', 'Un accord cassé', 'Un accord sans son', 'Un accord joué à la 12e frette'], correctAnswer: 'Un accord utilisant des cordes ouvertes (non frettées)' },
  'G, C, D, E, and A are common beginner open chords.': { prompt: 'Sol, Do, Ré, Mi et La sont des accords ouverts courants pour débutants.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Press your fingertips just ___ the fret for the cleanest sound.': { prompt: 'Appuyez le bout de vos doigts juste ___ la frette pour le son le plus net.', options: ['Derrière', 'Au-dessus de', 'Loin de', 'En dessous de'], correctAnswer: 'Derrière' },
  'Pressing fingers flat across multiple strings unintentionally.': { prompt: 'Appuyer les doigts à plat sur plusieurs cordes involontairement.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'How many notes make up a basic chord?': { prompt: 'Combien de notes composent un accord de base?', options: ['Au moins 3', '2', '7', '1'], correctAnswer: 'Au moins 3' },
  'You should check each string rings clearly when learning chords.': { prompt: 'Vous devriez vérifier que chaque corde résonne clairement en apprenant les accords.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Strumming
  'What should drive the strumming motion?': { prompt: 'Qu\'est-ce qui devrait guider le mouvement de grattage?', options: ['Coude', 'Poignet', 'Épaule', 'Doigts'], correctAnswer: 'Poignet' },
  'Strumming patterns combine downstrokes and upstrokes.': { prompt: 'Les patrons de grattage combinent des coups vers le bas et vers le haut.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The most basic strumming pattern is all ___ strokes.': { prompt: 'Le patron de grattage le plus basique est entièrement composé de coups vers le ___.', options: ['Bas', 'Haut', 'Côté', 'Étouffés'], correctAnswer: 'Bas' },
  'Keeping a steady rhythm even if you miss some strings.': { prompt: 'Garder un rythme régulier même si vous manquez quelques cordes.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What helps keep time while strumming?': { prompt: 'Qu\'est-ce qui aide à garder le tempo en grattant?', options: ['Jouer plus vite', 'Fermer les yeux', 'Utiliser un métronome', 'Sauter des temps'], correctAnswer: 'Utiliser un métronome' },
  'Your strumming arm should keep moving even on silent beats.': { prompt: 'Votre bras de grattage devrait continuer à bouger même sur les temps silencieux.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Finger Exercises
  'What does the "spider walk" exercise train?': { prompt: 'Qu\'est-ce que l\'exercice de la "marche de l\'araignée" entraîne?', options: ['La vitesse uniquement', 'Le chant', 'L\'indépendance et la dextérité des doigts', 'L\'entraînement de l\'oreille'], correctAnswer: 'L\'indépendance et la dextérité des doigts' },
  'Finger exercises should be practiced slowly first, then speed up.': { prompt: 'Les exercices de doigts devraient être pratiqués lentement d\'abord, puis accélérer.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Practice with a ___ to build speed gradually.': { prompt: 'Pratiquez avec un ___ pour augmenter la vitesse graduellement.', options: ['Métronome', 'Minuteur', 'Accordeur', 'Capo'], correctAnswer: 'Métronome' },
  'Practicing finger exercises until your hand hurts badly.': { prompt: 'Pratiquer les exercices de doigts jusqu\'à ce que votre main fasse très mal.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is "1-2-3-4" chromatic exercise?': { prompt: 'Qu\'est-ce que l\'exercice chromatique "1-2-3-4"?', options: ['Jouer chaque frette dans l\'ordre sur les cordes', 'Une progression d\'accords', 'Une méthode d\'accordage', 'Une chanson'], correctAnswer: 'Jouer chaque frette dans l\'ordre sur les cordes' },
  'Short daily practice is better than one long session per week.': { prompt: 'Une courte pratique quotidienne est meilleure qu\'une longue session par semaine.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Power Chords
  'How many notes make a power chord?': { prompt: 'Combien de notes composent un power chord?', options: ['4', '1', '2 (fondamentale et quinte)', '6'], correctAnswer: '2 (fondamentale et quinte)' },
  'Power chords are neither major nor minor.': { prompt: 'Les power chords ne sont ni majeurs ni mineurs.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Power chords are commonly used in ___ music.': { prompt: 'Les power chords sont couramment utilisés dans la musique ___.', options: ['Rock', 'Classique', 'Jazz', 'Baroque'], correctAnswer: 'Rock' },
  'Muting unused strings when playing power chords.': { prompt: 'Étouffer les cordes inutilisées en jouant des power chords.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What strings typically make a power chord on the E string?': { prompt: 'Quelles cordes forment typiquement un power chord sur la corde de Mi?', options: ['Les 6 cordes', 'Seulement le Mi aigu', 'Les cordes de Mi grave et La (même motif de frettes)', 'Les cordes 3 et 4'], correctAnswer: 'Les cordes de Mi grave et La (même motif de frettes)' },
  'Power chords are moveable shapes on the fretboard.': { prompt: 'Les power chords sont des formes déplaçables sur le manche.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Reading Tabs
  'How many lines does a guitar tab have?': { prompt: 'Combien de lignes une tablature de guitare a-t-elle?', options: ['5', '4', '8', '6'], correctAnswer: '6' },
  'The bottom line of a tab represents the lowest (thickest) string.': { prompt: 'La ligne du bas d\'une tablature représente la corde la plus basse (la plus épaisse).', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Numbers on tab lines represent ___ to press.': { prompt: 'Les chiffres sur les lignes de tablature représentent les ___ à presser.', options: ['Frettes', 'Cordes', 'Doigts', 'Notes'], correctAnswer: 'Frettes' },
  'What does "0" mean on a tab?': { prompt: 'Que signifie "0" sur une tablature?', options: ['Jouer la corde à vide', 'Ne pas jouer', 'Utiliser un capo', 'Étouffer la corde'], correctAnswer: 'Jouer la corde à vide' },
  'Learning to read both tabs and standard notation over time.': { prompt: 'Apprendre à lire à la fois les tablatures et la notation standard au fil du temps.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Tab shows you rhythm/timing by default.': { prompt: 'La tablature vous montre le rythme/tempo par défaut.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },

  // Barre Chords
  'What is a barre chord?': { prompt: 'Qu\'est-ce qu\'un accord barré?', options: ['Un accord ouvert', 'Un accord cassé', 'Un accord au bar', 'Un accord où un doigt appuie sur toutes les cordes à travers une frette'], correctAnswer: 'Un accord où un doigt appuie sur toutes les cordes à travers une frette' },
  'Barre chords are harder than open chords for beginners.': { prompt: 'Les accords barrés sont plus difficiles que les accords ouverts pour les débutants.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The ___ finger usually forms the barre across the fret.': { prompt: 'Le doigt ___ forme habituellement le barré à travers la frette.', options: ['Index', 'Majeur', 'Annulaire', 'Auriculaire'], correctAnswer: 'Index' },
  'Using the side/edge of your index finger for the barre.': { prompt: 'Utiliser le côté/bord de votre index pour le barré.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'An F major barre chord is based on which open chord shape?': { prompt: 'L\'accord barré de Fa majeur est basé sur quelle forme d\'accord ouvert?', options: ['Forme de La', 'Forme de Sol', 'Forme de Ré', 'Forme de Mi'], correctAnswer: 'Forme de Mi' },
  'Barre chords can be moved up and down the neck to change key.': { prompt: 'Les accords barrés peuvent être déplacés le long du manche pour changer de tonalité.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Minor Scale
  'What mood does a minor scale typically convey?': { prompt: 'Quelle ambiance une gamme mineure transmet-elle typiquement?', options: ['En colère', 'Aucune émotion', 'Joyeuse et brillante', 'Triste ou sombre'], correctAnswer: 'Triste ou sombre' },
  'The natural minor scale has 7 notes.': { prompt: 'La gamme mineure naturelle a 7 notes.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A minor is the ___ minor key (no sharps or flats).': { prompt: 'La mineur est la tonalité mineure ___ (sans dièses ni bémols).', options: ['Naturelle', 'Dièse', 'Bémol', 'Double'], correctAnswer: 'Naturelle' },
  'The minor pentatonic scale is crucial for which genre?': { prompt: 'La gamme pentatonique mineure est cruciale pour quel genre?', options: ['Blues et rock', 'Polka', 'Fanfare', 'Classique'], correctAnswer: 'Blues et rock' },
  'Practicing scales slowly before increasing speed.': { prompt: 'Pratiquer les gammes lentement avant d\'augmenter la vitesse.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'The minor pentatonic has 5 notes per octave.': { prompt: 'La pentatonique mineure a 5 notes par octave.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Tuning
  'What are the standard tuning notes from lowest to highest string?': { prompt: 'Quelles sont les notes de l\'accordage standard de la corde la plus basse à la plus haute?', options: ['Mi La Ré Sol Si Mi', 'La Ré Sol Do Mi La', 'Ré Sol Si Mi La Ré', 'Mi Si Sol Ré La Mi'], correctAnswer: 'Mi La Ré Sol Si Mi' },
  'A guitar tuner clip attaches to the headstock and detects pitch through vibrations.': { prompt: 'Un accordeur à pince se fixe à la tête de la guitare et détecte la hauteur par les vibrations.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The mnemonic "Every Amateur Does Get Better ___" helps remember string names.': { prompt: 'Le moyen mnémotechnique "Every Amateur Does Get Better ___" aide à se rappeler les noms des cordes.', options: ['Eventually', 'Easily', 'Early', 'Everywhere'], correctAnswer: 'Eventually' },
  'What is "drop D" tuning?': { prompt: 'Qu\'est-ce que l\'accordage "drop D"?', options: ['Accorder toutes les cordes un ton plus bas', 'Baisser la 6e corde de Mi à Ré', 'Monter la 1re corde à Fa', 'Retirer la corde de Ré'], correctAnswer: 'Baisser la 6e corde de Mi à Ré' },
  'New guitar strings go out of tune more frequently until they stretch in.': { prompt: 'Les cordes de guitare neuves se désaccordent plus fréquemment jusqu\'à ce qu\'elles s\'étirent.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Tuning your guitar every time before you practice.': { prompt: 'Accorder votre guitare à chaque fois avant de pratiquer.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What frequency is the standard tuning reference pitch (A4)?': { prompt: 'Quelle fréquence est la hauteur de référence de l\'accordage standard (La4)?', options: ['220 Hz', '440 Hz', '330 Hz', '520 Hz'], correctAnswer: '440 Hz' },
  'You can tune a guitar using harmonics at the 5th and 7th frets.': { prompt: 'Vous pouvez accorder une guitare en utilisant les harmoniques aux 5e et 7e frettes.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Major Scale
  'What is the interval pattern of a major scale?': { prompt: 'Quel est le patron d\'intervalles d\'une gamme majeure?', options: ['T-T-dt-T-T-T-dt', 'dt-T-T-dt-T-T-T', 'T-dt-T-T-dt-T-T', 'Tous des tons'], correctAnswer: 'T-T-dt-T-T-T-dt' },
  'The C major scale contains no sharps or flats.': { prompt: 'La gamme de Do majeur ne contient ni dièses ni bémols.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A major scale has ___ unique notes before repeating at the octave.': { prompt: 'Une gamme majeure a ___ notes uniques avant de se répéter à l\'octave.', options: ['7', '5', '6', '8'], correctAnswer: '7' },
  'On guitar, the G major scale is popular because it uses which frets in first position?': { prompt: 'Sur la guitare, la gamme de Sol majeur est populaire parce qu\'elle utilise quelles frettes en première position?', options: ['Seulement les cordes à vide', 'Frettes 1 à 3 avec cordes à vide', 'Frettes 5 à 8', 'Seulement des accords barrés'], correctAnswer: 'Frettes 1 à 3 avec cordes à vide' },
  'Learning the major scale is fundamental because most music theory is built on it.': { prompt: 'Apprendre la gamme majeure est fondamental car la plupart de la théorie musicale est construite dessus.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Practicing the major scale in only one position on the fretboard.': { prompt: 'Pratiquer la gamme majeure dans une seule position sur le manche.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'How many sharps does the G major scale have?': { prompt: 'Combien de dièses la gamme de Sol majeur a-t-elle?', options: ['Aucun', 'Deux', 'Un (Fa#)', 'Trois'], correctAnswer: 'Un (Fa#)' },
  'Every major scale sounds happy or bright compared to its relative minor.': { prompt: 'Chaque gamme majeure sonne joyeuse ou brillante comparée à sa relative mineure.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Pentatonic Scale
  'How many notes are in a pentatonic scale?': { prompt: 'Combien de notes y a-t-il dans une gamme pentatonique?', options: ['7', '5', '6', '4'], correctAnswer: '5' },
  'The minor pentatonic scale is the most commonly used scale for blues and rock guitar solos.': { prompt: 'La gamme pentatonique mineure est la gamme la plus utilisée pour les solos de guitare blues et rock.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The A minor pentatonic scale contains the notes A, C, D, E, and ___.': { prompt: 'La gamme pentatonique de La mineur contient les notes La, Do, Ré, Mi et ___.', options: ['Sol', 'Si', 'Fa', 'Fa#'], correctAnswer: 'Sol' },
  'What is "box 1" or "pattern 1" of the minor pentatonic?': { prompt: 'Qu\'est-ce que la "boîte 1" ou le "patron 1" de la pentatonique mineure?', options: ['Une gamme jouée sur une seule corde', 'Le premier et plus courant doigté commençant sur la fondamentale', 'Une forme d\'accord', 'Un patron de grattage'], correctAnswer: 'Le premier et plus courant doigté commençant sur la fondamentale' },
  'The major pentatonic and minor pentatonic are the same pattern, just starting from different notes.': { prompt: 'La pentatonique majeure et la pentatonique mineure sont le même patron, commençant simplement sur des notes différentes.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Learning all 5 pentatonic box patterns across the entire fretboard.': { prompt: 'Apprendre les 5 patrons de boîtes pentatoniques sur tout le manche.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Why does the pentatonic scale sound good over many chord progressions?': { prompt: 'Pourquoi la gamme pentatonique sonne-t-elle bien sur de nombreuses progressions d\'accords?', options: ['Elle a des vibrations spéciales', 'Elle évite les intervalles dissonants (demi-tons) qui entrent en conflit avec les accords', 'Elle est jouée plus vite', 'Elle n\'utilise que des cordes à vide'], correctAnswer: 'Elle évite les intervalles dissonants (demi-tons) qui entrent en conflit avec les accords' },
  'Adding the "blue note" (flat 5th) to the minor pentatonic creates the blues scale.': { prompt: 'Ajouter la "blue note" (quinte bémol) à la pentatonique mineure crée la gamme blues.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Fingerpicking
  'In standard fingerpicking, which finger plays the bass strings?': { prompt: 'Dans le fingerpicking standard, quel doigt joue les cordes basses?', options: ['Index', 'Majeur', 'Auriculaire', 'Pouce'], correctAnswer: 'Pouce' },
  'PIMA stands for Pulgar, Indice, Medio, Anular — the Spanish names for thumb, index, middle, ring.': { prompt: 'PIMA signifie Pulgar, Indice, Medio, Anular — les noms espagnols pour pouce, index, majeur, annulaire.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Travis picking alternates the ___ between bass notes while fingers play melody.': { prompt: 'Le Travis picking alterne le ___ entre les notes de basse pendant que les doigts jouent la mélodie.', options: ['Pouce', 'Index', 'Poignet', 'Médiator'], correctAnswer: 'Pouce' },
  'Which genre most commonly features fingerpicking?': { prompt: 'Quel genre présente le plus couramment le fingerpicking?', options: ['Heavy metal', 'Punk rock', 'Folk et classique', 'Ska'], correctAnswer: 'Folk et classique' },
  'You need long fingernails on your picking hand for fingerpicking.': { prompt: 'Vous avez besoin d\'ongles longs sur votre main de picking pour le fingerpicking.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'What is an arpeggio picking pattern?': { prompt: 'Qu\'est-ce qu\'un patron de picking en arpège?', options: ['Gratter toutes les cordes en même temps', 'Jouer les notes d\'un accord une à la fois en séquence', 'Jouer seulement des power chords', 'Un type de technique de glissando'], correctAnswer: 'Jouer les notes d\'un accord une à la fois en séquence' },
  'Anchoring your picking hand pinky on the guitar body for stability.': { prompt: 'Ancrer l\'auriculaire de votre main de picking sur le corps de la guitare pour la stabilité.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Which fingerpicking approach is better for beginners?': { prompt: 'Quelle approche de fingerpicking est meilleure pour les débutants?', options: ['Essayer de jouer un patron complexe à pleine vitesse immédiatement.', 'Commencer avec un patron simple lentement, puis ajouter graduellement de la complexité et de la vitesse.'], correctAnswer: 'Commencer avec un patron simple lentement, puis ajouter graduellement de la complexité et de la vitesse.' },

  // Rhythm & Timing
  'What time signature means 4 beats per measure?': { prompt: 'Quelle signature rythmique signifie 4 temps par mesure?', options: ['3/4', '6/8', '4/4', '2/2'], correctAnswer: '4/4' },
  'A dotted note lasts 1.5 times its original value.': { prompt: 'Une note pointée dure 1,5 fois sa valeur originale.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Playing slightly behind the beat is called laying ___.': { prompt: 'Jouer légèrement en retard sur le temps s\'appelle jouer en ___.', options: ['Retrait', 'Avant', 'Bas', 'Dessus'], correctAnswer: 'Retrait' },
  'What is syncopation?': { prompt: 'Qu\'est-ce que la syncope?', options: ['Jouer parfaitement en rythme', 'Accentuer des notes sur des temps inattendus ou des contretemps', 'Un type d\'étouffement', 'Jouer très lentement'], correctAnswer: 'Accentuer des notes sur des temps inattendus ou des contretemps' },
  'A metronome is one of the most valuable tools for developing solid timing.': { prompt: 'Un métronome est l\'un des outils les plus précieux pour développer un timing solide.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is a triplet?': { prompt: 'Qu\'est-ce qu\'un triolet?', options: ['Trois notes jouées dans l\'espace de deux', 'Trois accords d\'affilée', 'Un groupe de trois chansons', 'Trois notes identiques'], correctAnswer: 'Trois notes jouées dans l\'espace de deux' },
  'Rushing through difficult passages instead of keeping steady time.': { prompt: 'Se précipiter dans les passages difficiles au lieu de garder un tempo régulier.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'The "and" in counting "1 and 2 and 3 and 4 and" represents eighth notes.': { prompt: 'Le "et" dans le comptage "1 et 2 et 3 et 4 et" représente des croches.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Blues Basics
  'How many bars are in a standard blues progression?': { prompt: 'Combien de mesures y a-t-il dans une progression blues standard?', options: ['8', '16', '12', '10'], correctAnswer: '12' },
  'The 12-bar blues uses only three chords.': { prompt: 'Le blues de 12 mesures n\'utilise que trois accords.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A blues ___ is a short musical phrase that repeats throughout a song.': { prompt: 'Un ___ blues est une courte phrase musicale qui se répète tout au long d\'une chanson.', options: ['Riff', 'Gamme', 'Accord', 'Temps'], correctAnswer: 'Riff' },
  'What is a "shuffle" rhythm?': { prompt: 'Qu\'est-ce qu\'un rythme "shuffle"?', options: ['Jouer des notes au hasard', 'Un feeling swing où le temps est divisé en paires longue-courte', 'Jouer le plus vite possible', 'Un type de technique de glissando'], correctAnswer: 'Un feeling swing où le temps est divisé en paires longue-courte' },
  'String bending is an essential technique in blues guitar.': { prompt: 'Le bend de cordes est une technique essentielle en guitare blues.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What are "dominant 7th" chords in blues?': { prompt: 'Que sont les accords de "septième de dominante" en blues?', options: ['Des accords mineurs', 'Des accords majeurs avec une septième bémolisée ajoutée', 'Des power chords avec une note supplémentaire', 'Des accords diminués'], correctAnswer: 'Des accords majeurs avec une septième bémolisée ajoutée' },
  'Learning to play blues with feeling and dynamics rather than just speed.': { prompt: 'Apprendre à jouer le blues avec du feeling et des nuances plutôt que juste de la vitesse.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'The "turnaround" is a phrase played in the last two bars of the 12-bar blues to lead back to the beginning.': { prompt: 'Le "turnaround" est une phrase jouée dans les deux dernières mesures du blues de 12 mesures pour ramener au début.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Chord Transitions
  'What is the most important factor in smooth chord changes?': { prompt: 'Quel est le facteur le plus important pour des changements d\'accords fluides?', options: ['Jouer plus vite', 'Minimiser le mouvement des doigts entre les accords', 'Utiliser plus de pression', 'Regarder vos mains'], correctAnswer: 'Minimiser le mouvement des doigts entre les accords' },
  'Keeping a "pivot finger" in place when two chords share a common finger position helps transitions.': { prompt: 'Garder un "doigt pivot" en place quand deux accords partagent une position de doigt commune aide les transitions.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The transition from G to C is easier when you keep your ___ finger on the same string.': { prompt: 'La transition de Sol à Do est plus facile quand vous gardez votre doigt ___ sur la même corde.', options: ['Annulaire', 'Index', 'Majeur', 'Auriculaire'], correctAnswer: 'Annulaire' },
  'What is the "one-minute chord change" exercise?': { prompt: 'Qu\'est-ce que l\'exercice de "changement d\'accord en une minute"?', options: ['Une tentative de record de vitesse', 'Compter combien de changements d\'accords propres vous pouvez faire en 60 secondes', 'Jouer un accord pendant une minute', 'Un étirement d\'échauffement'], correctAnswer: 'Compter combien de changements d\'accords propres vous pouvez faire en 60 secondes' },
  'It is normal for chord transitions to be slow and messy when you first learn them.': { prompt: 'Il est normal que les transitions d\'accords soient lentes et brouillonnes quand vous les apprenez.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What should you focus on when practicing chord changes?': { prompt: 'Sur quoi devriez-vous vous concentrer en pratiquant les changements d\'accords?', options: ['La vitesse avant tout', 'La précision d\'abord, puis augmenter graduellement la vitesse', 'Seulement la main de grattage', 'Jouer les yeux fermés'], correctAnswer: 'La précision d\'abord, puis augmenter graduellement la vitesse' },
  'Stopping mid-song every time you fumble a chord change.': { prompt: 'S\'arrêter en pleine chanson à chaque fois que vous ratez un changement d\'accord.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Which chord change approach is better?': { prompt: 'Quelle approche de changement d\'accord est meilleure?', options: ['Lever tous les doigts du manche, pauser, puis les placer pour l\'accord suivant.', 'Déplacer tous les doigts vers la nouvelle forme d\'accord simultanément en un mouvement rapide.'], correctAnswer: 'Déplacer tous les doigts vers la nouvelle forme d\'accord simultanément en un mouvement rapide.' },

  // Capo Use
  'What does a capo do?': { prompt: 'Que fait un capo?', options: ['Étouffer toutes les cordes', 'Se fixe sur le manche pour élever la hauteur de toutes les cordes de manière égale', 'Change l\'accordage au hasard', 'Remplace une corde cassée'], correctAnswer: 'Se fixe sur le manche pour élever la hauteur de toutes les cordes de manière égale' },
  'Placing a capo on the 2nd fret and playing a G shape produces the sound of an A chord.': { prompt: 'Placer un capo à la 2e frette et jouer une forme de Sol produit le son d\'un accord de La.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A capo should be placed close to the ___ for the cleanest sound.': { prompt: 'Un capo devrait être placé près de la ___ pour le son le plus propre.', options: ['Frette', 'Sillet', 'Chevalet', 'Rosace'], correctAnswer: 'Frette' },
  'Why do singers use a capo?': { prompt: 'Pourquoi les chanteurs utilisent-ils un capo?', options: ['Pour rendre la guitare plus forte', 'Pour changer la tonalité afin de correspondre à leur tessiture vocale tout en utilisant des formes d\'accords familières', 'Pour jouer plus vite', 'Ça n\'a aucune utilité pratique'], correctAnswer: 'Pour changer la tonalité afin de correspondre à leur tessiture vocale tout en utilisant des formes d\'accords familières' },
  'A capo can only be used on acoustic guitars.': { prompt: 'Un capo ne peut être utilisé que sur des guitares acoustiques.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Capo on the 4th fret playing a C shape produces which chord?': { prompt: 'Un capo à la 4e frette jouant une forme de Do produit quel accord?', options: ['Ré', 'Mi', 'Fa', 'Sol'], correctAnswer: 'Mi' },
  'Relying entirely on a capo and never learning barre chords.': { prompt: 'Se fier entièrement à un capo et ne jamais apprendre les accords barrés.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Using a capo changes the timbre (tone quality) of the guitar, making it brighter as you move up the neck.': { prompt: 'Utiliser un capo change le timbre (qualité du son) de la guitare, le rendant plus brillant à mesure que vous montez le long du manche.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Music Theory
  'What is an "interval" in music?': { prompt: 'Qu\'est-ce qu\'un "intervalle" en musique?', options: ['Une pause entre les chansons', 'La distance en hauteur entre deux notes', 'Un type d\'accord', 'Un patron rythmique'], correctAnswer: 'La distance en hauteur entre deux notes' },
  'A chord built on the 1st, 4th, and 5th degrees of a scale forms the most common progression in music.': { prompt: 'Un accord construit sur les 1er, 4e et 5e degrés d\'une gamme forme la progression la plus courante en musique.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The distance of two frets (two half steps) on a guitar equals one ___ step.': { prompt: 'La distance de deux frettes (deux demi-tons) sur une guitare équivaut à un ___.', options: ['Ton', 'Demi-ton', 'Quart de ton', 'Double ton'], correctAnswer: 'Ton' },
  'What is a "key" in music?': { prompt: 'Qu\'est-ce qu\'une "tonalité" en musique?', options: ['Un bouton physique', 'Le groupe de notes et d\'accords construits sur une gamme spécifique', 'Le niveau de volume', 'La vitesse d\'une chanson'], correctAnswer: 'Le groupe de notes et d\'accords construits sur une gamme spécifique' },
  'The Nashville Number System uses numbers instead of letter names for chords.': { prompt: 'Le Nashville Number System utilise des chiffres au lieu de noms de lettres pour les accords.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is a "relative minor" key?': { prompt: 'Qu\'est-ce qu\'une tonalité "relative mineure"?', options: ['Une tonalité avec les mêmes dièses/bémols qu\'une tonalité majeure mais commençant sur le 6e degré', 'Une version plus forte du majeur', 'Une tonalité mineure un ton en dessous du majeur', 'La même chose que le mineur parallèle'], correctAnswer: 'Une tonalité avec les mêmes dièses/bémols qu\'une tonalité majeure mais commençant sur le 6e degré' },
  'Learning basic music theory to understand why certain chords and scales work together.': { prompt: 'Apprendre les bases de la théorie musicale pour comprendre pourquoi certains accords et gammes fonctionnent ensemble.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'A sharp (#) raises a note by one half step, and a flat (b) lowers it by one half step.': { prompt: 'Un dièse (#) élève une note d\'un demi-ton, et un bémol (b) l\'abaisse d\'un demi-ton.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Acoustic vs Electric
  'What is the main difference in how acoustic and electric guitars produce sound?': { prompt: 'Quelle est la principale différence dans la façon dont les guitares acoustiques et électriques produisent le son?', options: ['L\'acoustique utilise un corps creux pour amplifier les vibrations; l\'électrique utilise des micros et un amplificateur', 'Il n\'y a pas de vraie différence', 'Les guitares électriques sont toujours plus fortes', 'Les guitares acoustiques ont plus de cordes'], correctAnswer: 'L\'acoustique utilise un corps creux pour amplifier les vibrations; l\'électrique utilise des micros et un amplificateur' },
  'Electric guitars generally have thinner necks and lower string action than acoustics.': { prompt: 'Les guitares électriques ont généralement des manches plus fins et une action de cordes plus basse que les acoustiques.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Electric guitar ___ detect string vibrations and convert them into electrical signals.': { prompt: 'Les ___ de guitare électrique détectent les vibrations des cordes et les convertissent en signaux électriques.', options: ['Micros', 'Chevalets', 'Mécaniques', 'Frettes'], correctAnswer: 'Micros' },
  'Which guitar type is generally recommended for beginners?': { prompt: 'Quel type de guitare est généralement recommandé pour les débutants?', options: ['Électrique, car l\'action plus basse est plus facile pour les doigts', 'Guitare basse', 'Ça dépend du style de musique qu\'ils veulent jouer', 'Acoustique 12 cordes'], correctAnswer: 'Ça dépend du style de musique qu\'ils veulent jouer' },
  'Nylon-string (classical) guitars are easier on the fingers than steel-string acoustics.': { prompt: 'Les guitares à cordes de nylon (classiques) sont plus douces pour les doigts que les acoustiques à cordes d\'acier.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is a "humbucker" pickup?': { prompt: 'Qu\'est-ce qu\'un micro "humbucker"?', options: ['Un micro à simple bobinage', 'Un micro à double bobinage qui réduit le bourdonnement et produit un son plus épais', 'Un type de guitare acoustique', 'Un appareil d\'accordage'], correctAnswer: 'Un micro à double bobinage qui réduit le bourdonnement et produit un son plus épais' },
  'Using acoustic guitar strings on an electric guitar.': { prompt: 'Utiliser des cordes de guitare acoustique sur une guitare électrique.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'An acoustic-electric guitar has a built-in pickup so it can be plugged into an amplifier.': { prompt: 'Une guitare électro-acoustique a un micro intégré pour pouvoir être branchée à un amplificateur.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Song Structure
  'What are the most common sections of a song?': { prompt: 'Quelles sont les sections les plus courantes d\'une chanson?', options: ['Couplet, refrain, pont', 'Seulement couplet et refrain', 'Intro, solo, fin', 'Riff, lick, fill'], correctAnswer: 'Couplet, refrain, pont' },
  'The chorus is typically the most memorable and repeated part of a song.': { prompt: 'Le refrain est typiquement la partie la plus mémorable et répétée d\'une chanson.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A ___ connects two sections of a song and provides contrast from the verse and chorus.': { prompt: 'Un ___ relie deux sections d\'une chanson et offre un contraste avec le couplet et le refrain.', options: ['Pont', 'Riff', 'Solo', 'Fill'], correctAnswer: 'Pont' },
  'What does "AABA" form mean?': { prompt: 'Que signifie la forme "AABA"?', options: ['Une séquence de lettres aléatoire', 'A = section couplet/refrain, B = pont — une forme de chanson courante en jazz et pop', 'Quatre sections différentes', 'Une méthode d\'accordage'], correctAnswer: 'A = section couplet/refrain, B = pont — une forme de chanson courante en jazz et pop' },
  'An "outro" is the ending section of a song.': { prompt: 'Un "outro" est la section finale d\'une chanson.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is a "pre-chorus"?': { prompt: 'Qu\'est-ce qu\'un "pré-refrain"?', options: ['La section avant l\'intro', 'Une courte section entre le couplet et le refrain qui crée de la tension', 'Un autre nom pour le pont', 'Le premier couplet'], correctAnswer: 'Une courte section entre le couplet et le refrain qui crée de la tension' },
  'Learning full songs rather than only practicing exercises and scales.': { prompt: 'Apprendre des chansons complètes plutôt que de seulement pratiquer des exercices et des gammes.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Many hit songs use only 3-4 chords repeated throughout.': { prompt: 'Beaucoup de chansons à succès n\'utilisent que 3-4 accords répétés tout au long.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Practice Routine
  'How long should a beginner practice each day?': { prompt: 'Combien de temps un débutant devrait-il pratiquer chaque jour?', options: ['Au moins 3 heures', '15 à 30 minutes de pratique concentrée', '5 minutes maximum', 'Seulement les fins de semaine'], correctAnswer: '15 à 30 minutes de pratique concentrée' },
  'Warming up before practicing helps prevent injury and improves performance.': { prompt: 'S\'échauffer avant de pratiquer aide à prévenir les blessures et améliore la performance.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Practicing at a ___ tempo and gradually increasing speed is the most effective way to learn.': { prompt: 'Pratiquer à un tempo ___ et augmenter graduellement la vitesse est la façon la plus efficace d\'apprendre.', options: ['Lent', 'Rapide', 'Aléatoire', 'Maximum'], correctAnswer: 'Lent' },
  'What should an effective practice session include?': { prompt: 'Que devrait inclure une session de pratique efficace?', options: ['Seulement jouer des chansons que vous connaissez déjà', 'Échauffement, travail technique, nouveau matériel et jouer pour le plaisir', 'Seulement des gammes pour toute la session', 'Juste improviser librement'], correctAnswer: 'Échauffement, travail technique, nouveau matériel et jouer pour le plaisir' },
  'Recording yourself playing and listening back is a powerful practice tool.': { prompt: 'S\'enregistrer en jouant et se réécouter est un outil de pratique puissant.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is "deliberate practice"?': { prompt: 'Qu\'est-ce que la "pratique délibérée"?', options: ['Jouer ce qui vous tente', 'Travail concentré sur des faiblesses spécifiques avec des objectifs clairs', 'Jouer le plus longtemps possible', 'Pratiquer seulement du matériel facile'], correctAnswer: 'Travail concentré sur des faiblesses spécifiques avec des objectifs clairs' },
  'Only practicing things you are already good at and avoiding challenges.': { prompt: 'Pratiquer seulement ce que vous maîtrisez déjà et éviter les défis.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Which practice approach is more effective?': { prompt: 'Quelle approche de pratique est la plus efficace?', options: ['Jouer au hasard pendant une heure avec la télé allumée.', 'Mettre un minuteur de 20 minutes concentrées avec des objectifs spécifiques pour chaque section.'], correctAnswer: 'Mettre un minuteur de 20 minutes concentrées avec des objectifs spécifiques pour chaque section.' },
};
