export const magicTricksFr: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // Magic Basics
  'What is the #1 rule of magic?': { prompt: 'Quelle est la règle n°1 de la magie?', options: ['Porter une cape', 'Bouger vite', 'Utiliser des accessoires coûteux', 'Ne jamais révéler le secret'], correctAnswer: 'Ne jamais révéler le secret' },
  'Magic is mostly about speed of hands.': { prompt: 'La magie est principalement une question de vitesse des mains.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'What are the 3 parts of any magic trick?': { prompt: 'Quelles sont les 3 parties de tout tour de magie?', options: ['Préparation, Performance, Applaudissements', 'La Promesse, Le Tour, Le Prestige', 'Intro, Milieu, Fin', 'Mélange, Coupe, Distribution'], correctAnswer: 'La Promesse, Le Tour, Le Prestige' },
  'Practicing in front of a mirror before performing.': { prompt: 'Pratiquer devant un miroir avant de performer.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'You should always tell the audience what you\'re about to do.': { prompt: 'Vous devriez toujours dire au public ce que vous allez faire.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'What is a "gimmick" in magic?': { prompt: 'Qu\'est-ce qu\'un "gimmick" en magie?', options: ['Une blague que vous racontez', 'Un type de carte', 'Un dispositif secret qui aide le tour', 'Votre tenue de scène'], correctAnswer: 'Un dispositif secret qui aide le tour' },
  'The story a magician tells during a trick is called ___.': { prompt: 'L\'histoire qu\'un magicien raconte pendant un tour s\'appelle le ___.', options: ['Boniment', 'Script', 'Paroles', 'Scénario'], correctAnswer: 'Boniment' },
  'Which intro is better for a magic show?': { prompt: 'Quelle intro est meilleure pour un spectacle de magie?', options: ['Je vais faire un tour maintenant.', 'Avez-vous déjà vécu un moment où l\'impossible est devenu réel? Regardez bien...'], correctAnswer: 'Avez-vous déjà vécu un moment où l\'impossible est devenu réel? Regardez bien...' },

  // Card Fundamentals
  'How many cards are in a standard deck?': { prompt: 'Combien de cartes y a-t-il dans un jeu standard?', options: ['54', '50', '52', '48'], correctAnswer: '52' },
  'What are the 4 suits in a deck?': { prompt: 'Quelles sont les 4 enseignes d\'un jeu de cartes?', options: ['Cœurs, Étoiles, Lunes, Soleils', 'Rouge, Bleu, Vert, Jaune', 'As, Rois, Dames, Valets', 'Cœurs, Carreaux, Trèfles, Piques'], correctAnswer: 'Cœurs, Carreaux, Trèfles, Piques' },
  'A "bridge" is a way to shuffle cards by bending them.': { prompt: 'Un "bridge" est une façon de mélanger les cartes en les courbant.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is a "spread" in card magic?': { prompt: 'Qu\'est-ce qu\'un "spread" en magie des cartes?', options: ['Étaler les cartes face visible sur une table', 'Lancer les cartes partout', 'Couper le jeu', 'Distribuer aux joueurs'], correctAnswer: 'Étaler les cartes face visible sur une table' },
  'The top card of the deck is important because most ___ start there.': { prompt: 'La carte du dessus du jeu est importante car la plupart des ___ commencent là.', options: ['Contrôles', 'Mélanges', 'Paris', 'Jeux'], correctAnswer: 'Contrôles' },
  'Bending someone else\'s cards without permission.': { prompt: 'Plier les cartes de quelqu\'un d\'autre sans permission.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is a "key card"?': { prompt: 'Qu\'est-ce qu\'une "carte clé"?', options: ['Une carte dont vous connaissez secrètement la position', 'Une carte avec une marque', 'La carte la plus chère', 'L\'As de Pique'], correctAnswer: 'Une carte dont vous connaissez secrètement la position' },
  'You should always use a brand new deck for performances.': { prompt: 'Vous devriez toujours utiliser un jeu neuf pour les performances.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },

  // Coin Tricks
  'What is the "French Drop"?': { prompt: 'Qu\'est-ce que la "French Drop"?', options: ['Un faux transfert où la pièce reste cachée', 'Une disparition de pièce utilisant une table', 'Lancer une pièce en l\'air', 'Laisser tomber une pièce française'], correctAnswer: 'Un faux transfert où la pièce reste cachée' },
  'Larger coins are easier for beginners to palm.': { prompt: 'Les pièces plus grandes sont plus faciles à empalmer pour les débutants.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What size coin is most popular for magic?': { prompt: 'Quelle taille de pièce est la plus populaire pour la magie?', options: ['Dime', 'Penny', 'Quarter', 'Half Dollar'], correctAnswer: 'Half Dollar' },
  'Hiding a coin in the curl of your fingers is called ___ palm.': { prompt: 'Cacher une pièce dans la courbure de vos doigts s\'appelle l\'empalmage ___.', options: ['Classique', 'Français', 'Anglais', 'Digital'], correctAnswer: 'Classique' },
  'Looking at your hand where the coin is hidden.': { prompt: 'Regarder votre main où la pièce est cachée.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Where should you look during a coin vanish?': { prompt: 'Où devriez-vous regarder pendant une disparition de pièce?', options: ['La main qui tient secrètement la pièce', 'Le sol', 'Le plafond', 'La main que le public croit tenir la pièce'], correctAnswer: 'La main que le public croit tenir la pièce' },
  'The "Muscle Pass" launches a coin from your palm using muscle tension.': { prompt: 'Le "Muscle Pass" lance une pièce de votre paume en utilisant la tension musculaire.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which coin vanish presentation is better?': { prompt: 'Quelle présentation de disparition de pièce est meilleure?', options: ['Regardez, je vais faire disparaître cette pièce. *fait le mouvement*', 'Tendez votre main... sentez le poids de la pièce... maintenant fermez lentement vos doigts... ouvrez-les. Elle a disparu.'], correctAnswer: 'Tendez votre main... sentez le poids de la pièce... maintenant fermez lentement vos doigts... ouvrez-les. Elle a disparu.' },

  // Misdirection
  'What is misdirection?': { prompt: 'Qu\'est-ce que la misdirection?', options: ['Bouger très vite', 'Contrôler où le public regarde', 'Utiliser de la fumée et des miroirs', 'Parler très fort'], correctAnswer: 'Contrôler où le public regarde' },
  'People naturally look where you look.': { prompt: 'Les gens regardent naturellement là où vous regardez.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which is the strongest form of misdirection?': { prompt: 'Quelle est la forme de misdirection la plus forte?', options: ['Des bruits forts', 'La gestion naturelle de l\'attention', 'Un boniment confus', 'Des lumières vives'], correctAnswer: 'La gestion naturelle de l\'attention' },
  'Saying "don\'t look at my left hand" during a trick.': { prompt: 'Dire "ne regardez pas ma main gauche" pendant un tour.', options: ['Bonne misdirection', 'Mauvaise misdirection'], correctAnswer: 'Mauvaise misdirection' },
  'The moment when the secret move happens is called the ___ moment.': { prompt: 'Le moment où le mouvement secret se produit s\'appelle le moment ___.', options: ['Off-beat', 'High-beat', 'Secret', 'Silencieux'], correctAnswer: 'Off-beat' },
  'When should you do the secret move?': { prompt: 'Quand devriez-vous faire le mouvement secret?', options: ['Jamais — utilisez des gimmicks à la place', 'Quand tout le monde regarde attentivement', 'Au tout début', 'Pendant un moment de détente ou de rire'], correctAnswer: 'Pendant un moment de détente ou de rire' },
  'Humor is a powerful misdirection tool.': { prompt: 'L\'humour est un puissant outil de misdirection.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which uses better misdirection?': { prompt: 'Lequel utilise une meilleure misdirection?', options: ['*Fixe ses mains en faisant le mouvement*', '*Fait une blague, le public rit, fait le mouvement pendant le rire*'], correctAnswer: '*Fait une blague, le public rit, fait le mouvement pendant le rire*' },

  // The Double Lift
  'What is a double lift?': { prompt: 'Qu\'est-ce qu\'un double lift?', options: ['Prendre tout le jeu', 'Soulever une carte à deux mains', 'Retourner le jeu deux fois', 'Soulever deux cartes comme si c\'en était une seule'], correctAnswer: 'Soulever deux cartes comme si c\'en était une seule' },
  'The double lift is one of the most important sleights in card magic.': { prompt: 'Le double lift est l\'un des tours de passe-passe les plus importants en magie des cartes.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'How do you prepare for a double lift?': { prompt: 'Comment préparez-vous un double lift?', options: ['Secouer le jeu', 'Lécher vos doigts', 'Obtenir un "break" au-dessus des deux cartes du dessus', 'Courber tout le jeu'], correctAnswer: 'Obtenir un "break" au-dessus des deux cartes du dessus' },
  'A small gap held by your pinky between cards is called a ___.': { prompt: 'Un petit espace maintenu par votre auriculaire entre les cartes s\'appelle un ___.', options: ['Break', 'Split', 'Gap', 'Hold'], correctAnswer: 'Break' },
  'Practicing the double lift at the same speed as turning a single card.': { prompt: 'Pratiquer le double lift à la même vitesse que retourner une seule carte.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'A double lift should look exactly like turning one card over.': { prompt: 'Un double lift devrait ressembler exactement à retourner une seule carte.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What famous trick relies heavily on the double lift?': { prompt: 'Quel tour célèbre repose fortement sur le double lift?', options: ['La routine de la Carte Ambitieuse', 'Disparition de pièce', 'Corde coupée', 'Gobelets et balles'], correctAnswer: 'La routine de la Carte Ambitieuse' },
  'Lifting the cards at a different speed than a normal single flip.': { prompt: 'Soulever les cartes à une vitesse différente d\'un retournement simple normal.', options: ['Bonne technique', 'Mauvaise technique'], correctAnswer: 'Mauvaise technique' },

  // Palming
  'What is palming?': { prompt: 'Qu\'est-ce que l\'empalmage?', options: ['Applaudir des mains', 'Un type de coupe de cartes', 'Cacher secrètement un objet dans sa main', 'Montrer les deux mains vides'], correctAnswer: 'Cacher secrètement un objet dans sa main' },
  'Which palm hides a card in the center of your palm?': { prompt: 'Quel empalmage cache une carte au centre de votre paume?', options: ['Empalmage digital', 'Empalmage Tenkai', 'Gambler\'s cop', 'Empalmage classique'], correctAnswer: 'Empalmage classique' },
  'Your hand should look tense and closed when palming.': { prompt: 'Votre main devrait avoir l\'air tendue et fermée lors de l\'empalmage.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'The ___ palm holds the card using just the fingers, not the palm itself.': { prompt: 'L\'empalmage ___ tient la carte en utilisant seulement les doigts, pas la paume elle-même.', options: ['Digital', 'Classique', 'Dorsal', 'Latéral'], correctAnswer: 'Digital' },
  'Keeping your palming hand in a natural position at your side.': { prompt: 'Garder votre main d\'empalmage dans une position naturelle à votre côté.', options: ['Bonne technique', 'Mauvaise technique'], correctAnswer: 'Bonne technique' },
  'Squeezing the card tightly so it doesn\'t fall.': { prompt: 'Serrer la carte fort pour qu\'elle ne tombe pas.', options: ['Bonne technique', 'Mauvaise technique'], correctAnswer: 'Mauvaise technique' },
  'You should practice palming while watching TV to build muscle memory.': { prompt: 'Vous devriez pratiquer l\'empalmage en regardant la télé pour développer la mémoire musculaire.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What should your palming hand look like?': { prompt: 'À quoi devrait ressembler votre main d\'empalmage?', options: ['Naturellement détendue, légèrement courbée', 'Pointer quelque chose', 'Serrée en poing', 'Complètement plate et ouverte'], correctAnswer: 'Naturellement détendue, légèrement courbée' },

  // Forces
  'What is a "force" in magic?': { prompt: 'Qu\'est-ce qu\'un "forçage" en magie?', options: ['Pousser quelqu\'un à être volontaire', 'Utiliser la force physique dans les tours', 'Faire choisir à quelqu\'un une carte spécifique tout en se sentant libre', 'Plier une carte avec force'], correctAnswer: 'Faire choisir à quelqu\'un une carte spécifique tout en se sentant libre' },
  'What is the "Hindu Shuffle Force"?': { prompt: 'Qu\'est-ce que le "Forçage par mélange Hindou"?', options: ['Un forçage inventé en Inde', 'Faire glisser des paquets du jeu, s\'arrêter quand on vous le dit', 'Étaler les cartes sur un tapis hindou', 'Un forçage utilisant une prière hindoue'], correctAnswer: 'Faire glisser des paquets du jeu, s\'arrêter quand on vous le dit' },
  'The Classic Force requires no skill — anyone can do it.': { prompt: 'Le Forçage Classique ne requiert aucune compétence — n\'importe qui peut le faire.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'The simplest force is the ___ force, where you just ask them to say "stop".': { prompt: 'Le forçage le plus simple est le forçage par ___, où vous leur demandez juste de dire "stop".', options: ['Riffle', 'Classique', 'Hindou', 'Glissement'], correctAnswer: 'Riffle' },
  'Having a backup plan if the force fails.': { prompt: 'Avoir un plan de secours si le forçage échoue.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What makes a force convincing?': { prompt: 'Qu\'est-ce qui rend un forçage convaincant?', options: ['Faire sentir au spectateur qu\'il a vraiment eu un libre choix', 'Leur dire quelle carte prendre', 'Utiliser plusieurs jeux', 'Aller très vite'], correctAnswer: 'Faire sentir au spectateur qu\'il a vraiment eu un libre choix' },
  'If a force fails, you should tell the audience and try again.': { prompt: 'Si un forçage échoue, vous devriez le dire au public et réessayer.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Which force presentation is better?': { prompt: 'Quelle présentation de forçage est meilleure?', options: ['Prenez cette carte. Non, celle-ci. Prenez-la.', 'Parcourez les cartes... quand vous le sentez, touchez la carte qui vous appelle.'], correctAnswer: 'Parcourez les cartes... quand vous le sentez, touchez la carte qui vous appelle.' },
};
