export const marketingFr: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // Marketing 101
  'What are the 4 Ps of marketing?': { prompt: "Quels sont les 4 P du marketing?", options: ["Prix, Produit, Personnes, Processus", "Produit, Prix, Place, Promotion", "Planification, Production, Tarification, Publicité", "Position, Plateforme, Profit, Performance"], correctAnswer: "Produit, Prix, Place, Promotion" },
  'What is a value proposition?': { prompt: "Qu'est-ce qu'une proposition de valeur?", options: ["Le prix d'un produit", "Une déclaration qui explique pourquoi un client devrait acheter votre produit", "Une offre de réduction", "Une licence commerciale"], correctAnswer: "Une déclaration qui explique pourquoi un client devrait acheter votre produit" },
  'What is the difference between B2B and B2C?': { prompt: "Quelle est la différence entre B2B et B2C?", options: ["C'est la même chose", "B2B vend aux entreprises ; B2C vend aux consommateurs", "B2B est en ligne ; B2C est hors ligne", "B2B est gratuit ; B2C est payant"], correctAnswer: "B2B vend aux entreprises ; B2C vend aux consommateurs" },
  'What is ROI in marketing?': { prompt: "Qu'est-ce que le ROI en marketing?", options: ["Reach Of Influence", "Return On Investment", "Rate Of Interaction", "Revenue Over Income"], correctAnswer: "Return On Investment" },
  'Marketing and advertising are the same thing.': { prompt: "Le marketing et la publicité sont la même chose.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A strong brand can charge premium prices compared to unknown competitors.': { prompt: "Une marque forte peut facturer des prix premium par rapport à des concurrents inconnus.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Inbound marketing focuses on attracting customers through valuable content.': { prompt: "Le marketing entrant (inbound) se concentre sur l'attraction des clients par du contenu de valeur.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A ___ analysis examines Strengths, Weaknesses, Opportunities, and Threats.': { prompt: "Une analyse ___ examine les Forces, Faiblesses, Opportunités et Menaces.", options: ["PEST", "SWOT", "ROI", "KPI"], correctAnswer: "SWOT" },

  // Target Audience
  'What is a target audience?': { prompt: "Qu'est-ce qu'un public cible?", options: ["Tout le monde sur internet", "Un groupe spécifique de personnes les plus susceptibles d'acheter votre produit", "Vos concurrents", "Vos employés"], correctAnswer: "Un groupe spécifique de personnes les plus susceptibles d'acheter votre produit" },
  'What is a buyer persona?': { prompt: "Qu'est-ce qu'un persona d'acheteur?", options: ["Un faux compte de réseau social", "Un profil semi-fictif de votre client idéal", "Un ambassadeur célèbre", "Une analyse des concurrents"], correctAnswer: "Un profil semi-fictif de votre client idéal" },
  'What are demographics?': { prompt: "Que sont les données démographiques?", options: ["Des métriques de réseaux sociaux", "Des données statistiques sur une population (âge, sexe, revenu, etc.)", "Des analyses de site web", "Des caractéristiques de produit"], correctAnswer: "Des données statistiques sur une population (âge, sexe, revenu, etc.)" },
  'What are psychographics?': { prompt: "Que sont les données psychographiques?", options: ["Des données de santé mentale", "Des données sur les valeurs, intérêts, modes de vie et opinions", "Des caractéristiques physiques", "Des dossiers financiers"], correctAnswer: "Des données sur les valeurs, intérêts, modes de vie et opinions" },
  'What is market segmentation?': { prompt: "Qu'est-ce que la segmentation de marché?", options: ["Supprimer une partie du marché", "Diviser un large marché en groupes plus petits et définis", "Fusionner deux marchés", "Stratégie de prix"], correctAnswer: "Diviser un large marché en groupes plus petits et définis" },
  'Trying to market to everyone is more effective than targeting a niche audience.': { prompt: "Essayer de faire du marketing pour tout le monde est plus efficace que cibler un public de niche.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Customer surveys are a valid way to learn about your target audience.': { prompt: "Les sondages clients sont un moyen valide d'en apprendre sur votre public cible.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A customer ___ map visualizes the steps a customer takes from awareness to purchase.': { prompt: "Une carte du ___ client visualise les étapes qu'un client suit de la découverte à l'achat.", options: ["ventes", "parcours", "flux", "conversion"], correctAnswer: "parcours" },

  // Brand Identity
  'What makes up a brand identity?': { prompt: "Qu'est-ce qui compose une identité de marque?", options: ["Seulement le logo", "Logo, couleurs, polices, ton de voix et valeurs", "Seulement le nom de l'entreprise", "Seulement le site web"], correctAnswer: "Logo, couleurs, polices, ton de voix et valeurs" },
  'What is brand positioning?': { prompt: "Qu'est-ce que le positionnement de marque?", options: ["Où se trouve votre magasin", "Comment votre marque est perçue sur le marché par rapport aux concurrents", "L'emplacement de votre logo", "Le classement de votre site web"], correctAnswer: "Comment votre marque est perçue sur le marché par rapport aux concurrents" },
  'What is a brand style guide?': { prompt: "Qu'est-ce qu'un guide de style de marque?", options: ["Un magazine de mode", "Un document définissant comment utiliser les éléments de marque de manière cohérente", "Un plan marketing", "Un sondage client"], correctAnswer: "Un document définissant comment utiliser les éléments de marque de manière cohérente" },
  'What is tone of voice in branding?': { prompt: "Qu'est-ce que le ton de voix dans le branding?", options: ["Le volume de vos publicités", "La personnalité et l'émotion cohérentes exprimées dans la communication de la marque", "Le style de discours du PDG", "Le branding audio"], correctAnswer: "La personnalité et l'émotion cohérentes exprimées dans la communication de la marque" },
  'A strong brand identity makes a business more recognizable and trustworthy.': { prompt: "Une identité de marque forte rend une entreprise plus reconnaissable et digne de confiance.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Rebranding is never a good idea once a brand is established.': { prompt: "Le rebranding n'est jamais une bonne idée une fois qu'une marque est établie.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Color psychology plays a role in brand perception.': { prompt: "La psychologie des couleurs joue un rôle dans la perception de la marque.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Brand ___ is the commercial value derived from consumer perception of a brand name.': { prompt: "Le ___ de marque est la valeur commerciale dérivée de la perception d'un nom de marque par les consommateurs.", options: ["capital", "identité", "notoriété", "fidélité"], correctAnswer: "capital" },

  // Content Types
  'Which content format typically gets the most engagement on social media?': { prompt: "Quel format de contenu obtient généralement le plus d'engagement sur les réseaux sociaux?", options: ["Publications texte simples", "Contenu vidéo", "Liens externes", "Documents PDF"], correctAnswer: "Contenu vidéo" },
  'What is a content calendar?': { prompt: "Qu'est-ce qu'un calendrier de contenu?", options: ["Un calendrier de vacances", "Un plan qui organise quand et où publier du contenu", "Une liste de sujets de blog", "Une application de réseau social"], correctAnswer: "Un plan qui organise quand et où publier du contenu" },
  'What is user-generated content (UGC)?': { prompt: "Qu'est-ce que le contenu généré par les utilisateurs (UGC)?", options: ["Du contenu fait par l'IA", "Du contenu créé par les clients à propos d'une marque", "Du contenu des concurrents", "De la publicité payante"], correctAnswer: "Du contenu créé par les clients à propos d'une marque" },
  'What is evergreen content?': { prompt: "Qu'est-ce que le contenu evergreen (intemporel)?", options: ["Du contenu sur la nature", "Du contenu qui reste pertinent et utile sur une longue période", "Du contenu publié au printemps", "Du contenu promotionnel temporaire"], correctAnswer: "Du contenu qui reste pertinent et utile sur une longue période" },
  'Infographics combine visuals and data to make information easier to understand.': { prompt: "Les infographies combinent visuels et données pour rendre l'information plus facile à comprendre.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Long-form blog posts (2000+ words) tend to rank higher on Google than short ones.': { prompt: "Les articles de blog longs (2000+ mots) tendent à mieux se classer sur Google que les courts.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Repurposing content means creating the same content for different platforms without changes.': { prompt: "Réutiliser du contenu signifie créer le même contenu pour différentes plateformes sans changement.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A ___ is a series of related content pieces delivered over time, often via email.': { prompt: "Une ___ est une série de contenus liés livrés dans le temps, souvent par email.", options: ["entonnoir", "campagne au goutte-à-goutte", "page d'atterrissage", "webinaire"], correctAnswer: "campagne au goutte-à-goutte" },

  // Social Media
  'What is organic reach on social media?': { prompt: "Qu'est-ce que la portée organique sur les réseaux sociaux?", options: ["Portée publicitaire payante", "Le nombre de personnes qui voient votre contenu sans promotion payante", "Trafic de bots", "Abonnés email"], correctAnswer: "Le nombre de personnes qui voient votre contenu sans promotion payante" },
  'What is the best metric for measuring social media engagement?': { prompt: "Quelle est la meilleure métrique pour mesurer l'engagement sur les réseaux sociaux?", options: ["Nombre d'abonnés", "Taux d'engagement (likes + commentaires + partages / portée)", "Nombre de publications", "Âge du compte"], correctAnswer: "Taux d'engagement (likes + commentaires + partages / portée)" },
  'What is a social media algorithm?': { prompt: "Qu'est-ce qu'un algorithme de réseau social?", options: ["Un type de publication", "Un système qui décide quel contenu les utilisateurs voient dans leur fil", "Une stratégie marketing", "Un outil de planification"], correctAnswer: "Un système qui décide quel contenu les utilisateurs voient dans leur fil" },
  'What is the 80/20 rule in social media content?': { prompt: "Quelle est la règle 80/20 pour le contenu des réseaux sociaux?", options: ["80% pubs, 20% contenu", "80% valeur/divertissement, 20% promotionnel", "80% vidéo, 20% photos", "80% texte, 20% images"], correctAnswer: "80% valeur/divertissement, 20% promotionnel" },
  'Posting consistently is more important than posting frequently.': { prompt: "Publier de manière cohérente est plus important que publier fréquemment.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Hashtags are completely useless for discoverability in 2024+.': { prompt: "Les hashtags sont complètement inutiles pour la découvrabilité en 2024+.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Responding to comments increases your engagement rate and algorithm visibility.': { prompt: "Répondre aux commentaires augmente votre taux d'engagement et votre visibilité algorithmique.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A ___ is a pre-planned collection of content scheduled to post automatically.': { prompt: "Une ___ est une collection de contenu pré-planifié programmé pour être publié automatiquement.", options: ["file de contenu", "fil d'actualités", "story à la une", "blog roll"], correctAnswer: "file de contenu" },

  // Instagram
  'Which Instagram feature is best for behind-the-scenes content?': { prompt: "Quelle fonctionnalité Instagram est la meilleure pour le contenu en coulisses?", options: ["Publications du fil", "Stories", "Guides", "Boutique"], correctAnswer: "Stories" },
  'What is the ideal aspect ratio for Instagram Reels?': { prompt: "Quel est le ratio d'aspect idéal pour les Reels Instagram?", options: ["1:1", "16:9", "9:16", "4:3"], correctAnswer: "9:16" },
  'What are Instagram carousel posts?': { prompt: "Que sont les publications carrousel Instagram?", options: ["Des publications vidéo uniquement", "Des publications avec plusieurs images ou vidéos à faire défiler (jusqu'à 20)", "Des publications animées", "Un format publicitaire uniquement"], correctAnswer: "Des publications avec plusieurs images ou vidéos à faire défiler (jusqu'à 20)" },
  'What is the Instagram algorithm most likely to prioritize?': { prompt: "Que l'algorithme Instagram est-il le plus susceptible de prioriser?", options: ["Les publications avec le plus de hashtags", "Le contenu avec des taux élevés d'enregistrement et de partage", "Les publications avec des liens externes", "Les publications les plus anciennes d'abord"], correctAnswer: "Le contenu avec des taux élevés d'enregistrement et de partage" },
  'What is a CTA in an Instagram caption?': { prompt: "Qu'est-ce qu'un CTA dans une légende Instagram?", options: ["Creative Text Art", "Call To Action — une invitation disant aux utilisateurs quoi faire ensuite", "Caption Text Area", "Content Type Analysis"], correctAnswer: "Call To Action — une invitation disant aux utilisateurs quoi faire ensuite" },
  'Instagram Reels get more reach than static posts in most cases.': { prompt: "Les Reels Instagram obtiennent plus de portée que les publications statiques dans la plupart des cas.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'You need 10,000 followers to add links to Instagram Stories.': { prompt: "Vous avez besoin de 10 000 abonnés pour ajouter des liens aux Stories Instagram.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'The ___ in bio is often the only clickable link on an Instagram profile.': { prompt: "Le ___ dans la bio est souvent le seul lien cliquable sur un profil Instagram.", options: ["hashtag", "lien", "story", "reel"], correctAnswer: "lien" },

  // TikTok
  'What is TikTok\'s main content format?': { prompt: "Quel est le format de contenu principal de TikTok?", options: ["Longs articles de blog", "Vidéos verticales courtes", "Vidéos horizontales", "Podcasts audio"], correctAnswer: "Vidéos verticales courtes" },
  'What is the TikTok "For You Page" (FYP)?': { prompt: 'Qu\'est-ce que la page "Pour Toi" (FYP) de TikTok?', options: ["Une page de profil", "Un fil personnalisé de vidéos recommandées", "Une fonctionnalité de messagerie", "Une page de shopping"], correctAnswer: "Un fil personnalisé de vidéos recommandées" },
  'What is the most important factor for TikTok video success?': { prompt: "Quel est le facteur le plus important pour le succès d'une vidéo TikTok?", options: ["Le nombre d'abonnés", "Le temps de visionnage et le taux de complétion", "Le nombre de hashtags", "La durée de la vidéo"], correctAnswer: "Le temps de visionnage et le taux de complétion" },
  'What is a "hook" in TikTok content?': { prompt: 'Qu\'est-ce qu\'un "hook" dans le contenu TikTok?', options: ["Une référence à la pêche", "Les 1-3 premières secondes qui captent l'attention", "Un effet sonore", "Une transition"], correctAnswer: "Les 1-3 premières secondes qui captent l'attention" },
  'TikTok shows your content to non-followers on the For You Page.': { prompt: "TikTok montre votre contenu aux non-abonnés sur la page Pour Toi.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'High production quality is required for TikTok videos to go viral.': { prompt: "Une qualité de production élevée est nécessaire pour que les vidéos TikTok deviennent virales.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Using trending sounds on TikTok can increase your video\'s reach.': { prompt: "Utiliser des sons tendance sur TikTok peut augmenter la portée de votre vidéo.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'TikTok ___ lets businesses run paid ads and promote products directly in the app.': { prompt: "TikTok ___ permet aux entreprises de diffuser des publicités payantes et promouvoir des produits directement dans l'app.", options: ["Creator Fund", "Ads Manager", "Live Studio", "Duet"], correctAnswer: "Ads Manager" },

  // YouTube
  'What is the most important factor for YouTube video discoverability?': { prompt: "Quel est le facteur le plus important pour la découvrabilité des vidéos YouTube?", options: ["La durée de la vidéo", "La miniature et le titre", "Le nombre d'abonnés", "L'heure de mise en ligne"], correctAnswer: "La miniature et le titre" },
  'What is YouTube SEO?': { prompt: "Qu'est-ce que le SEO YouTube?", options: ["Un outil de montage vidéo", "Optimiser les vidéos pour mieux se classer dans les recherches YouTube et Google", "Un programme de monétisation", "Un format de contenu"], correctAnswer: "Optimiser les vidéos pour mieux se classer dans les recherches YouTube et Google" },
  'What is Average View Duration (AVD)?': { prompt: "Qu'est-ce que la Durée Moyenne de Visionnage (AVD)?", options: ["Total des vues", "Le temps moyen que les spectateurs passent à regarder une vidéo", "Fréquence de mise en ligne", "Nombre d'abonnés"], correctAnswer: "Le temps moyen que les spectateurs passent à regarder une vidéo" },
  'What are YouTube Shorts?': { prompt: "Que sont les YouTube Shorts?", options: ["Des descriptions courtes", "Des vidéos verticales de moins de 60 secondes", "Des URL raccourcies", "Des titres abrégés"], correctAnswer: "Des vidéos verticales de moins de 60 secondes" },
  'YouTube is the second largest search engine in the world.': { prompt: "YouTube est le deuxième plus grand moteur de recherche au monde.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'You need 1,000 subscribers and 4,000 watch hours to monetize on YouTube.': { prompt: "Vous avez besoin de 1 000 abonnés et 4 000 heures de visionnage pour monétiser sur YouTube.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Longer YouTube videos always perform better than shorter ones.': { prompt: "Les vidéos YouTube plus longues performent toujours mieux que les courtes.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Click-through rate (___) measures how often people click on your video after seeing the thumbnail.': { prompt: "Le taux de clic (___) mesure la fréquence à laquelle les gens cliquent sur votre vidéo après avoir vu la miniature.", options: ["CTR", "CPC", "CPM", "CTA"], correctAnswer: "CTR" },

  // Copywriting
  'What is copywriting?': { prompt: "Qu'est-ce que le copywriting?", options: ["Le droit d'auteur", "Écrire du texte persuasif pour inciter à l'action", "Copier le contenu des autres", "Écrire du code"], correctAnswer: "Écrire du texte persuasif pour inciter à l'action" },
  'What is the AIDA formula?': { prompt: "Quelle est la formule AIDA?", options: ["Une application d'écriture", "Attention, Intérêt, Désir, Action", "Analyser, Implémenter, Designer, Ajuster", "Audience, Influence, Données, Analytics"], correctAnswer: "Attention, Intérêt, Désir, Action" },
  'What is a headline\'s primary job?': { prompt: "Quel est le rôle principal d'un titre?", options: ["Tout résumer", "Amener le lecteur à lire la ligne suivante", "Inclure des mots-clés", "Être joli"], correctAnswer: "Amener le lecteur à lire la ligne suivante" },
  'What does "sell benefits, not features" mean?': { prompt: 'Que signifie "vendre des bénéfices, pas des fonctionnalités"?', options: ["Ne pas lister les spécifications", "Se concentrer sur comment le produit améliore la vie du client", "Les bénéfices sont moins chers à marketer", "Les fonctionnalités n'ont pas d'importance"], correctAnswer: "Se concentrer sur comment le produit améliore la vie du client" },
  'Using "you" and "your" in copy makes it more engaging than "we" and "our".': { prompt: 'Utiliser "vous" et "votre" dans les textes les rend plus engageants que "nous" et "notre".', options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Long copy never works — shorter is always better.': { prompt: "Les textes longs ne marchent jamais — plus court est toujours mieux.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Social proof (testimonials, reviews) is a powerful copywriting technique.': { prompt: "La preuve sociale (témoignages, avis) est une technique de copywriting puissante.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The PAS framework stands for Problem, Agitate, ___.': { prompt: "Le cadre PAS signifie Problème, Agitation, ___.", options: ["Vendre", "Solution", "Stratégie", "Histoire"], correctAnswer: "Solution" },

  // Email Marketing
  'What is a good email open rate benchmark?': { prompt: "Quel est un bon taux d'ouverture d'email de référence?", options: ["1-5%", "15-25%", "50-60%", "90-100%"], correctAnswer: "15-25%" },
  'What is the most important element for getting emails opened?': { prompt: "Quel est l'élément le plus important pour faire ouvrir les emails?", options: ["Le corps du texte", "Les images", "L'objet du mail", "Le pied de page"], correctAnswer: "L'objet du mail" },
  'What is email segmentation?': { prompt: "Qu'est-ce que la segmentation email?", options: ["Bloquer le spam", "Diviser votre liste d'emails en groupes ciblés", "Écrire des emails plus courts", "Envoyer moins d'emails"], correctAnswer: "Diviser votre liste d'emails en groupes ciblés" },
  'What is a lead magnet?': { prompt: "Qu'est-ce qu'un lead magnet?", options: ["Un aimant puissant", "Une ressource gratuite offerte en échange d'une adresse email", "Un type de template email", "Un filtre anti-spam"], correctAnswer: "Une ressource gratuite offerte en échange d'une adresse email" },
  'What does the CAN-SPAM Act require?': { prompt: "Qu'exige la loi CAN-SPAM?", options: ["Tous les emails doivent être chiffrés", "Les emails commerciaux doivent inclure une option de désinscription", "Seules les entreprises peuvent envoyer des emails", "Les emails doivent faire moins de 500 mots"], correctAnswer: "Les emails commerciaux doivent inclure une option de désinscription" },
  'Personalized emails (using the recipient\'s name) have higher open rates.': { prompt: "Les emails personnalisés (utilisant le nom du destinataire) ont des taux d'ouverture plus élevés.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Buying email lists is an effective and recommended strategy.': { prompt: "Acheter des listes d'emails est une stratégie efficace et recommandée.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'An email ___ sequence is a series of automated emails sent to new subscribers.': { prompt: "Une séquence email de ___ est une série d'emails automatisés envoyés aux nouveaux abonnés.", options: ["blast", "bienvenue", "vente", "spam"], correctAnswer: "bienvenue" },

  // SEO Basics
  'What does SEO stand for?': { prompt: "Que signifie SEO?", options: ["Social Engagement Optimization", "Search Engine Optimization", "Site Enhancement Operations", "Search Email Outreach"], correctAnswer: "Search Engine Optimization" },
  'What is organic traffic?': { prompt: "Qu'est-ce que le trafic organique?", options: ["Le trafic des réseaux sociaux", "Les visiteurs qui trouvent votre site via les résultats de recherche non payants", "Le trafic des publicités payantes", "Le trafic de bots"], correctAnswer: "Les visiteurs qui trouvent votre site via les résultats de recherche non payants" },
  'What is a backlink?': { prompt: "Qu'est-ce qu'un backlink?", options: ["Un lien cassé", "Un lien d'un autre site web pointant vers le vôtre", "Un lien vers votre page d'accueil", "Un lien de réseau social"], correctAnswer: "Un lien d'un autre site web pointant vers le vôtre" },
  'What is on-page SEO?': { prompt: "Qu'est-ce que le SEO on-page?", options: ["Du SEO fait par les moteurs de recherche", "Des optimisations faites directement sur les pages de votre site", "Payer Google pour des classements", "L'optimisation des réseaux sociaux"], correctAnswer: "Des optimisations faites directement sur les pages de votre site" },
  'Page loading speed affects SEO rankings.': { prompt: "La vitesse de chargement des pages affecte le classement SEO.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Keyword stuffing (overusing keywords) helps improve rankings.': { prompt: "Le bourrage de mots-clés (surutilisation de mots-clés) aide à améliorer les classements.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Mobile-friendliness is a Google ranking factor.': { prompt: "L'adaptation mobile est un facteur de classement Google.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A ___ tag is the HTML element that defines the title shown in search engine results.': { prompt: "Une balise ___ est l'élément HTML qui définit le titre affiché dans les résultats des moteurs de recherche.", options: ["header", "title", "meta", "heading"], correctAnswer: "title" },

  // Keywords
  'What is a long-tail keyword?': { prompt: "Qu'est-ce qu'un mot-clé longue traîne?", options: ["Un mot-clé avec beaucoup de caractères", "Une phrase spécifique de plusieurs mots avec moins de compétition", "Le mot-clé le plus populaire", "Un mot-clé utilisé dans les titres uniquement"], correctAnswer: "Une phrase spécifique de plusieurs mots avec moins de compétition" },
  'What is search intent?': { prompt: "Qu'est-ce que l'intention de recherche?", options: ["La fréquence de recherche", "Le but derrière la requête de recherche d'un utilisateur", "La vitesse de chargement des résultats", "Le nombre de résultats de recherche"], correctAnswer: "Le but derrière la requête de recherche d'un utilisateur" },
  'Which tool is commonly used for keyword research?': { prompt: "Quel outil est couramment utilisé pour la recherche de mots-clés?", options: ["Photoshop", "Google Keyword Planner", "Slack", "GitHub"], correctAnswer: "Google Keyword Planner" },
  'What does keyword difficulty measure?': { prompt: "Que mesure la difficulté d'un mot-clé?", options: ["La difficulté d'orthographe du mot-clé", "Le niveau de compétition pour se classer sur ce mot-clé", "La longueur du mot-clé", "La fréquence de changement du mot-clé"], correctAnswer: "Le niveau de compétition pour se classer sur ce mot-clé" },
  'What is keyword cannibalization?': { prompt: "Qu'est-ce que la cannibalisation de mots-clés?", options: ["Utiliser trop de mots-clés", "Plusieurs pages de votre site en compétition pour le même mot-clé", "Voler les mots-clés des concurrents", "Supprimer des mots-clés du contenu"], correctAnswer: "Plusieurs pages de votre site en compétition pour le même mot-clé" },
  'Higher search volume always means a better keyword to target.': { prompt: "Un volume de recherche plus élevé signifie toujours un meilleur mot-clé à cibler.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'LSI (Latent Semantic Indexing) keywords are related terms that help search engines understand content context.': { prompt: "Les mots-clés LSI (Indexation Sémantique Latente) sont des termes liés qui aident les moteurs de recherche à comprendre le contexte du contenu.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Search ___ represents the number of times a keyword is searched per month.': { prompt: "Le ___ de recherche représente le nombre de fois qu'un mot-clé est recherché par mois.", options: ["rang", "volume", "intention", "autorité"], correctAnswer: "volume" },

  // Google Ads
  'What is Google Ads (formerly AdWords)?': { prompt: "Qu'est-ce que Google Ads (anciennement AdWords)?", options: ["Un outil SEO gratuit", "Une plateforme publicitaire payante où vous enchérissez sur des mots-clés", "Le service email de Google", "Une plateforme de réseau social"], correctAnswer: "Une plateforme publicitaire payante où vous enchérissez sur des mots-clés" },
  'What does CPC stand for?': { prompt: "Que signifie CPC?", options: ["Cost Per Customer", "Cost Per Click", "Click Per Campaign", "Content Per Channel"], correctAnswer: "Cost Per Click" },
  'What is Quality Score in Google Ads?': { prompt: "Qu'est-ce que le Quality Score dans Google Ads?", options: ["Une note du design de votre site", "L'évaluation par Google de la pertinence de l'annonce, du CTR et de la qualité de la page d'atterrissage", "Vos dépenses publicitaires totales", "Un score d'avis clients"], correctAnswer: "L'évaluation par Google de la pertinence de l'annonce, du CTR et de la qualité de la page d'atterrissage" },
  'What are negative keywords?': { prompt: "Que sont les mots-clés négatifs?", options: ["Des mots-clés avec un faible volume de recherche", "Des mots-clés que vous excluez pour empêcher votre annonce de s'afficher pour des recherches non pertinentes", "Des mots-clés utilisés par les concurrents", "Des mots-clés qui nuisent à votre SEO"], correctAnswer: "Des mots-clés que vous excluez pour empêcher votre annonce de s'afficher pour des recherches non pertinentes" },
  'In Google Ads, you only pay when someone clicks on your ad (PPC model).': { prompt: "Dans Google Ads, vous ne payez que lorsque quelqu'un clique sur votre annonce (modèle PPC).", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A higher bid always guarantees the top ad position.': { prompt: "Une enchère plus élevée garantit toujours la première position publicitaire.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Google Display Ads appear on websites in the Google Display Network, not in search results.': { prompt: "Les annonces Google Display apparaissent sur les sites du Réseau Display de Google, pas dans les résultats de recherche.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The ___ rate measures what percentage of people who click your ad complete a desired action.': { prompt: "Le taux de ___ mesure quel pourcentage de personnes qui cliquent sur votre annonce complètent une action souhaitée.", options: ["rebond", "clic", "conversion", "impression"], correctAnswer: "conversion" },

  // Facebook Ads
  'What platform manages both Facebook and Instagram ads?': { prompt: "Quelle plateforme gère à la fois les publicités Facebook et Instagram?", options: ["Google Ads", "Meta Ads Manager", "TikTok Business", "Twitter Ads"], correctAnswer: "Meta Ads Manager" },
  'What is a Lookalike Audience?': { prompt: "Qu'est-ce qu'une audience similaire (Lookalike)?", options: ["Un ensemble de publicités dupliqué", "Une audience qui partage des caractéristiques avec vos clients existants", "Des gens qui ressemblent à vos employés", "L'audience d'un concurrent"], correctAnswer: "Une audience qui partage des caractéristiques avec vos clients existants" },
  'What is the Facebook Pixel?': { prompt: "Qu'est-ce que le Pixel Facebook?", options: ["Un type de format d'image", "Un extrait de code qui suit le comportement des utilisateurs sur votre site web", "Un filtre pour photos", "Une fonctionnalité Facebook pour les stories"], correctAnswer: "Un extrait de code qui suit le comportement des utilisateurs sur votre site web" },
  'What is retargeting (remarketing)?': { prompt: "Qu'est-ce que le retargeting (remarketing)?", options: ["Cibler de nouvelles audiences", "Montrer des publicités aux personnes qui ont déjà visité votre site ou interagi avec votre contenu", "Changer votre cible publicitaire", "Supprimer d'anciennes campagnes"], correctAnswer: "Montrer des publicités aux personnes qui ont déjà visité votre site ou interagi avec votre contenu" },
  'Facebook Ads use an auction system where advertisers bid to reach their target audience.': { prompt: "Les Facebook Ads utilisent un système d'enchères où les annonceurs enchérissent pour atteindre leur audience cible.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'You should use the same ad creative for all audiences and placements.': { prompt: "Vous devriez utiliser le même visuel publicitaire pour toutes les audiences et tous les placements.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Custom Audiences let you target people from your own customer list.': { prompt: "Les audiences personnalisées vous permettent de cibler des personnes de votre propre liste de clients.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'CPM stands for Cost Per ___, meaning the cost per 1,000 ad impressions.': { prompt: "CPM signifie Cost Per ___, c'est-à-dire le coût pour 1 000 impressions publicitaires.", options: ["Mile", "Mille", "Million", "Message"], correctAnswer: "Mille" },

  // Analytics
  'What does a "bounce rate" measure?': { prompt: 'Que mesure le "taux de rebond"?', options: ["La vitesse de chargement de votre site", "Le pourcentage de visiteurs qui partent après avoir vu une seule page", "Le nombre de pages par visite", "Le total des visiteurs du site"], correctAnswer: "Le pourcentage de visiteurs qui partent après avoir vu une seule page" },
  'What is a KPI?': { prompt: "Qu'est-ce qu'un KPI?", options: ["Key Performance Indicator", "Keyword Placement Index", "Knowledge Processing Input", "Key Product Information"], correctAnswer: "Key Performance Indicator" },
  'What is the difference between sessions and users in Google Analytics?': { prompt: "Quelle est la différence entre sessions et utilisateurs dans Google Analytics?", options: ["C'est la même chose", "Les utilisateurs sont des visiteurs uniques ; les sessions sont des visites individuelles", "Les sessions sont uniques ; les utilisateurs sont les visites totales", "Les utilisateurs sont des bots ; les sessions sont de vraies personnes"], correctAnswer: "Les utilisateurs sont des visiteurs uniques ; les sessions sont des visites individuelles" },
  'What is a conversion in analytics?': { prompt: "Qu'est-ce qu'une conversion en analytique?", options: ["Changer le design du site", "Quand un utilisateur complète une action souhaitée (achat, inscription, etc.)", "Changer d'outil analytique", "Convertir de la devise"], correctAnswer: "Quand un utilisateur complète une action souhaitée (achat, inscription, etc.)" },
  'Google Analytics 4 (GA4) uses an event-based tracking model.': { prompt: "Google Analytics 4 (GA4) utilise un modèle de suivi basé sur les événements.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Vanity metrics like page views always indicate business success.': { prompt: "Les métriques de vanité comme les pages vues indiquent toujours le succès commercial.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'UTM parameters help track which campaigns drive traffic to your website.': { prompt: "Les paramètres UTM aident à suivre quelles campagnes génèrent du trafic vers votre site.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The ___ rate is the percentage of visitors who complete a desired action out of total visitors.': { prompt: "Le taux de ___ est le pourcentage de visiteurs qui complètent une action souhaitée sur le total des visiteurs.", options: ["rebond", "clic", "conversion", "engagement"], correctAnswer: "conversion" },

  // A/B Testing
  'What is A/B testing?': { prompt: "Qu'est-ce que le test A/B?", options: ["Tester deux produits différents", "Comparer deux versions de quelque chose pour voir laquelle performe mieux", "Un système de notation", "Tester sur deux appareils"], correctAnswer: "Comparer deux versions de quelque chose pour voir laquelle performe mieux" },
  'What should you test first for the biggest impact?': { prompt: "Que devriez-vous tester en premier pour le plus grand impact?", options: ["La taille de police", "La couleur du bouton", "Les titres et les CTA", "Les liens du pied de page"], correctAnswer: "Les titres et les CTA" },
  'How many variables should you change in a proper A/B test?': { prompt: "Combien de variables devriez-vous changer dans un test A/B correct?", options: ["Le plus possible", "Une seule à la fois", "Au moins trois", "Aucune"], correctAnswer: "Une seule à la fois" },
  'What does "statistical significance" mean in testing?': { prompt: 'Que signifie "significativité statistique" dans les tests?', options: ["Les résultats sont importants", "Les résultats sont peu probablement dus au hasard", "Vous avez assez de données", "Le test est terminé"], correctAnswer: "Les résultats sont peu probablement dus au hasard" },
  'You should stop an A/B test as soon as one version looks better.': { prompt: "Vous devriez arrêter un test A/B dès qu'une version semble meilleure.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A/B testing can be applied to emails, landing pages, ads, and more.': { prompt: "Le test A/B peut être appliqué aux emails, pages d'atterrissage, publicités et plus.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The winning variant should be the new default, and you should keep testing further.': { prompt: "La variante gagnante devrait devenir le nouveau standard, et vous devriez continuer à tester.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A ___ test compares multiple variables simultaneously, unlike a simple A/B test.': { prompt: "Un test ___ compare plusieurs variables simultanément, contrairement à un simple test A/B.", options: ["split", "multivarié", "séquentiel", "bêta"], correctAnswer: "multivarié" },

  // Funnels
  'What is a marketing funnel?': { prompt: "Qu'est-ce qu'un entonnoir marketing?", options: ["Un outil de cuisine", "Un modèle montrant le parcours client de la découverte à l'achat", "Un type de publicité", "Une fonctionnalité de réseau social"], correctAnswer: "Un modèle montrant le parcours client de la découverte à l'achat" },
  'What is the top of the funnel (TOFU)?': { prompt: "Qu'est-ce que le haut de l'entonnoir (TOFU)?", options: ["L'étape d'achat", "L'étape de découverte où les gens découvrent votre marque pour la première fois", "L'étape de fidélité", "La page de paiement"], correctAnswer: "L'étape de découverte où les gens découvrent votre marque pour la première fois" },
  'What is a "tripwire" offer in a funnel?': { prompt: 'Qu\'est-ce qu\'une offre "tripwire" dans un entonnoir?', options: ["Un piège pour les concurrents", "Une offre à bas prix qui convertit les prospects en clients payants", "Un essai gratuit", "Une séquence email"], correctAnswer: "Une offre à bas prix qui convertit les prospects en clients payants" },
  'What is MOFU (Middle of Funnel)?': { prompt: "Qu'est-ce que le MOFU (Milieu de l'Entonnoir)?", options: ["L'étape où vous construisez la confiance et nourrissez la considération", "La première impression publicitaire", "L'achat final", "L'étape de remboursement"], correctAnswer: "L'étape où vous construisez la confiance et nourrissez la considération" },
  'Every person who enters the top of the funnel will reach the bottom.': { prompt: "Chaque personne qui entre en haut de l'entonnoir atteindra le bas.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'An upsell offers a complementary or premium product after the initial purchase.': { prompt: "Un upsell offre un produit complémentaire ou premium après l'achat initial.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Retaining existing customers is typically cheaper than acquiring new ones.': { prompt: "Retenir les clients existants est généralement moins cher que d'en acquérir de nouveaux.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The ___ of the funnel (BOFU) is where leads are ready to make a purchase decision.': { prompt: "Le ___ de l'entonnoir (BOFU) est là où les prospects sont prêts à prendre une décision d'achat.", options: ["haut", "milieu", "bas", "côté"], correctAnswer: "bas" },

  // Landing Pages
  'What is a landing page?': { prompt: "Qu'est-ce qu'une page d'atterrissage?", options: ["La page d'accueil de votre site", "Une page autonome conçue pour un objectif de conversion spécifique", "Une page d'erreur 404", "Un article de blog"], correctAnswer: "Une page autonome conçue pour un objectif de conversion spécifique" },
  'Why should a landing page have minimal navigation?': { prompt: "Pourquoi une page d'atterrissage devrait-elle avoir une navigation minimale?", options: ["Pour gagner du temps de design", "Pour garder les visiteurs concentrés sur l'action souhaitée unique", "La navigation est dépassée", "Pour réduire la vitesse de chargement"], correctAnswer: "Pour garder les visiteurs concentrés sur l'action souhaitée unique" },
  'What is the most critical element of a landing page?': { prompt: "Quel est l'élément le plus critique d'une page d'atterrissage?", options: ["Le pied de page", "Un titre clair et un CTA fort", "Les icônes de réseaux sociaux", "Une longue section FAQ"], correctAnswer: "Un titre clair et un CTA fort" },
  'What is "above the fold"?': { prompt: 'Qu\'est-ce que "above the fold" (au-dessus de la ligne de flottaison)?', options: ["Un terme de journal sans pertinence web", "Le contenu visible sans défiler", "Du contenu caché", "Une technique de design"], correctAnswer: "Le contenu visible sans défiler" },
  'Social proof (testimonials, logos, reviews) on landing pages increases conversions.': { prompt: "La preuve sociale (témoignages, logos, avis) sur les pages d'atterrissage augmente les conversions.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A landing page should have multiple different CTAs asking for different actions.': { prompt: "Une page d'atterrissage devrait avoir plusieurs CTA différents demandant des actions différentes.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Page loading speed affects landing page conversion rates.': { prompt: "La vitesse de chargement affecte les taux de conversion des pages d'atterrissage.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A ___ page is shown after a user completes a conversion action, confirming success.': { prompt: "Une page de ___ est affichée après qu'un utilisateur complète une action de conversion, confirmant le succès.", options: ["atterrissage", "remerciement", "accueil", "démarrage"], correctAnswer: "remerciement" },

  // Influencer Mkt
  'What is influencer marketing?': { prompt: "Qu'est-ce que le marketing d'influence?", options: ["Du marketing par des célébrités uniquement", "S'associer avec des personnes qui ont une influence sur leur audience pour promouvoir votre marque", "De l'auto-promotion sur les réseaux sociaux", "Un type de SEO"], correctAnswer: "S'associer avec des personnes qui ont une influence sur leur audience pour promouvoir votre marque" },
  'What is a micro-influencer?': { prompt: "Qu'est-ce qu'un micro-influenceur?", options: ["Un influenceur avec 1M+ d'abonnés", "Un influenceur avec environ 10K-100K abonnés", "Un employé de marque", "Un influenceur de moins de 18 ans"], correctAnswer: "Un influenceur avec environ 10K-100K abonnés" },
  'Which metric is most important when evaluating an influencer?': { prompt: "Quelle métrique est la plus importante lors de l'évaluation d'un influenceur?", options: ["Le nombre d'abonnés", "Le taux d'engagement", "Le nombre de publications", "L'âge du compte"], correctAnswer: "Le taux d'engagement" },
  'What is an affiliate partnership with an influencer?': { prompt: "Qu'est-ce qu'un partenariat d'affiliation avec un influenceur?", options: ["L'embaucher à temps plein", "Le payer une commission pour chaque vente qu'il génère", "Lui donner des produits gratuits uniquement", "Demander des mentions gratuites"], correctAnswer: "Le payer une commission pour chaque vente qu'il génère" },
  'Nano-influencers (1K-10K followers) can be highly effective for niche brands.': { prompt: "Les nano-influenceurs (1K-10K abonnés) peuvent être très efficaces pour les marques de niche.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Influencer partnerships must be disclosed as sponsored content by law.': { prompt: "Les partenariats avec des influenceurs doivent être divulgués comme contenu sponsorisé par la loi.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The biggest influencer is always the best choice for any brand.': { prompt: "Le plus gros influenceur est toujours le meilleur choix pour toute marque.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A ___ is a unique discount code given to an influencer to track sales they generate.': { prompt: "Un ___ est un code de réduction unique donné à un influenceur pour suivre les ventes qu'il génère.", options: ["code coupon", "code promo", "pixel de suivi", "lien de parrainage"], correctAnswer: "code promo" },

  // PR & Media
  'What does PR stand for?': { prompt: "Que signifie PR?", options: ["Paid Results", "Public Relations", "Press Release", "Product Review"], correctAnswer: "Public Relations" },
  'What is a press release?': { prompt: "Qu'est-ce qu'un communiqué de presse?", options: ["Une publication sur les réseaux sociaux", "Une déclaration officielle distribuée aux médias sur des événements dignes d'intérêt", "Un avis client", "Une publicité payante"], correctAnswer: "Une déclaration officielle distribuée aux médias sur des événements dignes d'intérêt" },
  'What is earned media?': { prompt: "Qu'est-ce que les médias gagnés (earned media)?", options: ["Des médias que vous payez", "De la couverture médiatique obtenue par les efforts RP, pas par un placement payant", "Vos propres réseaux sociaux", "Du contenu sponsorisé"], correctAnswer: "De la couverture médiatique obtenue par les efforts RP, pas par un placement payant" },
  'What is a media kit?': { prompt: "Qu'est-ce qu'un kit média?", options: ["Un sac photo", "Un ensemble de matériels sur votre marque préparé pour les journalistes", "Un outil de réseau social", "Une suite de montage vidéo"], correctAnswer: "Un ensemble de matériels sur votre marque préparé pour les journalistes" },
  'Earned media is generally more trusted by consumers than paid advertising.': { prompt: "Les médias gagnés sont généralement plus fiables aux yeux des consommateurs que la publicité payante.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Crisis communication is an important part of public relations.': { prompt: "La communication de crise est une partie importante des relations publiques.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'PR is only useful for large corporations.': { prompt: "Les RP ne sont utiles que pour les grandes entreprises.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A ___ pitch is a concise email sent to journalists proposing a story idea about your brand.': { prompt: "Un pitch ___ est un email concis envoyé aux journalistes proposant une idée d'article sur votre marque.", options: ["de vente", "média", "de marque", "de contenu"], correctAnswer: "média" },

  // Growth Hacking
  'What is growth hacking?': { prompt: "Qu'est-ce que le growth hacking?", options: ["Pirater les sites des concurrents", "Utiliser des stratégies créatives et peu coûteuses pour faire croître rapidement une entreprise", "Un type de virus informatique", "Acheter des abonnés"], correctAnswer: "Utiliser des stratégies créatives et peu coûteuses pour faire croître rapidement une entreprise" },
  'What is a viral loop?': { prompt: "Qu'est-ce qu'une boucle virale?", options: ["Un virus informatique", "Un mécanisme où les utilisateurs invitent naturellement d'autres, créant une croissance exponentielle", "Un formulaire de feedback", "Un budget marketing"], correctAnswer: "Un mécanisme où les utilisateurs invitent naturellement d'autres, créant une croissance exponentielle" },
  'What is product-market fit?': { prompt: "Qu'est-ce que l'adéquation produit-marché?", options: ["Concevoir un produit pour rentrer dans une boîte", "Quand votre produit satisfait une forte demande du marché", "Avoir un gros budget marketing", "Copier le produit d'un concurrent"], correctAnswer: "Quand votre produit satisfait une forte demande du marché" },
  'What is the AARRR framework (Pirate Metrics)?': { prompt: "Qu'est-ce que le cadre AARRR (Métriques Pirate)?", options: ["Un jeu de pirate", "Acquisition, Activation, Rétention, Recommandation, Revenu", "Une stratégie de réseau social", "Un outil de budgétisation"], correctAnswer: "Acquisition, Activation, Rétention, Recommandation, Revenu" },
  'Dropbox used a referral program offering extra storage as a famous growth hack.': { prompt: "Dropbox a utilisé un programme de parrainage offrant du stockage supplémentaire comme growth hack célèbre.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Growth hacking only works for tech startups.': { prompt: "Le growth hacking ne fonctionne que pour les startups tech.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'A/B testing is a core practice in growth hacking.': { prompt: "Le test A/B est une pratique fondamentale du growth hacking.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'The ___ coefficient measures how many new users each existing user brings in through referrals.': { prompt: "Le coefficient ___ mesure combien de nouveaux utilisateurs chaque utilisateur existant amène par parrainage.", options: ["de croissance", "viral", "de conversion", "de rétention"], correctAnswer: "viral" },

  // Automation
  'What is marketing automation?': { prompt: "Qu'est-ce que l'automatisation marketing?", options: ["Embaucher plus de marketeurs", "Utiliser des logiciels pour automatiser les tâches marketing répétitives", "Automatiser la fabrication de produits", "Publier manuellement sur les réseaux sociaux"], correctAnswer: "Utiliser des logiciels pour automatiser les tâches marketing répétitives" },
  'Which of these is a marketing automation platform?': { prompt: "Lequel est une plateforme d'automatisation marketing?", options: ["Photoshop", "HubSpot", "GitHub", "Figma"], correctAnswer: "HubSpot" },
  'What is lead scoring?': { prompt: "Qu'est-ce que le scoring de leads?", options: ["Noter le design de votre site", "Attribuer des points aux leads selon leur comportement et probabilité de conversion", "Compter le total des leads", "Noter votre visuel publicitaire"], correctAnswer: "Attribuer des points aux leads selon leur comportement et probabilité de conversion" },
  'What is a workflow in marketing automation?': { prompt: "Qu'est-ce qu'un workflow en automatisation marketing?", options: ["Une liste de tâches", "Une série d'actions automatisées déclenchées par des conditions spécifiques", "Une réunion d'équipe", "Un calendrier de contenu"], correctAnswer: "Une série d'actions automatisées déclenchées par des conditions spécifiques" },
  'Automation means you never need to check or optimize your campaigns.': { prompt: "L'automatisation signifie que vous n'avez jamais besoin de vérifier ou optimiser vos campagnes.", options: ["Vrai", "Faux"], correctAnswer: "Faux" },
  'Chatbots are a form of marketing automation.': { prompt: "Les chatbots sont une forme d'automatisation marketing.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Zapier connects different apps to automate workflows without coding.': { prompt: "Zapier connecte différentes applications pour automatiser les workflows sans coder.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A ___ is a predefined set of actions that runs when triggered by a user action or time-based event.': { prompt: "Un ___ est un ensemble d'actions prédéfinies qui s'exécute quand il est déclenché par une action utilisateur ou un événement temporel.", options: ["template", "déclencheur", "workflow d'automatisation", "campagne"], correctAnswer: "workflow d'automatisation" },

  // Campaign Launch
  'What is the first step in launching a marketing campaign?': { prompt: "Quelle est la première étape pour lancer une campagne marketing?", options: ["Acheter des publicités", "Définir des objectifs clairs et des KPI", "Publier sur les réseaux sociaux", "Engager une agence"], correctAnswer: "Définir des objectifs clairs et des KPI" },
  'What does a campaign brief include?': { prompt: "Que comprend un brief de campagne?", options: ["Seulement le budget", "Objectifs, public cible, message, canaux, calendrier et budget", "Juste le visuel publicitaire", "Les mots de passe des réseaux sociaux"], correctAnswer: "Objectifs, public cible, message, canaux, calendrier et budget" },
  'What is an omnichannel marketing strategy?': { prompt: "Qu'est-ce qu'une stratégie marketing omnicanale?", options: ["Utiliser un seul canal", "Offrir une expérience fluide à travers tous les canaux marketing", "Utiliser uniquement des canaux organiques", "Éviter les canaux numériques"], correctAnswer: "Offrir une expérience fluide à travers tous les canaux marketing" },
  'When should you analyze campaign results?': { prompt: "Quand devriez-vous analyser les résultats de campagne?", options: ["Jamais", "Seulement à la fin", "Continuellement pendant et après la campagne", "Avant le lancement"], correctAnswer: "Continuellement pendant et après la campagne" },
  'What is a post-mortem in marketing?': { prompt: "Qu'est-ce qu'un post-mortem en marketing?", options: ["Une campagne d'horreur", "Une analyse après campagne examinant ce qui a fonctionné et ce qui n'a pas fonctionné", "Une publication sur les réseaux sociaux", "Un type d'email"], correctAnswer: "Une analyse après campagne examinant ce qui a fonctionné et ce qui n'a pas fonctionné" },
  'Setting a realistic budget is essential before launching any campaign.': { prompt: "Définir un budget réaliste est essentiel avant de lancer toute campagne.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'A soft launch means releasing to a small audience before the full launch.': { prompt: "Un lancement progressif signifie publier pour un petit public avant le lancement complet.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'SMART goals are Specific, Measurable, Achievable, Relevant, and Time-___.': { prompt: "Les objectifs SMART sont Spécifiques, Mesurables, Atteignables, Pertinents et Limités dans le ___.", options: ["test", "suivi", "temps", "base"], correctAnswer: "temps" },

  // CMO Level
  'What does CMO stand for?': { prompt: "Que signifie CMO?", options: ["Chief Marketing Officer", "Content Marketing Operations", "Customer Management Office", "Creative Media Organizer"], correctAnswer: "Chief Marketing Officer" },
  'What is Customer Lifetime Value (CLV)?': { prompt: "Qu'est-ce que la Valeur Vie Client (CLV)?", options: ["La durée de vie d'un client", "Le revenu total qu'une entreprise peut attendre d'un seul client au fil du temps", "Le coût d'acquisition d'un client", "Un score de fidélité client"], correctAnswer: "Le revenu total qu'une entreprise peut attendre d'un seul client au fil du temps" },
  'What is CAC (Customer Acquisition Cost)?': { prompt: "Qu'est-ce que le CAC (Coût d'Acquisition Client)?", options: ["Creative Ad Content", "Le coût total pour acquérir un nouveau client", "Customer Appreciation Certificate", "Content Analysis Chart"], correctAnswer: "Le coût total pour acquérir un nouveau client" },
  'What is brand attribution in marketing?': { prompt: "Qu'est-ce que l'attribution de marque en marketing?", options: ["Donner du crédit aux designers", "Identifier quels points de contact marketing génèrent des conversions", "Attribuer une citation à quelqu'un", "Le copyright de marque"], correctAnswer: "Identifier quels points de contact marketing génèrent des conversions" },
  'What is the ideal CLV:CAC ratio?': { prompt: "Quel est le ratio CLV:CAC idéal?", options: ["1:1", "3:1 ou plus", "1:3", "10:1 minimum"], correctAnswer: "3:1 ou plus" },
  'A data-driven marketing approach outperforms gut-feeling decisions in most cases.': { prompt: "Une approche marketing basée sur les données surpasse les décisions instinctives dans la plupart des cas.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Diversifying marketing channels reduces risk compared to relying on one platform.': { prompt: "Diversifier les canaux marketing réduit les risques par rapport à la dépendance à une seule plateforme.", options: ["Vrai", "Faux"], correctAnswer: "Vrai" },
  'Market ___ is the percentage of total sales in a market captured by a company.': { prompt: "La ___ de marché est le pourcentage des ventes totales d'un marché capturé par une entreprise.", options: ["capitalisation", "part", "valeur", "portée"], correctAnswer: "part" },
};

export default marketingFr;
