export const marketingAgencyEs: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // What Is an Agency
  'What is a marketing agency?': { prompt: '¿Qué es una agencia de marketing?', options: ['Una empresa que vende productos físicos', 'Un negocio que provee servicios de marketing a otras empresas', 'Un organismo regulador gubernamental', 'Una plataforma de redes sociales'], correctAnswer: 'Un negocio que provee servicios de marketing a otras empresas' },
  'A marketing agency can only serve one industry at a time.': { prompt: 'Una agencia de marketing solo puede atender una industria a la vez.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What is the main revenue model for most marketing agencies?': { prompt: '¿Cuál es el modelo de ingresos principal para la mayoría de las agencias de marketing?', options: ['Vender espacios publicitarios directamente', 'Cobrar a los clientes retainers mensuales o tarifas por proyecto por servicios', 'Ganar comisiones de plataformas de redes sociales', 'Subvenciones gubernamentales'], correctAnswer: 'Cobrar a los clientes retainers mensuales o tarifas por proyecto por servicios' },
  "A ___ agency focuses on managing all aspects of a client's marketing strategy.": { prompt: 'Una agencia de ___ se enfoca en gestionar todos los aspectos de la estrategia de marketing de un cliente.', options: ['Servicio completo', 'Freelance', 'Interna', 'Nicho'], correctAnswer: 'Servicio completo' },
  'You need a degree in marketing to start a marketing agency.': { prompt: 'Necesitas un título en marketing para iniciar una agencia de marketing.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Which is NOT a common agency business model?': { prompt: '¿Cuál NO es un modelo de negocio de agencia común?', options: ['Retainer mensual', 'Precios por proyecto', 'Tarifas basadas en rendimiento', 'Cobrar por número de empleados a los clientes'], correctAnswer: 'Cobrar por número de empleados a los clientes' },
  'Most successful agencies start as a one-person operation before scaling.': { prompt: 'La mayoría de agencias exitosas empiezan como una operación de una persona antes de escalar.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  "What does \"white-label\" mean in the agency world?": { prompt: '¿Qué significa "white-label" en el mundo de las agencias?', options: ['Usar fondos blancos en sitios web', 'Revender servicios de otra empresa bajo tu propia marca', 'Solo trabajar con marcas de lujo', 'Un tipo de certificación gubernamental'], correctAnswer: 'Revender servicios de otra empresa bajo tu propia marca' },
  'The typical agency profit margin for a well-run agency is ___%.': { prompt: 'El margen de ganancia típico para una agencia bien administrada es ___%.', options: ['5-10%', '15-25%', '50-60%', '80-90%'], correctAnswer: '15-25%' },
  'A boutique agency typically serves fewer clients but offers more personalized service.': { prompt: 'Una agencia boutique típicamente atiende menos clientes pero ofrece un servicio más personalizado.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'SITUATION: You want to start an agency but have no clients or case studies. What is the best first step?': { prompt: 'SITUACIÓN: Quieres iniciar una agencia pero no tienes clientes ni casos de estudio. ¿Cuál es el mejor primer paso?', options: ['Alquilar una oficina elegante para verse profesional', 'Ofrecer trabajo gratis o con descuento a 2-3 negocios para construir casos de estudio y testimonios', 'Esperar hasta tener 5 años de experiencia', 'Comprar una franquicia de agencia'], correctAnswer: 'Ofrecer trabajo gratis o con descuento a 2-3 negocios para construir casos de estudio y testimonios' },
  "SITUATION: A friend asks what makes agencies fail. Which is the #1 reason most new agencies shut down?": { prompt: 'SITUACIÓN: Un amigo pregunta qué hace que las agencias fracasen. ¿Cuál es la razón #1 por la que cierran las agencias nuevas?', options: ['Mal diseño de logo', 'Incapacidad para adquirir clientes nuevos consistentemente', 'Usar las herramientas de software equivocadas', 'No tener un sitio web'], correctAnswer: 'Incapacidad para adquirir clientes nuevos consistentemente' },
  "An agency's ___ is the total value a client brings over the entire relationship.": { prompt: 'El ___ de una agencia es el valor total que un cliente aporta durante toda la relación.', options: ['AOV', 'LTV', 'CPC', 'CPM'], correctAnswer: 'LTV' },
  'An agency needs at least 10 employees before it can be considered a real agency.': { prompt: 'Una agencia necesita al menos 10 empleados antes de ser considerada una agencia real.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What is "scope creep" in agency work?': { prompt: '¿Qué es el "scope creep" en el trabajo de agencia?', options: ['Hacer crecer tu equipo muy rápido', 'Cuando un proyecto gradualmente se expande más allá de su alcance original sin compensación adicional', 'Un tipo de estrategia de marketing', 'Contratar de la competencia'], correctAnswer: 'Cuando un proyecto gradualmente se expande más allá de su alcance original sin compensación adicional' },

  // Choosing Your Niche
  'Why is niching down important for a new agency?': { prompt: '¿Por qué es importante especializarse para una agencia nueva?', options: ['Limita tu potencial de ingresos', 'Te convierte en especialista, construye autoridad más rápido y facilita el marketing', 'Es requerido por ley', 'No tiene beneficio real'], correctAnswer: 'Te convierte en especialista, construye autoridad más rápido y facilita el marketing' },
  'SMMA stands for Social Media Marketing Agency.': { prompt: 'SMMA significa Social Media Marketing Agency.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Which niche typically has the highest client lifetime value?': { prompt: '¿Qué nicho típicamente tiene el mayor valor de vida del cliente?', options: ['Restaurantes locales', 'Agentes inmobiliarios', 'Empresas SaaS', 'Food trucks'], correctAnswer: 'Empresas SaaS' },
  "A ___ agency specializes in improving a client's organic search rankings on Google.": { prompt: 'Una agencia de ___ se especializa en mejorar las posiciones de búsqueda orgánica de un cliente en Google.', options: ['PPC', 'SEO', 'PR', 'UX'], correctAnswer: 'SEO' },
  'You should pick a niche based solely on what pays the most, regardless of your interest.': { prompt: 'Deberías elegir un nicho basándote únicamente en lo que paga más, sin importar tu interés.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What makes a good agency niche?': { prompt: '¿Qué hace un buen nicho de agencia?', options: ['Negocios con dinero, necesidad recurrente de marketing y ROI medible', 'Negocios difíciles de encontrar en línea', 'Industrias sin competencia alguna', 'Solo organizaciones sin fines de lucro'], correctAnswer: 'Negocios con dinero, necesidad recurrente de marketing y ROI medible' },
  'A paid ads agency manages platforms like Facebook Ads and Google Ads for clients.': { prompt: 'Una agencia de anuncios pagados gestiona plataformas como Facebook Ads y Google Ads para clientes.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Which is the best way to validate a niche before committing?': { prompt: '¿Cuál es la mejor manera de validar un nicho antes de comprometerse?', options: ['Leer un blog post al respecto', 'Hablar con 10-20 dueños de negocios en ese nicho y preguntar sobre sus problemas', 'Elegir basándose en una tendencia de TikTok', 'Elegir lo que tu amigo está haciendo'], correctAnswer: 'Hablar con 10-20 dueños de negocios en ese nicho y preguntar sobre sus problemas' },
  'A content agency typically creates ___, blog posts, and social media content for clients.': { prompt: 'Una agencia de contenido típicamente crea ___, blog posts y contenido de redes sociales para clientes.', options: ['Facturas', 'Videos', 'Documentos legales', 'Software'], correctAnswer: 'Videos' },
  'A web design agency can only build websites and cannot offer ongoing maintenance.': { prompt: 'Una agencia de diseño web solo puede construir sitios web y no puede ofrecer mantenimiento continuo.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Which industry is known for high agency retainers ($3K-10K/month)?': { prompt: '¿Qué industria es conocida por retainers altos de agencia ($3K-10K/mes)?', options: ['Panaderías locales', 'Consultorios dentales y clínicas médicas', 'Puestos de limonada', 'Servicios de cuidado de mascotas'], correctAnswer: 'Consultorios dentales y clínicas médicas' },
  'You can run a successful agency serving any niche as long as you deliver results.': { prompt: 'Puedes tener una agencia exitosa sirviendo cualquier nicho mientras entregues resultados.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'An SMMA typically manages social media ___, content creation, and community management for clients.': { prompt: 'Una SMMA típicamente gestiona ___ de redes sociales, creación de contenido y gestión de comunidad para clientes.', options: ['Servidores', 'Publicidad', 'Almacenes', 'Inventario'], correctAnswer: 'Publicidad' },

  // Cold Email Scripts
  'What is the ideal length for a cold email to a potential client?': { prompt: '¿Cuál es la longitud ideal para un email en frío a un cliente potencial?', options: ['500+ palabras con casos de estudio completos', '75-125 palabras — corto, personalizado y con un CTA claro', '10 palabras o menos', 'Un adjunto PDF de 3 páginas'], correctAnswer: '75-125 palabras — corto, personalizado y con un CTA claro' },
  'You should include your full pricing in the first cold email.': { prompt: 'Deberías incluir todos tus precios en el primer email en frío.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What is the most important element of a cold email?': { prompt: '¿Cuál es el elemento más importante de un email en frío?', options: ['El logo de tu empresa', 'El asunto — determina si el email se abre', 'La firma del email', 'La fuente que uses'], correctAnswer: 'El asunto — determina si el email se abre' },
  'A good cold email ___ line should create curiosity or reference something specific about the prospect.': { prompt: 'Una buena línea de ___ de email en frío debería crear curiosidad o hacer referencia a algo específico del prospecto.', options: ['Cierre', 'Asunto', 'Descargo', 'Pie de página'], correctAnswer: 'Asunto' },
  'Sending the same generic cold email to 1,000 people is more effective than sending 100 personalized emails.': { prompt: 'Enviar el mismo email genérico en frío a 1,000 personas es más efectivo que enviar 100 emails personalizados.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What is a "CTA" in a cold email?': { prompt: '¿Qué es un "CTA" en un email en frío?', options: ['Click-Through Analytics', 'Call To Action — lo que quieres que el lector haga después', 'Client Trust Agreement', 'Cost To Acquire'], correctAnswer: 'Call To Action — lo que quieres que el lector haga después' },
  'Following up after a cold email that got no reply is considered rude and should be avoided.': { prompt: 'Hacer seguimiento después de un email en frío sin respuesta se considera grosero y debe evitarse.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  "How many follow-up emails should you typically send after the initial cold email?": { prompt: '¿Cuántos emails de seguimiento deberías enviar típicamente después del email en frío inicial?', options: ['0 — si no respondieron, no están interesados', '2-4 seguimientos espaciados 3-5 días', '10+ seguimientos diarios hasta que respondan', '1 seguimiento después de 30 días'], correctAnswer: '2-4 seguimientos espaciados 3-5 días' },
  'Email ___ is the percentage of recipients who opened your email.': { prompt: 'La tasa de ___ de email es el porcentaje de destinatarios que abrieron tu email.', options: ['Rebote', 'Apertura', 'Clic', 'Spam'], correctAnswer: 'Apertura' },
  'A 20-30% open rate on cold emails is considered good.': { prompt: 'Una tasa de apertura del 20-30% en emails en frío se considera buena.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What is "email warm-up" and why is it important?': { prompt: '¿Qué es el "calentamiento de email" y por qué es importante?', options: ['Calentar tu computadora antes de enviar emails', 'Aumentar gradualmente el volumen de emails desde un nuevo dominio para construir reputación de remitente', 'Enviar saludos cálidos en cada email', 'Un tipo de plantilla de email'], correctAnswer: 'Aumentar gradualmente el volumen de emails desde un nuevo dominio para construir reputación de remitente' },
  'Which personalization technique is most effective in cold emails?': { prompt: '¿Qué técnica de personalización es más efectiva en emails en frío?', options: ['Usar solo su nombre', 'Hacer referencia a algo específico de su negocio, como una publicación reciente o un problema en su sitio web', 'Usar plantillas HTML elegantes', 'Agregar emojis al asunto'], correctAnswer: 'Hacer referencia a algo específico de su negocio, como una publicación reciente o un problema en su sitio web' },
  'Using tools like Instantly, Smartlead, or Lemlist can help automate cold email sequences.': { prompt: 'Usar herramientas como Instantly, Smartlead o Lemlist puede ayudar a automatizar secuencias de email en frío.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  "The ___ rate measures how many cold emails actually reached the recipient's inbox.": { prompt: 'La tasa de ___ mide cuántos emails en frío realmente llegaron a la bandeja de entrada del destinatario.', options: ['Rebote', 'Entregabilidad', 'Conversión', 'Interacción'], correctAnswer: 'Entregabilidad' },

  // Cold Calling Basics
  'What is the purpose of a cold call for an agency?': { prompt: '¿Cuál es el propósito de una llamada en frío para una agencia?', options: ['Vender tu paquete completo de servicios inmediatamente', 'Iniciar una conversación y agendar una reunión de descubrimiento', 'Leer todo tu sitio web al prospecto', 'Solo pedir una referencia'], correctAnswer: 'Iniciar una conversación y agendar una reunión de descubrimiento' },
  'Cold calling is dead and no longer works for agency client acquisition.': { prompt: 'Las llamadas en frío están muertas y ya no funcionan para la adquisición de clientes de agencia.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What is the best opening line structure for a cold call?': { prompt: '¿Cuál es la mejor estructura de línea de apertura para una llamada en frío?', options: ['Hola, déjame contarte sobre nuestros increíbles servicios', 'Di tu nombre, empresa, razón de la llamada y haz una pregunta basada en permiso', 'Oye, ¿eres el dueño? Genial, escucha...', 'Empieza con un chiste para romper el hielo'], correctAnswer: 'Di tu nombre, empresa, razón de la llamada y haz una pregunta basada en permiso' },
  'You should aim to make 20-50 cold calls per day when actively prospecting.': { prompt: 'Deberías apuntar a hacer 20-50 llamadas en frío por día cuando estás prospectando activamente.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'The best time to cold call business owners is typically Tuesday-Thursday between 10 AM and 12 PM.': { prompt: 'El mejor momento para llamar en frío a dueños de negocios es típicamente de martes a jueves entre 10 AM y 12 PM.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'What is "objection handling" in cold calling?': { prompt: '¿Qué es el "manejo de objeciones" en llamadas en frío?', options: ['Evitar todas las objeciones hablando rápido', 'Tener respuestas preparadas para razones comunes por las que los prospectos no están interesados', 'Objetar el modelo de negocio del prospecto', 'Transferir la llamada cuando escuchas una objeción'], correctAnswer: 'Tener respuestas preparadas para razones comunes por las que los prospectos no están interesados' },
  'Recording your cold calls (where legal) and reviewing them is a great way to improve.': { prompt: 'Grabar tus llamadas en frío (donde sea legal) y revisarlas es una gran manera de mejorar.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Using a CRM to track cold call outcomes helps you improve your process over time.': { prompt: 'Usar un CRM para rastrear los resultados de llamadas en frío te ayuda a mejorar tu proceso con el tiempo.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Service Packaging
  'What is "service packaging" for an agency?': { prompt: '¿Qué es el "empaquetado de servicios" para una agencia?', options: ['Envolver productos físicos', 'Agrupar tus servicios en ofertas claras y definidas con entregables y precios específicos', 'Solo ofrecer un servicio', 'Copiar los servicios de otra agencia'], correctAnswer: 'Agrupar tus servicios en ofertas claras y definidas con entregables y precios específicos' },
  'Offering 3 pricing tiers (Basic, Pro, Premium) is a common agency packaging strategy.': { prompt: 'Ofrecer 3 niveles de precio (Básico, Pro, Premium) es una estrategia común de empaquetado de agencia.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You should always include a clear list of deliverables in every service package.': { prompt: 'Siempre deberías incluir una lista clara de entregables en cada paquete de servicio.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Bundling SEO + content creation + social media into one package increases perceived value.': { prompt: 'Agrupar SEO + creación de contenido + redes sociales en un paquete aumenta el valor percibido.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Including revision limits in your packages helps prevent scope creep.': { prompt: 'Incluir límites de revisiones en tus paquetes ayuda a prevenir el scope creep.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Higher-priced packages should include priority support and faster turnaround times.': { prompt: 'Los paquetes de precio más alto deberían incluir soporte prioritario y tiempos de entrega más rápidos.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Retainer vs Project
  'What is a retainer pricing model?': { prompt: '¿Qué es un modelo de precios de retainer?', options: ['Una tarifa única por proyecto', 'Una tarifa mensual recurrente por servicios continuos', 'Un modelo basado en comisiones', 'Precios de pago por clic'], correctAnswer: 'Una tarifa mensual recurrente por servicios continuos' },
  'Retainer clients provide more predictable revenue than project-based clients.': { prompt: 'Los clientes de retainer proporcionan ingresos más predecibles que los clientes por proyecto.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Value-based pricing charges based on the ___ your service delivers, not the hours worked.': { prompt: 'La fijación de precios basada en valor cobra según el ___ que tu servicio entrega, no las horas trabajadas.', options: ['Costo', 'Valor', 'Dificultad', 'Velocidad'], correctAnswer: 'Valor' },
  'A $2,000/month retainer with 12-month average retention is worth $24,000 in lifetime value.': { prompt: 'Un retainer de $2,000/mes con retención promedio de 12 meses vale $24,000 en valor de vida.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Charging per hour incentivizes working slower, which is bad for both agency and client.': { prompt: 'Cobrar por hora incentiva trabajar más lento, lo cual es malo tanto para la agencia como para el cliente.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'A minimum contract length of ___ months is common for agency retainers to ensure enough time to show results.': { prompt: 'Una duración mínima de contrato de ___ meses es común para retainers de agencia para asegurar tiempo suficiente para mostrar resultados.', options: ['1', '3', '12', '24'], correctAnswer: '3' },
  'You should raise your prices every year as you gain more experience and case studies.': { prompt: 'Deberías subir tus precios cada año a medida que ganas más experiencia y casos de estudio.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Performance-based pricing (taking a % of revenue generated) can work well for agencies that are confident in their results.': { prompt: 'Los precios basados en rendimiento (tomar un % de los ingresos generados) pueden funcionar bien para agencias que confían en sus resultados.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Proposals & SOW
  'What does SOW stand for in agency work?': { prompt: '¿Qué significa SOW en el trabajo de agencia?', options: ['Statement of Work', 'Standard Operating Widget', 'Service Order Worksheet', 'Sales Opportunity Window'], correctAnswer: 'Statement of Work' },
  'A proposal should always include a clear timeline for deliverables.': { prompt: 'Una propuesta siempre debería incluir un cronograma claro para los entregables.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You should send a proposal before having a discovery call with the prospect.': { prompt: 'Deberías enviar una propuesta antes de tener una llamada de descubrimiento con el prospecto.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Using proposal software like PandaDoc or Proposify makes your agency look more professional.': { prompt: 'Usar software de propuestas como PandaDoc o Proposify hace que tu agencia se vea más profesional.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Including case studies and testimonials in your proposal increases close rates.': { prompt: 'Incluir casos de estudio y testimonios en tu propuesta aumenta las tasas de cierre.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'A well-structured proposal can double your close rate compared to sending a simple price quote.': { prompt: 'Una propuesta bien estructurada puede duplicar tu tasa de cierre comparada con enviar una cotización simple.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Client Onboarding
  'What is client onboarding?': { prompt: '¿Qué es el onboarding de clientes?', options: ['Subir a un cliente a un barco', 'El proceso estructurado de dar la bienvenida a un nuevo cliente y configurar todo lo necesario para empezar a trabajar', 'Despedir a un mal cliente', 'La primera factura que envías'], correctAnswer: 'El proceso estructurado de dar la bienvenida a un nuevo cliente y configurar todo lo necesario para empezar a trabajar' },
  'A kickoff call should happen within the first week of signing a new client.': { prompt: 'Una llamada de inicio debería ocurrir dentro de la primera semana de firmar un nuevo cliente.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You should set clear expectations about response times during onboarding.': { prompt: 'Deberías establecer expectativas claras sobre tiempos de respuesta durante el onboarding.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Sending a welcome packet or onboarding guide makes clients feel more confident in their decision to hire you.': { prompt: 'Enviar un paquete de bienvenida o guía de onboarding hace que los clientes se sientan más confiados en su decisión de contratarte.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Using a project management tool like ClickUp or Asana helps keep onboarding organized.': { prompt: 'Usar una herramienta de gestión de proyectos como ClickUp o Asana ayuda a mantener el onboarding organizado.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Automating parts of your onboarding process saves time as you scale.': { prompt: 'Automatizar partes de tu proceso de onboarding ahorra tiempo al escalar.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Client Retention
  'Sending monthly performance reports helps retain agency clients.': { prompt: 'Enviar reportes de rendimiento mensuales ayuda a retener clientes de agencia.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Proactively suggesting new strategies and upsells shows clients you care about their growth.': { prompt: 'Sugerir proactivamente nuevas estrategias y upsells muestra a los clientes que te importa su crecimiento.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Over-communicating with clients is better than under-communicating.': { prompt: 'Sobre-comunicarse con los clientes es mejor que sub-comunicarse.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'If results are temporarily bad, hiding it from the client is better than being transparent.': { prompt: 'Si los resultados son temporalmente malos, ocultarlo al cliente es mejor que ser transparente.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Having a dedicated account manager for each client improves retention rates.': { prompt: 'Tener un gerente de cuenta dedicado para cada cliente mejora las tasas de retención.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Delivering FB Ads
  'You should always start Facebook Ads campaigns in the learning phase with at least $20-50/day per ad set.': { prompt: 'Siempre deberías iniciar campañas de Facebook Ads en la fase de aprendizaje con al menos $20-50/día por conjunto de anuncios.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Creative (images and videos) is the single biggest factor in Facebook Ads performance.': { prompt: 'El creativo (imágenes y videos) es el factor más importante en el rendimiento de Facebook Ads.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You should test at least 3-5 different ad creatives when launching a new campaign.': { prompt: 'Deberías probar al menos 3-5 creativos de anuncios diferentes al lanzar una nueva campaña.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Retargeting ads (showing ads to people who already visited the website) typically have higher ROAS than cold ads.': { prompt: 'Los anuncios de retargeting (mostrar anuncios a personas que ya visitaron el sitio web) típicamente tienen mayor ROAS que los anuncios en frío.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Delivering Google Ads
  'Google Ads Quality Score affects both your ad position and cost per click.': { prompt: 'El Quality Score de Google Ads afecta tanto la posición de tu anuncio como el costo por clic.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Long-tail keywords (3+ words) typically have lower competition and cost less per click.': { prompt: 'Las palabras clave long-tail (3+ palabras) típicamente tienen menos competencia y cuestan menos por clic.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You should always send Google Ads traffic to your homepage for best results.': { prompt: 'Siempre deberías enviar tráfico de Google Ads a tu página principal para mejores resultados.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Broad match keywords in Google Ads can show your ad for searches only loosely related to your keyword.': { prompt: 'Las palabras clave de concordancia amplia en Google Ads pueden mostrar tu anuncio para búsquedas solo vagamente relacionadas con tu palabra clave.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Google Ads remarketing lets you show ads to people who previously visited your client\'s website.': { prompt: 'El remarketing de Google Ads te permite mostrar anuncios a personas que previamente visitaron el sitio web de tu cliente.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Delivering SEO
  'SEO results typically take 3-6 months to show significant improvement.': { prompt: 'Los resultados de SEO típicamente toman 3-6 meses para mostrar una mejora significativa.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Keyword stuffing (overusing keywords) can get a website penalized by Google.': { prompt: 'El keyword stuffing (sobreuso de palabras clave) puede hacer que Google penalice un sitio web.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Google My Business optimization is a part of local SEO strategy.': { prompt: 'La optimización de Google My Business es parte de la estrategia de SEO local.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Site speed is a ranking factor for Google search results.': { prompt: 'La velocidad del sitio es un factor de posicionamiento para los resultados de búsqueda de Google.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Mobile-first indexing means Google primarily uses the mobile version of content for ranking.': { prompt: 'El indexado mobile-first significa que Google usa principalmente la versión móvil del contenido para el posicionamiento.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Hiring VAs
  'What does VA stand for in the agency context?': { prompt: '¿Qué significa VA en el contexto de agencia?', options: ['Virtual Application', 'Asistente Virtual — un trabajador remoto que maneja tareas específicas', 'Very Ambitious', 'Video Animation'], correctAnswer: 'Asistente Virtual — un trabajador remoto que maneja tareas específicas' },
  'Hiring VAs from countries like the Philippines can cost $4-8/hour for skilled work.': { prompt: 'Contratar VAs de países como Filipinas puede costar $4-8/hora por trabajo especializado.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You should create SOPs (Standard Operating Procedures) before hiring a VA.': { prompt: 'Deberías crear SOPs (Procedimientos Operativos Estándar) antes de contratar un VA.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'A contractor (freelancer) is different from an employee — contractors handle their own taxes and work independently.': { prompt: 'Un contratista (freelancer) es diferente de un empleado — los contratistas manejan sus propios impuestos y trabajan independientemente.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You should have clear KPIs (Key Performance Indicators) for every team member.': { prompt: 'Deberías tener KPIs (Indicadores Clave de Rendimiento) claros para cada miembro del equipo.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Using time-tracking tools like Toggl helps you understand how long tasks actually take.': { prompt: 'Usar herramientas de seguimiento de tiempo como Toggl te ayuda a entender cuánto tardan realmente las tareas.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // SOPs & Systems
  'What does SOP stand for?': { prompt: '¿Qué significa SOP?', options: ['Standard Operating Procedure', 'Sales Opportunity Pipeline', 'Service Optimization Plan', 'Strategic Outreach Program'], correctAnswer: 'Standard Operating Procedure' },
  'SOPs allow you to delegate tasks without being involved in every step.': { prompt: 'Los SOPs te permiten delegar tareas sin involucrarte en cada paso.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'An agency should have SOPs for every repeatable process, from onboarding to reporting.': { prompt: 'Una agencia debería tener SOPs para cada proceso repetible, desde el onboarding hasta los reportes.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Zapier and Make (formerly Integromat) can automate repetitive tasks between different software tools.': { prompt: 'Zapier y Make (anteriormente Integromat) pueden automatizar tareas repetitivas entre diferentes herramientas de software.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Templates for proposals, contracts, and reports save significant time as you take on more clients.': { prompt: 'Las plantillas para propuestas, contratos y reportes ahorran tiempo significativo al tomar más clientes.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'A project management system becomes essential once you have more than 3-5 active clients.': { prompt: 'Un sistema de gestión de proyectos se vuelve esencial una vez que tienes más de 3-5 clientes activos.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Financial Management
  'A healthy agency net profit margin is typically 15-25%.': { prompt: 'Un margen de ganancia neta saludable para una agencia es típicamente 15-25%.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You should separate personal and business finances from day one.': { prompt: 'Deberías separar las finanzas personales y de negocio desde el primer día.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Agencies should keep 3-6 months of operating expenses in reserve.': { prompt: 'Las agencias deberían mantener 3-6 meses de gastos operativos en reserva.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'QuickBooks, Xero, or FreshBooks are common accounting tools for agencies.': { prompt: 'QuickBooks, Xero o FreshBooks son herramientas de contabilidad comunes para agencias.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Tracking time spent per client helps you understand your true profitability per account.': { prompt: 'Rastrear el tiempo invertido por cliente te ayuda a entender tu verdadera rentabilidad por cuenta.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Zero to 10K/Month
  'Most agencies reach $10K/month with just 3-7 clients.': { prompt: 'La mayoría de agencias alcanzan $10K/mes con solo 3-7 clientes.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You need a perfect brand and website before you can start selling agency services.': { prompt: 'Necesitas una marca y sitio web perfectos antes de poder empezar a vender servicios de agencia.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Free or discounted initial projects are a valid strategy to build your first case studies.': { prompt: 'Los proyectos iniciales gratuitos o con descuento son una estrategia válida para construir tus primeros casos de estudio.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Consistency in outreach (doing it every day) matters more than perfecting one email.': { prompt: 'La consistencia en el alcance (hacerlo cada día) importa más que perfeccionar un email.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'The jump from $0 to $5K/month is harder than from $5K to $10K/month.': { prompt: 'El salto de $0 a $5K/mes es más difícil que de $5K a $10K/mes.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // 10K to 100K
  'To reach $100K/month, you need to transition from doing the work yourself to managing a team that does it.': { prompt: 'Para alcanzar $100K/mes, necesitas transicionar de hacer el trabajo tú mismo a gestionar un equipo que lo haga.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Adding new services is always the best way to increase revenue.': { prompt: 'Agregar nuevos servicios siempre es la mejor manera de aumentar los ingresos.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Revenue plateaus between $20K-$50K/month are common and usually require a systems overhaul to break through.': { prompt: 'Los estancamientos de ingresos entre $20K-$50K/mes son comunes y usualmente requieren una revisión de sistemas para superarlos.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Agencies that reach $100K/month typically have strong SOPs for every major process.': { prompt: 'Las agencias que alcanzan $100K/mes típicamente tienen SOPs fuertes para cada proceso importante.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Partnering with complementary agencies (e.g., a web design agency partnering with an SEO agency) can accelerate growth through referrals.': { prompt: 'Asociarse con agencias complementarias (ej. una agencia de diseño web asociándose con una agencia de SEO) puede acelerar el crecimiento a través de referidos.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },

  // Agency Automation
  'AI tools like ChatGPT can help agencies create first drafts of content, emails, and ad copy faster.': { prompt: 'Las herramientas de IA como ChatGPT pueden ayudar a las agencias a crear primeros borradores de contenido, emails y copy de anuncios más rápido.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Agencies can use Make (formerly Integromat) as an alternative to Zapier for workflow automation.': { prompt: 'Las agencias pueden usar Make (anteriormente Integromat) como alternativa a Zapier para automatización de workflows.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Automating lead follow-up within 5 minutes of inquiry can increase conversion rates by 400%.': { prompt: 'Automatizar el seguimiento de leads dentro de los 5 minutos de la consulta puede aumentar las tasas de conversión en un 400%.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You should automate everything in your agency before getting your first client.': { prompt: 'Deberías automatizar todo en tu agencia antes de conseguir tu primer cliente.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
};

export default marketingAgencyEs;
