export const meditationFr: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // Why Meditate?
  'What is a proven benefit of regular meditation?': { prompt: 'Quel est un bienfait prouvé de la méditation régulière?', options: ['Ne jamais se sentir triste', 'Perte de poids instantanée', 'Mémoire parfaite', 'Réduction du stress et de l\'anxiété'], correctAnswer: 'Réduction du stress et de l\'anxiété' },
  'Meditation has been shown to reduce cortisol (stress hormone) levels.': { prompt: 'Il a été démontré que la méditation réduit les niveaux de cortisol (hormone du stress).', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Meditation can improve ___ and concentration over time.': { prompt: 'La méditation peut améliorer la ___ et la concentration au fil du temps.', options: ['Concentration', 'Taille', 'Vitesse', 'Appétit'], correctAnswer: 'Concentration' },
  'Expecting meditation to solve all problems instantly.': { prompt: 'S\'attendre à ce que la méditation résolve tous les problèmes instantanément.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'How long does it take to notice meditation benefits?': { prompt: 'Combien de temps faut-il pour remarquer les bienfaits de la méditation?', options: ['Au moins 5 ans', 'Quelques semaines de pratique régulière', 'Jamais', 'Instantanément'], correctAnswer: 'Quelques semaines de pratique régulière' },
  'Meditation can help improve sleep quality.': { prompt: 'La méditation peut aider à améliorer la qualité du sommeil.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Posture
  'What is the ideal meditation posture?': { prompt: 'Quelle est la posture idéale de méditation?', options: ['Couché à plat', 'Debout sur une jambe', 'Droit, détendu, avec la colonne vertébrale droite', 'Affalé'], correctAnswer: 'Droit, détendu, avec la colonne vertébrale droite' },
  'You must sit in lotus position to meditate properly.': { prompt: 'Vous devez vous asseoir en position du lotus pour méditer correctement.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Sitting on a cushion can help tilt your ___ forward for better posture.': { prompt: 'S\'asseoir sur un coussin peut aider à incliner votre ___ vers l\'avant pour une meilleure posture.', options: ['Bassin', 'Tête', 'Genoux', 'Pieds'], correctAnswer: 'Bassin' },
  'Meditating in a chair if cross-legged sitting is uncomfortable.': { prompt: 'Méditer dans une chaise si s\'asseoir en tailleur est inconfortable.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Where should your hands rest during meditation?': { prompt: 'Où devraient reposer vos mains pendant la méditation?', options: ['Derrière votre dos', 'Confortablement sur vos genoux ou dans votre giron', 'Au-dessus de votre tête', 'En tenant un téléphone'], correctAnswer: 'Confortablement sur vos genoux ou dans votre giron' },
  'Your shoulders should be relaxed, not tense, during meditation.': { prompt: 'Vos épaules devraient être détendues, pas tendues, pendant la méditation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Breath Focus
  'What is breath-focused meditation?': { prompt: 'Qu\'est-ce que la méditation centrée sur la respiration?', options: ['Retenir son souffle', 'Respirer le plus vite possible', 'Arrêter de respirer', 'Porter attention au rythme naturel de la respiration'], correctAnswer: 'Porter attention au rythme naturel de la respiration' },
  'You need to control your breathing during breath meditation.': { prompt: 'Vous devez contrôler votre respiration pendant la méditation sur le souffle.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'When your mind wanders, gently return attention to the ___.': { prompt: 'Quand votre esprit s\'égare, ramenez doucement votre attention sur le ___.', options: ['Souffle', 'Téléphone', 'Horloge', 'Musique'], correctAnswer: 'Souffle' },
  'Getting frustrated when your mind wanders during meditation.': { prompt: 'Se frustrer quand votre esprit s\'égare pendant la méditation.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Where can you focus attention during breath meditation?': { prompt: 'Où pouvez-vous porter votre attention pendant la méditation sur le souffle?', options: ['Vos oreilles', 'Les narines, la poitrine ou le ventre', 'Le plafond', 'Vos pieds'], correctAnswer: 'Les narines, la poitrine ou le ventre' },
  'Noticing your mind has wandered IS the practice of meditation.': { prompt: 'Remarquer que votre esprit s\'est égaré EST la pratique de la méditation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // 5-Min Sit
  'Is 5 minutes of meditation worthwhile?': { prompt: '5 minutes de méditation, est-ce que ça vaut la peine?', options: ['Oui, même les courtes sessions ont des bienfaits', 'Seulement si vous le faites 10 fois', 'Jamais', 'Non, c\'est trop court'], correctAnswer: 'Oui, même les courtes sessions ont des bienfaits' },
  'Consistency matters more than session length for beginners.': { prompt: 'La constance compte plus que la durée de la session pour les débutants.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Start with ___ minutes and gradually increase as it becomes a habit.': { prompt: 'Commencez avec ___ minutes et augmentez graduellement à mesure que ça devient une habitude.', options: ['5', '30', '60', '120'], correctAnswer: '5' },
  'Setting a gentle timer so you don\'t watch the clock.': { prompt: 'Régler un minuteur doux pour ne pas regarder l\'horloge.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What is the best time to meditate?': { prompt: 'Quel est le meilleur moment pour méditer?', options: ['Seulement à midi', 'Seulement pendant la pleine lune', 'Seulement à minuit', 'Le moment que vous pouvez faire régulièrement'], correctAnswer: 'Le moment que vous pouvez faire régulièrement' },
  'Five minutes daily is better than 30 minutes once a week.': { prompt: 'Cinq minutes par jour c\'est mieux que 30 minutes une fois par semaine.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Body Scan
  'What is a body scan meditation?': { prompt: 'Qu\'est-ce qu\'une méditation de balayage corporel?', options: ['Courir sur place', 'Se regarder dans un miroir', 'Remarquer lentement les sensations dans chaque partie du corps', 'Une procédure médicale'], correctAnswer: 'Remarquer lentement les sensations dans chaque partie du corps' },
  'Body scan meditation helps increase body awareness.': { prompt: 'La méditation de balayage corporel aide à augmenter la conscience corporelle.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A body scan typically starts from the ___ and moves up (or vice versa).': { prompt: 'Un balayage corporel commence typiquement par les ___ et monte (ou vice versa).', options: ['Orteils', 'Tête', 'Mains', 'Poitrine'], correctAnswer: 'Orteils' },
  'Trying to change or fix sensations during a body scan.': { prompt: 'Essayer de changer ou corriger les sensations pendant un balayage corporel.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What should you do with tension you notice during a body scan?': { prompt: 'Que devriez-vous faire avec la tension que vous remarquez pendant un balayage corporel?', options: ['Se tendre davantage', 'Simplement l\'observer sans jugement', 'Arrêter de méditer', 'L\'ignorer'], correctAnswer: 'Simplement l\'observer sans jugement' },
  'Body scans can help with stress and tension release.': { prompt: 'Les balayages corporels peuvent aider à relâcher le stress et la tension.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Monkey Mind
  'What is "monkey mind"?': { prompt: 'Qu\'est-ce que l\'"esprit de singe"?', options: ['Un esprit agité et instable qui saute d\'une pensée à l\'autre', 'Une technique de méditation', 'Un type de yoga', 'Penser aux singes'], correctAnswer: 'Un esprit agité et instable qui saute d\'une pensée à l\'autre' },
  'Having a busy mind during meditation means you\'re doing it wrong.': { prompt: 'Avoir un esprit agité pendant la méditation signifie que vous le faites mal.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'The goal isn\'t to ___ thinking, but to notice thoughts without getting caught up.': { prompt: 'L\'objectif n\'est pas d\'___ de penser, mais de remarquer les pensées sans s\'y perdre.', options: ['Arrêter', 'Commencer', 'Augmenter', 'Forcer'], correctAnswer: 'Arrêter' },
  'Labeling thoughts as "thinking" and returning to breath.': { prompt: 'Étiqueter les pensées comme "pensée" et revenir au souffle.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'How should you treat thoughts during meditation?': { prompt: 'Comment devriez-vous traiter les pensées pendant la méditation?', options: ['Les combattre', 'Comme des nuages passant dans le ciel — observer et laisser aller', 'Analyser chacune en profondeur', 'Les écrire toutes immédiatement'], correctAnswer: 'Comme des nuages passant dans le ciel — observer et laisser aller' },
  'Everyone experiences monkey mind, even experienced meditators.': { prompt: 'Tout le monde expérimente l\'esprit de singe, même les méditants expérimentés.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Counting Breath
  'How does counting breaths help meditation?': { prompt: 'Comment le comptage des respirations aide-t-il la méditation?', options: ['Ça remplace la respiration', 'Ça donne le vertige', 'Ça n\'aide pas', 'Ça donne à l\'esprit un ancrage pour rester concentré'], correctAnswer: 'Ça donne à l\'esprit un ancrage pour rester concentré' },
  'A common practice is to count breaths from 1 to 10, then restart.': { prompt: 'Une pratique courante est de compter les respirations de 1 à 10, puis recommencer.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'If you lose count, simply start back at ___ without judgment.': { prompt: 'Si vous perdez le compte, recommencez simplement à ___ sans jugement.', options: ['Un', 'Zéro', 'Dix', 'Cinq'], correctAnswer: 'Un' },
  'Getting upset with yourself when you lose count.': { prompt: 'Se fâcher contre soi-même quand on perd le compte.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'When do you count during breath counting?': { prompt: 'Quand comptez-vous pendant le comptage des respirations?', options: ['Seulement à l\'inspiration', 'Vous ne comptez pas', 'Entre les respirations', 'À l\'expiration typiquement'], correctAnswer: 'À l\'expiration typiquement' },
  'Counting breath is a great technique for meditation beginners.': { prompt: 'Le comptage des respirations est une excellente technique pour les débutants en méditation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Noting
  'What is "noting" in meditation?': { prompt: 'Qu\'est-ce que la "notation mentale" en méditation?', options: ['Étiqueter mentalement les pensées, sentiments ou sensations à mesure qu\'ils surgissent', 'La notation musicale', 'Lire des notes', 'Écrire des notes'], correctAnswer: 'Étiqueter mentalement les pensées, sentiments ou sensations à mesure qu\'ils surgissent' },
  'Common labels in noting include "thinking," "feeling," and "hearing."': { prompt: 'Les étiquettes courantes dans la notation mentale incluent "penser", "ressentir" et "entendre".', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Noting helps create ___ from your experiences rather than getting lost in them.': { prompt: 'La notation mentale aide à créer de la ___ par rapport à vos expériences plutôt que de s\'y perdre.', options: ['Distance', 'Plus', 'Confusion', 'Attachement'], correctAnswer: 'Distance' },
  'Using simple one-word labels when noting during meditation.': { prompt: 'Utiliser des étiquettes simples d\'un mot lors de la notation mentale pendant la méditation.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'After noting a thought, what should you do?': { prompt: 'Après avoir noté une pensée, que devriez-vous faire?', options: ['Ramener l\'attention au souffle ou au corps', 'L\'écrire', 'Arrêter de méditer', 'L\'analyser en profondeur'], correctAnswer: 'Ramener l\'attention au souffle ou au corps' },
  'Noting practice builds self-awareness and mindfulness.': { prompt: 'La pratique de notation mentale développe la conscience de soi et la pleine conscience.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Walking Meditation
  'What is walking meditation?': { prompt: 'Qu\'est-ce que la méditation en marchant?', options: ['Marcher le plus vite possible', 'Marcher lentement et délibérément en portant attention à chaque pas et aux sensations corporelles', 'Marcher en dormant', 'Faire de la randonnée pour l\'exercice'], correctAnswer: 'Marcher lentement et délibérément en portant attention à chaque pas et aux sensations corporelles' },
  'Walking meditation is a good alternative for people who find sitting meditation difficult.': { prompt: 'La méditation en marchant est une bonne alternative pour les gens qui trouvent la méditation assise difficile.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'During walking meditation, focus on the sensation of your ___ touching the ground.': { prompt: 'Pendant la méditation en marchant, concentrez-vous sur la sensation de vos ___ touchant le sol.', options: ['Pieds', 'Mains', 'Tête', 'Dos'], correctAnswer: 'Pieds' },
  'Where is the best place to practice walking meditation?': { prompt: 'Quel est le meilleur endroit pour pratiquer la méditation en marchant?', options: ['Seulement dans un temple', 'Un endroit calme et plat où vous pouvez marcher d\'avant en arrière', 'Une autoroute achalandée', 'Un centre commercial bondé'], correctAnswer: 'Un endroit calme et plat où vous pouvez marcher d\'avant en arrière' },
  'You must close your eyes during walking meditation.': { prompt: 'Vous devez fermer les yeux pendant la méditation en marchant.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Walking at your normal fast pace while trying to meditate.': { prompt: 'Marcher à votre rythme rapide normal tout en essayant de méditer.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What can you silently note during walking meditation?': { prompt: 'Que pouvez-vous noter silencieusement pendant la méditation en marchant?', options: ['Votre horaire de demain', 'Lever, déplacer, poser — les phases de chaque pas', 'Les paroles d\'une chanson', 'Rien du tout'], correctAnswer: 'Lever, déplacer, poser — les phases de chaque pas' },
  'Walking meditation can be practiced outdoors in nature for added mindfulness benefits.': { prompt: 'La méditation en marchant peut être pratiquée en plein air dans la nature pour des bienfaits de pleine conscience accrus.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Loving-Kindness
  'What is loving-kindness (metta) meditation?': { prompt: 'Qu\'est-ce que la méditation de bienveillance aimante (metta)?', options: ['Un rituel de prière', 'Répéter silencieusement des phrases de bienveillance envers soi-même et les autres', 'Un type de yoga', 'Penser seulement aux gens qu\'on aime'], correctAnswer: 'Répéter silencieusement des phrases de bienveillance envers soi-même et les autres' },
  'Loving-kindness meditation typically starts by sending good wishes to yourself.': { prompt: 'La méditation de bienveillance aimante commence typiquement par envoyer de bons souhaits à soi-même.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A common metta phrase is "May I be happy, may I be ___, may I be at peace."': { prompt: 'Une phrase metta courante est "Puissé-je être heureux, puissé-je être ___, puissé-je être en paix."', options: ['En santé', 'Riche', 'Célèbre', 'Puissant'], correctAnswer: 'En santé' },
  'What has research shown about regular loving-kindness practice?': { prompt: 'Qu\'ont montré les recherches sur la pratique régulière de bienveillance aimante?', options: ['Elle n\'a aucun effet mesurable', 'Elle augmente les émotions positives et la connexion sociale', 'Elle ne fonctionne que pour les moines', 'Elle augmente la colère'], correctAnswer: 'Elle augmente les émotions positives et la connexion sociale' },
  'You must feel the emotions immediately for loving-kindness meditation to work.': { prompt: 'Vous devez ressentir les émotions immédiatement pour que la méditation de bienveillance aimante fonctionne.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Skipping yourself and only sending loving-kindness to others.': { prompt: 'Se sauter soi-même et n\'envoyer de la bienveillance qu\'aux autres.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'In which order do you typically expand loving-kindness?': { prompt: 'Dans quel ordre élargissez-vous typiquement la bienveillance aimante?', options: ['Les ennemis d\'abord, puis les inconnus, puis les amis', 'Soi-même, les proches, les personnes neutres, les personnes difficiles, tous les êtres', 'Seulement soi-même', 'Ordre aléatoire'], correctAnswer: 'Soi-même, les proches, les personnes neutres, les personnes difficiles, tous les êtres' },
  'Loving-kindness meditation can help reduce feelings of isolation and loneliness.': { prompt: 'La méditation de bienveillance aimante peut aider à réduire les sentiments d\'isolement et de solitude.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Visualization
  'What is visualization meditation?': { prompt: 'Qu\'est-ce que la méditation de visualisation?', options: ['Regarder une vidéo', 'Utiliser l\'imagerie mentale pour créer des scènes apaisantes ou stimulantes dans votre esprit', 'Dessiner en méditant', 'Regarder une bougie'], correctAnswer: 'Utiliser l\'imagerie mentale pour créer des scènes apaisantes ou stimulantes dans votre esprit' },
  'The brain responds to vivid mental imagery similarly to real experiences.': { prompt: 'Le cerveau réagit à l\'imagerie mentale vivide de façon similaire aux expériences réelles.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A common visualization is imagining a peaceful ___ like a beach, forest, or mountain.': { prompt: 'Une visualisation courante est d\'imaginer un ___ paisible comme une plage, une forêt ou une montagne.', options: ['Lieu', 'Son', 'Couleur', 'Mot'], correctAnswer: 'Lieu' },
  'How can you make visualization more effective?': { prompt: 'Comment pouvez-vous rendre la visualisation plus efficace?', options: ['N\'utiliser que la vue', 'Engager tous les sens: vue, son, odorat, toucher et température', 'Penser seulement en mots', 'Garder les yeux ouverts'], correctAnswer: 'Engager tous les sens: vue, son, odorat, toucher et température' },
  'Athletes use visualization meditation to improve performance.': { prompt: 'Les athlètes utilisent la méditation de visualisation pour améliorer leur performance.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Getting frustrated that your mental images are not perfectly vivid and clear.': { prompt: 'Se frustrer que vos images mentales ne soient pas parfaitement vivides et claires.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is "healing light" visualization?': { prompt: 'Qu\'est-ce que la visualisation de "lumière guérisseuse"?', options: ['Fixer une lampe', 'Imaginer une lumière chaude et guérisseuse traversant les zones de tension ou de douleur', 'Une procédure médicale', 'Un type de lampe de poche'], correctAnswer: 'Imaginer une lumière chaude et guérisseuse traversant les zones de tension ou de douleur' },
  'Visualization can be combined with breath work for deeper relaxation.': { prompt: 'La visualisation peut être combinée avec le travail respiratoire pour une relaxation plus profonde.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Mindful Eating
  'What is mindful eating?': { prompt: 'Qu\'est-ce que l\'alimentation consciente?', options: ['Manger le plus vite possible', 'Compter chaque calorie de façon obsessive', 'Porter une attention complète à l\'expérience de manger avec tous vos sens', 'Ne manger que de la nourriture saine'], correctAnswer: 'Porter une attention complète à l\'expérience de manger avec tous vos sens' },
  'Eating while watching TV or scrolling your phone is mindful eating.': { prompt: 'Manger en regardant la télé ou en défilant sur votre téléphone est de l\'alimentation consciente.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'The "raisin exercise" is a classic mindful eating practice where you spend several ___ eating a single raisin.': { prompt: 'L\'"exercice du raisin" est une pratique classique d\'alimentation consciente où vous passez plusieurs ___ à manger un seul raisin.', options: ['Minutes', 'Secondes', 'Heures', 'Jours'], correctAnswer: 'Minutes' },
  'What does mindful eating help you recognize?': { prompt: 'Que l\'alimentation consciente vous aide-t-elle à reconnaître?', options: ['Comment cuisiner', 'Les signaux de faim et de satiété que votre corps envoie', 'Les prix des aliments', 'Les faits nutritionnels'], correctAnswer: 'Les signaux de faim et de satiété que votre corps envoie' },
  'Chewing food slowly and thoroughly is a key part of mindful eating.': { prompt: 'Mâcher la nourriture lentement et complètement est un élément clé de l\'alimentation consciente.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Taking three deep breaths before starting a meal to bring awareness to the moment.': { prompt: 'Prendre trois respirations profondes avant de commencer un repas pour amener la conscience au moment présent.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'How can mindful eating help with emotional eating?': { prompt: 'Comment l\'alimentation consciente peut-elle aider avec l\'alimentation émotionnelle?', options: ['Elle ne peut pas aider', 'En créant un espace entre l\'envie de manger et l\'action, vous permettant de choisir consciemment', 'En restreignant la nourriture', 'En comptant les calories'], correctAnswer: 'En créant un espace entre l\'envie de manger et l\'action, vous permettant de choisir consciemment' },
  'Mindful eating is about restriction and dieting.': { prompt: 'L\'alimentation consciente est une question de restriction et de régime.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },

  // Sleep Meditation
  'How does meditation help with sleep?': { prompt: 'Comment la méditation aide-t-elle le sommeil?', options: ['Elle remplace le sommeil', 'Elle active le système nerveux parasympathique, signalant au corps de se détendre', 'Elle vous rend plus alerte', 'Elle n\'a aucun effet sur le sommeil'], correctAnswer: 'Elle active le système nerveux parasympathique, signalant au corps de se détendre' },
  'A body scan meditation done in bed can help you fall asleep.': { prompt: 'Un balayage corporel fait au lit peut vous aider à vous endormir.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The ___ breathing technique (inhale 4, hold 7, exhale 8) is popular for sleep.': { prompt: 'La technique de respiration ___ (inspirer 4, retenir 7, expirer 8) est populaire pour le sommeil.', options: ['4-7-8', '1-2-3', '10-10-10', '5-5-5'], correctAnswer: '4-7-8' },
  'What should you avoid before a sleep meditation?': { prompt: 'Que devriez-vous éviter avant une méditation pour le sommeil?', options: ['Tamiser les lumières', 'Le temps d\'écran, la caféine et le contenu stimulant', 'Un bain chaud', 'Lire un livre calme'], correctAnswer: 'Le temps d\'écran, la caféine et le contenu stimulant' },
  'It is okay to fall asleep during a sleep meditation — that is the goal.': { prompt: 'C\'est correct de s\'endormir pendant une méditation pour le sommeil — c\'est l\'objectif.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Checking your phone if you cannot fall asleep during sleep meditation.': { prompt: 'Vérifier votre téléphone si vous ne pouvez pas vous endormir pendant la méditation pour le sommeil.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is "yoga nidra" or "yogic sleep"?': { prompt: 'Qu\'est-ce que le "yoga nidra" ou "sommeil yogique"?', options: ['Dormir pendant un cours de yoga', 'Une pratique guidée qui vous amène au seuil entre l\'éveil et le sommeil', 'Un type d\'étirement', 'Faire une sieste après le yoga'], correctAnswer: 'Une pratique guidée qui vous amène au seuil entre l\'éveil et le sommeil' },
  'Consistent bedtime meditation can help establish a healthy sleep routine.': { prompt: 'La méditation régulière au coucher peut aider à établir une routine de sommeil saine.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Stress Relief
  'What stress hormone does meditation help reduce?': { prompt: 'Quelle hormone du stress la méditation aide-t-elle à réduire?', options: ['Insuline', 'Cortisol', 'Adrénaline uniquement', 'Mélatonine'], correctAnswer: 'Cortisol' },
  'Even 5 minutes of deep breathing can reduce acute stress.': { prompt: 'Même 5 minutes de respiration profonde peuvent réduire le stress aigu.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The "fight or ___" response is the body\'s automatic reaction to perceived threats.': { prompt: 'La réponse de "lutte ou ___" est la réaction automatique du corps aux menaces perçues.', options: ['Fuite', 'Gel', 'Sommeil', 'Nourriture'], correctAnswer: 'Fuite' },
  'Which breathing technique quickly calms the nervous system?': { prompt: 'Quelle technique de respiration calme rapidement le système nerveux?', options: ['Respiration rapide et superficielle', 'Retenir son souffle le plus longtemps possible', 'Expiration prolongée — expirer plus longtemps qu\'on inspire', 'Respirer uniquement par la bouche'], correctAnswer: 'Expiration prolongée — expirer plus longtemps qu\'on inspire' },
  'Chronic stress can weaken the immune system and cause physical illness.': { prompt: 'Le stress chronique peut affaiblir le système immunitaire et causer des maladies physiques.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Using meditation only during a crisis instead of practicing regularly.': { prompt: 'Utiliser la méditation seulement pendant une crise au lieu de pratiquer régulièrement.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is "progressive muscle relaxation"?': { prompt: 'Qu\'est-ce que la "relaxation musculaire progressive"?', options: ['Faire de l\'exercice de plus en plus difficile', 'Tendre systématiquement puis relâcher chaque groupe musculaire', 'Un type de massage', 'Musculation progressive'], correctAnswer: 'Tendre systématiquement puis relâcher chaque groupe musculaire' },
  'Meditation changes brain structure over time, strengthening areas related to emotional regulation.': { prompt: 'La méditation change la structure du cerveau au fil du temps, renforçant les zones liées à la régulation émotionnelle.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Focus Training
  'What type of meditation is specifically designed to improve concentration?': { prompt: 'Quel type de méditation est spécifiquement conçu pour améliorer la concentration?', options: ['Méditation pour le sommeil', 'Méditation d\'attention focalisée sur un seul objet', 'Rêverie libre', 'Visualisation uniquement'], correctAnswer: 'Méditation d\'attention focalisée sur un seul objet' },
  'Meditation has been shown to increase attention span with regular practice.': { prompt: 'Il a été démontré que la méditation augmente la durée d\'attention avec une pratique régulière.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Trataka is a meditation practice involving steady ___ at a candle flame.': { prompt: 'Trataka est une pratique de méditation impliquant un ___ fixe sur une flamme de bougie.', options: ['Regard', 'Écoute', 'Respiration', 'Chant'], correctAnswer: 'Regard' },
  'What happens each time you notice your mind wandered and bring it back?': { prompt: 'Que se passe-t-il chaque fois que vous remarquez que votre esprit s\'est égaré et que vous le ramenez?', options: ['Vous échouez', 'Rien d\'utile', 'Vous renforcez votre "muscle" d\'attention', 'Vous devriez arrêter de méditer'], correctAnswer: 'Vous renforcez votre "muscle" d\'attention' },
  'Multitasking is more efficient than single-focused attention.': { prompt: 'Le multitâche est plus efficace que l\'attention concentrée sur une seule chose.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Meditating for 10 minutes daily to improve focus rather than just taking stimulants.': { prompt: 'Méditer 10 minutes par jour pour améliorer la concentration plutôt que de simplement prendre des stimulants.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'How long does it take to start seeing focus improvements from meditation?': { prompt: 'Combien de temps faut-il pour commencer à voir des améliorations de concentration grâce à la méditation?', options: ['Instantanément', 'Environ 2 à 4 semaines de pratique régulière', 'Au moins 5 ans', 'Ça ne fonctionne jamais'], correctAnswer: 'Environ 2 à 4 semaines de pratique régulière' },
  'Training focus through meditation can improve performance at work and school.': { prompt: 'Entraîner la concentration par la méditation peut améliorer la performance au travail et à l\'école.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Gratitude Practice
  'What is gratitude meditation?': { prompt: 'Qu\'est-ce que la méditation de gratitude?', options: ['Dire seulement "merci"', 'Se concentrer délibérément sur les choses que vous appréciez pour cultiver des émotions positives', 'Être reconnaissant seulement quand de bonnes choses arrivent', 'Une prière'], correctAnswer: 'Se concentrer délibérément sur les choses que vous appréciez pour cultiver des émotions positives' },
  'Research shows gratitude practice can increase overall happiness and life satisfaction.': { prompt: 'Les recherches montrent que la pratique de gratitude peut augmenter le bonheur global et la satisfaction de vie.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Writing down ___ things you are grateful for each day is a common gratitude exercise.': { prompt: 'Écrire ___ choses pour lesquelles vous êtes reconnaissant chaque jour est un exercice de gratitude courant.', options: ['Trois', 'Vingt', 'Cent', 'Zéro'], correctAnswer: 'Trois' },
  'Why does the brain have a "negativity bias"?': { prompt: 'Pourquoi le cerveau a-t-il un "biais de négativité"?', options: ['Le cerveau est défectueux', 'Il a évolué pour prioriser les menaces pour la survie', 'Les gens sont naturellement pessimistes', 'Il n\'existe pas'], correctAnswer: 'Il a évolué pour prioriser les menaces pour la survie' },
  'You should only practice gratitude for big, life-changing events.': { prompt: 'Vous ne devriez pratiquer la gratitude que pour les grands événements qui changent la vie.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Starting each meditation session by reflecting on one thing you are thankful for.': { prompt: 'Commencer chaque session de méditation en réfléchissant à une chose pour laquelle vous êtes reconnaissant.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What area of the brain is activated by gratitude practice?': { prompt: 'Quelle zone du cerveau est activée par la pratique de gratitude?', options: ['Le centre de la peur', 'Le cortex préfrontal et les circuits de récompense', 'Seulement le cortex visuel', 'Le cortex moteur'], correctAnswer: 'Le cortex préfrontal et les circuits de récompense' },
  'Gratitude journaling before bed can improve sleep quality.': { prompt: 'Écrire un journal de gratitude avant le coucher peut améliorer la qualité du sommeil.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Mantra Meditation
  'What is a mantra in meditation?': { prompt: 'Qu\'est-ce qu\'un mantra en méditation?', options: ['Un sort magique', 'Un mot ou une phrase répété silencieusement ou à voix haute comme point de concentration', 'Une technique de respiration', 'Un type de posture de yoga'], correctAnswer: 'Un mot ou une phrase répété silencieusement ou à voix haute comme point de concentration' },
  '"Om" is one of the oldest and most well-known mantras.': { prompt: '"Om" est l\'un des mantras les plus anciens et les plus connus.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'In Transcendental Meditation, a ___ mantra is given to each practitioner.': { prompt: 'Dans la Méditation Transcendantale, un mantra ___ est donné à chaque pratiquant.', options: ['Personnel', 'Public', 'Aléatoire', 'Partagé'], correctAnswer: 'Personnel' },
  'Do you need to use a Sanskrit mantra, or can you use any word?': { prompt: 'Avez-vous besoin d\'utiliser un mantra en sanskrit, ou pouvez-vous utiliser n\'importe quel mot?', options: ['Seul le sanskrit fonctionne', 'N\'importe quel mot ou phrase apaisant peut servir de mantra', 'Seuls les mots anglais fonctionnent', 'Les mantras doivent être en latin'], correctAnswer: 'N\'importe quel mot ou phrase apaisant peut servir de mantra' },
  'The vibration of chanting a mantra aloud can have a calming physical effect.': { prompt: 'La vibration de chanter un mantra à voix haute peut avoir un effet physique apaisant.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Changing your mantra every session because you get bored.': { prompt: 'Changer votre mantra à chaque session parce que vous vous ennuyez.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'How should you handle distracting thoughts during mantra meditation?': { prompt: 'Comment devriez-vous gérer les pensées distrayantes pendant la méditation mantra?', options: ['Se fâcher contre soi-même', 'Revenir doucement à la répétition du mantra sans jugement', 'Arrêter de méditer', 'Analyser chaque pensée'], correctAnswer: 'Revenir doucement à la répétition du mantra sans jugement' },
  'Mantra meditation can be practiced anywhere, even silently in a noisy environment.': { prompt: 'La méditation mantra peut être pratiquée n\'importe où, même silencieusement dans un environnement bruyant.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Chakra Basics
  'How many main chakras are there in traditional yoga philosophy?': { prompt: 'Combien de chakras principaux y a-t-il dans la philosophie yoga traditionnelle?', options: ['3', '7', '12', '5'], correctAnswer: '7' },
  'The root chakra is located at the base of the spine and relates to safety and grounding.': { prompt: 'Le chakra racine est situé à la base de la colonne vertébrale et est lié à la sécurité et à l\'ancrage.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The heart chakra (Anahata) is associated with ___ and compassion.': { prompt: 'Le chakra du coeur (Anahata) est associé à l\'___ et à la compassion.', options: ['Amour', 'Pouvoir', 'Parole', 'Intuition'], correctAnswer: 'Amour' },
  'What color is traditionally associated with the throat chakra?': { prompt: 'Quelle couleur est traditionnellement associée au chakra de la gorge?', options: ['Rouge', 'Bleu', 'Jaune', 'Vert'], correctAnswer: 'Bleu' },
  'Chakra meditation focuses on visualizing energy centers along the spine.': { prompt: 'La méditation des chakras se concentre sur la visualisation des centres d\'énergie le long de la colonne vertébrale.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Approaching chakra meditation with curiosity rather than needing to believe in literal energy centers.': { prompt: 'Aborder la méditation des chakras avec curiosité plutôt que de devoir croire en des centres d\'énergie littéraux.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Which chakra is associated with intuition and is sometimes called the "third eye"?': { prompt: 'Quel chakra est associé à l\'intuition et est parfois appelé le "troisième oeil"?', options: ['Chakra racine', 'Chakra du coeur', 'Chakra Ajna (troisième oeil)', 'Chakra du plexus solaire'], correctAnswer: 'Chakra Ajna (troisième oeil)' },
  'The crown chakra at the top of the head is associated with spiritual connection and awareness.': { prompt: 'Le chakra couronne au sommet de la tête est associé à la connexion spirituelle et à la conscience.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Zen Basics
  'What is Zen meditation (zazen)?': { prompt: 'Qu\'est-ce que la méditation Zen (zazen)?', options: ['Un type d\'exercice', 'La méditation assise mettant l\'accent sur la posture, la respiration et l\'expérience directe', 'Un art martial', 'Lire des livres de philosophie'], correctAnswer: 'La méditation assise mettant l\'accent sur la posture, la respiration et l\'expérience directe' },
  'In Zen, the practice itself is the goal — there is nothing to achieve.': { prompt: 'Dans le Zen, la pratique elle-même est l\'objectif — il n\'y a rien à atteindre.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A ___ is a paradoxical question used in Zen to transcend logical thinking.': { prompt: 'Un ___ est une question paradoxale utilisée dans le Zen pour transcender la pensée logique.', options: ['Koan', 'Mantra', 'Sutra', 'Mudra'], correctAnswer: 'Koan' },
  'What is the traditional Zen meditation posture?': { prompt: 'Quelle est la posture traditionnelle de la méditation Zen?', options: ['Debout sur une jambe', 'Assis sur un coussin (zafu) en position jambes croisées avec les mains en mudra', 'Couché uniquement', 'En marchant uniquement'], correctAnswer: 'Assis sur un coussin (zafu) en position jambes croisées avec les mains en mudra' },
  'Zen meditation traditionally keeps the eyes partially open with a downward gaze.': { prompt: 'La méditation Zen garde traditionnellement les yeux partiellement ouverts avec un regard vers le bas.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Approaching Zen with a "beginner\'s mind" — open, eager, and without preconceptions.': { prompt: 'Aborder le Zen avec un "esprit du débutant" — ouvert, enthousiaste et sans préjugés.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What does "mindfulness" (sati) mean in the context of Zen?': { prompt: 'Que signifie "pleine conscience" (sati) dans le contexte du Zen?', options: ['Penser au futur', 'Porter une attention nue au moment présent sans jugement', 'Avoir l\'esprit plein', 'Mémoriser des textes'], correctAnswer: 'Porter une attention nue au moment présent sans jugement' },
  'Zen values direct experience over theoretical knowledge about meditation.': { prompt: 'Le Zen valorise l\'expérience directe par rapport aux connaissances théoriques sur la méditation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Daily Habit
  'What is the most effective way to build a daily meditation habit?': { prompt: 'Quelle est la façon la plus efficace de construire une habitude de méditation quotidienne?', options: ['Méditer seulement quand on est stressé', 'Lier la méditation à une routine quotidienne existante (empilement d\'habitudes)', 'Attendre le moment parfait', 'Le faire différemment chaque jour'], correctAnswer: 'Lier la méditation à une routine quotidienne existante (empilement d\'habitudes)' },
  'Meditating at the same time each day helps establish the habit.': { prompt: 'Méditer à la même heure chaque jour aide à établir l\'habitude.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'It takes roughly ___ days of consistent practice for a new habit to feel automatic.': { prompt: 'Il faut environ ___ jours de pratique régulière pour qu\'une nouvelle habitude devienne automatique.', options: ['66', '7', '365', '3'], correctAnswer: '66' },
  'What should you do if you miss a day of meditation?': { prompt: 'Que devriez-vous faire si vous manquez un jour de méditation?', options: ['Abandonner complètement', 'Simplement reprendre le lendemain sans culpabilité', 'Recommencer du jour un', 'Doubler la prochaine session'], correctAnswer: 'Simplement reprendre le lendemain sans culpabilité' },
  'Starting with just 2 minutes per day is a valid way to begin a meditation practice.': { prompt: 'Commencer avec seulement 2 minutes par jour est une façon valide de débuter une pratique de méditation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Committing to meditate for 1 hour daily as a total beginner.': { prompt: 'S\'engager à méditer 1 heure par jour en tant que débutant total.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What tool can help maintain accountability for daily meditation?': { prompt: 'Quel outil peut aider à maintenir la responsabilité pour la méditation quotidienne?', options: ['Rien ne peut aider', 'Une application de méditation avec suivi de séries', 'Seulement un gourou personnel', 'De l\'équipement coûteux'], correctAnswer: 'Une application de méditation avec suivi de séries' },
  'Morning meditation can set a calm, focused tone for the entire day.': { prompt: 'La méditation du matin peut donner un ton calme et concentré pour toute la journée.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
};
