export const negotiationFr: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // Negotiation 101
  'What is the primary goal of a negotiation?': { prompt: 'Quel est l\'objectif principal d\'une négociation ?', options: ['Vaincre l\'autre partie', 'Parvenir à un accord mutuellement acceptable', 'Éviter complètement le conflit', 'Faire la première concession'], correctAnswer: 'Parvenir à un accord mutuellement acceptable' },
  'Negotiation only happens in formal business settings.': { prompt: 'La négociation n\'a lieu que dans des contextes d\'affaires formels.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Which of these is a distributive negotiation?': { prompt: 'Lequel de ces exemples est une négociation distributive ?', options: ['Deux entreprises formant une coentreprise', 'Marchander le prix d\'une voiture d\'occasion', 'Brainstormer de nouvelles fonctionnalités ensemble', 'Médier un conflit au travail'], correctAnswer: 'Marchander le prix d\'une voiture d\'occasion' },
  'In negotiation, your "___" is the range between your ideal outcome and your walk-away point.': { prompt: 'En négociation, votre « ___ » est l\'écart entre votre résultat idéal et votre point de retrait.', options: ['BATNA', 'Zone de négociation', 'Ancrage', 'Prix de réserve'], correctAnswer: 'Zone de négociation' },
  'Integrative negotiation seeks to expand value for all parties.': { prompt: 'La négociation intégrative cherche à augmenter la valeur pour toutes les parties.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What does ZOPA stand for?': { prompt: 'Que signifie ZOPA ?', options: ['Zone d\'accord possible', 'Ajustement de prix à option zéro', 'Zone d\'action principale', 'Analyse de probabilité de résultat zéro'], correctAnswer: 'Zone d\'accord possible' },
  'Preparation is considered the most important phase of negotiation.': { prompt: 'La préparation est considérée comme la phase la plus importante de la négociation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which negotiation style focuses on maintaining the relationship above all?': { prompt: 'Quel style de négociation se concentre avant tout sur le maintien de la relation ?', options: ['Compétitif', 'Accommodant', 'Évitant', 'Compromis'], correctAnswer: 'Accommodant' },

  // BATNA
  'What does BATNA stand for?': { prompt: 'Que signifie BATNA ?', options: ['Meilleure alternative à un accord négocié', 'Termes de base pour une approche de négociation', 'Arrangement bilatéral pour la négociation commerciale', 'Meilleur objectif atteignable dans l\'analyse de négociation'], correctAnswer: 'Meilleure alternative à un accord négocié' },
  'A strong BATNA gives you more power in a negotiation.': { prompt: 'Un BATNA solide vous donne plus de pouvoir dans une négociation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'When should you reveal your BATNA?': { prompt: 'Quand devriez-vous révéler votre BATNA ?', options: ['Toujours au début', 'Seulement quand cela renforce votre position', 'Jamais en aucune circonstance', 'Seulement par écrit'], correctAnswer: 'Seulement quand cela renforce votre position' },
  'Your ___ price is the worst deal you would still accept before walking away.': { prompt: 'Votre prix ___ est la pire offre que vous accepteriez encore avant de partir.', options: ['De réserve', 'Demandé', 'Du marché', 'D\'ouverture'], correctAnswer: 'De réserve' },
  'You should accept any deal that is better than your BATNA.': { prompt: 'Vous devriez accepter tout accord meilleur que votre BATNA.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'How can you improve your BATNA?': { prompt: 'Comment pouvez-vous améliorer votre BATNA ?', options: ['Ignorer les alternatives et se concentrer sur une seule offre', 'Développer plusieurs alternatives solides avant de négocier', 'Accepter la première offre rapidement', 'Éviter de rechercher le marché'], correctAnswer: 'Développer plusieurs alternatives solides avant de négocier' },
  'If you have no BATNA, you are in a very weak negotiating position.': { prompt: 'Si vous n\'avez pas de BATNA, vous êtes dans une position de négociation très faible.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Who introduced the concept of BATNA?': { prompt: 'Qui a introduit le concept de BATNA ?', options: ['Daniel Kahneman', 'Roger Fisher et William Ury', 'Robert Cialdini', 'Dale Carnegie'], correctAnswer: 'Roger Fisher et William Ury' },

  // Anchoring
  'What is anchoring in negotiation?': { prompt: 'Qu\'est-ce que l\'ancrage en négociation ?', options: ['Refuser de bouger de sa position', 'Établir un point de référence initial qui influence le résultat', 'Accepter tout ce que l\'autre partie dit', 'Quitter la table de négociation'], correctAnswer: 'Établir un point de référence initial qui influence le résultat' },
  'The party who makes the first offer usually has an advantage due to anchoring.': { prompt: 'La partie qui fait la première offre a généralement un avantage grâce à l\'ancrage.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'How should you counter an aggressive anchor?': { prompt: 'Comment devriez-vous contrer un ancrage agressif ?', options: ['L\'accepter comme juste', 'L\'ignorer et poser votre propre ancrage', 'Partir immédiatement', 'Couper la poire en deux immédiatement'], correctAnswer: 'L\'ignorer et poser votre propre ancrage' },
  'An effective anchor should be ___ but still justifiable with reasoning.': { prompt: 'Un ancrage efficace devrait être ___ mais justifiable avec un raisonnement.', options: ['Agressif', 'Modéré', 'Bas', 'Aléatoire'], correctAnswer: 'Agressif' },
  'Anchoring only works with numbers and prices.': { prompt: 'L\'ancrage ne fonctionne qu\'avec les chiffres et les prix.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'A car dealer lists a car at $30,000 knowing they will accept $25,000. The $30,000 is:': { prompt: 'Un concessionnaire affiche une voiture à 30 000 $ sachant qu\'il acceptera 25 000 $. Le 30 000 $ est :', options: ['Le prix de réserve', 'Le BATNA', 'L\'ancrage', 'La ZOPA'], correctAnswer: 'L\'ancrage' },
  'You should always make the first offer to set the anchor.': { prompt: 'Vous devriez toujours faire la première offre pour poser l\'ancrage.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Which cognitive bias makes anchoring effective?': { prompt: 'Quel biais cognitif rend l\'ancrage efficace ?', options: ['Biais de confirmation', 'Biais d\'ancrage — ajustement insuffisant à partir des valeurs initiales', 'Effet Dunning-Kruger', 'Biais rétrospectif'], correctAnswer: 'Biais d\'ancrage — ajustement insuffisant à partir des valeurs initiales' },

  // Win-Win
  'What characterizes a win-win negotiation outcome?': { prompt: 'Qu\'est-ce qui caractérise un résultat de négociation gagnant-gagnant ?', options: ['Les deux parties font des compromis égaux', 'Les deux parties sentent qu\'elles ont gagné de la valeur', 'Une partie gagne plus que l\'autre', 'Aucune partie n\'obtient ce qu\'elle veut'], correctAnswer: 'Les deux parties sentent qu\'elles ont gagné de la valeur' },
  'Win-win outcomes require both parties to have identical interests.': { prompt: 'Les résultats gagnant-gagnant exigent que les deux parties aient des intérêts identiques.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Which technique best supports win-win negotiation?': { prompt: 'Quelle technique soutient le mieux la négociation gagnant-gagnant ?', options: ['Menacer de partir', 'Explorer les intérêts sous-jacents plutôt que les positions', 'Tout diviser 50/50', 'Cacher vos priorités'], correctAnswer: 'Explorer les intérêts sous-jacents plutôt que les positions' },
  'Logrolling is a win-win technique where parties trade concessions on different issues.': { prompt: 'Le logrolling est une technique gagnant-gagnant où les parties échangent des concessions sur différents sujets.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Expanding the ___ means finding ways to create more total value before dividing it.': { prompt: 'Agrandir le ___ signifie trouver des moyens de créer plus de valeur totale avant de la diviser.', options: ['Gâteau', 'Budget', 'Calendrier', 'Équipe'], correctAnswer: 'Gâteau' },
  'Two sisters fight over one orange. A win-win solution reveals that one wants the juice and the other wants the peel. This illustrates:': { prompt: 'Deux sœurs se disputent une orange. Une solution gagnant-gagnant révèle que l\'une veut le jus et l\'autre la pelure. Cela illustre :', options: ['L\'ancrage', 'La négociation basée sur les positions vs les intérêts', 'Les dynamiques de pouvoir', 'L\'analyse BATNA'], correctAnswer: 'La négociation basée sur les positions vs les intérêts' },
  'Win-win negotiation is always possible in every situation.': { prompt: 'La négociation gagnant-gagnant est toujours possible dans toute situation.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Which book popularized the concept of principled, win-win negotiation?': { prompt: 'Quel livre a popularisé le concept de négociation raisonnée gagnant-gagnant ?', options: ['L\'Art de la guerre', 'Getting to Yes', 'Never Split the Difference', 'Les 48 lois du pouvoir'], correctAnswer: 'Getting to Yes' },

  // Power Dynamics
  'Which factor most increases your negotiating power?': { prompt: 'Quel facteur augmente le plus votre pouvoir de négociation ?', options: ['Être plus âgé que votre interlocuteur', 'Avoir de solides alternatives (BATNA)', 'Parler plus fort', 'Arriver tôt à la réunion'], correctAnswer: 'Avoir de solides alternatives (BATNA)' },
  'The party with more information always has more power in a negotiation.': { prompt: 'La partie avec plus d\'information a toujours plus de pouvoir dans une négociation.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Legitimate power comes from ___, titles, or recognized authority.': { prompt: 'Le pouvoir légitime vient des ___, des titres ou de l\'autorité reconnue.', options: ['Positions', 'Argent', 'Menaces', 'Silence'], correctAnswer: 'Positions' },
  'How can a weaker party increase their negotiating power?': { prompt: 'Comment une partie plus faible peut-elle augmenter son pouvoir de négociation ?', options: ['Bluffer sur ses alternatives', 'Former des coalitions avec d\'autres parties prenantes', 'Accepter la première offre', 'Éviter la préparation'], correctAnswer: 'Former des coalitions avec d\'autres parties prenantes' },
  'Time pressure always hurts the negotiator under deadline.': { prompt: 'La pression du temps nuit toujours au négociateur sous échéance.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is "referent power" in negotiation?': { prompt: 'Qu\'est-ce que le « pouvoir de référence » en négociation ?', options: ['Le pouvoir des contrats légaux', 'Le pouvoir d\'être apprécié ou respecté', 'Le pouvoir des ressources financières', 'Le pouvoir de la présence physique'], correctAnswer: 'Le pouvoir d\'être apprécié ou respecté' },
  'Perceived power is as influential as actual power in negotiation.': { prompt: 'Le pouvoir perçu est aussi influent que le pouvoir réel en négociation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which tactic shifts power by creating urgency?': { prompt: 'Quelle tactique déplace le pouvoir en créant de l\'urgence ?', options: ['L\'écoute active', 'Fixer une échéance', 'Le miroir', 'Poser des questions ouvertes'], correctAnswer: 'Fixer une échéance' },

  // Active Listening
  'What is the primary purpose of active listening in negotiation?': { prompt: 'Quel est l\'objectif principal de l\'écoute active en négociation ?', options: ['Trouver des faiblesses à exploiter', 'Comprendre pleinement les besoins et préoccupations de l\'autre partie', 'Gagner du temps pour réfléchir', 'Paraître poli'], correctAnswer: 'Comprendre pleinement les besoins et préoccupations de l\'autre partie' },
  'Paraphrasing what the other party said is a key active listening technique.': { prompt: 'Reformuler ce que l\'autre partie a dit est une technique clé d\'écoute active.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which response demonstrates active listening?': { prompt: 'Quelle réponse démontre l\'écoute active ?', options: ['C\'est faux, laissez-moi vous expliquer pourquoi', 'Donc, ce que vous dites, c\'est que vous avez besoin de flexibilité sur le calendrier ?', 'Je sais déjà ce que vous voulez dire', 'Pouvons-nous passer à autre chose ?'], correctAnswer: 'Donc, ce que vous dites, c\'est que vous avez besoin de flexibilité sur le calendrier ?' },
  'Labeling emotions means saying things like "It sounds like you\'re ___ about the deadline."': { prompt: 'Étiqueter les émotions signifie dire des choses comme « On dirait que vous êtes ___ par l\'échéance. »', options: ['Frustré', 'Content', 'Tort', 'Menteur'], correctAnswer: 'Frustré' },
  'Silence can be an effective active listening tool in negotiation.': { prompt: 'Le silence peut être un outil d\'écoute active efficace en négociation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Chris Voss\'s "mirroring" technique involves:': { prompt: 'La technique du « miroir » de Chris Voss consiste à :', options: ['Copier exactement le langage corporel', 'Répéter les 1 à 3 derniers mots que l\'autre personne a dits', 'Maintenir un contact visuel direct sans cligner', 'S\'habiller de manière similaire à votre interlocuteur'], correctAnswer: 'Répéter les 1 à 3 derniers mots que l\'autre personne a dits' },
  'Active listening means agreeing with everything the other party says.': { prompt: 'L\'écoute active signifie être d\'accord avec tout ce que l\'autre partie dit.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Which question type promotes deeper conversation?': { prompt: 'Quel type de question favorise une conversation plus profonde ?', options: ['Questions oui ou non', 'Questions ouvertes commençant par « comment » ou « quoi »', 'Questions suggestives', 'Questions rhétoriques'], correctAnswer: 'Questions ouvertes commençant par « comment » ou « quoi »' },

  // Reading the Room
  'What does "reading the room" mean in negotiation?': { prompt: 'Que signifie « lire la salle » en négociation ?', options: ['Compter le nombre de personnes présentes', 'Évaluer le climat émotionnel et les dynamiques non dites', 'Lire les documents sur la table', 'Vérifier la salle pour des appareils d\'enregistrement'], correctAnswer: 'Évaluer le climat émotionnel et les dynamiques non dites' },
  'Crossed arms always mean the other party is hostile.': { prompt: 'Les bras croisés signifient toujours que l\'autre partie est hostile.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'When someone leans ___ during your proposal, it often signals interest or engagement.': { prompt: 'Quand quelqu\'un se penche ___ pendant votre proposition, cela signale souvent de l\'intérêt ou de l\'engagement.', options: ['En avant', 'En arrière', 'De côté', 'Au loin'], correctAnswer: 'En avant' },
  'You notice your counterpart keeps glancing at their watch. What does this likely signal?': { prompt: 'Vous remarquez que votre interlocuteur regarde sans cesse sa montre. Que signale probablement ce comportement ?', options: ['Il est d\'accord avec tout', 'Il est sous pression de temps ou perd de l\'intérêt', 'Il enregistre la réunion', 'Il calcule des chiffres'], correctAnswer: 'Il est sous pression de temps ou perd de l\'intérêt' },
  'The tone of voice can communicate more than the actual words spoken.': { prompt: 'Le ton de la voix peut communiquer plus que les mots réellement prononcés.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'In a team negotiation, you should pay most attention to:': { prompt: 'Dans une négociation d\'équipe, vous devriez porter le plus d\'attention à :', options: ['Seulement le négociateur principal', 'La personne qui parle le plus fort', 'Le décideur silencieux dans la salle', 'La personne la plus proche de la porte'], correctAnswer: 'Le décideur silencieux dans la salle' },
  'A sudden shift to small talk may indicate the other party needs a mental break from tense topics.': { prompt: 'Un passage soudain à la conversation légère peut indiquer que l\'autre partie a besoin d\'une pause mentale des sujets tendus.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What should you do when you sense frustration rising in the room?': { prompt: 'Que devriez-vous faire quand vous sentez la frustration monter dans la salle ?', options: ['Pousser plus fort pour vos demandes', 'Reconnaître la tension et suggérer une courte pause', 'L\'ignorer et continuer à présenter', 'Quitter la salle immédiatement'], correctAnswer: 'Reconnaître la tension et suggérer une courte pause' },

  // Making Offers
  'What makes a strong opening offer?': { prompt: 'Qu\'est-ce qui fait une bonne offre d\'ouverture ?', options: ['C\'est votre seuil absolu', 'C\'est ambitieux mais justifiable avec des données', 'C\'est exactement ce que vous espérez obtenir', 'C\'est inférieur à ce que vous voulez'], correctAnswer: 'C\'est ambitieux mais justifiable avec des données' },
  'You should always let the other party make the first offer.': { prompt: 'Vous devriez toujours laisser l\'autre partie faire la première offre.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'What is a "package offer"?': { prompt: 'Qu\'est-ce qu\'une « offre globale » ?', options: ['Une offre livrée dans une boîte', 'Une proposition groupée couvrant plusieurs enjeux à la fois', 'Une offre qui expire en 24 heures', 'Une offre faite à plusieurs parties simultanément'], correctAnswer: 'Une proposition groupée couvrant plusieurs enjeux à la fois' },
  'An "exploding offer" is one that ___ if not accepted by a certain deadline.': { prompt: 'Une « offre explosive » est une offre qui ___ si elle n\'est pas acceptée avant une certaine échéance.', options: ['Expire', 'Double', 'S\'améliore', 'Se répète'], correctAnswer: 'Expire' },
  'Making an offer with precise numbers (e.g., $5,125) can be more effective than round numbers ($5,000).': { prompt: 'Faire une offre avec des chiffres précis (ex. 5 125 $) peut être plus efficace que des chiffres ronds (5 000 $).', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'When presenting your offer, you should:': { prompt: 'Lorsque vous présentez votre offre, vous devriez :', options: ['Vous excuser de demander trop', 'La présenter avec confiance et un raisonnement solide', 'Dire « à prendre ou à laisser »', 'La marmonner rapidement'], correctAnswer: 'La présenter avec confiance et un raisonnement solide' },
  'Presenting multiple equivalent offers simultaneously (MESOs) increases the chance of agreement.': { prompt: 'Présenter plusieurs offres équivalentes simultanément (MESOs) augmente les chances d\'accord.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is the risk of making an extremely aggressive first offer?': { prompt: 'Quel est le risque de faire une première offre extrêmement agressive ?', options: ['L\'autre partie acceptera toujours', 'Cela peut endommager la confiance et faire partir l\'autre partie', 'Cela montre de la faiblesse', 'Aucun risque du tout'], correctAnswer: 'Cela peut endommager la confiance et faire partir l\'autre partie' },

  // Counter Offers
  'What is the best first step after receiving an offer?': { prompt: 'Quelle est la meilleure première étape après avoir reçu une offre ?', options: ['Accepter immédiatement si c\'est raisonnable', 'La rejeter catégoriquement', 'Prendre le temps d\'évaluer avant de répondre', 'Faire une contre-offre tout aussi extrême'], correctAnswer: 'Prendre le temps d\'évaluer avant de répondre' },
  'A counter offer automatically rejects the original offer.': { prompt: 'Une contre-offre rejette automatiquement l\'offre originale.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The "___" strategy involves making your counter offer with a detailed justification.': { prompt: 'La stratégie « ___ » consiste à faire votre contre-offre avec une justification détaillée.', options: ['Raisonnée', 'Silencieuse', 'Agressive', 'Passive'], correctAnswer: 'Raisonnée' },
  'What should a counter offer signal to the other party?': { prompt: 'Que devrait signaler une contre-offre à l\'autre partie ?', options: ['Que vous n\'êtes pas sérieux dans la négociation', 'Que vous voulez un accord différent mais êtes prêt à travailler vers un accord', 'Que vous êtes désespéré', 'Que vous n\'avez pas d\'alternatives'], correctAnswer: 'Que vous voulez un accord différent mais êtes prêt à travailler vers un accord' },
  'You should always counter offer exactly halfway between your position and theirs.': { prompt: 'Vous devriez toujours contre-offrir exactement à mi-chemin entre votre position et la leur.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'How can you soften a counter offer?': { prompt: 'Comment pouvez-vous adoucir une contre-offre ?', options: ['Ajouter une menace', 'Reconnaître le mérite de leur offre avant de présenter la vôtre', 'Utiliser un langage agressif', 'Refuser d\'expliquer votre raisonnement'], correctAnswer: 'Reconnaître le mérite de leur offre avant de présenter la vôtre' },
  'Making three concessions in a row without getting anything back is a strong strategy.': { prompt: 'Faire trois concessions d\'affilée sans rien obtenir en retour est une stratégie forte.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'The "Ackerman model" for counter offers involves:': { prompt: 'Le « modèle Ackerman » pour les contre-offres implique :', options: ['Commencer à 100 % et ne jamais bouger', 'Offrir des incréments décroissants (65 %, 85 %, 95 %, 100 %)', 'Toujours couper la poire en deux', 'Faire une seule contre-offre'], correctAnswer: 'Offrir des incréments décroissants (65 %, 85 %, 95 %, 100 %)' },

  // Concessions
  'What is the golden rule of concessions?': { prompt: 'Quelle est la règle d\'or des concessions ?', options: ['Ne jamais faire de concessions', 'Toujours égaler les concessions', 'Chaque concession devrait être échangée contre quelque chose en retour', 'Faire toutes les concessions au début'], correctAnswer: 'Chaque concession devrait être échangée contre quelque chose en retour' },
  'Making large concessions early signals desperation.': { prompt: 'Faire de grandes concessions tôt signale du désespoir.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Concessions should get ___ over time to signal you are approaching your limit.': { prompt: 'Les concessions devraient devenir ___ au fil du temps pour signaler que vous approchez votre limite.', options: ['Plus petites', 'Plus grandes', 'Plus rapides', 'Plus fortes'], correctAnswer: 'Plus petites' },
  'What is "nibbling" in negotiation?': { prompt: 'Qu\'est-ce que le « grignotage » en négociation ?', options: ['Manger pendant les négociations', 'Demander de petits extras après que l\'accord principal est conclu', 'Faire la première offre', 'Refuser toutes les concessions'], correctAnswer: 'Demander de petits extras après que l\'accord principal est conclu' },
  'Labeling your concessions increases their perceived value.': { prompt: 'Nommer vos concessions augmente leur valeur perçue.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'You should concede on items that:': { prompt: 'Vous devriez concéder sur des éléments qui :', options: ['Sont les plus importants pour vous', 'Vous coûtent peu mais sont précieux pour l\'autre partie', 'L\'autre partie n\'a pas demandés', 'Sont complètement non pertinents'], correctAnswer: 'Vous coûtent peu mais sont précieux pour l\'autre partie' },
  'Unconditional concessions build goodwill and encourage reciprocity.': { prompt: 'Les concessions inconditionnelles créent de la bonne volonté et encouragent la réciprocité.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'What is the "door in the face" concession technique?': { prompt: 'Qu\'est-ce que la technique de concession « porte au nez » ?', options: ['Claquer la porte et partir', 'Commencer par une demande extrême, puis reculer vers ce que vous voulez vraiment', 'Faire votre vraie demande en premier', 'Demander moins que ce que vous voulez'], correctAnswer: 'Commencer par une demande extrême, puis reculer vers ce que vous voulez vraiment' },

  // Deadlocks
  'What is a deadlock in negotiation?': { prompt: 'Qu\'est-ce qu\'une impasse en négociation ?', options: ['Quand les deux parties s\'entendent trop vite', 'Quand aucune des parties n\'est prête à bouger davantage', 'Quand les négociations commencent bien', 'Quand un médiateur est présent'], correctAnswer: 'Quand aucune des parties n\'est prête à bouger davantage' },
  'Deadlocks always mean the negotiation has permanently failed.': { prompt: 'Les impasses signifient toujours que la négociation a échoué définitivement.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Which technique can help break a deadlock?': { prompt: 'Quelle technique peut aider à briser une impasse ?', options: ['Répéter votre dernière offre plus fort', 'Changer le cadre de négociation ou introduire de nouvelles variables', 'Partir définitivement', 'Menacer d\'une action en justice immédiatement'], correctAnswer: 'Changer le cadre de négociation ou introduire de nouvelles variables' },
  'Bringing in a neutral ___ can help resolve deadlocks between two parties.': { prompt: 'Faire intervenir un ___ neutre peut aider à résoudre les impasses entre deux parties.', options: ['Médiateur', 'Concurrent', 'Avocat', 'Investisseur'], correctAnswer: 'Médiateur' },
  'Taking a break during a deadlock can be productive.': { prompt: 'Prendre une pause pendant une impasse peut être productif.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A "cooling off period" in a deadlock refers to:': { prompt: 'Une « période de refroidissement » dans une impasse fait référence à :', options: ['Baisser la climatisation', 'Une pause planifiée pour réduire les émotions et réévaluer', 'Mettre fin définitivement aux négociations', 'Faire venir un négociateur de remplacement'], correctAnswer: 'Une pause planifiée pour réduire les émotions et réévaluer' },
  'Escalating to higher-level decision makers is sometimes necessary to break deadlocks.': { prompt: 'Escalader vers des décideurs de niveau supérieur est parfois nécessaire pour briser les impasses.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which approach is counterproductive during a deadlock?': { prompt: 'Quelle approche est contre-productive pendant une impasse ?', options: ['Explorer les intérêts sous-jacents', 'Émettre des ultimatums et des menaces', 'Suggérer une séance de remue-méninges', 'Proposer un accord partiel sur les points résolus'], correctAnswer: 'Émettre des ultimatums et des menaces' },

  // Salary Negotiation
  'When is the best time to negotiate salary?': { prompt: 'Quel est le meilleur moment pour négocier le salaire ?', options: ['Pendant le premier entretien', 'Après avoir reçu une offre formelle', 'Le premier jour de travail', 'Après avoir été refusé'], correctAnswer: 'Après avoir reçu une offre formelle' },
  'You should always accept the first salary offer a company makes.': { prompt: 'Vous devriez toujours accepter la première offre salariale d\'une entreprise.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Before negotiating salary, you should research the market ___ for your role and location.': { prompt: 'Avant de négocier le salaire, vous devriez rechercher le ___ du marché pour votre rôle et votre emplacement.', options: ['Taux', 'Tendance', 'Historique', 'Moyenne'], correctAnswer: 'Taux' },
  'If salary is fixed, what else can you negotiate?': { prompt: 'Si le salaire est fixe, que d\'autre pouvez-vous négocier ?', options: ['Rien — le salaire c\'est tout', 'Prime de signature, jours de vacances, télétravail, options d\'actions', 'Seulement le titre du poste', 'L\'adresse de l\'entreprise'], correctAnswer: 'Prime de signature, jours de vacances, télétravail, options d\'actions' },
  'Sharing your current salary is always required during negotiation.': { prompt: 'Partager votre salaire actuel est toujours requis pendant la négociation.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'How should you frame a salary counter offer?': { prompt: 'Comment devriez-vous formuler une contre-offre salariale ?', options: ['J\'ai besoin de plus d\'argent pour mes dépenses personnelles', 'Basé sur mes recherches, les données du marché et la valeur que j\'apporte, j\'aimerais discuter d\'une fourchette de...', 'Je n\'accepterai que le double de votre offre', 'Ce que vous pensez être juste'], correctAnswer: 'Basé sur mes recherches, les données du marché et la valeur que j\'apporte, j\'aimerais discuter d\'une fourchette de...' },
  'Negotiating salary can get a job offer rescinded in most professional settings.': { prompt: 'Négocier le salaire peut faire retirer une offre d\'emploi dans la plupart des contextes professionnels.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'What is the advantage of giving a salary range instead of a single number?': { prompt: 'Quel est l\'avantage de donner une fourchette salariale plutôt qu\'un seul chiffre ?', options: ['Cela montre que vous êtes incertain', 'Cela ancre haut tout en paraissant flexible', 'Cela résulte toujours au chiffre le plus bas', 'Les employeurs préfèrent les fourchettes aux chiffres précis'], correctAnswer: 'Cela ancre haut tout en paraissant flexible' },

  // Car Buying
  'What should you research before negotiating at a car dealership?': { prompt: 'Que devriez-vous rechercher avant de négocier chez un concessionnaire automobile ?', options: ['La vie personnelle du vendeur', 'Le prix facture et la juste valeur marchande du véhicule', 'La couleur de la salle d\'exposition', 'Rien — faites confiance au vendeur'], correctAnswer: 'Le prix facture et la juste valeur marchande du véhicule' },
  'The sticker price (MSRP) on a new car is always the final price.': { prompt: 'Le prix affiché (PDSF) sur une voiture neuve est toujours le prix final.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'When should you discuss your trade-in vehicle?': { prompt: 'Quand devriez-vous discuter de votre véhicule d\'échange ?', options: ['En premier, avant de discuter du prix de la nouvelle voiture', 'Après avoir réglé le prix de la nouvelle voiture', 'Pendant l\'essai routier', 'Ne jamais le mentionner'], correctAnswer: 'Après avoir réglé le prix de la nouvelle voiture' },
  'Getting pre-approved for financing before visiting a dealer gives you ___ power.': { prompt: 'Obtenir un préapprobation de financement avant de visiter un concessionnaire vous donne du pouvoir de ___.', options: ['Négociation', 'Légal', 'Physique', 'Social'], correctAnswer: 'Négociation' },
  'End of month is often a better time to buy because dealers need to hit sales quotas.': { prompt: 'La fin du mois est souvent un meilleur moment pour acheter car les concessionnaires doivent atteindre leurs quotas de ventes.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is the "four-square" method dealers use?': { prompt: 'Qu\'est-ce que la méthode « quatre carrés » utilisée par les concessionnaires ?', options: ['Un arrangement de sièges', 'Une feuille de calcul qui confond les acheteurs en regroupant prix, échange, mise de fonds et paiement mensuel', 'Un programme de fidélité', 'Un type de modèle de voiture'], correctAnswer: 'Une feuille de calcul qui confond les acheteurs en regroupant prix, échange, mise de fonds et paiement mensuel' },
  'Walking away from a deal is a legitimate and powerful negotiation tactic at a dealership.': { prompt: 'Partir d\'une offre est une tactique de négociation légitime et puissante chez un concessionnaire.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Why is it effective to negotiate via email with multiple dealers?': { prompt: 'Pourquoi est-il efficace de négocier par courriel avec plusieurs concessionnaires ?', options: ['Les concessionnaires ne peuvent pas utiliser de tactiques de pression par courriel', 'Cela crée de la compétition entre les concessionnaires pour votre affaire', 'Le courriel est juridiquement contraignant', 'Les concessionnaires donnent de plus gros rabais les fins de semaine'], correctAnswer: 'Cela crée de la compétition entre les concessionnaires pour votre affaire' },

  // Real Estate Deals
  'What is "earnest money" in a real estate negotiation?': { prompt: 'Qu\'est-ce que l\'« arrhes » dans une négociation immobilière ?', options: ['Le paiement final à la clôture', 'Un dépôt montrant que vous êtes sérieux à propos de l\'achat', 'La commission de l\'agent', 'Une pénalité pour se retirer'], correctAnswer: 'Un dépôt montrant que vous êtes sérieux à propos de l\'achat' },
  'In a buyer\'s market, buyers have more negotiating power.': { prompt: 'Dans un marché d\'acheteurs, les acheteurs ont plus de pouvoir de négociation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A home ___ gives buyers leverage by revealing the property\'s true condition and needed repairs.': { prompt: 'Une ___ domiciliaire donne aux acheteurs un levier en révélant l\'état réel de la propriété et les réparations nécessaires.', options: ['Inspection', 'Inscription', 'Visite', 'Mise en scène'], correctAnswer: 'Inspection' },
  'What is a common seller counter-tactic to multiple low offers?': { prompt: 'Quelle est une contre-tactique courante du vendeur face à plusieurs offres basses ?', options: ['Accepter l\'offre la plus basse', 'Fixer une échéance pour les offres « meilleures et finales »', 'Retirer la maison du marché', 'Baisser immédiatement le prix demandé'], correctAnswer: 'Fixer une échéance pour les offres « meilleures et finales »' },
  'Contingencies in a real estate contract protect the buyer.': { prompt: 'Les conditions dans un contrat immobilier protègent l\'acheteur.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Why might a cash offer beat a higher financed offer?': { prompt: 'Pourquoi une offre comptant pourrait-elle battre une offre financée plus élevée ?', options: ['Le comptant est illégal en immobilier', 'Le comptant clôture plus vite avec moins de risques d\'échec', 'Les offres comptant sont exonérées d\'impôt', 'Les banques préfèrent les transactions comptant'], correctAnswer: 'Le comptant clôture plus vite avec moins de risques d\'échec' },
  'Waiving all contingencies is a smart strategy for first-time buyers.': { prompt: 'Renoncer à toutes les conditions est une stratégie intelligente pour les premiers acheteurs.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'What negotiation leverage do you gain from a low appraisal?': { prompt: 'Quel levier de négociation obtenez-vous d\'une évaluation basse ?', options: ['Aucun — les évaluations sont sans importance', 'Vous pouvez renégocier le prix à la valeur évaluée', 'Le vendeur doit payer vos frais de clôture', 'Vous obtenez automatiquement la maison gratuitement'], correctAnswer: 'Vous pouvez renégocier le prix à la valeur évaluée' },

  // Vendor Contracts
  'What is the most important clause to negotiate in a vendor contract?': { prompt: 'Quelle est la clause la plus importante à négocier dans un contrat fournisseur ?', options: ['La police du document', 'Les clauses de résiliation et de sortie', 'L\'historique de l\'entreprise du fournisseur', 'La qualité du papier du contrat'], correctAnswer: 'Les clauses de résiliation et de sortie' },
  'Volume discounts are a common leverage point in vendor negotiations.': { prompt: 'Les rabais de volume sont un levier courant dans les négociations avec les fournisseurs.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is an SLA in a vendor contract?': { prompt: 'Qu\'est-ce qu\'un SLA dans un contrat fournisseur ?', options: ['Accord de prospect de vente', 'Accord de niveau de service', 'Arrangement juridique standard', 'Évaluation de logistique d\'approvisionnement'], correctAnswer: 'Accord de niveau de service' },
  'A "most favored ___ " clause ensures you get the best price the vendor offers any customer.': { prompt: 'Une clause de « ___ le plus favorisé » garantit que vous obtenez le meilleur prix que le fournisseur offre à tout client.', options: ['Client', 'Nation', 'Fournisseur', 'Employé'], correctAnswer: 'Client' },
  'Auto-renewal clauses always benefit the buyer.': { prompt: 'Les clauses de renouvellement automatique profitent toujours à l\'acheteur.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'When negotiating with a sole-source vendor, how can you create leverage?': { prompt: 'Lors de la négociation avec un fournisseur unique, comment pouvez-vous créer un levier ?', options: ['Vous ne pouvez pas — ils ont tout le pouvoir', 'Démontrer que vous évaluez des solutions alternatives ou construisez en interne', 'Accepter les conditions qu\'ils offrent', 'Menacer de poursuivre immédiatement'], correctAnswer: 'Démontrer que vous évaluez des solutions alternatives ou construisez en interne' },
  'Payment terms (net 30, net 60) are negotiable elements of vendor contracts.': { prompt: 'Les conditions de paiement (net 30, net 60) sont des éléments négociables des contrats fournisseurs.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Why should you negotiate a price escalation cap?': { prompt: 'Pourquoi devriez-vous négocier un plafond d\'augmentation de prix ?', options: ['Pour garantir des services gratuits', 'Pour limiter combien le fournisseur peut augmenter les prix annuellement', 'Pour obtenir un support illimité', 'Pour éviter de signer le contrat'], correctAnswer: 'Pour limiter combien le fournisseur peut augmenter les prix annuellement' },

  // Hostage Tactics
  'What is the core principle behind hostage negotiation tactics adapted for business?': { prompt: 'Quel est le principe fondamental des tactiques de négociation d\'otages adaptées aux affaires ?', options: ['Utiliser les menaces et l\'intimidation', 'Construire un rapport et une confiance pour influencer le comportement', 'Toujours céder aux demandes', 'Négocier uniquement par l\'intermédiaire d\'avocats'], correctAnswer: 'Construire un rapport et une confiance pour influencer le comportement' },
  'Chris Voss, a former FBI hostage negotiator, advocates using tactical empathy in business negotiations.': { prompt: 'Chris Voss, un ancien négociateur d\'otages du FBI, préconise l\'utilisation de l\'empathie tactique dans les négociations d\'affaires.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is a "calibrated question"?': { prompt: 'Qu\'est-ce qu\'une « question calibrée » ?', options: ['Une question avec une réponse mathématique', 'Une question ouverte « comment » ou « quoi » conçue pour que l\'autre partie résolve votre problème', 'Une question oui ou non posée calmement', 'Une question posée au moment exact'], correctAnswer: 'Une question ouverte « comment » ou « quoi » conçue pour que l\'autre partie résolve votre problème' },
  'The "late-night FM DJ ___" is a calm, slow tone used to build authority and trust.': { prompt: 'La « ___ d\'animateur FM de nuit » est un ton calme et lent utilisé pour bâtir l\'autorité et la confiance.', options: ['Voix', 'Musique', 'Émission', 'Style'], correctAnswer: 'Voix' },
  'In hostage negotiation tactics, "no" is considered more valuable than "yes" as a starting point.': { prompt: 'Dans les tactiques de négociation d\'otages, « non » est considéré comme plus précieux que « oui » comme point de départ.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What does "tactical empathy" mean?': { prompt: 'Que signifie « empathie tactique » ?', options: ['Faire semblant de se soucier de quelqu\'un', 'Comprendre les sentiments et la perspective de l\'autre partie pour influencer le résultat', 'Être émotif pendant la négociation', 'Être tellement empathique qu\'on cède'], correctAnswer: 'Comprendre les sentiments et la perspective de l\'autre partie pour influencer le résultat' },
  'An accusation audit pre-empts the other party\'s objections by listing them first.': { prompt: 'Un audit d\'accusations devance les objections de l\'autre partie en les énumérant en premier.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Why is "That\'s right" a more powerful response than "You\'re right" in negotiation?': { prompt: 'Pourquoi « C\'est exact » est-il une réponse plus puissante que « Vous avez raison » en négociation ?', options: ['Ils signifient la même chose', '« C\'est exact » signifie qu\'ils se sentent compris ; « Vous avez raison » signifie qu\'ils veulent que vous arrêtiez de parler', '« Vous avez raison » est toujours sincère', '« C\'est exact » est grammaticalement correct'], correctAnswer: '« C\'est exact » signifie qu\'ils se sentent compris ; « Vous avez raison » signifie qu\'ils veulent que vous arrêtiez de parler' },
};
