export const negotiationEs: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // Negotiation 101
  'What is the primary goal of a negotiation?': { prompt: '¿Cuál es el objetivo principal de una negociación?', options: ['Derrotar a la otra parte', 'Llegar a un acuerdo mutuamente aceptable', 'Evitar el conflicto por completo', 'Hacer la primera concesión'], correctAnswer: 'Llegar a un acuerdo mutuamente aceptable' },
  'Negotiation only happens in formal business settings.': { prompt: 'La negociación solo ocurre en entornos formales de negocios.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Which of these is a distributive negotiation?': { prompt: '¿Cuál de estos es una negociación distributiva?', options: ['Dos empresas formando una empresa conjunta', 'Regatear el precio de un auto usado', 'Generar ideas para nuevos productos juntos', 'Mediar una disputa laboral'], correctAnswer: 'Regatear el precio de un auto usado' },
  'In negotiation, your "___" is the range between your ideal outcome and your walk-away point.': { prompt: 'En negociación, tu "___" es el rango entre tu resultado ideal y tu punto de retiro.', options: ['BATNA', 'Zona de negociación', 'Ancla', 'Precio de reserva'], correctAnswer: 'Zona de negociación' },
  'Integrative negotiation seeks to expand value for all parties.': { prompt: 'La negociación integrativa busca expandir el valor para todas las partes.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'What does ZOPA stand for?': { prompt: '¿Qué significa ZOPA?', options: ['Zona de Acuerdo Posible', 'Ajuste de Precio de Opción Cero', 'Zona de Acción Primaria', 'Análisis de Probabilidad de Resultado Cero'], correctAnswer: 'Zona de Acuerdo Posible' },
  'Preparation is considered the most important phase of negotiation.': { prompt: 'La preparación se considera la fase más importante de la negociación.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Which negotiation style focuses on maintaining the relationship above all?': { prompt: '¿Qué estilo de negociación se enfoca en mantener la relación por encima de todo?', options: ['Competitivo', 'Acomodaticio', 'Evasivo', 'Compromiso'], correctAnswer: 'Acomodaticio' },

  // BATNA
  'What does BATNA stand for?': { prompt: '¿Qué significa BATNA?', options: ['Mejor Alternativa a un Acuerdo Negociado', 'Términos Básicos para Enfoque de Negociación', 'Acuerdo Bilateral para Negociación Comercial', 'Mejor Objetivo Alcanzable en Análisis de Negociación'], correctAnswer: 'Mejor Alternativa a un Acuerdo Negociado' },
  'A strong BATNA gives you more power in a negotiation.': { prompt: 'Un BATNA fuerte te da más poder en una negociación.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'When should you reveal your BATNA?': { prompt: '¿Cuándo deberías revelar tu BATNA?', options: ['Siempre al inicio', 'Solo cuando fortalece tu posición', 'Nunca bajo ninguna circunstancia', 'Solo por escrito'], correctAnswer: 'Solo cuando fortalece tu posición' },
  'Your ___ price is the worst deal you would still accept before walking away.': { prompt: 'Tu precio ___ es el peor trato que aceptarías antes de retirarte.', options: ['De reserva', 'Pedido', 'De mercado', 'De apertura'], correctAnswer: 'De reserva' },
  'You should accept any deal that is better than your BATNA.': { prompt: 'Deberías aceptar cualquier trato que sea mejor que tu BATNA.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'How can you improve your BATNA?': { prompt: '¿Cómo puedes mejorar tu BATNA?', options: ['Ignorar alternativas y enfocarte en un solo trato', 'Desarrollar múltiples alternativas sólidas antes de negociar', 'Aceptar la primera oferta rápidamente', 'Evitar investigar el mercado'], correctAnswer: 'Desarrollar múltiples alternativas sólidas antes de negociar' },
  'If you have no BATNA, you are in a very weak negotiating position.': { prompt: 'Si no tienes BATNA, estás en una posición de negociación muy débil.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Who introduced the concept of BATNA?': { prompt: '¿Quién introdujo el concepto de BATNA?', options: ['Daniel Kahneman', 'Roger Fisher y William Ury', 'Robert Cialdini', 'Dale Carnegie'], correctAnswer: 'Roger Fisher y William Ury' },

  // Anchoring
  'What is anchoring in negotiation?': { prompt: '¿Qué es el anclaje en negociación?', options: ['Negarse a moverse de tu posición', 'Establecer un punto de referencia inicial que influye en el resultado', 'Aceptar todo lo que la otra parte dice', 'Retirarse de la mesa de negociación'], correctAnswer: 'Establecer un punto de referencia inicial que influye en el resultado' },
  'The party who makes the first offer usually has an advantage due to anchoring.': { prompt: 'La parte que hace la primera oferta generalmente tiene una ventaja debido al anclaje.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'How should you counter an aggressive anchor?': { prompt: '¿Cómo deberías contrarrestar un ancla agresiva?', options: ['Aceptarla como justa', 'Ignorarla y poner tu propia ancla', 'Irte inmediatamente', 'Dividir la diferencia de inmediato'], correctAnswer: 'Ignorarla y poner tu propia ancla' },
  'An effective anchor should be ___ but still justifiable with reasoning.': { prompt: 'Un ancla efectiva debería ser ___ pero aún justificable con razonamiento.', options: ['Agresiva', 'Moderada', 'Baja', 'Aleatoria'], correctAnswer: 'Agresiva' },
  'Anchoring only works with numbers and prices.': { prompt: 'El anclaje solo funciona con números y precios.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'A car dealer lists a car at $30,000 knowing they will accept $25,000. The $30,000 is:': { prompt: 'Un concesionario lista un auto en $30,000 sabiendo que aceptará $25,000. Los $30,000 son:', options: ['El precio de reserva', 'El BATNA', 'El ancla', 'La ZOPA'], correctAnswer: 'El ancla' },
  'You should always make the first offer to set the anchor.': { prompt: 'Siempre deberías hacer la primera oferta para establecer el ancla.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Which cognitive bias makes anchoring effective?': { prompt: '¿Qué sesgo cognitivo hace efectivo el anclaje?', options: ['Sesgo de confirmación', 'Sesgo de anclaje — ajuste insuficiente desde valores iniciales', 'Efecto Dunning-Kruger', 'Sesgo retrospectivo'], correctAnswer: 'Sesgo de anclaje — ajuste insuficiente desde valores iniciales' },

  // Win-Win
  'What characterizes a win-win negotiation outcome?': { prompt: '¿Qué caracteriza un resultado de negociación ganar-ganar?', options: ['Ambas partes se comprometen por igual', 'Ambas partes sienten que ganaron valor', 'Una parte gana más que la otra', 'Ninguna parte obtiene lo que quiere'], correctAnswer: 'Ambas partes sienten que ganaron valor' },
  'Win-win outcomes require both parties to have identical interests.': { prompt: 'Los resultados ganar-ganar requieren que ambas partes tengan intereses idénticos.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Which technique best supports win-win negotiation?': { prompt: '¿Qué técnica apoya mejor la negociación ganar-ganar?', options: ['Amenazar con retirarse', 'Explorar los intereses subyacentes en lugar de las posiciones', 'Dividir todo 50/50', 'Ocultar tus prioridades'], correctAnswer: 'Explorar los intereses subyacentes en lugar de las posiciones' },
  'Logrolling is a win-win technique where parties trade concessions on different issues.': { prompt: 'El logrolling es una técnica ganar-ganar donde las partes intercambian concesiones sobre diferentes temas.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Expanding the ___ means finding ways to create more total value before dividing it.': { prompt: 'Expandir el ___ significa encontrar formas de crear más valor total antes de dividirlo.', options: ['Pastel', 'Presupuesto', 'Plazo', 'Equipo'], correctAnswer: 'Pastel' },
  'Two sisters fight over one orange. A win-win solution reveals that one wants the juice and the other wants the peel. This illustrates:': { prompt: 'Dos hermanas pelean por una naranja. Una solución ganar-ganar revela que una quiere el jugo y la otra la cáscara. Esto ilustra:', options: ['Anclaje', 'Negociación basada en posiciones vs intereses', 'Dinámicas de poder', 'Análisis BATNA'], correctAnswer: 'Negociación basada en posiciones vs intereses' },
  'Win-win negotiation is always possible in every situation.': { prompt: 'La negociación ganar-ganar siempre es posible en toda situación.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Which book popularized the concept of principled, win-win negotiation?': { prompt: '¿Qué libro popularizó el concepto de negociación principista ganar-ganar?', options: ['El Arte de la Guerra', 'Getting to Yes', 'Never Split the Difference', 'Las 48 leyes del poder'], correctAnswer: 'Getting to Yes' },

  // Power Dynamics
  'Which factor most increases your negotiating power?': { prompt: '¿Qué factor aumenta más tu poder de negociación?', options: ['Ser mayor que tu contraparte', 'Tener alternativas sólidas (BATNA)', 'Hablar más fuerte', 'Llegar temprano a la reunión'], correctAnswer: 'Tener alternativas sólidas (BATNA)' },
  'The party with more information always has more power in a negotiation.': { prompt: 'La parte con más información siempre tiene más poder en una negociación.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Legitimate power comes from ___, titles, or recognized authority.': { prompt: 'El poder legítimo viene de ___, títulos o autoridad reconocida.', options: ['Posiciones', 'Dinero', 'Amenazas', 'Silencio'], correctAnswer: 'Posiciones' },
  'How can a weaker party increase their negotiating power?': { prompt: '¿Cómo puede una parte más débil aumentar su poder de negociación?', options: ['Blufear sobre sus alternativas', 'Formar coaliciones con otras partes interesadas', 'Aceptar la primera oferta', 'Evitar la preparación'], correctAnswer: 'Formar coaliciones con otras partes interesadas' },
  'Time pressure always hurts the negotiator under deadline.': { prompt: 'La presión del tiempo siempre perjudica al negociador bajo plazo.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'What is "referent power" in negotiation?': { prompt: '¿Qué es el "poder referente" en negociación?', options: ['Poder de contratos legales', 'Poder de ser querido o respetado', 'Poder de recursos financieros', 'Poder de presencia física'], correctAnswer: 'Poder de ser querido o respetado' },
  'Perceived power is as influential as actual power in negotiation.': { prompt: 'El poder percibido es tan influyente como el poder real en la negociación.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Which tactic shifts power by creating urgency?': { prompt: '¿Qué táctica cambia el poder creando urgencia?', options: ['Escucha activa', 'Establecer una fecha límite', 'Espejeo', 'Hacer preguntas abiertas'], correctAnswer: 'Establecer una fecha límite' },

  // Active Listening
  'What is the primary purpose of active listening in negotiation?': { prompt: '¿Cuál es el propósito principal de la escucha activa en negociación?', options: ['Encontrar debilidades para explotar', 'Comprender completamente las necesidades y preocupaciones de la otra parte', 'Ganar tiempo mientras piensas una respuesta', 'Parecer educado'], correctAnswer: 'Comprender completamente las necesidades y preocupaciones de la otra parte' },
  'Paraphrasing what the other party said is a key active listening technique.': { prompt: 'Parafrasear lo que la otra parte dijo es una técnica clave de escucha activa.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Which response demonstrates active listening?': { prompt: '¿Qué respuesta demuestra escucha activa?', options: ['Eso está mal, déjame explicarte por qué', 'Entonces, lo que dices es que necesitas flexibilidad en los plazos?', 'Ya sé lo que quieres decir', '¿Podemos avanzar?'], correctAnswer: 'Entonces, lo que dices es que necesitas flexibilidad en los plazos?' },
  'Labeling emotions means saying things like "It sounds like you\'re ___ about the deadline."': { prompt: 'Etiquetar emociones significa decir cosas como "Parece que estás ___ por la fecha límite."', options: ['Frustrado', 'Contento', 'Equivocado', 'Mintiendo'], correctAnswer: 'Frustrado' },
  'Silence can be an effective active listening tool in negotiation.': { prompt: 'El silencio puede ser una herramienta de escucha activa efectiva en negociación.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Chris Voss\'s "mirroring" technique involves:': { prompt: 'La técnica de "espejeo" de Chris Voss consiste en:', options: ['Copiar exactamente el lenguaje corporal', 'Repetir las últimas 1-3 palabras que la otra persona dijo', 'Mantener contacto visual directo sin parpadear', 'Vestirse de manera similar a tu contraparte'], correctAnswer: 'Repetir las últimas 1-3 palabras que la otra persona dijo' },
  'Active listening means agreeing with everything the other party says.': { prompt: 'La escucha activa significa estar de acuerdo con todo lo que la otra parte dice.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Which question type promotes deeper conversation?': { prompt: '¿Qué tipo de pregunta promueve una conversación más profunda?', options: ['Preguntas de sí o no', 'Preguntas abiertas que empiezan con "cómo" o "qué"', 'Preguntas sugestivas', 'Preguntas retóricas'], correctAnswer: 'Preguntas abiertas que empiezan con "cómo" o "qué"' },

  // Reading the Room
  'What does "reading the room" mean in negotiation?': { prompt: '¿Qué significa "leer la sala" en negociación?', options: ['Contar cuántas personas están presentes', 'Evaluar el clima emocional y las dinámicas no expresadas', 'Leer los documentos sobre la mesa', 'Revisar la sala en busca de dispositivos de grabación'], correctAnswer: 'Evaluar el clima emocional y las dinámicas no expresadas' },
  'Crossed arms always mean the other party is hostile.': { prompt: 'Los brazos cruzados siempre significan que la otra parte es hostil.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'When someone leans ___ during your proposal, it often signals interest or engagement.': { prompt: 'Cuando alguien se inclina ___ durante tu propuesta, a menudo señala interés o compromiso.', options: ['Hacia adelante', 'Hacia atrás', 'De lado', 'Lejos'], correctAnswer: 'Hacia adelante' },
  'You notice your counterpart keeps glancing at their watch. What does this likely signal?': { prompt: 'Notas que tu contraparte sigue mirando su reloj. ¿Qué señala esto probablemente?', options: ['Está de acuerdo con todo', 'Tiene presión de tiempo o está perdiendo interés', 'Está grabando la reunión', 'Está calculando números'], correctAnswer: 'Tiene presión de tiempo o está perdiendo interés' },
  'The tone of voice can communicate more than the actual words spoken.': { prompt: 'El tono de voz puede comunicar más que las palabras reales dichas.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'In a team negotiation, you should pay most attention to:': { prompt: 'En una negociación de equipo, deberías prestar más atención a:', options: ['Solo el negociador principal', 'La persona que habla más fuerte', 'El tomador de decisiones silencioso en la sala', 'La persona más cercana a la puerta'], correctAnswer: 'El tomador de decisiones silencioso en la sala' },
  'A sudden shift to small talk may indicate the other party needs a mental break from tense topics.': { prompt: 'Un cambio repentino a charla casual puede indicar que la otra parte necesita un descanso mental de los temas tensos.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'What should you do when you sense frustration rising in the room?': { prompt: '¿Qué deberías hacer cuando sientes que la frustración aumenta en la sala?', options: ['Presionar más fuerte tus demandas', 'Reconocer la tensión y sugerir un breve descanso', 'Ignorarlo y seguir presentando', 'Salir de la sala inmediatamente'], correctAnswer: 'Reconocer la tensión y sugerir un breve descanso' },

  // Making Offers
  'What makes a strong opening offer?': { prompt: '¿Qué hace una buena oferta de apertura?', options: ['Es tu línea mínima absoluta', 'Es ambiciosa pero justificable con datos', 'Es exactamente lo que esperas obtener', 'Es menor de lo que quieres'], correctAnswer: 'Es ambiciosa pero justificable con datos' },
  'You should always let the other party make the first offer.': { prompt: 'Siempre deberías dejar que la otra parte haga la primera oferta.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What is a "package offer"?': { prompt: '¿Qué es una "oferta paquete"?', options: ['Una oferta entregada en una caja', 'Una propuesta agrupada que cubre múltiples temas a la vez', 'Una oferta que expira en 24 horas', 'Una oferta hecha a múltiples partes simultáneamente'], correctAnswer: 'Una propuesta agrupada que cubre múltiples temas a la vez' },
  'An "exploding offer" is one that ___ if not accepted by a certain deadline.': { prompt: 'Una "oferta explosiva" es una que ___ si no se acepta antes de cierta fecha límite.', options: ['Expira', 'Se duplica', 'Mejora', 'Se repite'], correctAnswer: 'Expira' },
  'Making an offer with precise numbers (e.g., $5,125) can be more effective than round numbers ($5,000).': { prompt: 'Hacer una oferta con números precisos (ej. $5,125) puede ser más efectivo que números redondos ($5,000).', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'When presenting your offer, you should:': { prompt: 'Al presentar tu oferta, deberías:', options: ['Disculparte por pedir demasiado', 'Presentarla con confianza y fundamentos sólidos', 'Decir "tómalo o déjalo"', 'Murmurarla rápidamente'], correctAnswer: 'Presentarla con confianza y fundamentos sólidos' },
  'Presenting multiple equivalent offers simultaneously (MESOs) increases the chance of agreement.': { prompt: 'Presentar múltiples ofertas equivalentes simultáneamente (MESOs) aumenta la probabilidad de acuerdo.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'What is the risk of making an extremely aggressive first offer?': { prompt: '¿Cuál es el riesgo de hacer una primera oferta extremadamente agresiva?', options: ['La otra parte siempre aceptará', 'Puede dañar la confianza y hacer que la otra parte se retire', 'Muestra debilidad', 'No tiene ningún riesgo'], correctAnswer: 'Puede dañar la confianza y hacer que la otra parte se retire' },

  // Counter Offers
  'What is the best first step after receiving an offer?': { prompt: '¿Cuál es el mejor primer paso después de recibir una oferta?', options: ['Aceptar inmediatamente si es razonable', 'Rechazarla de plano', 'Tomarse tiempo para evaluar antes de responder', 'Hacer una contraoferta igualmente extrema'], correctAnswer: 'Tomarse tiempo para evaluar antes de responder' },
  'A counter offer automatically rejects the original offer.': { prompt: 'Una contraoferta rechaza automáticamente la oferta original.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'The "___" strategy involves making your counter offer with a detailed justification.': { prompt: 'La estrategia "___" implica hacer tu contraoferta con una justificación detallada.', options: ['Razonada', 'Silenciosa', 'Agresiva', 'Pasiva'], correctAnswer: 'Razonada' },
  'What should a counter offer signal to the other party?': { prompt: '¿Qué debería señalar una contraoferta a la otra parte?', options: ['Que no eres serio en la negociación', 'Que quieres un trato diferente pero estás dispuesto a trabajar hacia un acuerdo', 'Que estás desesperado', 'Que no tienes alternativas'], correctAnswer: 'Que quieres un trato diferente pero estás dispuesto a trabajar hacia un acuerdo' },
  'You should always counter offer exactly halfway between your position and theirs.': { prompt: 'Siempre deberías contraofertar exactamente a mitad de camino entre tu posición y la suya.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'How can you soften a counter offer?': { prompt: '¿Cómo puedes suavizar una contraoferta?', options: ['Agregar una amenaza', 'Reconocer el mérito de su oferta antes de presentar la tuya', 'Usar lenguaje agresivo', 'Negarte a explicar tu razonamiento'], correctAnswer: 'Reconocer el mérito de su oferta antes de presentar la tuya' },
  'Making three concessions in a row without getting anything back is a strong strategy.': { prompt: 'Hacer tres concesiones seguidas sin obtener nada a cambio es una estrategia fuerte.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'The "Ackerman model" for counter offers involves:': { prompt: 'El "modelo Ackerman" para contraoferta implica:', options: ['Empezar al 100% y nunca moverse', 'Ofrecer incrementos decrecientes (65%, 85%, 95%, 100%)', 'Siempre dividir la diferencia', 'Hacer solo una contraoferta'], correctAnswer: 'Ofrecer incrementos decrecientes (65%, 85%, 95%, 100%)' },

  // Concessions
  'What is the golden rule of concessions?': { prompt: '¿Cuál es la regla de oro de las concesiones?', options: ['Nunca hacer concesiones', 'Siempre igualar las concesiones', 'Cada concesión debería intercambiarse por algo a cambio', 'Hacer todas las concesiones al principio'], correctAnswer: 'Cada concesión debería intercambiarse por algo a cambio' },
  'Making large concessions early signals desperation.': { prompt: 'Hacer grandes concesiones temprano señala desesperación.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Concessions should get ___ over time to signal you are approaching your limit.': { prompt: 'Las concesiones deberían volverse ___ con el tiempo para señalar que te acercas a tu límite.', options: ['Más pequeñas', 'Más grandes', 'Más rápidas', 'Más fuertes'], correctAnswer: 'Más pequeñas' },
  'What is "nibbling" in negotiation?': { prompt: '¿Qué es el "mordisqueo" en negociación?', options: ['Comer durante las negociaciones', 'Pedir pequeños extras después de que se acuerda el trato principal', 'Hacer la primera oferta', 'Rechazar todas las concesiones'], correctAnswer: 'Pedir pequeños extras después de que se acuerda el trato principal' },
  'Labeling your concessions increases their perceived value.': { prompt: 'Etiquetar tus concesiones aumenta su valor percibido.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'You should concede on items that:': { prompt: 'Deberías conceder en elementos que:', options: ['Son los más importantes para ti', 'Te cuestan poco pero son valiosos para la otra parte', 'La otra parte no ha pedido', 'Son completamente irrelevantes'], correctAnswer: 'Te cuestan poco pero son valiosos para la otra parte' },
  'Unconditional concessions build goodwill and encourage reciprocity.': { prompt: 'Las concesiones incondicionales generan buena voluntad y fomentan la reciprocidad.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What is the "door in the face" concession technique?': { prompt: '¿Qué es la técnica de concesión "portazo en la cara"?', options: ['Cerrar la puerta e irse', 'Empezar con una petición extrema, luego retroceder a lo que realmente quieres', 'Hacer tu petición real primero', 'Pedir menos de lo que quieres'], correctAnswer: 'Empezar con una petición extrema, luego retroceder a lo que realmente quieres' },

  // Deadlocks
  'What is a deadlock in negotiation?': { prompt: '¿Qué es un punto muerto en negociación?', options: ['Cuando ambas partes acuerdan demasiado rápido', 'Cuando ninguna parte está dispuesta a moverse más', 'Cuando las negociaciones comienzan bien', 'Cuando un mediador está presente'], correctAnswer: 'Cuando ninguna parte está dispuesta a moverse más' },
  'Deadlocks always mean the negotiation has permanently failed.': { prompt: 'Los puntos muertos siempre significan que la negociación ha fracasado permanentemente.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Which technique can help break a deadlock?': { prompt: '¿Qué técnica puede ayudar a romper un punto muerto?', options: ['Repetir tu última oferta más fuerte', 'Cambiar el marco de negociación o introducir nuevas variables', 'Irte permanentemente', 'Amenazar con acción legal inmediatamente'], correctAnswer: 'Cambiar el marco de negociación o introducir nuevas variables' },
  'Bringing in a neutral ___ can help resolve deadlocks between two parties.': { prompt: 'Traer un ___ neutral puede ayudar a resolver puntos muertos entre dos partes.', options: ['Mediador', 'Competidor', 'Abogado', 'Inversionista'], correctAnswer: 'Mediador' },
  'Taking a break during a deadlock can be productive.': { prompt: 'Tomar un descanso durante un punto muerto puede ser productivo.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'A "cooling off period" in a deadlock refers to:': { prompt: 'Un "período de enfriamiento" en un punto muerto se refiere a:', options: ['Bajar el aire acondicionado', 'Una pausa programada para reducir emociones y reevaluar', 'Terminar las negociaciones permanentemente', 'Traer un negociador de reemplazo'], correctAnswer: 'Una pausa programada para reducir emociones y reevaluar' },
  'Escalating to higher-level decision makers is sometimes necessary to break deadlocks.': { prompt: 'Escalar a tomadores de decisiones de nivel superior a veces es necesario para romper puntos muertos.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Which approach is counterproductive during a deadlock?': { prompt: '¿Qué enfoque es contraproducente durante un punto muerto?', options: ['Explorar intereses subyacentes', 'Emitir ultimátums y amenazas', 'Sugerir una sesión de lluvia de ideas', 'Proponer un acuerdo parcial sobre temas resueltos'], correctAnswer: 'Emitir ultimátums y amenazas' },

  // Salary Negotiation
  'When is the best time to negotiate salary?': { prompt: '¿Cuál es el mejor momento para negociar el salario?', options: ['Durante la primera entrevista', 'Después de recibir una oferta formal', 'En tu primer día de trabajo', 'Después de ser rechazado'], correctAnswer: 'Después de recibir una oferta formal' },
  'You should always accept the first salary offer a company makes.': { prompt: 'Siempre deberías aceptar la primera oferta salarial de una empresa.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'Before negotiating salary, you should research the market ___ for your role and location.': { prompt: 'Antes de negociar el salario, deberías investigar la ___ del mercado para tu rol y ubicación.', options: ['Tasa', 'Tendencia', 'Historia', 'Promedio'], correctAnswer: 'Tasa' },
  'If salary is fixed, what else can you negotiate?': { prompt: 'Si el salario es fijo, ¿qué más puedes negociar?', options: ['Nada — el salario es todo', 'Bono de firma, días de vacaciones, trabajo remoto, opciones de acciones', 'Solo el título del puesto', 'La dirección de la empresa'], correctAnswer: 'Bono de firma, días de vacaciones, trabajo remoto, opciones de acciones' },
  'Sharing your current salary is always required during negotiation.': { prompt: 'Compartir tu salario actual siempre es requerido durante la negociación.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'How should you frame a salary counter offer?': { prompt: '¿Cómo deberías enmarcar una contraoferta salarial?', options: ['Necesito más dinero para gastos personales', 'Basándome en mi investigación, datos del mercado y el valor que aporto, me gustaría discutir un rango de...', 'Solo aceptaré el doble de tu oferta', 'Lo que usted considere justo'], correctAnswer: 'Basándome en mi investigación, datos del mercado y el valor que aporto, me gustaría discutir un rango de...' },
  'Negotiating salary can get a job offer rescinded in most professional settings.': { prompt: 'Negociar el salario puede hacer que retiren una oferta de empleo en la mayoría de entornos profesionales.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What is the advantage of giving a salary range instead of a single number?': { prompt: '¿Cuál es la ventaja de dar un rango salarial en vez de un solo número?', options: ['Muestra que estás inseguro', 'Ancla alto mientras parece flexible', 'Siempre resulta en el número más bajo', 'Los empleadores prefieren rangos a números específicos'], correctAnswer: 'Ancla alto mientras parece flexible' },

  // Car Buying
  'What should you research before negotiating at a car dealership?': { prompt: '¿Qué deberías investigar antes de negociar en un concesionario?', options: ['La vida personal del vendedor', 'El precio de factura y el valor justo de mercado del auto', 'El color de la sala de exhibición', 'Nada — confía en el vendedor'], correctAnswer: 'El precio de factura y el valor justo de mercado del auto' },
  'The sticker price (MSRP) on a new car is always the final price.': { prompt: 'El precio de etiqueta (MSRP) de un auto nuevo siempre es el precio final.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'When should you discuss your trade-in vehicle?': { prompt: '¿Cuándo deberías discutir tu vehículo de intercambio?', options: ['Primero, antes de discutir el precio del auto nuevo', 'Después de acordar el precio del auto nuevo', 'Durante la prueba de manejo', 'Nunca mencionarlo'], correctAnswer: 'Después de acordar el precio del auto nuevo' },
  'Getting pre-approved for financing before visiting a dealer gives you ___ power.': { prompt: 'Obtener preaprobación de financiamiento antes de visitar un concesionario te da poder de ___.', options: ['Negociación', 'Legal', 'Físico', 'Social'], correctAnswer: 'Negociación' },
  'End of month is often a better time to buy because dealers need to hit sales quotas.': { prompt: 'El fin de mes a menudo es mejor momento para comprar porque los concesionarios necesitan cumplir cuotas de ventas.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'What is the "four-square" method dealers use?': { prompt: '¿Qué es el método de "cuatro cuadros" que usan los concesionarios?', options: ['Un arreglo de asientos', 'Una hoja que confunde a compradores agrupando precio, intercambio, enganche y pago mensual', 'Un programa de lealtad', 'Un tipo de modelo de auto'], correctAnswer: 'Una hoja que confunde a compradores agrupando precio, intercambio, enganche y pago mensual' },
  'Walking away from a deal is a legitimate and powerful negotiation tactic at a dealership.': { prompt: 'Retirarse de un trato es una táctica de negociación legítima y poderosa en un concesionario.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Why is it effective to negotiate via email with multiple dealers?': { prompt: '¿Por qué es efectivo negociar por correo electrónico con múltiples concesionarios?', options: ['Los concesionarios no pueden usar tácticas de presión por correo', 'Crea competencia entre los concesionarios por tu negocio', 'El correo es legalmente vinculante', 'Los concesionarios dan mayores descuentos los fines de semana'], correctAnswer: 'Crea competencia entre los concesionarios por tu negocio' },

  // Real Estate Deals
  'What is "earnest money" in a real estate negotiation?': { prompt: '¿Qué es el "depósito de buena fe" en una negociación inmobiliaria?', options: ['El pago final al cierre', 'Un depósito que muestra que eres serio sobre la compra', 'La comisión del agente', 'Una penalidad por retirarse'], correctAnswer: 'Un depósito que muestra que eres serio sobre la compra' },
  'In a buyer\'s market, buyers have more negotiating power.': { prompt: 'En un mercado de compradores, los compradores tienen más poder de negociación.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'A home ___ gives buyers leverage by revealing the property\'s true condition and needed repairs.': { prompt: 'Una ___ de la vivienda da ventaja a los compradores al revelar la verdadera condición y reparaciones necesarias.', options: ['Inspección', 'Publicación', 'Visita', 'Preparación'], correctAnswer: 'Inspección' },
  'What is a common seller counter-tactic to multiple low offers?': { prompt: '¿Cuál es una contratáctica común del vendedor ante múltiples ofertas bajas?', options: ['Aceptar la oferta más baja', 'Establecer una fecha límite para ofertas "mejores y finales"', 'Retirar la casa del mercado', 'Bajar el precio de venta inmediatamente'], correctAnswer: 'Establecer una fecha límite para ofertas "mejores y finales"' },
  'Contingencies in a real estate contract protect the buyer.': { prompt: 'Las contingencias en un contrato inmobiliario protegen al comprador.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Why might a cash offer beat a higher financed offer?': { prompt: '¿Por qué una oferta en efectivo podría ganarle a una oferta financiada más alta?', options: ['El efectivo es ilegal en bienes raíces', 'El efectivo cierra más rápido con menos riesgos de caerse', 'Las ofertas en efectivo están libres de impuestos', 'Los bancos prefieren transacciones en efectivo'], correctAnswer: 'El efectivo cierra más rápido con menos riesgos de caerse' },
  'Waiving all contingencies is a smart strategy for first-time buyers.': { prompt: 'Renunciar a todas las contingencias es una estrategia inteligente para compradores primerizos.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'What negotiation leverage do you gain from a low appraisal?': { prompt: '¿Qué ventaja de negociación obtienes de una tasación baja?', options: ['Ninguna — las tasaciones son irrelevantes', 'Puedes renegociar el precio al valor tasado', 'El vendedor debe pagar tus costos de cierre', 'Automáticamente obtienes la casa gratis'], correctAnswer: 'Puedes renegociar el precio al valor tasado' },

  // Vendor Contracts
  'What is the most important clause to negotiate in a vendor contract?': { prompt: '¿Cuál es la cláusula más importante a negociar en un contrato con proveedores?', options: ['La fuente del documento', 'Las cláusulas de terminación y salida', 'La historia de la empresa del proveedor', 'La calidad del papel del contrato'], correctAnswer: 'Las cláusulas de terminación y salida' },
  'Volume discounts are a common leverage point in vendor negotiations.': { prompt: 'Los descuentos por volumen son un punto de ventaja común en negociaciones con proveedores.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'What is an SLA in a vendor contract?': { prompt: '¿Qué es un SLA en un contrato con proveedores?', options: ['Acuerdo de Prospecto de Ventas', 'Acuerdo de Nivel de Servicio', 'Arreglo Legal Estándar', 'Evaluación de Logística de Suministro'], correctAnswer: 'Acuerdo de Nivel de Servicio' },
  'A "most favored ___ " clause ensures you get the best price the vendor offers any customer.': { prompt: 'Una cláusula de "___ más favorecido" asegura que obtengas el mejor precio que el proveedor ofrece a cualquier cliente.', options: ['Cliente', 'Nación', 'Proveedor', 'Empleado'], correctAnswer: 'Cliente' },
  'Auto-renewal clauses always benefit the buyer.': { prompt: 'Las cláusulas de renovación automática siempre benefician al comprador.', options: ['Verdadero', 'Falso'], correctAnswer: 'Falso' },
  'When negotiating with a sole-source vendor, how can you create leverage?': { prompt: 'Al negociar con un proveedor único, ¿cómo puedes crear ventaja?', options: ['No puedes — ellos tienen todo el poder', 'Demostrar que estás evaluando soluciones alternativas o construyendo internamente', 'Aceptar los términos que ofrecen', 'Amenazar con demandar inmediatamente'], correctAnswer: 'Demostrar que estás evaluando soluciones alternativas o construyendo internamente' },
  'Payment terms (net 30, net 60) are negotiable elements of vendor contracts.': { prompt: 'Los plazos de pago (neto 30, neto 60) son elementos negociables de contratos con proveedores.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Why should you negotiate a price escalation cap?': { prompt: '¿Por qué deberías negociar un tope de aumento de precio?', options: ['Para garantizar servicios gratuitos', 'Para limitar cuánto puede aumentar el proveedor los precios anualmente', 'Para obtener soporte ilimitado', 'Para evitar firmar el contrato'], correctAnswer: 'Para limitar cuánto puede aumentar el proveedor los precios anualmente' },

  // Hostage Tactics
  'What is the core principle behind hostage negotiation tactics adapted for business?': { prompt: '¿Cuál es el principio fundamental detrás de las tácticas de negociación de rehenes adaptadas para negocios?', options: ['Usar amenazas e intimidación', 'Construir rapport y confianza para influir en el comportamiento', 'Siempre ceder a las demandas', 'Negociar solo a través de abogados'], correctAnswer: 'Construir rapport y confianza para influir en el comportamiento' },
  'Chris Voss, a former FBI hostage negotiator, advocates using tactical empathy in business negotiations.': { prompt: 'Chris Voss, un ex negociador de rehenes del FBI, promueve el uso de empatía táctica en negociaciones de negocios.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'What is a "calibrated question"?': { prompt: '¿Qué es una "pregunta calibrada"?', options: ['Una pregunta con respuesta matemática', 'Una pregunta abierta de "cómo" o "qué" diseñada para que la otra parte resuelva tu problema', 'Una pregunta de sí o no hecha con calma', 'Una pregunta hecha en el momento exacto'], correctAnswer: 'Una pregunta abierta de "cómo" o "qué" diseñada para que la otra parte resuelva tu problema' },
  'The "late-night FM DJ ___" is a calm, slow tone used to build authority and trust.': { prompt: 'La "___ de DJ de FM nocturno" es un tono calmado y lento usado para construir autoridad y confianza.', options: ['Voz', 'Música', 'Programa', 'Estilo'], correctAnswer: 'Voz' },
  'In hostage negotiation tactics, "no" is considered more valuable than "yes" as a starting point.': { prompt: 'En tácticas de negociación de rehenes, "no" se considera más valioso que "sí" como punto de partida.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'What does "tactical empathy" mean?': { prompt: '¿Qué significa "empatía táctica"?', options: ['Fingir que te importa alguien', 'Comprender los sentimientos y la perspectiva de la otra parte para influir en el resultado', 'Ser emocional durante la negociación', 'Tener tanta empatía que cedes'], correctAnswer: 'Comprender los sentimientos y la perspectiva de la otra parte para influir en el resultado' },
  'An accusation audit pre-empts the other party\'s objections by listing them first.': { prompt: 'Una auditoría de acusaciones se adelanta a las objeciones de la otra parte al listarlas primero.', options: ['Verdadero', 'Falso'], correctAnswer: 'Verdadero' },
  'Why is "That\'s right" a more powerful response than "You\'re right" in negotiation?': { prompt: '¿Por qué "Así es" es una respuesta más poderosa que "Tienes razón" en negociación?', options: ['Significan lo mismo', '"Así es" significa que se sienten comprendidos; "Tienes razón" significa que quieren que dejes de hablar', '"Tienes razón" siempre es sincero', '"Así es" es gramaticalmente correcto'], correctAnswer: '"Así es" significa que se sienten comprendidos; "Tienes razón" significa que quieren que dejes de hablar' },
};
