export const persuasionFr: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // Influence 101
  'Who wrote the influential book "Influence: The Psychology of Persuasion"?': { prompt: 'Qui a écrit le livre influent « Influence : la psychologie de la persuasion » ?', options: ['Dale Carnegie', 'Robert Cialdini', 'Daniel Kahneman', 'Malcolm Gladwell'], correctAnswer: 'Robert Cialdini' },
  'Persuasion and manipulation are exactly the same thing.': { prompt: 'La persuasion et la manipulation sont exactement la même chose.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'What is the key difference between persuasion and coercion?': { prompt: 'Quelle est la différence clé entre la persuasion et la coercition ?', options: ['Il n\'y a aucune différence', 'La persuasion change les esprits volontairement ; la coercition force la conformité par des menaces', 'La coercition est toujours légale ; la persuasion ne l\'est pas', 'La persuasion est plus lente'], correctAnswer: 'La persuasion change les esprits volontairement ; la coercition force la conformité par des menaces' },
  'Cialdini originally identified ___ principles of influence in his research.': { prompt: 'Cialdini a identifié à l\'origine ___ principes d\'influence dans ses recherches.', options: ['Six', 'Trois', 'Dix', 'Deux'], correctAnswer: 'Six' },
  'Understanding influence principles helps you both persuade others AND defend against manipulation.': { prompt: 'Comprendre les principes d\'influence vous aide à persuader les autres ET à vous défendre contre la manipulation.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which is NOT one of Cialdini\'s original principles?': { prompt: 'Lequel N\'EST PAS un des principes originaux de Cialdini ?', options: ['Réciprocité', 'Rareté', 'Peur', 'Autorité'], correctAnswer: 'Peur' },
  'Influence principles work because they exploit cognitive shortcuts (heuristics) our brains use.': { prompt: 'Les principes d\'influence fonctionnent car ils exploitent les raccourcis cognitifs (heuristiques) que notre cerveau utilise.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Cialdini\'s 7th principle, added later, is:': { prompt: 'Le 7e principe de Cialdini, ajouté plus tard, est :', options: ['Peur de rater quelque chose', 'Unité — identité partagée et appartenance', 'Curiosité', 'Compétition'], correctAnswer: 'Unité — identité partagée et appartenance' },

  // Reciprocity
  'What is the reciprocity principle?': { prompt: 'Qu\'est-ce que le principe de réciprocité ?', options: ['Toujours donner plus que ce que l\'on reçoit', 'Les gens se sentent obligés de rendre les faveurs et les cadeaux', 'Ne jamais accepter de cadeaux d\'inconnus', 'Ne donner qu\'aux gens qui donnent en premier'], correctAnswer: 'Les gens se sentent obligés de rendre les faveurs et les cadeaux' },
  'Free samples at grocery stores leverage the reciprocity principle.': { prompt: 'Les échantillons gratuits dans les épiceries exploitent le principe de réciprocité.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Reciprocity is effective because:': { prompt: 'La réciprocité est efficace parce que :', options: ['Les gens sont naturellement généreux', 'Violer la norme de réciprocité cause un malaise social', 'Cela ne fonctionne que sur les gens crédules', 'Les lois exigent la réciprocité'], correctAnswer: 'Violer la norme de réciprocité cause un malaise social' },
  'The reciprocity principle can cause people to return a ___ favor with a much larger one.': { prompt: 'Le principe de réciprocité peut amener les gens à rendre une ___ faveur par une beaucoup plus grande.', options: ['Petite', 'Grande', 'Égale', 'Financière'], correctAnswer: 'Petite' },
  'Personalized, unexpected gifts trigger stronger reciprocity than generic ones.': { prompt: 'Les cadeaux personnalisés et inattendus déclenchent une réciprocité plus forte que les cadeaux génériques.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'How can you defend against reciprocity-based manipulation?': { prompt: 'Comment pouvez-vous vous défendre contre la manipulation basée sur la réciprocité ?', options: ['Ne jamais rien accepter de personne', 'Reconnaître la tactique et évaluer la demande selon ses propres mérites', 'Toujours rendre immédiatement', 'Refuser toutes les offres gratuites'], correctAnswer: 'Reconnaître la tactique et évaluer la demande selon ses propres mérites' },
  'Reciprocal concessions (making a smaller request after a big one is rejected) leverage reciprocity.': { prompt: 'Les concessions réciproques (faire une petite demande après qu\'une grande a été refusée) exploitent la réciprocité.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'In business, which is an example of strategic reciprocity?': { prompt: 'En affaires, quel est un exemple de réciprocité stratégique ?', options: ['Ignorer les clients', 'Fournir du contenu gratuit de valeur avant de demander une vente', 'Exiger un paiement initial toujours', 'Refuser de négocier'], correctAnswer: 'Fournir du contenu gratuit de valeur avant de demander une vente' },

  // Scarcity
  'The scarcity principle states that:': { prompt: 'Le principe de rareté affirme que :', options: ['Les choses rares sont toujours de meilleure qualité', 'Les gens accordent plus de valeur aux choses limitées ou difficiles à obtenir', 'La rareté ne s\'applique qu\'aux produits de luxe', 'Créer l\'abondance augmente le désir'], correctAnswer: 'Les gens accordent plus de valeur aux choses limitées ou difficiles à obtenir' },
  '"Only 3 left in stock!" is an example of scarcity marketing.': { prompt: '« Il n\'en reste que 3 en stock ! » est un exemple de marketing de rareté.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which type of scarcity is more powerful psychologically?': { prompt: 'Quel type de rareté est psychologiquement plus puissant ?', options: ['L\'abondance qui a toujours existé', 'La rareté qui a toujours existé', 'La rareté qui vient d\'apparaître — quelque chose devenant nouvellement rare', 'Aucune rareté du tout'], correctAnswer: 'La rareté qui vient d\'apparaître — quelque chose devenant nouvellement rare' },
  '"This offer expires at midnight" creates ___ scarcity to drive immediate action.': { prompt: '« Cette offre expire à minuit » crée une rareté de ___ pour inciter à l\'action immédiate.', options: ['Temps', 'Quantité', 'Qualité', 'Social'], correctAnswer: 'Temps' },
  'The "Romeo and Juliet effect" shows that parental opposition can make romantic relationships more desirable.': { prompt: 'L\'« effet Roméo et Juliette » montre que l\'opposition parentale peut rendre les relations amoureuses plus désirables.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'How can you defend against scarcity manipulation?': { prompt: 'Comment pouvez-vous vous défendre contre la manipulation par la rareté ?', options: ['Tout acheter immédiatement avant que ça ne parte', 'Vous demander : voudrais-je ceci s\'il était disponible en abondance ?', 'Ignorer toutes les offres limitées', 'Faire confiance à tous les compteurs à rebours'], correctAnswer: 'Vous demander : voudrais-je ceci s\'il était disponible en abondance ?' },
  'Exclusive access (VIP, invite-only) is a form of scarcity.': { prompt: 'L\'accès exclusif (VIP, sur invitation uniquement) est une forme de rareté.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is "artificial scarcity"?': { prompt: 'Qu\'est-ce que la « rareté artificielle » ?', options: ['L\'épuisement des ressources naturelles', 'Limiter délibérément l\'offre pour augmenter la valeur perçue, même quand on pourrait en produire plus', 'Une réglementation gouvernementale sur la production', 'Une stratégie de prix basée sur les coûts'], correctAnswer: 'Limiter délibérément l\'offre pour augmenter la valeur perçue, même quand on pourrait en produire plus' },

  // Authority
  'The authority principle states that people tend to:': { prompt: 'Le principe d\'autorité affirme que les gens ont tendance à :', options: ['Ignorer tous les experts', 'Se conformer aux demandes des figures d\'autorité perçues', 'Ne suivre que les élus', 'Résister à toutes les formes d\'autorité'], correctAnswer: 'Se conformer aux demandes des figures d\'autorité perçues' },
  'Milgram\'s experiment showed that people would administer seemingly dangerous electric shocks when directed by an authority figure.': { prompt: 'L\'expérience de Milgram a montré que les gens administreraient des chocs électriques apparemment dangereux lorsque dirigés par une figure d\'autorité.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which of these symbols triggers the authority principle?': { prompt: 'Lequel de ces symboles déclenche le principe d\'autorité ?', options: ['Un t-shirt coloré', 'Un sarrau blanc, un titre ou un uniforme', 'Des sandales décontractées', 'Une casquette de baseball'], correctAnswer: 'Un sarrau blanc, un titre ou un uniforme' },
  '"4 out of 5 ___ recommend this toothpaste" uses authority to persuade.': { prompt: '« 4 ___ sur 5 recommandent ce dentifrice » utilise l\'autorité pour persuader.', options: ['Dentistes', 'Amis', 'Voisins', 'Étudiants'], correctAnswer: 'Dentistes' },
  'An authority admitting a small weakness before presenting their case can actually increase persuasiveness.': { prompt: 'Une autorité admettant une petite faiblesse avant de présenter son argument peut en fait augmenter sa persuasivité.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'How can authority be used unethically?': { prompt: 'Comment l\'autorité peut-elle être utilisée de manière non éthique ?', options: ['En partageant une expertise authentique', 'En falsifiant des diplômes ou en utilisant des symboles d\'autorité sans vrai savoir', 'En publiant des recherches évaluées par des pairs', 'En obtenant un diplôme'], correctAnswer: 'En falsifiant des diplômes ou en utilisant des symboles d\'autorité sans vrai savoir' },
  'People are more persuaded by authority figures who appear confident, even when they are wrong.': { prompt: 'Les gens sont plus persuadés par des figures d\'autorité qui paraissent confiantes, même quand elles ont tort.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'To defend against misused authority, you should ask:': { prompt: 'Pour vous défendre contre l\'autorité mal utilisée, vous devriez vous demander :', options: ['Cette personne est-elle célèbre ?', 'Cette personne est-elle vraiment qualifiée dans CE domaine spécifique, et est-elle honnête ?', 'Cette personne a-t-elle beaucoup d\'abonnés ?', 'Cette personne porte-t-elle un costume ?'], correctAnswer: 'Cette personne est-elle vraiment qualifiée dans CE domaine spécifique, et est-elle honnête ?' },

  // Social Proof
  'What is social proof?': { prompt: 'Qu\'est-ce que la preuve sociale ?', options: ['Un document légal prouvant le statut social', 'La tendance à suivre ce que font les autres, surtout dans l\'incertitude', 'Un type de preuve mathématique', 'Un badge de vérification de réseau social'], correctAnswer: 'La tendance à suivre ce que font les autres, surtout dans l\'incertitude' },
  'Online reviews and ratings are a form of social proof.': { prompt: 'Les avis et évaluations en ligne sont une forme de preuve sociale.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Social proof is most powerful when:': { prompt: 'La preuve sociale est plus puissante quand :', options: ['Vous êtes confiant dans votre décision', 'Vous êtes incertain et les personnes fournissant la preuve vous ressemblent', 'Vous êtes seul sans information', 'Vous êtes en désaccord avec la majorité'], correctAnswer: 'Vous êtes incertain et les personnes fournissant la preuve vous ressemblent' },
  'The "bystander effect" is a dark side of social proof where people fail to help because ___ else is helping.': { prompt: 'L\'« effet du témoin » est un côté sombre de la preuve sociale où les gens n\'aident pas parce que ___ d\'autre n\'aide.', options: ['Personne', 'Tout le monde', 'Quelqu\'un', 'Une personne'], correctAnswer: 'Personne' },
  'Showing "10,000+ happy customers" on a website is an application of social proof.': { prompt: 'Afficher « 10 000+ clients satisfaits » sur un site web est une application de la preuve sociale.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which is an example of negative social proof (social proof that backfires)?': { prompt: 'Quel est un exemple de preuve sociale négative (preuve sociale qui se retourne contre vous) ?', options: ['« Rejoignez les millions qui se sont déjà inscrits ! »', '« La plupart des gens paient leurs impôts à temps »', '« X millions de personnes piratent de la musique chaque année » (ce qui normalise le piratage)', '« 95% des clients nous recommandent »'], correctAnswer: '« X millions de personnes piratent de la musique chaque année » (ce qui normalise le piratage)' },
  'Fake testimonials and fabricated social proof are both unethical and often illegal.': { prompt: 'Les faux témoignages et la preuve sociale fabriquée sont à la fois non éthiques et souvent illégaux.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'How can you defend against social proof manipulation?': { prompt: 'Comment pouvez-vous vous défendre contre la manipulation par la preuve sociale ?', options: ['Ne jamais lire d\'avis', 'Vérifier si la preuve sociale est authentique, pertinente et provient de sources fiables', 'Toujours suivre la majorité', 'Ignorer toutes les recommandations'], correctAnswer: 'Vérifier si la preuve sociale est authentique, pertinente et provient de sources fiables' },

  // Liking
  'The liking principle states that we are more easily persuaded by people who:': { prompt: 'Le principe de sympathie affirme que nous sommes plus facilement persuadés par les gens que :', options: ['Sont des inconnus', 'Nous aimons, trouvons attirants ou qui nous ressemblent', 'Sont en désaccord avec nous', 'Nous ignorent'], correctAnswer: 'Nous aimons, trouvons attirants ou qui nous ressemblent' },
  'Physical attractiveness can increase a person\'s persuasive power, even on unrelated topics.': { prompt: 'L\'attrait physique peut augmenter le pouvoir de persuasion d\'une personne, même sur des sujets non liés.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Finding ___ with someone (shared interests, background, values) increases liking and persuasion.': { prompt: 'Trouver des ___ avec quelqu\'un (intérêts, antécédents, valeurs communs) augmente la sympathie et la persuasion.', options: ['Similarités', 'Différences', 'Défauts', 'Argent'], correctAnswer: 'Similarités' },
  'Tupperware parties leverage the liking principle by:': { prompt: 'Les soirées Tupperware exploitent le principe de sympathie en :', options: ['Vendant des produits bon marché', 'Faisant vendre des amis à des amis, exploitant les relations existantes', 'Utilisant des célébrités', 'Offrant les prix les plus bas'], correctAnswer: 'Faisant vendre des amis à des amis, exploitant les relations existantes' },
  'Complimenting someone genuinely can increase their willingness to comply with your requests.': { prompt: 'Complimenter quelqu\'un sincèrement peut augmenter sa volonté de se conformer à vos demandes.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which sales technique directly exploits the liking principle?': { prompt: 'Quelle technique de vente exploite directement le principe de sympathie ?', options: ['Appeler des inconnus à froid', 'Construire un rapport et trouver un terrain d\'entente avant de proposer', 'Envoyer des courriels de masse', 'Offrir le prix le plus bas'], correctAnswer: 'Construire un rapport et trouver un terrain d\'entente avant de proposer' },
  'Association with positive things (celebrities, good causes) transfers positive feelings to a brand.': { prompt: 'L\'association avec des choses positives (célébrités, bonnes causes) transfère des sentiments positifs à une marque.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'To defend against the liking principle, you should:': { prompt: 'Pour vous défendre contre le principe de sympathie, vous devriez :', options: ['Détester tout le monde également', 'Séparer vos sentiments envers la personne des mérites de sa demande', 'Ne jamais être amical avec les vendeurs', 'N\'acheter qu\'en ligne'], correctAnswer: 'Séparer vos sentiments envers la personne des mérites de sa demande' },

  // Commitment
  'The commitment and consistency principle states that:': { prompt: 'Le principe d\'engagement et de cohérence affirme que :', options: ['Les gens évitent tous les engagements', 'Une fois engagées, les gens ressentent une pression pour agir de manière cohérente avec cet engagement', 'La cohérence est sans importance en persuasion', 'Les gens changent facilement d\'avis après s\'être engagés'], correctAnswer: 'Une fois engagées, les gens ressentent une pression pour agir de manière cohérente avec cet engagement' },
  'Written commitments are more binding psychologically than verbal ones.': { prompt: 'Les engagements écrits sont psychologiquement plus contraignants que les verbaux.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The "foot-in-the-door" technique works by:': { prompt: 'La technique du « pied dans la porte » fonctionne en :', options: ['Mettant votre pied dans la porte de quelqu\'un', 'Commençant par une petite demande pour augmenter la conformité à une plus grande ensuite', 'Faisant la plus grande demande en premier', 'Utilisant l\'intimidation physique'], correctAnswer: 'Commençant par une petite demande pour augmenter la conformité à une plus grande ensuite' },
  'Public commitments are harder to break because our ___ is at stake.': { prompt: 'Les engagements publics sont plus difficiles à rompre parce que notre ___ est en jeu.', options: ['Réputation', 'Argent', 'Santé', 'Vie privée'], correctAnswer: 'Réputation' },
  'The "lowball" technique works by getting commitment first, then changing the terms.': { prompt: 'La technique du « lowball » fonctionne en obtenant l\'engagement d\'abord, puis en changeant les termes.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'How does commitment escalation work in cults?': { prompt: 'Comment l\'escalade d\'engagement fonctionne-t-elle dans les sectes ?', options: ['Elles exigent un engagement total immédiatement', 'Elles commencent par de petites demandes faciles qui s\'intensifient graduellement vers des exigences majeures', 'Elles n\'utilisent que la peur', 'Elles paient les membres'], correctAnswer: 'Elles commencent par de petites demandes faciles qui s\'intensifient graduellement vers des exigences majeures' },
  'Goal-setting apps leverage the commitment principle by making your goals visible and trackable.': { prompt: 'Les applis de fixation d\'objectifs exploitent le principe d\'engagement en rendant vos objectifs visibles et suivis.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'To defend against commitment manipulation, you should:': { prompt: 'Pour vous défendre contre la manipulation par l\'engagement, vous devriez :', options: ['Ne jamais s\'engager dans quoi que ce soit', 'Vous demander : sachant ce que je sais maintenant, ferais-je le même choix ?', 'Toujours tenir parole quoi qu\'il arrive', 'Ignorer les nouvelles informations'], correctAnswer: 'Vous demander : sachant ce que je sais maintenant, ferais-je le même choix ?' },

  // Framing Effects
  'What is a "framing effect"?': { prompt: 'Qu\'est-ce qu\'un « effet de cadrage » ?', options: ['Mettre une image dans un cadre', 'Comment la présentation de l\'information influence la prise de décision, même quand les faits sont identiques', 'Un type d\'illusion d\'optique', 'Un cadre juridique pour les contrats'], correctAnswer: 'Comment la présentation de l\'information influence la prise de décision, même quand les faits sont identiques' },
  '"90% fat-free" sounds healthier than "contains 10% fat" even though they mean the same thing.': { prompt: '« 90% sans gras » semble plus sain que « contient 10% de gras » même s\'ils signifient la même chose.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'In Kahneman and Tversky\'s disease problem, people preferred the "200 saved" frame over "400 will die" because:': { prompt: 'Dans le problème de maladie de Kahneman et Tversky, les gens préféraient le cadrage « 200 sauvés » à « 400 mourront » parce que :', options: ['200 est un plus grand nombre', 'Les gens sont averses au risque pour les gains mais cherchent le risque pour les pertes', 'Les deux cadres étaient identiques', '200 est plus facile à calculer'], correctAnswer: 'Les gens sont averses au risque pour les gains mais cherchent le risque pour les pertes' },
  'Presenting a $1,000 product as "$2.74 per day" is an example of ___ framing.': { prompt: 'Présenter un produit de 1 000 $ comme « 2,74 $ par jour » est un exemple de cadrage ___.', options: ['Temporel', 'Positif', 'Négatif', 'Social'], correctAnswer: 'Temporel' },
  'A surgeon who says "95% survival rate" will get more patients than one who says "5% mortality rate."': { prompt: 'Un chirurgien qui dit « taux de survie de 95% » aura plus de patients que celui qui dit « taux de mortalité de 5% ».', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which is a loss-framed message?': { prompt: 'Lequel est un message cadré sur la perte ?', options: ['Économisez 100 $ avec notre service', 'Vous perdez 100 $ chaque mois sans notre service', 'Gagnez des récompenses supplémentaires avec nous', 'Rejoignez des milliers de clients satisfaits'], correctAnswer: 'Vous perdez 100 $ chaque mois sans notre service' },
  'Framing effects disappear when people have expertise in the subject matter.': { prompt: 'Les effets de cadrage disparaissent quand les gens ont une expertise dans le sujet.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'To defend against framing manipulation, you should:': { prompt: 'Pour vous défendre contre la manipulation par le cadrage, vous devriez :', options: ['Ne lire que les titres', 'Recadrer l\'information vous-même de plusieurs façons avant de décider', 'Faire confiance au premier cadrage rencontré', 'Ignorer toutes les statistiques'], correctAnswer: 'Recadrer l\'information vous-même de plusieurs façons avant de décider' },

  // Anchoring Bias
  'Anchoring bias occurs when:': { prompt: 'Le biais d\'ancrage se produit quand :', options: ['Les gens ancrent leurs bateaux correctement', 'Une information initiale influence de manière disproportionnée les jugements suivants', 'Les gens choisissent toujours l\'option du milieu', 'Les gens ignorent toute information initiale'], correctAnswer: 'Une information initiale influence de manière disproportionnée les jugements suivants' },
  'Even random numbers can serve as anchors and influence unrelated decisions.': { prompt: 'Même des chiffres aléatoires peuvent servir d\'ancrage et influencer des décisions sans rapport.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A store lists a jacket at $500 (crossed out) then shows $199. The $500 serves as:': { prompt: 'Un magasin affiche une veste à 500 $ (barré) puis montre 199 $. Le 500 $ sert de :', options: ['Le vrai prix', 'Une erreur arbitraire', 'Un ancrage qui fait paraître 199 $ comme une bonne affaire', 'Le prix de gros'], correctAnswer: 'Un ancrage qui fait paraître 199 $ comme une bonne affaire' },
  'Anchoring works because people ___ adjust from initial values.': { prompt: 'L\'ancrage fonctionne parce que les gens ___ ajustent à partir des valeurs initiales.', options: ['Insuffisamment', 'Trop', 'Parfaitement', 'Jamais'], correctAnswer: 'Insuffisamment' },
  'Awareness of anchoring bias completely eliminates its effect.': { prompt: 'La conscience du biais d\'ancrage élimine complètement son effet.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'In salary negotiation, who benefits from setting the first number?': { prompt: 'Dans la négociation salariale, qui bénéficie d\'établir le premier chiffre ?', options: ['Aucune des parties', 'La partie qui fixe l\'ancrage, car cela influence le résultat final', 'Seulement l\'employeur', 'Seulement l\'employé'], correctAnswer: 'La partie qui fixe l\'ancrage, car cela influence le résultat final' },
  'Menu psychology uses anchoring by placing expensive items first to make other items seem reasonable.': { prompt: 'La psychologie des menus utilise l\'ancrage en plaçant les articles chers en premier pour que les autres semblent raisonnables.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'To counter anchoring bias, you should:': { prompt: 'Pour contrer le biais d\'ancrage, vous devriez :', options: ['Accepter le premier chiffre entendu', 'Générer votre propre estimation indépendante avant de voir les chiffres des autres', 'Toujours choisir l\'option du milieu', 'Ignorer tous les chiffres'], correctAnswer: 'Générer votre propre estimation indépendante avant de voir les chiffres des autres' },

  // Loss Aversion
  'Loss aversion means that:': { prompt: 'L\'aversion à la perte signifie que :', options: ['Les gens adorent perdre', 'La douleur de perdre est psychologiquement environ deux fois plus puissante que le plaisir de gagner', 'Les gens sont indifférents aux gains et aux pertes', 'Les pertes et les gains sont ressentis également'], correctAnswer: 'La douleur de perdre est psychologiquement environ deux fois plus puissante que le plaisir de gagner' },
  '"Don\'t miss out on this deal!" leverages loss aversion.': { prompt: '« Ne ratez pas cette offre ! » exploite l\'aversion à la perte.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A company offers a "free trial that ends in 7 days." Loss aversion makes you:': { prompt: 'Une entreprise offre un « essai gratuit qui se termine dans 7 jours ». L\'aversion à la perte vous rend :', options: ['Annuler immédiatement', 'Plus susceptible de vous abonner parce que perdre l\'accès est douloureux', 'Complètement indifférent', 'Demander un remboursement'], correctAnswer: 'Plus susceptible de vous abonner parce que perdre l\'accès est douloureux' },
  'The ___ effect means people value things more once they own them, making loss aversion stronger.': { prompt: 'L\'effet de ___ signifie que les gens accordent plus de valeur aux choses une fois qu\'ils les possèdent, rendant l\'aversion à la perte plus forte.', options: ['Dotation', 'Mode', 'Halo', 'Placebo'], correctAnswer: 'Dotation' },
  'Insurance companies exploit loss aversion by emphasizing what you could lose without coverage.': { prompt: 'Les compagnies d\'assurance exploitent l\'aversion à la perte en soulignant ce que vous pourriez perdre sans couverture.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which message is more motivating due to loss aversion?': { prompt: 'Quel message est plus motivant en raison de l\'aversion à la perte ?', options: ['« Vous pourriez économiser 500 $ cette année »', '« Vous perdez 500 $ chaque année »', '« Notre produit coûte 500 $ »', '« 500 $ est une économie moyenne »'], correctAnswer: '« Vous perdez 500 $ chaque année »' },
  'Loss aversion can lead to poor investment decisions like holding losing stocks too long.': { prompt: 'L\'aversion à la perte peut mener à de mauvaises décisions d\'investissement comme garder des actions perdantes trop longtemps.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'How can you defend against loss aversion manipulation?': { prompt: 'Comment pouvez-vous vous défendre contre la manipulation par l\'aversion à la perte ?', options: ['Ne jamais rien acheter', 'Évaluer les décisions en fonction de la valeur réelle du résultat, pas de la peur de la perte', 'Toujours éviter les pertes à tout prix', 'Ignorer tout marketing'], correctAnswer: 'Évaluer les décisions en fonction de la valeur réelle du résultat, pas de la peur de la perte' },

  // Dark Patterns
  'What are "dark patterns" in design?': { prompt: 'Que sont les « dark patterns » en design ?', options: ['Des sites web au thème sombre', 'Des conceptions d\'interface qui trompent les gens pour qu\'ils fassent des choses non voulues', 'Des sites web qui chargent lentement', 'Des palettes de couleurs utilisant des couleurs sombres'], correctAnswer: 'Des conceptions d\'interface qui trompent les gens pour qu\'ils fassent des choses non voulues' },
  'Making the "unsubscribe" button tiny and hard to find is a dark pattern.': { prompt: 'Rendre le bouton « se désabonner » minuscule et difficile à trouver est un dark pattern.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A "roach motel" dark pattern refers to:': { prompt: 'Le dark pattern « hôtel à cafards » fait référence à :', options: ['Une réservation d\'hôtel bon marché', 'Rendre l\'inscription facile mais l\'annulation extrêmement difficile', 'Un type de bogue de site web', 'Une publicité popup'], correctAnswer: 'Rendre l\'inscription facile mais l\'annulation extrêmement difficile' },
  '"Confirmshaming" uses ___ language on the decline button to make users feel bad about opting out.': { prompt: 'Le « confirmshaming » utilise un langage ___ sur le bouton de refus pour que les utilisateurs se sentent mal de refuser.', options: ['Culpabilisant', 'Neutre', 'Positif', 'Technique'], correctAnswer: 'Culpabilisant' },
  'Pre-checked boxes that add items to your cart or sign you up for newsletters are a dark pattern.': { prompt: 'Les cases pré-cochées qui ajoutent des articles à votre panier ou vous inscrivent à des infolettres sont un dark pattern.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which is a "misdirection" dark pattern?': { prompt: 'Lequel est un dark pattern de « détournement d\'attention » ?', options: ['Un formulaire clair et bien conçu', 'Utiliser le design visuel pour détourner l\'attention des options défavorables', 'Une page de prix transparente', 'Un processus de paiement simple'], correctAnswer: 'Utiliser le design visuel pour détourner l\'attention des options défavorables' },
  'Dark patterns are now being regulated and banned in some countries including the EU.': { prompt: 'Les dark patterns sont maintenant réglementés et interdits dans certains pays dont l\'UE.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Adding hidden charges that only appear at checkout is called:': { prompt: 'Ajouter des frais cachés qui n\'apparaissent qu\'au paiement s\'appelle :', options: ['Prix transparent', 'Prix au goutte-à-goutte (dark pattern de coûts cachés)', 'Prix dynamique', 'Prix équitable'], correctAnswer: 'Prix au goutte-à-goutte (dark pattern de coûts cachés)' },

  // Gaslighting Defense
  'What is gaslighting?': { prompt: 'Qu\'est-ce que le gaslighting ?', options: ['Ajuster l\'éclairage d\'une pièce', 'Une forme de manipulation psychologique qui fait douter les victimes de leur propre réalité', 'Une technique de négociation', 'Une technique de design d\'éclairage'], correctAnswer: 'Une forme de manipulation psychologique qui fait douter les victimes de leur propre réalité' },
  'The term "gaslighting" comes from the 1944 film "Gaslight."': { prompt: 'Le terme « gaslighting » vient du film de 1944 « Gaslight ».', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which is a common gaslighting phrase?': { prompt: 'Quelle est une phrase de gaslighting courante ?', options: ['« J\'apprécie votre perspective »', '« Ça n\'est jamais arrivé — vous imaginez des choses »', '« Laissez-moi réfléchir à ce que vous avez dit »', '« Je comprends pourquoi vous ressentez cela »'], correctAnswer: '« Ça n\'est jamais arrivé — vous imaginez des choses »' },
  'Keeping a ___ of events and conversations is one defense against gaslighting.': { prompt: 'Tenir un ___ des événements et conversations est une défense contre le gaslighting.', options: ['Journal', 'Secret', 'Photo', 'Score'], correctAnswer: 'Journal' },
  'Gaslighting only occurs in romantic relationships.': { prompt: 'Le gaslighting ne se produit que dans les relations amoureuses.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'A key defense against gaslighting is:': { prompt: 'Une défense clé contre le gaslighting est :', options: ['Toujours être d\'accord avec le manipulateur pour garder la paix', 'Faire confiance à vos propres perceptions et chercher la validation de tiers de confiance', 'Vous isoler de tout le monde', 'Faire du gaslighting en retour'], correctAnswer: 'Faire confiance à vos propres perceptions et chercher la validation de tiers de confiance' },
  'Gaslighters often isolate their victims from friends and family.': { prompt: 'Les gaslighters isolent souvent leurs victimes de leurs amis et de leur famille.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which behavior pattern suggests someone may be gaslighting you?': { prompt: 'Quel schéma de comportement suggère que quelqu\'un vous fait du gaslighting ?', options: ['Ils admettent toujours quand ils ont tort', 'Ils nient systématiquement des choses que vous savez arrivées, vous blâment et minimisent vos sentiments', 'Ils vous encouragent à parler à vos amis des désaccords', 'Ils suggèrent une thérapie de couple'], correctAnswer: 'Ils nient systématiquement des choses que vous savez arrivées, vous blâment et minimisent vos sentiments' },

  // Emotional Triggers
  'Why are emotional triggers so effective in persuasion?': { prompt: 'Pourquoi les déclencheurs émotionnels sont-ils si efficaces en persuasion ?', options: ['Les émotions sont sans rapport avec les décisions', 'Les émotions contournent la pensée rationnelle et accélèrent la prise de décision', 'Les gens n\'utilisent que la logique pour décider', 'Les émotions ralentissent la prise de décision'], correctAnswer: 'Les émotions contournent la pensée rationnelle et accélèrent la prise de décision' },
  'Fear-based advertising (e.g., "act now or lose everything") works by triggering the fight-or-flight response.': { prompt: 'La publicité basée sur la peur (ex. « agissez maintenant ou perdez tout ») fonctionne en déclenchant la réponse combat-ou-fuite.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Advertisements that make you feel ___ (warm, fuzzy feelings) increase your liking of the brand.': { prompt: 'Les publicités qui vous font ressentir de la ___ (sentiments chaleureux) augmentent votre appréciation de la marque.', options: ['Nostalgie', 'Colère', 'Confusion', 'Ennui'], correctAnswer: 'Nostalgie' },
  'Which emotional trigger is most commonly used in charity appeals?': { prompt: 'Quel déclencheur émotionnel est le plus couramment utilisé dans les appels caritatifs ?', options: ['Cupidité', 'Culpabilité et empathie', 'Colère', 'Fierté'], correctAnswer: 'Culpabilité et empathie' },
  'The "identifiable victim effect" means we donate more to help one named child than millions of unnamed ones.': { prompt: 'L\'« effet de la victime identifiable » signifie que nous donnons plus pour aider un enfant nommé que des millions d\'anonymes.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Anger as an emotional trigger in persuasion is used to:': { prompt: 'La colère comme déclencheur émotionnel en persuasion est utilisée pour :', options: ['Calmer les gens', 'Mobiliser l\'action contre un ennemi perçu ou une injustice', 'Endormir les gens', 'Augmenter la pensée logique'], correctAnswer: 'Mobiliser l\'action contre un ennemi perçu ou une injustice' },
  'You should make important decisions immediately after experiencing strong emotions.': { prompt: 'Vous devriez prendre des décisions importantes immédiatement après avoir ressenti de fortes émotions.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'How can you defend against emotional trigger manipulation?': { prompt: 'Comment pouvez-vous vous défendre contre la manipulation par les déclencheurs émotionnels ?', options: ['Supprimer toutes les émotions pour toujours', 'Remarquer quand vous ressentez une forte émotion et faire une pause avant d\'agir', 'Toujours suivre votre instinct immédiatement', 'Éviter tous les médias'], correctAnswer: 'Remarquer quand vous ressentez une forte émotion et faire une pause avant d\'agir' },

  // NLP Basics
  'What does NLP stand for in the context of persuasion?': { prompt: 'Que signifie PNL dans le contexte de la persuasion ?', options: ['Traitement du langage naturel', 'Programmation neuro-linguistique', 'Nouveaux principes de leadership', 'Psychologie non linéaire'], correctAnswer: 'Programmation neuro-linguistique' },
  'NLP is widely accepted as scientifically proven by the mainstream psychology community.': { prompt: 'La PNL est largement acceptée comme scientifiquement prouvée par la communauté de psychologie dominante.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'What is "rapport building" in NLP?': { prompt: 'Qu\'est-ce que la « construction du rapport » en PNL ?', options: ['Ignorer l\'autre personne', 'Créer une connexion en adaptant le langage, le langage corporel et les schémas respiratoires', 'Lire dans les pensées', 'Utiliser l\'hypnose sans consentement'], correctAnswer: 'Créer une connexion en adaptant le langage, le langage corporel et les schémas respiratoires' },
  'NLP suggests people have preferred ___ systems: visual, auditory, or kinesthetic.': { prompt: 'La PNL suggère que les gens ont des systèmes ___ préférés : visuel, auditif ou kinesthésique.', options: ['Représentationnels', 'Opérants', 'Nerveux', 'Sociaux'], correctAnswer: 'Représentationnels' },
  'Matching someone\'s language patterns (visual: "I see," auditory: "I hear you") is an NLP technique.': { prompt: 'Adapter ses schémas de langage (visuel : « je vois », auditif : « je vous entends ») est une technique de PNL.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is "anchoring" in NLP?': { prompt: 'Qu\'est-ce que l\'« ancrage » en PNL ?', options: ['Laisser tomber une ancre dans l\'eau', 'Associer un stimulus spécifique (toucher, mot, geste) à un état émotionnel désiré', 'Le premier chiffre dans une négociation de prix', 'Un type de méditation'], correctAnswer: 'Associer un stimulus spécifique (toucher, mot, geste) à un état émotionnel désiré' },
  'Critical thinking about NLP claims is important because some techniques lack scientific validation.': { prompt: 'La pensée critique sur les affirmations de la PNL est importante car certaines techniques manquent de validation scientifique.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Reframing in NLP involves:': { prompt: 'Le recadrage en PNL implique :', options: ['Mettre un nouveau cadre sur une photo', 'Changer le contexte ou le sens d\'une expérience pour modifier son impact émotionnel', 'Oublier complètement une expérience', 'Répéter la même histoire'], correctAnswer: 'Changer le contexte ou le sens d\'une expérience pour modifier son impact émotionnel' },

  // Storytelling Power
  'Why is storytelling one of the most powerful persuasion tools?': { prompt: 'Pourquoi le storytelling est-il l\'un des outils de persuasion les plus puissants ?', options: ['Les histoires sont toujours vraies', 'Les histoires engagent les émotions, créent de l\'empathie et sont retenues 22x plus que les faits seuls', 'Les gens s\'ennuient avec les faits', 'Les histoires sont plus rapides à raconter'], correctAnswer: 'Les histoires engagent les émotions, créent de l\'empathie et sont retenues 22x plus que les faits seuls' },
  'Stories that include conflict or tension are more engaging and persuasive than those without.': { prompt: 'Les histoires qui incluent un conflit ou une tension sont plus engageantes et persuasives que celles sans.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is the "hero\'s journey" in storytelling?': { prompt: 'Qu\'est-ce que le « voyage du héros » dans le storytelling ?', options: ['Un programme de fitness', 'Une structure narrative où un personnage affronte des défis, se transforme et revient changé', 'Un type d\'argumentaire de vente', 'Un événement historique'], correctAnswer: 'Une structure narrative où un personnage affronte des défis, se transforme et revient changé' },
  'Stories create "neural ___" — the listener\'s brain activity mirrors the storyteller\'s.': { prompt: 'Les histoires créent un « ___ neural » — l\'activité cérébrale de l\'auditeur reflète celle du conteur.', options: ['Couplage', 'Dommage', 'Déclin', 'Blocage'], correctAnswer: 'Couplage' },
  'Data presented within a story is more persuasive than data presented alone.': { prompt: 'Les données présentées dans une histoire sont plus persuasives que les données présentées seules.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'In persuasive storytelling, who should be the "hero" of the story?': { prompt: 'Dans le storytelling persuasif, qui devrait être le « héros » de l\'histoire ?', options: ['Vous (l\'orateur)', 'Votre entreprise', 'L\'audience (ou quelqu\'un comme eux)', 'Un personnage fictif'], correctAnswer: 'L\'audience (ou quelqu\'un comme eux)' },
  'Vulnerability in storytelling (sharing failures or struggles) increases trust and connection.': { prompt: 'La vulnérabilité dans le storytelling (partager des échecs ou des difficultés) augmente la confiance et la connexion.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The "But & Therefore" storytelling structure replaces:': { prompt: 'La structure de storytelling « Mais & Donc » remplace :', options: ['Tous les adjectifs', '« Et puis... et puis... » par « mais... donc... » pour la tension et la causalité', 'Le personnage principal', 'La conclusion'], correctAnswer: '« Et puis... et puis... » par « mais... donc... » pour la tension et la causalité' },
};
