export const photographyFr: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // Camera Basics
  'What does a camera sensor do?': { prompt: 'Que fait un capteur d\'appareil photo?', options: ['Capture la lumière et la convertit en image', 'Stocke les photos', 'Ajoute des filtres', 'Zoome'], correctAnswer: 'Capture la lumière et la convertit en image' },
  'Megapixels alone determine photo quality.': { prompt: 'Les mégapixels seuls déterminent la qualité d\'une photo.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'The ___ controls how much light reaches the sensor.': { prompt: 'L\'___ contrôle combien de lumière atteint le capteur.', options: ['Ouverture de l\'objectif', 'Flash', 'Écran', 'Batterie'], correctAnswer: 'Ouverture de l\'objectif' },
  'What does ISO control?': { prompt: 'Que contrôle l\'ISO?', options: ['La mise au point', 'La sensibilité du capteur à la lumière', 'La balance des blancs', 'Le niveau de zoom'], correctAnswer: 'La sensibilité du capteur à la lumière' },
  'Shooting in automatic mode while learning the basics.': { prompt: 'Photographier en mode automatique en apprenant les bases.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Higher ISO adds more noise/grain to photos.': { prompt: 'Un ISO plus élevé ajoute plus de bruit/grain aux photos.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Composition
  'What is composition in photography?': { prompt: 'Qu\'est-ce que la composition en photographie?', options: ['Comment les éléments sont disposés dans le cadre', 'La marque de l\'appareil photo', 'Le logiciel d\'édition', 'Le format de fichier'], correctAnswer: 'Comment les éléments sont disposés dans le cadre' },
  'Centering the subject always makes the best composition.': { prompt: 'Centrer le sujet fait toujours la meilleure composition.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Leading ___ guide the viewer\'s eye through the image.': { prompt: 'Les ___ directrices guident l\'oeil du spectateur à travers l\'image.', options: ['Lignes', 'Couleurs', 'Sons', 'Mots'], correctAnswer: 'Lignes' },
  'Including distracting elements in the background.': { prompt: 'Inclure des éléments distrayants dans l\'arrière-plan.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is "negative space"?': { prompt: 'Qu\'est-ce que l\'"espace négatif"?', options: ['Une mauvaise photo', 'L\'espace vide autour du sujet', 'Les zones floues', 'Les zones sombres uniquement'], correctAnswer: 'L\'espace vide autour du sujet' },
  'Framing your subject with natural elements can improve composition.': { prompt: 'Encadrer votre sujet avec des éléments naturels peut améliorer la composition.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Rule of Thirds
  'What is the rule of thirds?': { prompt: 'Qu\'est-ce que la règle des tiers?', options: ['Utiliser 3 couleurs', 'Diviser le cadre en une grille 3x3 et placer les sujets sur les lignes', 'Photographier en groupes de 3', 'Ne prendre que 3 photos'], correctAnswer: 'Diviser le cadre en une grille 3x3 et placer les sujets sur les lignes' },
  'The most interesting spots are where grid lines intersect.': { prompt: 'Les endroits les plus intéressants sont là où les lignes de la grille se croisent.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Place the horizon on the top or bottom ___ line, not centered.': { prompt: 'Placez l\'horizon sur la ligne du ___ supérieur ou inférieur, pas au centre.', options: ['Tiers', 'Milieu', 'Quart', 'Bord'], correctAnswer: 'Tiers' },
  'Turning on the grid overlay in your camera to practice composition.': { prompt: 'Activer la grille de superposition dans votre appareil photo pour pratiquer la composition.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'How many intersection points does the rule of thirds grid create?': { prompt: 'Combien de points d\'intersection la grille de la règle des tiers crée-t-elle?', options: ['9', '2', '4', '6'], correctAnswer: '4' },
  'The rule of thirds can be intentionally broken for effect.': { prompt: 'La règle des tiers peut être intentionnellement brisée pour l\'effet.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Natural Light
  'What is "golden hour"?': { prompt: 'Qu\'est-ce que l\'"heure dorée"?', options: ['Midi', 'Minuit', 'N\'importe quel jour nuageux', 'Peu après le lever du soleil ou avant le coucher du soleil'], correctAnswer: 'Peu après le lever du soleil ou avant le coucher du soleil' },
  'Harsh midday sun creates the most flattering portraits.': { prompt: 'Le soleil dur de midi crée les portraits les plus flatteurs.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Cloudy days act as a natural ___, creating soft, even light.': { prompt: 'Les jours nuageux agissent comme un ___ naturel, créant une lumière douce et uniforme.', options: ['Diffuseur', 'Réflecteur', 'Flash', 'Filtre'], correctAnswer: 'Diffuseur' },
  'Shooting portraits in direct, harsh overhead sunlight.': { prompt: 'Photographier des portraits en plein soleil direct et dur.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is "blue hour"?': { prompt: 'Qu\'est-ce que l\'"heure bleue"?', options: ['Quand le ciel est toujours bleu', 'Midi par temps clair', 'Pendant une tempête', 'La brève période de crépuscule avant le lever ou après le coucher du soleil'], correctAnswer: 'La brève période de crépuscule avant le lever ou après le coucher du soleil' },
  'Window light is excellent for indoor photography.': { prompt: 'La lumière de fenêtre est excellente pour la photographie d\'intérieur.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Focus
  'What is "depth of field"?': { prompt: 'Qu\'est-ce que la "profondeur de champ"?', options: ['Un effet de filtre', 'La profondeur de l\'appareil photo', 'Quelle partie de l\'image est nette', 'La profondeur de l\'océan sur une photo'], correctAnswer: 'Quelle partie de l\'image est nette' },
  'Autofocus is always more accurate than manual focus.': { prompt: 'L\'autofocus est toujours plus précis que la mise au point manuelle.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'In portraits, focus should be on the subject\'s ___.': { prompt: 'En portrait, la mise au point devrait être sur les ___ du sujet.', options: ['Yeux', 'Oreilles', 'Menton', 'Cheveux'], correctAnswer: 'Yeux' },
  'Half-pressing the shutter to lock focus before taking the shot.': { prompt: 'Appuyer à mi-course sur le déclencheur pour verrouiller la mise au point avant de prendre la photo.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What creates a blurry background (bokeh)?': { prompt: 'Qu\'est-ce qui crée un arrière-plan flou (bokeh)?', options: ['ISO élevé', 'Petite ouverture', 'Vitesse d\'obturation lente', 'Grande ouverture (petit nombre f)'], correctAnswer: 'Grande ouverture (petit nombre f)' },
  'A shallow depth of field isolates the subject from the background.': { prompt: 'Une faible profondeur de champ isole le sujet de l\'arrière-plan.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Exposure
  'What three things control exposure?': { prompt: 'Quelles trois choses contrôlent l\'exposition?', options: ['Ouverture, vitesse d\'obturation, ISO', 'Contraste, luminosité, saturation', 'Mise au point, zoom, flash', 'Couleurs RVB'], correctAnswer: 'Ouverture, vitesse d\'obturation, ISO' },
  'The exposure triangle balances aperture, shutter speed, and ISO.': { prompt: 'Le triangle d\'exposition équilibre l\'ouverture, la vitesse d\'obturation et l\'ISO.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'An ___ photo is too bright, a dark photo is underexposed.': { prompt: 'Une photo ___ est trop lumineuse, une photo sombre est sous-exposée.', options: ['Surexposée', 'Nette', 'Filtrée', 'Recadrée'], correctAnswer: 'Surexposée' },
  'Checking the histogram to verify exposure.': { prompt: 'Vérifier l\'histogramme pour confirmer l\'exposition.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What does exposure compensation do?': { prompt: 'Que fait la compensation d\'exposition?', options: ['Rend l\'image plus lumineuse ou plus sombre que ce que le posemètre suggère', 'Ajoute des filtres', 'Change la couleur', 'Change la mise au point'], correctAnswer: 'Rend l\'image plus lumineuse ou plus sombre que ce que le posemètre suggère' },
  'Shooting in RAW gives more flexibility to fix exposure later.': { prompt: 'Photographier en RAW donne plus de flexibilité pour corriger l\'exposition après.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Aperture
  'What does aperture control?': { prompt: 'Que contrôle l\'ouverture?', options: ['La taille de l\'ouverture de l\'objectif', 'La puissance du flash', 'Le zoom', 'Le point de mise au point'], correctAnswer: 'La taille de l\'ouverture de l\'objectif' },
  'A smaller f-number means a wider aperture opening.': { prompt: 'Un nombre f plus petit signifie une ouverture plus grande.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'f/1.8 lets in ___ light than f/16.': { prompt: 'f/1.8 laisse entrer ___ de lumière que f/16.', options: ['Plus', 'Moins', 'Autant', 'Pas'], correctAnswer: 'Plus' },
  'What aperture is best for landscape sharpness?': { prompt: 'Quelle ouverture est la meilleure pour la netteté des paysages?', options: ['f/8 à f/11', 'f/1.4', 'f/2.8', 'f/1.2'], correctAnswer: 'f/8 à f/11' },
  'Using f/1.8 for a group photo where everyone needs to be sharp.': { prompt: 'Utiliser f/1.8 pour une photo de groupe où tout le monde doit être net.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Wider apertures create shallower depth of field.': { prompt: 'Les ouvertures plus grandes créent une profondeur de champ plus faible.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Shutter Speed
  'What does shutter speed control?': { prompt: 'Que contrôle la vitesse d\'obturation?', options: ['La précision de la mise au point', 'La taille de l\'ouverture', 'Combien de temps le capteur est exposé à la lumière', 'Le niveau ISO'], correctAnswer: 'Combien de temps le capteur est exposé à la lumière' },
  'A fast shutter speed freezes motion.': { prompt: 'Une vitesse d\'obturation rapide fige le mouvement.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  '1/1000 is a ___ shutter speed than 1/30.': { prompt: '1/1000 est une vitesse d\'obturation plus ___ que 1/30.', options: ['Rapide', 'Lente', 'Pareille', 'Large'], correctAnswer: 'Rapide' },
  'What shutter speed might cause motion blur when hand-holding?': { prompt: 'Quelle vitesse d\'obturation pourrait causer du flou de mouvement en tenant à la main?', options: ['1/1000', '1/30 ou plus lent', '1/250', '1/500'], correctAnswer: '1/30 ou plus lent' },
  'Using a tripod for long exposure night photography.': { prompt: 'Utiliser un trépied pour la photographie de nuit en longue exposition.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Slow shutter speeds can create artistic motion blur intentionally.': { prompt: 'Les vitesses d\'obturation lentes peuvent créer un flou de mouvement artistique intentionnel.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // ISO
  'What does ISO stand for in photography?': { prompt: 'Que signifie ISO en photographie?', options: ['International Standards Organization', 'Image Stabilization Option', 'Internal Sensor Output', 'Infrared Sensitivity Override'], correctAnswer: 'International Standards Organization' },
  'Raising ISO always improves image quality.': { prompt: 'Augmenter l\'ISO améliore toujours la qualité de l\'image.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Doubling the ISO from 400 to 800 doubles the sensor\'s ___ to light.': { prompt: 'Doubler l\'ISO de 400 à 800 double la ___ du capteur à la lumière.', options: ['Sensibilité', 'Résolution', 'Profondeur de couleur', 'Plage de mise au point'], correctAnswer: 'Sensibilité' },
  'Which ISO setting produces the least noise?': { prompt: 'Quel réglage ISO produit le moins de bruit?', options: ['ISO 6400', 'ISO 100', 'ISO 3200', 'ISO 1600'], correctAnswer: 'ISO 100' },
  'Modern cameras handle high ISO much better than older models.': { prompt: 'Les appareils photo modernes gèrent les ISO élevés bien mieux que les anciens modèles.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'When should you increase ISO?': { prompt: 'Quand devriez-vous augmenter l\'ISO?', options: ['Quand vous voulez plus de flou', 'Quand l\'éclairage est trop lumineux', 'Quand vous avez besoin d\'une vitesse d\'obturation plus rapide en basse lumière', 'Quand vous photographiez des paysages'], correctAnswer: 'Quand vous avez besoin d\'une vitesse d\'obturation plus rapide en basse lumière' },
  'Using Auto ISO with a maximum limit set for your camera.': { prompt: 'Utiliser l\'ISO Auto avec une limite maximale définie pour votre appareil photo.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What is "base ISO" on most cameras?': { prompt: 'Qu\'est-ce que l\'"ISO de base" sur la plupart des appareils photo?', options: ['ISO 50', 'ISO 100 ou 200', 'ISO 800', 'ISO 400'], correctAnswer: 'ISO 100 ou 200' },

  // White Balance
  'What does white balance control?': { prompt: 'Que contrôle la balance des blancs?', options: ['Le niveau d\'exposition', 'La précision de la mise au point', 'La température de couleur de votre image', 'La netteté de l\'image'], correctAnswer: 'La température de couleur de votre image' },
  'Different light sources emit light at different color temperatures.': { prompt: 'Différentes sources de lumière émettent de la lumière à différentes températures de couleur.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Color temperature is measured in degrees ___.': { prompt: 'La température de couleur est mesurée en degrés ___.', options: ['Kelvin', 'Celsius', 'Fahrenheit', 'Lumens'], correctAnswer: 'Kelvin' },
  'What color cast does tungsten/incandescent lighting produce?': { prompt: 'Quelle dominante de couleur l\'éclairage tungstène/incandescent produit-il?', options: ['Bleu', 'Vert', 'Orange/jaune chaud', 'Violet'], correctAnswer: 'Orange/jaune chaud' },
  'Shooting in RAW lets you change white balance in post-processing without quality loss.': { prompt: 'Photographier en RAW permet de changer la balance des blancs en post-traitement sans perte de qualité.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which white balance preset would you use on a cloudy day?': { prompt: 'Quel préréglage de balance des blancs utiliseriez-vous par temps nuageux?', options: ['Tungstène', 'Fluorescent', 'Nuageux/Couvert', 'Flash'], correctAnswer: 'Nuageux/Couvert' },
  'Always leaving white balance on Auto and never learning manual settings.': { prompt: 'Toujours laisser la balance des blancs sur Auto et ne jamais apprendre les réglages manuels.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'A lower Kelvin number (e.g., 3000K) represents cooler, bluer light.': { prompt: 'Un nombre Kelvin plus bas (ex: 3000K) représente une lumière plus froide et plus bleue.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },

  // Portrait Photography
  'What focal length range is considered ideal for portraits?': { prompt: 'Quelle plage de focale est considérée idéale pour les portraits?', options: ['10-20mm', '85-135mm', '200-400mm', '35mm uniquement'], correctAnswer: '85-135mm' },
  'Wide-angle lenses distort facial features in close-up portraits.': { prompt: 'Les objectifs grand-angle déforment les traits du visage dans les portraits en gros plan.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'In portrait photography, focus should always be on the subject\'s ___.': { prompt: 'En photographie de portrait, la mise au point devrait toujours être sur les ___ du sujet.', options: ['Yeux', 'Front', 'Menton', 'Oreilles'], correctAnswer: 'Yeux' },
  'What is "catchlight" in portrait photography?': { prompt: 'Qu\'est-ce qu\'un "catchlight" en photographie de portrait?', options: ['Un type de flash', 'Le reflet de la lumière dans les yeux du sujet', 'L\'éclairage d\'arrière-plan', 'Un réglage de l\'appareil photo'], correctAnswer: 'Le reflet de la lumière dans les yeux du sujet' },
  'Shooting portraits at f/1.8 ensures the entire face is in sharp focus.': { prompt: 'Photographier des portraits à f/1.8 assure que tout le visage est parfaitement net.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Having your subject stand directly against a wall for their portrait.': { prompt: 'Faire poser votre sujet directement contre un mur pour son portrait.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is Rembrandt lighting?': { prompt: 'Qu\'est-ce que l\'éclairage Rembrandt?', options: ['Un éclairage plat et uniforme sur le visage', 'Une lumière créant un triangle de lumière sur la joue ombragée', 'Un contre-jour uniquement', 'Utiliser seulement des bougies'], correctAnswer: 'Une lumière créant un triangle de lumière sur la joue ombragée' },
  'Having the subject turn slightly rather than face the camera straight on is usually more flattering.': { prompt: 'Faire tourner légèrement le sujet plutôt que de face la caméra directement est habituellement plus flatteur.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Landscape Photography
  'What aperture range is typically used for sharp landscape photos?': { prompt: 'Quelle plage d\'ouverture est typiquement utilisée pour des photos de paysage nettes?', options: ['f/1.4 à f/2.8', 'f/8 à f/13', 'f/22 à f/32', 'f/4 uniquement'], correctAnswer: 'f/8 à f/13' },
  'A tripod is essential for sharp landscape photos, especially at sunrise/sunset.': { prompt: 'Un trépied est essentiel pour des photos de paysage nettes, surtout au lever/coucher du soleil.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Including a ___ element gives landscapes a sense of scale and depth.': { prompt: 'Inclure un élément de ___ donne aux paysages un sens d\'échelle et de profondeur.', options: ['Premier plan', 'Arrière-plan', 'Ciel', 'Nuage'], correctAnswer: 'Premier plan' },
  'What does a polarizing filter do for landscapes?': { prompt: 'Que fait un filtre polarisant pour les paysages?', options: ['Rend tout flou', 'Réduit les reflets et intensifie le bleu du ciel', 'Ajoute des tons chauds uniquement', 'Augmente l\'ISO'], correctAnswer: 'Réduit les reflets et intensifie le bleu du ciel' },
  'Shooting at f/22 always gives the sharpest possible landscape image.': { prompt: 'Photographier à f/22 donne toujours l\'image de paysage la plus nette possible.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'Arriving at a landscape location just 30 minutes before golden hour to scout compositions.': { prompt: 'Arriver sur un site de paysage 30 minutes avant l\'heure dorée pour repérer les compositions.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What is "hyperfocal distance"?': { prompt: 'Qu\'est-ce que la "distance hyperfocale"?', options: ['Le point de mise au point le plus proche', 'La distance qui maximise la profondeur de champ du premier plan à l\'infini', 'La portée maximale du zoom de votre objectif', 'Un type d\'objectif'], correctAnswer: 'La distance qui maximise la profondeur de champ du premier plan à l\'infini' },
  'Neutral density filters allow you to use longer exposures in bright conditions.': { prompt: 'Les filtres à densité neutre permettent d\'utiliser des expositions plus longues en conditions lumineuses.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Street Photography
  'What focal length is most popular for street photography?': { prompt: 'Quelle focale est la plus populaire pour la photographie de rue?', options: ['200mm', '35mm ou 50mm', '14mm', '500mm'], correctAnswer: '35mm ou 50mm' },
  'Street photography always requires the subject\'s permission.': { prompt: 'La photographie de rue nécessite toujours la permission du sujet.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'The "decisive ___" is a concept coined by Henri Cartier-Bresson about capturing the perfect instant.': { prompt: 'Le "___ décisif" est un concept inventé par Henri Cartier-Bresson sur la capture de l\'instant parfait.', options: ['Moment', 'Cadre', 'Cliché', 'Déclic'], correctAnswer: 'Moment' },
  'What camera setting helps you shoot quickly on the street?': { prompt: 'Quel réglage d\'appareil photo aide à photographier rapidement dans la rue?', options: ['Tout en manuel', 'Priorité ouverture avec ISO Auto', 'Mode Bulb', 'Mode minuteur'], correctAnswer: 'Priorité ouverture avec ISO Auto' },
  'Shooting in black and white can emphasize form and contrast in street photos.': { prompt: 'Photographier en noir et blanc peut accentuer les formes et le contraste dans les photos de rue.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Using a large telephoto lens to secretly photograph people from far away.': { prompt: 'Utiliser un gros téléobjectif pour photographier secrètement les gens de loin.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is "zone focusing"?': { prompt: 'Qu\'est-ce que la "mise au point par zone"?', options: ['Ne faire la mise au point que dans certaines zones d\'une ville', 'Prérégler la mise au point sur une plage de distance pour que tout dans cette zone soit net', 'Un type de filtre pour objectif', 'Un mode de suivi autofocus'], correctAnswer: 'Prérégler la mise au point sur une plage de distance pour que tout dans cette zone soit net' },
  'Overcast days provide even, shadowless light that works well for street photography.': { prompt: 'Les jours couverts fournissent une lumière uniforme et sans ombre qui fonctionne bien pour la photographie de rue.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Golden Hour
  'When exactly is golden hour?': { prompt: 'Quand exactement est l\'heure dorée?', options: ['Le midi', 'La première et la dernière heure de lumière solaire chaque jour', 'Minuit', 'N\'importe quand il fait soleil'], correctAnswer: 'La première et la dernière heure de lumière solaire chaque jour' },
  'Golden hour light is warm because sunlight travels through more atmosphere.': { prompt: 'La lumière de l\'heure dorée est chaude parce que la lumière du soleil traverse plus d\'atmosphère.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Golden hour produces long ___ that add depth and drama to photos.': { prompt: 'L\'heure dorée produit de longues ___ qui ajoutent de la profondeur et du drame aux photos.', options: ['Ombres', 'Expositions', 'Éclairs', 'Zooms'], correctAnswer: 'Ombres' },
  'What happens to golden hour duration near the equator?': { prompt: 'Que se passe-t-il avec la durée de l\'heure dorée près de l\'équateur?', options: ['Elle dure toute la journée', 'Elle est plus courte qu\'aux latitudes plus élevées', 'Elle n\'existe pas', 'Elle dure 3 heures'], correctAnswer: 'Elle est plus courte qu\'aux latitudes plus élevées' },
  'Backlighting during golden hour can create a beautiful rim of light around subjects.': { prompt: 'Le contre-jour pendant l\'heure dorée peut créer un beau halo de lumière autour des sujets.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Using a weather app to check sunrise/sunset times before a golden hour shoot.': { prompt: 'Utiliser une application météo pour vérifier les heures de lever/coucher du soleil avant une séance à l\'heure dorée.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What white balance setting enhances golden hour warmth?': { prompt: 'Quel réglage de balance des blancs accentue la chaleur de l\'heure dorée?', options: ['Tungstène', 'Ombre ou Nuageux', 'Fluorescent', 'Auto'], correctAnswer: 'Ombre ou Nuageux' },
  'Golden hour light only works for landscape photography.': { prompt: 'La lumière de l\'heure dorée ne fonctionne que pour la photographie de paysage.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },

  // Flash Photography
  'What does "bouncing" flash mean?': { prompt: 'Que signifie "rebondir" le flash?', options: ['Laisser tomber le flash', 'Diriger le flash vers un plafond ou un mur pour que la lumière se reflète doucement sur le sujet', 'Utiliser deux flashs', 'Allumer et éteindre le flash rapidement'], correctAnswer: 'Diriger le flash vers un plafond ou un mur pour que la lumière se reflète doucement sur le sujet' },
  'Direct on-camera flash often creates harsh shadows and red-eye.': { prompt: 'Le flash direct sur l\'appareil crée souvent des ombres dures et des yeux rouges.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A flash ___ softens and spreads the light for more flattering results.': { prompt: 'Un ___ de flash adoucit et diffuse la lumière pour des résultats plus flatteurs.', options: ['Diffuseur', 'Chargeur', 'Support', 'Déclencheur'], correctAnswer: 'Diffuseur' },
  'What is "fill flash" used for?': { prompt: 'À quoi sert le "flash d\'appoint"?', options: ['Remplacer toute la lumière ambiante', 'Éclaircir les ombres par temps ensoleillé sans dominer la lumière naturelle', 'Tout rendre blanc', 'La photographie de nuit uniquement'], correctAnswer: 'Éclaircir les ombres par temps ensoleillé sans dominer la lumière naturelle' },
  'Flash sync speed is the fastest shutter speed that works with flash.': { prompt: 'La vitesse de synchronisation du flash est la vitesse d\'obturation la plus rapide qui fonctionne avec le flash.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Using flash at full power pointed directly at someone\'s face from close range.': { prompt: 'Utiliser le flash à pleine puissance pointé directement vers le visage de quelqu\'un de près.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is TTL flash metering?': { prompt: 'Qu\'est-ce que la mesure flash TTL?', options: ['Through The Lens — l\'appareil contrôle automatiquement la puissance du flash', 'Un mode flash manuel', 'Un type de support de flash', 'Une marque de flash'], correctAnswer: 'Through The Lens — l\'appareil contrôle automatiquement la puissance du flash' },
  'Off-camera flash gives more creative control over lighting direction and quality.': { prompt: 'Le flash déporté offre plus de contrôle créatif sur la direction et la qualité de la lumière.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Post-Processing
  'What is the most important advantage of shooting in RAW format?': { prompt: 'Quel est l\'avantage le plus important de photographier en format RAW?', options: ['Taille de fichier plus petite', 'Plus de flexibilité d\'édition sans perte de qualité', 'Meilleur autofocus', 'Vitesse de prise de vue plus rapide'], correctAnswer: 'Plus de flexibilité d\'édition sans perte de qualité' },
  'JPEG files are already processed and compressed by the camera.': { prompt: 'Les fichiers JPEG sont déjà traités et compressés par l\'appareil photo.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The ___ slider adjusts the overall brightness of an image in editing.': { prompt: 'Le curseur d\'___ ajuste la luminosité globale d\'une image en édition.', options: ['Exposition', 'Saturation', 'Teinte', 'Clarté'], correctAnswer: 'Exposition' },
  'What does the "clarity" slider typically enhance?': { prompt: 'Que le curseur "clarté" améliore-t-il typiquement?', options: ['La saturation des couleurs', 'La luminosité globale', 'Le contraste des tons moyens et le détail des contours', 'La récupération des ombres'], correctAnswer: 'Le contraste des tons moyens et le détail des contours' },
  'Over-saturating colors is a common beginner editing mistake.': { prompt: 'Sursaturer les couleurs est une erreur d\'édition courante chez les débutants.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Always editing photos on a calibrated monitor for accurate colors.': { prompt: 'Toujours éditer les photos sur un moniteur calibré pour des couleurs précises.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What is the difference between "vibrance" and "saturation"?': { prompt: 'Quelle est la différence entre "vibrance" et "saturation"?', options: ['Ils sont identiques', 'La vibrance renforce les couleurs atténuées tout en protégeant les tons déjà saturés', 'La saturation n\'affecte que les bleus', 'La vibrance ne fonctionne que sur les fichiers RAW'], correctAnswer: 'La vibrance renforce les couleurs atténuées tout en protégeant les tons déjà saturés' },
  'Cropping in post-processing can improve composition.': { prompt: 'Le recadrage en post-traitement peut améliorer la composition.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Lens Types
  'What is a "prime" lens?': { prompt: 'Qu\'est-ce qu\'un objectif "fixe"?', options: ['L\'objectif le plus cher', 'Un objectif avec une seule focale fixe', 'Un objectif zoom', 'Un objectif fabriqué par Amazon'], correctAnswer: 'Un objectif avec une seule focale fixe' },
  'A 50mm lens is often called the "nifty fifty" and is great for beginners.': { prompt: 'Un objectif 50mm est souvent appelé le "nifty fifty" et est excellent pour les débutants.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A ___ lens has a focal length shorter than 35mm and captures a wider field of view.': { prompt: 'Un objectif ___ a une focale inférieure à 35mm et capture un champ de vision plus large.', options: ['Grand-angle', 'Téléobjectif', 'Macro', 'Fixe'], correctAnswer: 'Grand-angle' },
  'What is a macro lens designed for?': { prompt: 'Pour quoi un objectif macro est-il conçu?', options: ['La photographie en très gros plan de petits sujets', 'Seulement la photographie de paysage', 'La photographie sportive', 'L\'astrophotographie'], correctAnswer: 'La photographie en très gros plan de petits sujets' },
  'Telephoto lenses compress the apparent distance between objects.': { prompt: 'Les téléobjectifs compriment la distance apparente entre les objets.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Which lens would you choose for bird photography?': { prompt: 'Quel objectif choisiriez-vous pour la photographie d\'oiseaux?', options: ['Fisheye 15mm', 'Fixe 50mm', 'Téléobjectif 300-600mm', 'Grand-angle 35mm'], correctAnswer: 'Téléobjectif 300-600mm' },
  'Buying every lens available before mastering one or two.': { prompt: 'Acheter tous les objectifs disponibles avant d\'en maîtriser un ou deux.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Zoom lenses offer convenience by covering multiple focal lengths in one lens.': { prompt: 'Les objectifs zoom offrent la commodité de couvrir plusieurs focales en un seul objectif.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Depth of Field
  'Which factor does NOT affect depth of field?': { prompt: 'Quel facteur n\'affecte PAS la profondeur de champ?', options: ['L\'ouverture', 'La focale', 'La distance au sujet', 'La vitesse d\'obturation'], correctAnswer: 'La vitesse d\'obturation' },
  'A wider aperture (lower f-number) creates a shallower depth of field.': { prompt: 'Une ouverture plus grande (nombre f plus bas) crée une profondeur de champ plus faible.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Moving ___ to your subject creates a shallower depth of field.': { prompt: 'Se rapprocher ___ de votre sujet crée une profondeur de champ plus faible.', options: ['Plus près', 'Plus loin', 'Parallèlement', 'En s\'éloignant'], correctAnswer: 'Plus près' },
  'What is "bokeh"?': { prompt: 'Qu\'est-ce que le "bokeh"?', options: ['Une marque d\'appareil photo', 'La qualité esthétique des zones floues d\'une photo', 'Un type d\'objectif', 'Un plat japonais'], correctAnswer: 'La qualité esthétique des zones floues d\'une photo' },
  'Longer focal lengths produce shallower depth of field at the same aperture.': { prompt: 'Les focales plus longues produisent une profondeur de champ plus faible à la même ouverture.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Using a wide aperture like f/2.8 to isolate a single flower from a busy background.': { prompt: 'Utiliser une grande ouverture comme f/2.8 pour isoler une seule fleur d\'un arrière-plan chargé.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'For a group photo of 10 people in two rows, which aperture is best?': { prompt: 'Pour une photo de groupe de 10 personnes en deux rangées, quelle ouverture est la meilleure?', options: ['f/1.4', 'f/2.0', 'f/8', 'f/2.8'], correctAnswer: 'f/8' },
  'Smartphone portrait modes simulate shallow depth of field using software.': { prompt: 'Les modes portrait des smartphones simulent une faible profondeur de champ par logiciel.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Color Theory
  'What are complementary colors?': { prompt: 'Que sont les couleurs complémentaires?', options: ['Des couleurs voisines sur le cercle chromatique', 'Des couleurs opposées sur le cercle chromatique', 'Seulement le noir et le blanc', 'N\'importe quelles deux couleurs'], correctAnswer: 'Des couleurs opposées sur le cercle chromatique' },
  'Warm colors (red, orange, yellow) tend to advance visually while cool colors recede.': { prompt: 'Les couleurs chaudes (rouge, orange, jaune) tendent à avancer visuellement tandis que les couleurs froides reculent.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The color combination of blue and ___ is one of the most popular complementary pairs in photography.': { prompt: 'La combinaison de couleurs bleu et ___ est l\'une des paires complémentaires les plus populaires en photographie.', options: ['Orange', 'Vert', 'Violet', 'Rouge'], correctAnswer: 'Orange' },
  'What is a monochromatic color scheme?': { prompt: 'Qu\'est-ce qu\'un schéma de couleurs monochromatique?', options: ['Utiliser toutes les couleurs', 'Utiliser seulement le noir et blanc', 'Utiliser des variations d\'une seule teinte', 'Utiliser des couleurs au hasard'], correctAnswer: 'Utiliser des variations d\'une seule teinte' },
  'Color can convey mood and emotion in photographs.': { prompt: 'La couleur peut transmettre l\'ambiance et l\'émotion dans les photographies.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is "color grading" in photography?': { prompt: 'Qu\'est-ce que l\'"étalonnage des couleurs" en photographie?', options: ['Noter les photos par couleur', 'Ajuster et styliser la tonalité globale des couleurs d\'une image', 'Trier les photos par teinte', 'Un réglage de l\'appareil photo'], correctAnswer: 'Ajuster et styliser la tonalité globale des couleurs d\'une image' },
  'Using clashing, random colors throughout a photo series with no consistency.': { prompt: 'Utiliser des couleurs discordantes et aléatoires dans une série de photos sans cohérence.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Analogous colors are those next to each other on the color wheel and create harmony.': { prompt: 'Les couleurs analogues sont celles qui sont adjacentes sur le cercle chromatique et créent de l\'harmonie.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Night Photography
  'What is the most essential piece of gear for night photography?': { prompt: 'Quel est l\'équipement le plus essentiel pour la photographie de nuit?', options: ['Un flash', 'Un téléobjectif', 'Un trépied solide', 'Un filtre'], correctAnswer: 'Un trépied solide' },
  'The "500 rule" helps calculate the maximum shutter speed to avoid star trails.': { prompt: 'La "règle des 500" aide à calculer la vitesse d\'obturation maximale pour éviter les traînées d\'étoiles.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'For star photography, use a ___ aperture to let in maximum light.': { prompt: 'Pour la photographie d\'étoiles, utilisez une ouverture ___ pour laisser entrer un maximum de lumière.', options: ['Grande', 'Petite', 'Moyenne', 'Variable'], correctAnswer: 'Grande' },
  'What ISO range is commonly used for Milky Way photography?': { prompt: 'Quelle plage d\'ISO est couramment utilisée pour la photographie de la Voie Lactée?', options: ['ISO 50-100', 'ISO 200-400', 'ISO 1600-6400', 'ISO 100-200'], correctAnswer: 'ISO 1600-6400' },
  'Light pollution makes it harder to photograph stars.': { prompt: 'La pollution lumineuse rend la photographie d\'étoiles plus difficile.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Using a 2-second timer or remote shutter release to avoid camera shake during long exposures.': { prompt: 'Utiliser un minuteur de 2 secondes ou un déclencheur à distance pour éviter le bougé de l\'appareil pendant les longues expositions.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'What is "light painting" in night photography?': { prompt: 'Qu\'est-ce que le "light painting" en photographie de nuit?', options: ['Peindre votre appareil photo', 'Déplacer une source de lumière pendant une longue exposition pour créer des motifs', 'Utiliser Photoshop', 'Ajouter des filtres'], correctAnswer: 'Déplacer une source de lumière pendant une longue exposition pour créer des motifs' },
  'Long exposure noise reduction in-camera takes a second dark frame to subtract noise.': { prompt: 'La réduction du bruit en longue exposition dans l\'appareil prend une deuxième image sombre pour soustraire le bruit.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
};
