export const pianoFr: Record<string, { prompt: string; options?: string[]; correctAnswer?: string | string[] }> = {
  // Keyboard Layout
  'How many white keys are in one octave?': { prompt: 'Combien de touches blanches y a-t-il dans une octave?', options: ['5', '7', '8', '12'], correctAnswer: '7' },
  'A full-size piano has 88 keys.': { prompt: 'Un piano pleine grandeur a 88 touches.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Black keys are grouped in sets of ___ and 3.': { prompt: 'Les touches noires sont regroupées en ensembles de ___ et 3.', options: ['2', '4', '5', '1'], correctAnswer: '2' },
  'What note is to the left of the group of 2 black keys?': { prompt: 'Quelle note se trouve à gauche du groupe de 2 touches noires?', options: ['Ré', 'Fa', 'Mi', 'Do'], correctAnswer: 'Do' },
  'Finding Middle C as a reference point on the keyboard.': { prompt: 'Trouver le Do du milieu comme point de référence sur le clavier.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Moving right on the keyboard makes notes higher in pitch.': { prompt: 'Se déplacer vers la droite sur le clavier rend les notes plus aiguës.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Basic Scales
  'How many notes are in a major scale?': { prompt: 'Combien de notes y a-t-il dans une gamme majeure?', options: ['5', '7', '8', '6'], correctAnswer: '7' },
  'The C major scale uses only white keys.': { prompt: 'La gamme de Do majeur n\'utilise que des touches blanches.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The C major scale starts and ends on ___.': { prompt: 'La gamme de Do majeur commence et finit sur ___.', options: ['Do', 'Ré', 'Sol', 'La'], correctAnswer: 'Do' },
  'What is the pattern for a major scale?': { prompt: 'Quel est le patron d\'une gamme majeure?', options: ['dt-dt-T-dt-dt-T-dt', 'T-T-dt-T-T-T-dt', 'Aléatoire', 'Tous des tons'], correctAnswer: 'T-T-dt-T-T-T-dt' },
  'Practicing scales with each hand separately first.': { prompt: 'Pratiquer les gammes avec chaque main séparément d\'abord.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'A half step is the distance between two adjacent keys.': { prompt: 'Un demi-ton est la distance entre deux touches adjacentes.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Simple Chords
  'How many notes make a triad chord?': { prompt: 'Combien de notes composent un accord de triade?', options: ['3', '4', '5', '2'], correctAnswer: '3' },
  'C major chord uses the notes C, E, and G.': { prompt: 'L\'accord de Do majeur utilise les notes Do, Mi et Sol.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A ___ chord sounds happy, while a minor chord sounds sad.': { prompt: 'Un accord ___ sonne joyeux, tandis qu\'un accord mineur sonne triste.', options: ['Majeur', 'Dièse', 'Bémol', 'Diminué'], correctAnswer: 'Majeur' },
  'What makes a minor chord different from major?': { prompt: 'Qu\'est-ce qui rend un accord mineur différent d\'un majeur?', options: ['La note du milieu est abaissée d\'un demi-ton', 'Il a plus de notes', 'Il est joué plus vite', 'Il est plus fort'], correctAnswer: 'La note du milieu est abaissée d\'un demi-ton' },
  'Pressing all chord notes simultaneously with even pressure.': { prompt: 'Appuyer sur toutes les notes d\'un accord simultanément avec une pression uniforme.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'You can play chords with either hand.': { prompt: 'Vous pouvez jouer des accords avec n\'importe quelle main.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Hand Position
  'How should your fingers be curved at the piano?': { prompt: 'Comment vos doigts devraient-ils être courbés au piano?', options: ['Complètement plats', 'Doucement courbés comme si vous teniez une balle', 'Pliés vers l\'arrière', 'Rigides et droits'], correctAnswer: 'Doucement courbés comme si vous teniez une balle' },
  'Wrists should be level with the keyboard, not dropped or raised.': { prompt: 'Les poignets devraient être au niveau du clavier, ni tombants ni relevés.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Fingers are numbered 1 (thumb) through ___ (pinky).': { prompt: 'Les doigts sont numérotés de 1 (pouce) à ___ (auriculaire).', options: ['5', '4', '3', '10'], correctAnswer: '5' },
  'Tensing your shoulders while playing piano.': { prompt: 'Tendre vos épaules en jouant du piano.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What is the correct bench height?': { prompt: 'Quelle est la bonne hauteur de banc?', options: ['Les avant-bras à peu près parallèles au clavier', 'Ça n\'a pas d\'importance', 'Le plus bas possible', 'Le plus haut possible'], correctAnswer: 'Les avant-bras à peu près parallèles au clavier' },
  'Playing with flat fingers reduces speed and control.': { prompt: 'Jouer avec les doigts plats réduit la vitesse et le contrôle.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Right Hand
  'What does the right hand typically play?': { prompt: 'Que joue typiquement la main droite?', options: ['Seulement des accords', 'La mélodie', 'Les notes de basse', 'Rien'], correctAnswer: 'La mélodie' },
  'The right hand usually plays in the treble clef.': { prompt: 'La main droite joue habituellement en clef de sol.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The treble clef is also called the ___ clef.': { prompt: 'La clef de sol est aussi appelée la clef de ___.', options: ['Sol', 'Fa', 'Do', 'Ré'], correctAnswer: 'Sol' },
  'Practicing the right hand alone before adding the left.': { prompt: 'Pratiquer la main droite seule avant d\'ajouter la gauche.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'In C position, what note does the right thumb play?': { prompt: 'En position de Do, quelle note le pouce droit joue-t-il?', options: ['Fa', 'Ré', 'Sol', 'Do'], correctAnswer: 'Do' },
  'Each finger should stay over its assigned key in basic position.': { prompt: 'Chaque doigt devrait rester au-dessus de sa touche assignée en position de base.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Left Hand
  'What does the left hand typically play?': { prompt: 'Que joue typiquement la main gauche?', options: ['La basse et l\'accompagnement', 'Rien', 'La mélodie', 'Seulement des gammes'], correctAnswer: 'La basse et l\'accompagnement' },
  'The left hand usually reads the bass clef.': { prompt: 'La main gauche lit habituellement la clef de fa.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The bass clef is also called the ___ clef.': { prompt: 'La clef de fa est aussi appelée la clef de ___.', options: ['Fa', 'Sol', 'Do', 'Si'], correctAnswer: 'Fa' },
  'Neglecting left hand practice because it\'s harder.': { prompt: 'Négliger la pratique de la main gauche parce que c\'est plus difficile.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'In C position, the left pinky (finger 5) plays which note?': { prompt: 'En position de Do, l\'auriculaire gauche (doigt 5) joue quelle note?', options: ['Do', 'Sol', 'Ré', 'Fa'], correctAnswer: 'Do' },
  'The left hand pinky is finger 5 and thumb is finger 1.': { prompt: 'L\'auriculaire de la main gauche est le doigt 5 et le pouce est le doigt 1.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Both Hands
  'What is the biggest challenge of playing with both hands?': { prompt: 'Quel est le plus grand défi de jouer avec les deux mains?', options: ['S\'asseoir correctement', 'Trouver les touches', 'Lire la musique', 'La coordination et l\'indépendance'], correctAnswer: 'La coordination et l\'indépendance' },
  'You should master each hand separately before combining them.': { prompt: 'Vous devriez maîtriser chaque main séparément avant de les combiner.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Start ___ when combining hands, then gradually speed up.': { prompt: 'Commencez ___ en combinant les mains, puis accélérez graduellement.', options: ['Lentement', 'Vite', 'Fort', 'Doucement'], correctAnswer: 'Lentement' },
  'Practicing hands together from the very start of a new piece.': { prompt: 'Pratiquer les deux mains ensemble dès le début d\'un nouveau morceau.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'What helps synchronize both hands?': { prompt: 'Qu\'est-ce qui aide à synchroniser les deux mains?', options: ['Jouer plus vite', 'Fermer les yeux', 'Pratiquer avec un métronome', 'Jouer une seule main'], correctAnswer: 'Pratiquer avec un métronome' },
  'Breaking a piece into small sections makes hands-together practice easier.': { prompt: 'Diviser un morceau en petites sections rend la pratique mains ensemble plus facile.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Chord Inversions
  'What is a chord inversion?': { prompt: 'Qu\'est-ce qu\'un renversement d\'accord?', options: ['Jouer un accord à l\'envers', 'Ajouter plus de notes', 'Jouer un accord plus fort', 'Réarranger quelle note est en bas'], correctAnswer: 'Réarranger quelle note est en bas' },
  'Root position means the root note is on the bottom.': { prompt: 'La position fondamentale signifie que la note fondamentale est en bas.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'First inversion has the ___ of the chord as the lowest note.': { prompt: 'Le premier renversement a la ___ de l\'accord comme note la plus basse.', options: ['Tierce', 'Quinte', 'Fondamentale', 'Septième'], correctAnswer: 'Tierce' },
  'Why use chord inversions?': { prompt: 'Pourquoi utiliser les renversements d\'accords?', options: ['Pour jouer plus vite', 'Pour des transitions plus fluides entre les accords', 'Ils sonnent complètement différemment', 'Pour jouer plus fort'], correctAnswer: 'Pour des transitions plus fluides entre les accords' },
  'Learning inversions to minimize hand movement between chords.': { prompt: 'Apprendre les renversements pour minimiser le mouvement des mains entre les accords.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'C/E means C chord with E as the bass note (first inversion).': { prompt: 'Do/Mi signifie un accord de Do avec Mi comme note de basse (premier renversement).', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Major Scales
  'How many major scales are there in total?': { prompt: 'Combien de gammes majeures y a-t-il au total?', options: ['7', '12', '5', '15'], correctAnswer: '12' },
  'The G major scale has one sharp: F#.': { prompt: 'La gamme de Sol majeur a un dièse: Fa#.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The correct fingering crosses the thumb ___ the other fingers when playing scales.': { prompt: 'Le doigté correct passe le pouce ___ les autres doigts en jouant des gammes.', options: ['Sous', 'Par-dessus', 'Entre', 'Derrière'], correctAnswer: 'Sous' },
  'What is the order of sharps in key signatures?': { prompt: 'Quel est l\'ordre des dièses dans les armures?', options: ['Fa Do Sol Ré La Mi Si', 'Si Mi La Ré Sol Do Fa', 'Do Ré Mi Fa Sol La Si', 'Sol La Si Do Ré Mi Fa'], correctAnswer: 'Fa Do Sol Ré La Mi Si' },
  'Playing scales with both hands in parallel motion means they move in the same direction.': { prompt: 'Jouer des gammes avec les deux mains en mouvement parallèle signifie qu\'elles bougent dans la même direction.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The D major scale has how many sharps?': { prompt: 'La gamme de Ré majeur a combien de dièses?', options: ['Aucun', 'Un', 'Deux', 'Trois'], correctAnswer: 'Deux' },
  'Practicing scales with correct fingering even when it feels awkward at first.': { prompt: 'Pratiquer les gammes avec le bon doigté même quand c\'est maladroit au début.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Bb major and A# major are enharmonic equivalents — same sound, different notation.': { prompt: 'Si bémol majeur et La dièse majeur sont des équivalents enharmoniques — même son, notation différente.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Minor Scales
  'What are the three types of minor scales?': { prompt: 'Quels sont les trois types de gammes mineures?', options: ['Naturelle, harmonique et mélodique', 'Dièse, bémol et naturelle', 'Bas, moyen et haut', 'Majeure, mineure et diminuée'], correctAnswer: 'Naturelle, harmonique et mélodique' },
  'The A natural minor scale uses only white keys on the piano.': { prompt: 'La gamme de La mineur naturelle n\'utilise que des touches blanches sur le piano.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The harmonic minor scale raises the ___ degree by a half step.': { prompt: 'La gamme mineure harmonique élève le ___ degré d\'un demi-ton.', options: ['7e', '3e', '5e', '2e'], correctAnswer: '7e' },
  'What interval gives the harmonic minor scale its exotic sound?': { prompt: 'Quel intervalle donne à la gamme mineure harmonique son son exotique?', options: ['Une seconde mineure', 'Une seconde augmentée entre le 6e et le 7e degré élevé', 'Une quinte juste', 'Une tierce majeure'], correctAnswer: 'Une seconde augmentée entre le 6e et le 7e degré élevé' },
  'Every major key has a relative minor that shares the same key signature.': { prompt: 'Chaque tonalité majeure a une relative mineure qui partage la même armure.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The melodic minor scale is different going up and coming down. Why?': { prompt: 'La gamme mineure mélodique est différente en montant et en descendant. Pourquoi?', options: ['C\'est une erreur dans la théorie musicale', 'Les 6e et 7e degrés élevés en montant créent une conduite de voix plus fluide; ils reviennent au mineur naturel en descendant', 'Ça sonne mieux au hasard', 'Seulement en musique classique'], correctAnswer: 'Les 6e et 7e degrés élevés en montant créent une conduite de voix plus fluide; ils reviennent au mineur naturel en descendant' },
  'Only practicing natural minor scales and ignoring harmonic and melodic forms.': { prompt: 'Pratiquer seulement les gammes mineures naturelles et ignorer les formes harmoniques et mélodiques.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'D minor is the relative minor of F major.': { prompt: 'Ré mineur est la relative mineure de Fa majeur.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Arpeggios
  'What is an arpeggio?': { prompt: 'Qu\'est-ce qu\'un arpège?', options: ['Jouer toutes les notes d\'un accord en même temps', 'Jouer les notes d\'un accord une à la fois en séquence', 'Un type de gamme', 'Un accord fort'], correctAnswer: 'Jouer les notes d\'un accord une à la fois en séquence' },
  'A C major arpeggio uses the notes C, E, and G.': { prompt: 'Un arpège de Do majeur utilise les notes Do, Mi et Sol.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Arpeggios help develop finger ___ and smooth hand crossing on the piano.': { prompt: 'Les arpèges aident à développer l\'___ des doigts et le croisement fluide des mains au piano.', options: ['Indépendance', 'Force', 'Vitesse', 'Taille'], correctAnswer: 'Indépendance' },
  'How do arpeggios differ from scales?': { prompt: 'Comment les arpèges diffèrent-ils des gammes?', options: ['Ils utilisent des pianos différents', 'Les arpèges sautent des notes (jouant seulement les notes de l\'accord), les gammes jouent chaque note dans l\'ordre', 'Il n\'y a aucune différence', 'Les arpèges sont toujours plus rapides'], correctAnswer: 'Les arpèges sautent des notes (jouant seulement les notes de l\'accord), les gammes jouent chaque note dans l\'ordre' },
  'Practicing arpeggios improves your ability to play accompaniment patterns.': { prompt: 'Pratiquer les arpèges améliore votre capacité à jouer des patrons d\'accompagnement.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is the Alberti bass pattern?': { prompt: 'Qu\'est-ce que la basse d\'Alberti?', options: ['Une technique de guitare basse', 'Un patron d\'accord brisé: bas-haut-milieu-haut, couramment utilisé au piano de la période classique', 'Jouer les notes de basse fort', 'Un exercice de gamme pour la main gauche'], correctAnswer: 'Un patron d\'accord brisé: bas-haut-milieu-haut, couramment utilisé au piano de la période classique' },
  'Practicing arpeggios in all 12 keys to build complete keyboard fluency.': { prompt: 'Pratiquer les arpèges dans les 12 tonalités pour développer une maîtrise complète du clavier.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'A diminished arpeggio has a dark, tense sound used in dramatic musical moments.': { prompt: 'Un arpège diminué a un son sombre et tendu utilisé dans les moments musicaux dramatiques.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Sight Reading
  'What is sight reading?': { prompt: 'Qu\'est-ce que la lecture à vue?', options: ['Mémoriser la musique avant de jouer', 'Jouer de la musique à partir d\'une partition pour la première fois', 'Lire sur la théorie musicale', 'Regarder les touches en jouant'], correctAnswer: 'Jouer de la musique à partir d\'une partition pour la première fois' },
  'The treble clef lines from bottom to top spell E-G-B-D-F (Every Good Boy Does Fine).': { prompt: 'Les lignes de la clef de sol de bas en haut épellent Mi-Sol-Si-Ré-Fa (Every Good Boy Does Fine).', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The bass clef spaces from bottom to top spell A-C-E-G, remembered as "All Cows Eat ___."': { prompt: 'Les espaces de la clef de fa de bas en haut épellent La-Do-Mi-Sol, mémorisés comme "All Cows Eat ___."', options: ['Grass', 'Grain', 'Greens', 'Grapes'], correctAnswer: 'Grass' },
  'What should you look at before starting to sight read a piece?': { prompt: 'Que devriez-vous regarder avant de commencer à lire à vue un morceau?', options: ['Seulement la première note', 'L\'armure, la signature rythmique et l\'indication de tempo', 'Le titre seulement', 'La dernière mesure'], correctAnswer: 'L\'armure, la signature rythmique et l\'indication de tempo' },
  'When sight reading, it is better to keep going even if you make a mistake than to stop and correct it.': { prompt: 'En lecture à vue, il est préférable de continuer même si vous faites une erreur plutôt que de s\'arrêter pour la corriger.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'How can you improve sight reading skills?': { prompt: 'Comment pouvez-vous améliorer vos compétences en lecture à vue?', options: ['Ne jouer que des morceaux que vous connaissez déjà', 'Pratiquer la lecture de nouveaux morceaux faciles chaque jour', 'Éviter de lire la musique et jouer d\'oreille', 'Mémoriser chaque morceau immédiatement'], correctAnswer: 'Pratiquer la lecture de nouveaux morceaux faciles chaque jour' },
  'Looking down at your hands constantly while sight reading.': { prompt: 'Regarder constamment vos mains en lisant à vue.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Reading ahead (looking at the next few notes while playing the current ones) is a key sight-reading skill.': { prompt: 'Lire en avance (regarder les prochaines notes en jouant les actuelles) est une compétence clé de lecture à vue.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Dynamics
  'What does "forte" (f) mean?': { prompt: 'Que signifie "forte" (f)?', options: ['Doux', 'Rapide', 'Fort', 'Lent'], correctAnswer: 'Fort' },
  '"Piano" (p) means to play softly — this is also where the instrument gets its name.': { prompt: '"Piano" (p) signifie jouer doucement — c\'est aussi d\'où l\'instrument tire son nom.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A ___ means to gradually get louder.': { prompt: 'Un ___ signifie devenir graduellement plus fort.', options: ['Crescendo', 'Decrescendo', 'Fortissimo', 'Staccato'], correctAnswer: 'Crescendo' },
  'What does "mezzo forte" (mf) mean?': { prompt: 'Que signifie "mezzo forte" (mf)?', options: ['Très fort', 'Très doux', 'Modérément fort', 'Silencieux'], correctAnswer: 'Modérément fort' },
  'Dynamics only refer to volume and have nothing to do with musical expression.': { prompt: 'Les nuances ne se réfèrent qu\'au volume et n\'ont rien à voir avec l\'expression musicale.', options: ['Vrai', 'Faux'], correctAnswer: 'Faux' },
  'How do you play softly on the piano?': { prompt: 'Comment jouez-vous doucement au piano?', options: ['Appuyer les touches lentement', 'Utiliser moins de poids et une vitesse de touche plus lente', 'N\'utiliser qu\'un seul doigt', 'Appuyer sur la pédale de sustain'], correctAnswer: 'Utiliser moins de poids et une vitesse de touche plus lente' },
  'Playing everything at the same volume with no dynamic variation.': { prompt: 'Jouer tout au même volume sans variation de nuances.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'The dynamic marking "pp" (pianissimo) means very soft.': { prompt: 'L\'indication de nuance "pp" (pianissimo) signifie très doux.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Pedal Technique
  'What does the sustain (right) pedal do?': { prompt: 'Que fait la pédale de sustain (droite)?', options: ['Rend le piano plus fort', 'Lève tous les étouffoirs, permettant aux cordes de vibrer librement et aux notes de résonner', 'Change la hauteur', 'Enregistre ce que vous jouez'], correctAnswer: 'Lève tous les étouffoirs, permettant aux cordes de vibrer librement et aux notes de résonner' },
  'The soft (left) pedal is called the "una corda" pedal.': { prompt: 'La pédale douce (gauche) est appelée la pédale "una corda".', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  '"Legato pedaling" means pressing the pedal ___ after striking a new note to connect sounds smoothly.': { prompt: 'Le "pédalage legato" signifie appuyer sur la pédale ___ après avoir frappé une nouvelle note pour connecter les sons en douceur.', options: ['Immédiatement', 'Bien avant', 'Jamais', 'Au hasard'], correctAnswer: 'Immédiatement' },
  'What happens if you hold the sustain pedal too long?': { prompt: 'Que se passe-t-il si vous tenez la pédale de sustain trop longtemps?', options: ['Rien', 'Le piano brise', 'Les notes se mélangent créant un son brouillé', 'Ça sonne mieux'], correctAnswer: 'Les notes se mélangent créant un son brouillé' },
  'You should use the ball of your foot on the pedal, keeping your heel on the floor.': { prompt: 'Vous devriez utiliser l\'avant du pied sur la pédale, en gardant le talon au sol.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'How many pedals does a standard grand piano have?': { prompt: 'Combien de pédales un piano à queue standard a-t-il?', options: ['1', '2', '3', '4'], correctAnswer: '3' },
  'Using the sustain pedal to mask sloppy playing instead of learning the notes properly.': { prompt: 'Utiliser la pédale de sustain pour masquer un jeu bâclé au lieu d\'apprendre les notes correctement.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Which pedal approach is better?': { prompt: 'Quelle approche de pédalage est meilleure?', options: ['Tenir la pédale enfoncée pendant tout le morceau sans la changer.', 'Changer la pédale à chaque nouvelle harmonie, gardant le son clair et connecté.'], correctAnswer: 'Changer la pédale à chaque nouvelle harmonie, gardant le son clair et connecté.' },

  // Key Signatures
  'What does a key signature tell you?': { prompt: 'Que vous indique une armure?', options: ['À quelle vitesse jouer', 'Quelles notes sont systématiquement dièses ou bémols tout au long du morceau', 'À quel volume jouer', 'Quel instrument utiliser'], correctAnswer: 'Quelles notes sont systématiquement dièses ou bémols tout au long du morceau' },
  'A key signature with no sharps or flats indicates C major or A minor.': { prompt: 'Une armure sans dièses ni bémols indique Do majeur ou La mineur.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The order of flats in key signatures is B-E-A-D-G-C-F, remembered as "___."': { prompt: 'L\'ordre des bémols dans les armures est Si-Mi-La-Ré-Sol-Do-Fa, mémorisé comme "___."', options: ['BEAD Greatest Common Factor', 'Battle Ends And Down Goes Charles Father', 'Big Elephants Always Dance Gracefully', 'Both Every And Do Go C First'], correctAnswer: 'Battle Ends And Down Goes Charles Father' },
  'How do you determine the major key from a sharp key signature?': { prompt: 'Comment déterminez-vous la tonalité majeure à partir d\'une armure avec des dièses?', options: ['Compter les dièses', 'La tonalité est un demi-ton au-dessus du dernier dièse', 'Regarder le premier dièse', 'C\'est toujours Do'], correctAnswer: 'La tonalité est un demi-ton au-dessus du dernier dièse' },
  'F major has one flat: Bb.': { prompt: 'Fa majeur a un bémol: Si bémol.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is the "circle of fifths"?': { prompt: 'Qu\'est-ce que le "cycle des quintes"?', options: ['Un type d\'accord', 'Un diagramme montrant la relation entre les 12 tonalités majeures et mineures', 'Un exercice de pratique', 'Une marque de piano'], correctAnswer: 'Un diagramme montrant la relation entre les 12 tonalités majeures et mineures' },
  'Memorizing key signatures so you can identify them instantly.': { prompt: 'Mémoriser les armures pour pouvoir les identifier instantanément.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Eb major has three flats: Bb, Eb, and Ab.': { prompt: 'Mi bémol majeur a trois bémols: Si bémol, Mi bémol et La bémol.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Time Signatures
  'What does the top number in a time signature indicate?': { prompt: 'Que indique le chiffre du haut dans une signature rythmique?', options: ['Le tempo', 'Combien de temps il y a dans chaque mesure', 'La tonalité', 'Le volume'], correctAnswer: 'Combien de temps il y a dans chaque mesure' },
  '4/4 time is also called "common time."': { prompt: 'Le temps 4/4 est aussi appelé "temps commun."', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'In 3/4 time, each measure has ___ beats, giving it a waltz feel.': { prompt: 'En 3/4, chaque mesure a ___ temps, donnant une sensation de valse.', options: ['3', '4', '6', '2'], correctAnswer: '3' },
  'What does the bottom number in a time signature indicate?': { prompt: 'Que indique le chiffre du bas dans une signature rythmique?', options: ['Le nombre de mesures', 'Quelle valeur de note reçoit un temps', 'La vitesse du tempo', 'Combien de dièses'], correctAnswer: 'Quelle valeur de note reçoit un temps' },
  '6/8 time has a different feel than 3/4, even though both have the same total duration per measure.': { prompt: 'Le 6/8 a une sensation différente du 3/4, même si les deux ont la même durée totale par mesure.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is a "pickup" or "anacrusis"?': { prompt: 'Qu\'est-ce qu\'une "levée" ou "anacrouse"?', options: ['Un type d\'accord', 'Des notes qui viennent avant la première mesure complète', 'Un temps supplémentaire à la fin', 'Un silence au début'], correctAnswer: 'Des notes qui viennent avant la première mesure complète' },
  'Counting out loud when learning a new time signature.': { prompt: 'Compter à voix haute en apprenant une nouvelle signature rythmique.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'A whole note lasts 4 beats in 4/4 time.': { prompt: 'Une ronde dure 4 temps en 4/4.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Chord Progressions
  'What is the most common chord progression in pop music?': { prompt: 'Quelle est la progression d\'accords la plus courante en musique pop?', options: ['I-V-vi-IV', 'i-VII-VI-V', 'I-II-III-IV', 'vi-V-IV-III'], correctAnswer: 'I-V-vi-IV' },
  'Roman numerals represent chords built on each degree of the scale.': { prompt: 'Les chiffres romains représentent les accords construits sur chaque degré de la gamme.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A V-I progression is called a ___ cadence and creates a strong sense of resolution.': { prompt: 'Une progression V-I est appelée une cadence ___ et crée un fort sentiment de résolution.', options: ['Parfaite', 'Plagale', 'Demi', 'Trompeuse'], correctAnswer: 'Parfaite' },
  'What is a "12-bar blues" progression?': { prompt: 'Qu\'est-ce qu\'une progression "blues de 12 mesures"?', options: ['N\'importe quels 12 accords d\'affilée', 'Le patron I-I-I-I, IV-IV-I-I, V-IV-I-V sur 12 mesures', 'Une chanson de 12 minutes', 'Jouer 12 tonalités différentes'], correctAnswer: 'Le patron I-I-I-I, IV-IV-I-I, V-IV-I-V sur 12 mesures' },
  'The ii-V-I progression is the most important progression in jazz.': { prompt: 'La progression ii-V-I est la progression la plus importante en jazz.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is a "plagal cadence"?': { prompt: 'Qu\'est-ce qu\'une "cadence plagale"?', options: ['V-I', 'IV-I, aussi connue comme la cadence "Amen"', 'I-V', 'vi-IV'], correctAnswer: 'IV-I, aussi connue comme la cadence "Amen"' },
  'Learning chord progressions by number (Roman numerals) rather than only by letter name in one key.': { prompt: 'Apprendre les progressions d\'accords par chiffres (chiffres romains) plutôt que seulement par nom de lettre dans une tonalité.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'Which approach to learning progressions is better?': { prompt: 'Quelle approche pour apprendre les progressions est meilleure?', options: ['Mémoriser les lettres d\'accords pour une chanson dans une tonalité.', 'Apprendre la progression par chiffre romain pour pouvoir la jouer dans n\'importe quelle tonalité.'], correctAnswer: 'Apprendre la progression par chiffre romain pour pouvoir la jouer dans n\'importe quelle tonalité.' },

  // Blues Piano
  'What makes blues piano sound different from classical piano?': { prompt: 'Qu\'est-ce qui rend le son du piano blues différent du piano classique?', options: ['Une technique de pédale différente', 'L\'utilisation de "blue notes" (3e, 5e et 7e bémolisés) et du rythme swing', 'Jouer seulement les touches noires', 'Utiliser seulement la main gauche'], correctAnswer: 'L\'utilisation de "blue notes" (3e, 5e et 7e bémolisés) et du rythme swing' },
  'The left hand in boogie-woogie piano plays a repetitive bass pattern.': { prompt: 'La main gauche au piano boogie-woogie joue un patron de basse répétitif.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Playing a note slightly flat then bending it into pitch is called a blues ___.': { prompt: 'Jouer une note légèrement bémolisée puis la faire glisser vers la hauteur juste s\'appelle un ___ blues.', options: ['Crush', 'Bend', 'Slide', 'Roll'], correctAnswer: 'Crush' },
  'Which scale is most commonly used for blues piano improvisation?': { prompt: 'Quelle gamme est la plus couramment utilisée pour l\'improvisation au piano blues?', options: ['Gamme majeure', 'Gamme blues (pentatonique mineure + quinte bémol)', 'Gamme chromatique', 'Gamme par tons'], correctAnswer: 'Gamme blues (pentatonique mineure + quinte bémol)' },
  'Swing rhythm means playing eighth notes with a long-short feel rather than evenly.': { prompt: 'Le rythme swing signifie jouer les croches avec un feeling long-court plutôt qu\'uniformément.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'Who is considered the "Father of Boogie-Woogie"?': { prompt: 'Qui est considéré comme le "Père du Boogie-Woogie"?', options: ['Mozart', 'Pinetop Smith', 'Beethoven', 'Ray Charles'], correctAnswer: 'Pinetop Smith' },
  'Playing blues piano with strict, rigid timing and no swing feel.': { prompt: 'Jouer du piano blues avec un timing strict et rigide sans feeling swing.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Tremolos (rapidly alternating between two notes) are a common blues piano technique.': { prompt: 'Les trémolos (alterner rapidement entre deux notes) sont une technique courante du piano blues.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },

  // Practice Methods
  'What is "chunking" in piano practice?': { prompt: 'Qu\'est-ce que le "découpage" dans la pratique du piano?', options: ['Jouer le morceau entier sans arrêt', 'Diviser un morceau en petites sections et maîtriser chacune', 'Jouer fort par morceaux', 'Un type d\'exercice rythmique'], correctAnswer: 'Diviser un morceau en petites sections et maîtriser chacune' },
  'Practicing slowly is more effective for learning new material than practicing at full speed.': { prompt: 'Pratiquer lentement est plus efficace pour apprendre du nouveau matériel que pratiquer à pleine vitesse.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'The technique of practicing ___ separate before combining them is fundamental to piano learning.': { prompt: 'La technique de pratiquer les ___ séparément avant de les combiner est fondamentale pour l\'apprentissage du piano.', options: ['Mains', 'Pieds', 'Yeux', 'Pages'], correctAnswer: 'Mains' },
  'How often should a beginner practice piano?': { prompt: 'À quelle fréquence un débutant devrait-il pratiquer le piano?', options: ['Une fois par mois', 'Quotidiennement, même seulement 15 à 20 minutes', 'Seulement avant les leçons', 'Pendant 3 heures deux fois par semaine'], correctAnswer: 'Quotidiennement, même seulement 15 à 20 minutes' },
  'Playing through mistakes repeatedly reinforces the errors in muscle memory.': { prompt: 'Jouer à travers les erreurs de façon répétée renforce les erreurs dans la mémoire musculaire.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is "mental practice" for piano?': { prompt: 'Qu\'est-ce que la "pratique mentale" pour le piano?', options: ['Ne pas pratiquer du tout', 'Vous visualiser en train de jouer le morceau loin du piano', 'Penser à acheter un piano', 'Écouter de la musique passivement'], correctAnswer: 'Vous visualiser en train de jouer le morceau loin du piano' },
  'Always starting practice from the beginning of a piece instead of working on weak sections.': { prompt: 'Toujours commencer la pratique par le début d\'un morceau au lieu de travailler les sections faibles.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Mauvaise pratique' },
  'Which practice approach is more effective?': { prompt: 'Quelle approche de pratique est la plus efficace?', options: ['Jouer le morceau entier 10 fois, en espérant que les erreurs se corrigent d\'elles-mêmes.', 'Identifier les 4 mesures les plus difficiles, les pratiquer lentement 10 fois chacune, puis jouer le morceau.'], correctAnswer: 'Identifier les 4 mesures les plus difficiles, les pratiquer lentement 10 fois chacune, puis jouer le morceau.' },

  // Music Theory
  'What is a "half step" on the piano?': { prompt: 'Qu\'est-ce qu\'un "demi-ton" au piano?', options: ['Deux touches d\'écart', 'La distance de n\'importe quelle touche à la touche immédiatement adjacente (noire ou blanche)', 'La moitié d\'une octave', 'Enfoncer une touche à moitié'], correctAnswer: 'La distance de n\'importe quelle touche à la touche immédiatement adjacente (noire ou blanche)' },
  'There are 12 half steps in one octave.': { prompt: 'Il y a 12 demi-tons dans une octave.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'A chord made of root, major third, and perfect fifth is called a ___ triad.': { prompt: 'Un accord composé d\'une fondamentale, d\'une tierce majeure et d\'une quinte juste est appelé une triade ___.', options: ['Majeure', 'Mineure', 'Diminuée', 'Augmentée'], correctAnswer: 'Majeure' },
  'What interval is from C to G?': { prompt: 'Quel intervalle y a-t-il de Do à Sol?', options: ['Tierce majeure', 'Quarte juste', 'Quinte juste', 'Sixte mineure'], correctAnswer: 'Quinte juste' },
  'A scale degree is the position of a note within a scale, numbered 1 through 7.': { prompt: 'Un degré de gamme est la position d\'une note dans une gamme, numérotée de 1 à 7.', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
  'What is the difference between a major and minor third?': { prompt: 'Quelle est la différence entre une tierce majeure et une tierce mineure?', options: ['Une tierce majeure fait 4 demi-tons; une tierce mineure fait 3 demi-tons', 'Ils sont pareils', 'Une tierce majeure est plus forte', 'Une tierce mineure est plus rapide'], correctAnswer: 'Une tierce majeure fait 4 demi-tons; une tierce mineure fait 3 demi-tons' },
  'Learning intervals by ear in addition to reading them on the staff.': { prompt: 'Apprendre les intervalles à l\'oreille en plus de les lire sur la portée.', options: ['Bonne pratique', 'Mauvaise pratique'], correctAnswer: 'Bonne pratique' },
  'The dominant (5th degree) chord naturally wants to resolve to the tonic (1st degree).': { prompt: 'L\'accord de dominante (5e degré) veut naturellement résoudre vers la tonique (1er degré).', options: ['Vrai', 'Faux'], correctAnswer: 'Vrai' },
};
